### ISSUE TITLE
deCONZ Lights and groups not grouped anymore after update to 0.104.0

### ISSUE THREAD

**Issue by djmaze** [home-assistant/hassio-addons#1001]
After upgrading to Hass 0.104.0, Lovelace shows all deCONZ lights and groups separately. They are not grouped into areas anymore. Removing and re-adding the deCONZ integration does not change this. The area assignments are still there though.

My smart+ plugs (which deCONZ categorizes as lights as well) are still correctly grouped into their respective areas though.

This seems to be a compatibility problem between deCONZ and the new Home Assistant version?

**Comment by frenck** [comment]
That is an integration issue in Home Assistant. The add-on hasn't been updated.

Please file a bug here: https://github.com/home-assistant/home-assistant/issues
Be sure to check if there is already an issue, before creating one.

Thanks! 👍
