### ISSUE TITLE
Feature request: add support for accessing deCONZ Phoscon app without using ingress

### ISSUE THREAD

**Issue by pietpuk978** [home-assistant/hassio-addons#1002]
It would be nice if the Phoscon web-app could be accessed using a regular browser via for example hassio.local:40850. Since it is a fully optimized web app it's a shame it's not accessible via a web browser. This also makes it possible for non Hassio admins to access Phoscon and allows to visit it on a iPad as well.
Maybe add it as an option which is by default off but can be enabled for people who really want it.

**Comment by allanpersson** [comment]
@pietpuk978 i think i have the quick fix for your issue, and maybe some fix should be implementet.

I assume you have the ports active in the deconz addon, i did have that but was not able to connect to the port. Restarts was not working either.

**The solution** was:
- Change the port to a new port number, in my case i changed from 40850 -> 40851
- Restarted the addon.
- Then i clicked "reset to defaults"
- Then entered the default port numbers again.
- Restarted the addon
And now it was working.

I know from the Danish HA facebook group others had the same error, and the above solution worked for them as well.

**Comment by SAOPP** [comment]
Guys, just to clarify the situation again. I just upgraded to addon version 5.1.

The port for VNC, as it worked earlier, works fine now. But the other two ports didn't work. And after I open deconz addon page, and slick save under section of container ports, I have only one port now - it's VNC port, the other two ports for rest api were gone, 40850 and 4860.

What I need to do for back this possibility to the addon/container? Thanks in advanced!

**Comment by frenck** [comment]
Click reset to defaults on the network sections.

Both Ingress AND direct access are available for the add-on.

**Comment by allanpersson** [comment]
@soapp or see my post ⬆️ https://github.com/home-assistant/hassio-addons/issues/1002#issuecomment-575754651

**Comment by SAOPP** [comment]
@frenck thanks for answer. Of course I did it, but still, I have only one port - it's for vnc.

But, I already see today, after I push 'reset to defaults' it's reset the ports now, and I see the two fields for api and websocket ports.

When I'm will back to home, I check it, and will post about my situation. Thanks homies.

**Comment by SAOPP** [comment]
@frenck & @allanpersson thanks guys! I'm already can send rest api confoguration to my Xiaomi motion sensors, thnaks again all wolrs fine for me now! :) :+1
