### ISSUE TITLE
deconz: add automatic OTA downloading

### ISSUE THREAD

**Issue by jdeluyck** [home-assistant/hassio-addons#1004]
**Home Assistant release with the issue:**
0.40.1

**Last working Home Assistant release (if known):**
N/A

**Operating environment (Hass.io/Docker/Windows/etc.):**
Hassio on RPI3

**Integration:**
deconz
https://www.home-assistant.io/integrations/deconz/

**Description of problem:**
Currently, there is no easy way to download OTA updates for eg. Ikea bulbs, while DeCONZ does support flashing these updates.

Would it be possible to add two configuration parameters to the integration:
```yaml
download_otas: true
download_time: '04:00'
```
that adds a cron job to the container to automatically download the OTA's using the scripts that deconz delivers in /bin ?

```
/bin/ika-otau-dl.sh  
/bin/ledvance-otau-dl.sh 
```

**Comment by olijouve** [comment]
> /bin/ika-otau-dl.sh  
> /bin/ledvance-otau-dl.sh

Actually, it's quite simple for IKEA and LEDVANCE/OSRAM as those scripts are always running and automatically check and download new firmwares every 72 hours.
Firmware updates are not that frequent, waiting from 0 to 3 days max depending last time they checked doesn't seems that bad.
