### ISSUE TITLE
eufy integration doesn't handle T1016 bulb

### ISSUE THREAD

**Issue by kburnes** [home-assistant/hassio-addons#1005]

**Comment by frenck** [comment]
Hi there @kburnes!

This is the add-on GitHub repository, where we handle issues with Hass.io Add-ons.
For raising issues with Home Assistant (and the integrations), please raise an issue at the codebase repository:

<https://github.com/home-assistant/home-assistant/issues>

Thanks! 👍

**Comment by kburnes** [comment]
I have added the issue as requested.
P.S.  Love your youtube videos!

kb
