### ISSUE TITLE
Hass.io Example add-ons no longer working & outdated

### ISSUE THREAD

**Issue by VonXavier** [home-assistant/hassio-addons#1006]
fresh installation, the error occurs cyclically, Any advice?

20-01-12 21:54:12 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/c2eea46b/sync/config.json: required key not provided @ data['arch']. Got None
20-01-12 21:54:12 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/c2eea46b/coffee_maker/config.json: required key not provided @ data['arch']. Got None

Rpi3b+ docker, hassio
Supervisor 195
Home Assistant 0.103.6
arch armv7l
dev false
docker true
hassio true
os_name Linux
python_version 3.7.6
timezone Europe / Warsaw
version 0.103.6
virtualenv false

mode storage
resources 1
views 5

full log: https://pastebin.com/dmBuJd0c

**Comment by frenck** [comment]
The example add-ons are heavily outdated and might need an update.

<https://github.com/home-assistant/hassio-addons-example>

If you remove that repository, the error should be gone.

**Comment by spacegaier** [comment]
@pvizeli @frenck I think this issue is solved by this PR https://github.com/home-assistant/addons-example/pull/6 and could be closed here.

**Comment by frenck** [comment]
Correct! Thanks, @spacegaier 👍
