### ISSUE TITLE
Deconz not discovered after reboot

### ISSUE THREAD

**Issue by chbndrhnns** [home-assistant/hassio-addons#1007]
In my setup, after a reboot of my system, the IP address of the Deconz container was not updated in `.storage/config.config_entries`.  After I retrieved it manually via `docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' addon_core_deconz`, put it in the file and restarted homeassistant, it could recognize Deconz again.

**Comment by frenck** [comment]
Thanks, @chbndrhnns!

I discovered this issue myself as well this weekend, looking into it!

**Comment by stepman0** [comment]
I have a similar issue on the latest version - My deconz is not discovered anymore. I can search for the gateway in the UI, but never find one.
The above mentioned workaround with docker inspect seems already implemented in my system, the ip in `config.config_entries` is correct.
I use Home Assistant 195 in Hass.os 3.8 (virtual machine running on Synology).
Deconz seems to run in background, I can access VNC.
Any suggestions?
