### ISSUE TITLE
deCONZ addon can't upgrade from 3.8 to newer one 5.1 integration always turn up empty.

### ISSUE THREAD

**Issue by eskimos2000** [home-assistant/hassio-addons#1014]
I nearly gave up. I tried all steps from deconz addon page. I tried uninstall addon, restart hass, install new addon, restore devices from backup, integrate again. Nada, always empty. On the phoscan webui all is good, devices are there. On the integration nothing. I have some weird problem which I can not find and solve. Help please.

**Comment by frenck** [comment]
Hi there @eskimos2000,

If the add-on shows the devices correctly, it should work from the add-on endpoint.
I would highly recommend to open up an issue on the Home Assistant repository with as many details as possible, as it seems to be an issue with the integration itself.

<https://github.com/home-assistant/home-assistant/issues/new/choose>

Thanks! 👍
