### ISSUE TITLE
Aqara Magic Cube + Deconz, automation always triggered on Wake-up

### ISSUE THREAD

**Issue by Luke95vl** [home-assistant/hassio-addons#1017]
Hi everyone, I connected the Aqara Magic Cube to Deconz via the addon in Home Assistant, I wanted to create automations, such as turning on the lights when I turn it 90 degrees, and following a guide I used it as a trigger (in the guided creation of HA automations) Device -> Mi Magic Cube (name of the device) -> Device rotated 90 degrees.

Everything is ok here, but when the cube is inactive for a few minutes the cube sends a “Wake-up” signal with event id 7000 on deconz_event and triggers the automation to switch on the lights, just by touching it! I don’t understand how it’s possible because I haven’t touched anything but it happens with any type of movement, even 180 degrees or slide etc, any ideas? It’s a deconz problem?

**Comment by frenck** [comment]
Thank you for reaching out. We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
