### ISSUE TITLE
Feature request: Letsencrypt - Support of ClouDNS acme.sh challenge

### ISSUE THREAD

**Issue by cepxuo** [home-assistant/hassio-addons#1022]
Could you please add support of ClouDNS.net? Here is how it works in general with them: https://www.cloudns.net/wiki/article/186/

They use general acme.sh script.

**Comment by ThomasThomsen01** [comment]
Please also add gratisdns.dk - they also use acme.sh

**Comment by RoganDawes** [comment]
Any chance of getting some more attention on this? I see it was closed due to being ignored at the time, not because it is not possible to support.
