### ISSUE TITLE
Under integration cannot see anything when changed backgroundcolor

### ISSUE THREAD

**Issue by mawi13** [home-assistant/hassio-addons#1023]
If I change the backgroundcolor to something else except Backend selected, I'm not able to see any integration - just a white screen, happens with chromium and firefox. It' just visible when i have backend-selected activated. but I'm able to click on something and the device shows up.

**Comment by frenck** [comment]
Hi there, thanks for reporting an issue, however, this is a frontend issue.
Please report frontend issues here: <https://github.com/home-assistant/home-assistant-polymer/issues>

Thanks! 👍
