### ISSUE TITLE
DECONZ: Entity ID:s changes in Home Assistant.

### ISSUE THREAD

**Issue by karimmarczak** [home-assistant/hassio-addons#1025]
Hi!,

I posted my question on reddit first because seemed fishy I though it is on me or Xiaomi: here is my original question: https://www.reddit.com/r/homeassistant/comments/ddl4m9/xiaomi_aqara_multi_sensor_in_home_assistant_with/

The issue does not seem to be Xiaomi related but overall, the other day I noticed that some of my automatons stopped working, mainly the automation to turn off all the lights when sun is up and none is home. The other things worked fine so I couldn't figure it out until checked the entity ID:s

I have in Deconz a light Group called "Alla Ljus" where I have all the lights that I would turn off in. Originally that mapped to entity ID in Hass to "light.alla_ljus", today I noticed that "light.alla_ljus" is unavailable and there is a working copy "light.alla_ljus_2" which works:
![image](https://user-images.githubusercontent.com/3043429/73240965-de65ae80-41a0-11ea-81e2-02c863416db0.png)

![image](https://user-images.githubusercontent.com/3043429/73240975-e6bde980-41a0-11ea-898c-f922b2ded7e4.png)

I am running Deconz and Home assistant on a Linux environment(Ubuntu Desktop) and in Docker containers, I am not really sure why or when it happens so I am not sure how to reproduce this, but I know it has happened a few times before.

Config is:

    Conbee 2,
    NUC (i5)
    Ubuntu Desktop
    Home assistant in Docker
    deCONZ in Docker

If you want more info, don't hesitate asking I am not sure where to start looking.

**Comment by frenck** [comment]
Hi there,

Please report an issue with Home Assistant. Integrations provide/create entities, not the add-on, hence, it should be reported in the core code base:

<https://github.com/home-assistant/home-assistant/issues>

Thanks! 👍
