### ISSUE TITLE
Deconz - get Ingress error

### ISSUE THREAD

**Issue by oyta** [home-assistant/hassio-addons#1027]
Posting two errors as I think they are related to the Ingress error.

**Setup**
- Hardware: Raspberry Pi 3 Model B with Raspbee.
- Using latest Hassos 3.8, Hassio superviser 195.
- Using the official Deconz addon.

**Current State**
- Testing both through local network and through Nabu Casa.
- Managed to setup Deconz and paired a couple of Zigbee thermometers from Aqara
- Pairing suddenly stopped working, and have not been able to get it going again. Tried reboot several times. Deleted everything existing in Deconz, made a fresh image on the micro SD-card, setup everything again but nothing work. Then all of the sudden I managed to pair a few thermometers again, but it stopped working after a while. No I am not able to pair anything again.
- I do get updates from the few thermometers I did manage to pair.

**Case 1: Settings --> Gateway page in Deconz**
-  I'm rarely able to access the "Settings --> Gateway" page in Deconz.
- When I am able to access it, it says "A new firmware version is available".

![image](https://user-images.githubusercontent.com/7596134/73381920-def86500-42c6-11ea-9b6a-577b30dc2ceb.png)

- It has completed the update, but accessing the same page again it says I need to update.
- It sometimes says that the update fails. I do believe that I get an error message in Hassio when that happens: 
	`20-01-29 17:27:10 ERROR (MainThread) [hassio.api.ingress] Ingress error: None`

![image](https://user-images.githubusercontent.com/7596134/73381963-f899ac80-42c6-11ea-8e91-bfaa6144e523.png)

**Case 2 - pairing new devices**
As I am currently remote, I cannot reset the unpaired devices, however I have noticed that I get some errors looking in the developer portal:

![image](https://user-images.githubusercontent.com/7596134/73382016-0fd89a00-42c7-11ea-9dcd-dfb32091edbd.png)
```
172.30.32.2 - - [29/Jan/2020:18:34:54 +0100] "GET /pwa/developer.js HTTP/1.1" 404 142 "https://[XXX]nabu.casa/api/hassio_ingress/na8hpJ0WepBZr-tkpMhHpB2SFsg_UT2e2drn_6N9KT4/pwa/index.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
	172.30.32.2 - - [29/Jan/2020:18:34:54 +0100] "GET /api/8099BA8C81/config?_=1580319293502 HTTP/1.1" 200 2773 "https://[XXX]nabu.casa/api/hassio_ingress/na8hpJ0WepBZr-tkpMhHpB2SFsg_UT2e2drn_6N9KT4/pwa/index.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
	172.30.32.2 - - [29/Jan/2020:18:34:54 +0100] "GET /api/8099BA8C81/config?_=1580319293503 HTTP/1.1" 200 2773 "https://[XXX]nabu.casa/api/hassio_ingress/na8hpJ0WepBZr-tkpMhHpB2SFsg_UT2e2drn_6N9KT4/pwa/index.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
	172.30.32.2 - - [29/Jan/2020:18:34:54 +0100] "GET /api/8099BA8C81/groups?_=1580319293504 HTTP/1.1" 200 365 "https://[XXX]nabu.casa/api/hassio_ingress/na8hpJ0WepBZr-tkpMhHpB2SFsg_UT2e2drn_6N9KT4/pwa/index.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
	172.30.32.2 - - [29/Jan/2020:18:34:54 +0100] "PUT /api/8099BA8C81/config HTTP/1.1" 503 108 "https://[XXX]nabu.casa/api/hassio_ingress/na8hpJ0WepBZr-tkpMhHpB2SFsg_UT2e2drn_6N9KT4/pwa/index.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
	172.30.32.2 - - [29/Jan/2020:18:34:54 +0100] "GET /api/8099BA8C81/lights?_=1580319293505 HTTP/1.1" 200 12 "https://[XXX]nabu.casa/api/hassio_ingress/na8hpJ0WepBZr-tkpMhHpB2SFsg_UT2e2drn_6N9KT4/pwa/index.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
	172.30.32.2 - - [29/Jan/2020:18:34:55 +0100] "GET /api/8099BA8C81/sensors?_=1580319293506 HTTP/1.1" 200 4485 "https://[XXX]nabu.casa/api/hassio_ingress/na8hpJ0WepBZr-tkpMhHpB2SFsg_UT2e2drn_6N9KT4/pwa/index.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
	172.30.32.2 - - [29/Jan/2020:18:34:55 +0100] "GET /api/8099BA8C81/config?_=1580319293507 HTTP/1.1" 200 2773 "https://[XXX]nabu.casa/api/hassio_ingress/na8hpJ0WepBZr-tkpMhHpB2SFsg_UT2e2drn_6N9KT4/pwa/index.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"
```

**Comment by QbaF** [comment]
This same error here
`ERROR (MainThread) [hassio.api.ingress] Ingress error: None`
But all other seems working ok.
