### ISSUE TITLE
Configurator under HA 0.105.0b0 

### ISSUE THREAD

**Issue by bussio** [home-assistant/hassio-addons#1028]
A file selection is not possible under the current Beta 0.105.0b0 and text appears next to the edit field.

![2020-01-30_17-26-43](https://user-images.githubusercontent.com/48105172/73469288-6ce75500-4386-11ea-8ab2-fcb6190ece8c.jpg)

**Comment by frenck** [comment]
I'm unable to reproduce this issue :(

Have you tried a different browser?

**Comment by bussio** [comment]
> Have you tried a different browser?

i tried on mac with safari, google chrome and firefox. the result is the same for everyone.

**Comment by bussio** [comment]
Very funny, without having changed anything, it works again on all Macs, iPads and iPhones this morning ?! Sorry for the hassle.

**Comment by frenck** [comment]
Don't worry, glad it is resolved for you now!
