### ISSUE TITLE
plese add letsencrypt support aliyun dns  provider

### ISSUE THREAD

**Issue by kylinfedora** [home-assistant/hassio-addons#1029]
Aliyun DNS Authenticator plugin for Certbot is OK!
plese add letsencrypt support aliyun dns  provider!
https://github.com/tengattack/certbot-dns-aliyun

**Comment by kylinfedora** [comment]
acme.sh is also support aliyun dns 
https://github.com/acmesh-official/acme.sh/wiki/dnsapi

**Comment by kylinfedora** [comment]
anybody can help me?

**Comment by ThomasThomsen01** [comment]
If gratisdns.dk could be added - I would be pleased
