### ISSUE TITLE
Tradfri using Deconz does not adjust color

### ISSUE THREAD

**Issue by MysticNynja** [home-assistant/hassio-addons#1032]
I'm using CT lighting because I have the White dimable tradfri bulb with Deconz. It moves the brightness up and down as I would suspect but it does not move the color.

So I am using brightness in the config and it seems to be working fine.

I am trying to set the color and brightness in the Services tool and brightness works, but I cannot find the correct color attribute to send.  I have tried the highlighted parameters and nothing seems to move the color. 

Brightness works though.  

![image](https://user-images.githubusercontent.com/11483359/73569101-5e08ad00-442f-11ea-9655-934d0720eb11.png)

**Comment by FunPsycho** [comment]
I brought this up in the official Deconz repository https://github.com/claytonjn/hass-circadian_lighting/issues/65

**Comment by frenck** [comment]
This is not an add-on issue, please report this for the deCONZ integration:

<https://github.com/home-assistant/home-assistant/issues>

Please note: It might be closed there as well, as you might be redirected to Dresden/deCONZ. However, this location here, the add-on, there is nothing we can do, since we wrap existing applications.

Note 2: I'm using Circadian Lightning with deCONZ and IKEA Tradfri bulbs, and do not experience this issue myself.

**Comment by MysticNynja** [comment]
Can you tell me what event I can send to the Tradfri lights to get them to change color?  I've tried everything noted above, but they do not work.

I can change the color through Deconz, but I would rather work with all the entities inside of HA.

I watched your recent video about replacing the IKEA hub and saw that when you changed the brightness of the bulbs that were connected to circadian lights it did not let them change brightness until you turned off the circadian light state.  Mine does not work like that so maybe I am setting it up incorrectly?

I will take a look at your config and see how yours is set up.  In the mean time If anyone knows what event is called to the IKEA bulbs to change their color I would love to hear it.

I'm also running HASSOS and think I am going to change over to a Linux distro with portainer or something. I've heard that it is a bit more stable that way, but I have no idea why.

**Comment by frenck** [comment]
Depends on the bulb, if it is a color temperature supported bulb, it is, of course, color_temp you need to send.

> I'm also running HASSOS and think I am going to change over to a Linux distro with portainer or something. I've heard that it is a bit more stable that way, but I have no idea why.

That is not related, and will not give you a different experience. As a matter of fact, the same docker containers are used for both setups you suggested.


Please note, Circadian lightning is a custom integration and is thus not supported by Home Assistant.

**Comment by MysticNynja** [comment]
I am using the white color temperature bulb.  

Ok I will hold off on changing over since the same docker container is used, makes sense to not change. 

https://www.ikea.com/us/en/p/tradfri-led-bulb-e26-1000-lumen-wireless-dimmable-white-spectrum-opal-70408492/

I think the real issue comes from not being able to send color values to the bulb, I can't do it with events outside of circadian lights.  If I can get it to work with an event I can just write something to do it myself
