### ISSUE TITLE
hass.io CEC Scanner still on version 2, update to version 2.2 not showing up

### ISSUE THREAD

**Issue by docholiday** [home-assistant/hassio-addons#1041]
Hi there,

could anyone please tell me, how I can update the CEC Scanner in hass.io to the current version 2.2?
In my hass.io installation (see below) it is still on version 2 with no update showing up, while here on github the changelog says it should be on 2.2.

hassio > info
arch: armv7
channel: stable
hassos: "3.8"
homeassistant: 0.104.3
hostname: hassio
logging: info
machine: raspberrypi3
supervisor: "195"
supported_arch:
- armv7
- armhf

Version 2 has a bug that affects (atleast) Raspberry Pi Model 3B and therefor me:
See https://github.com/home-assistant/hassio-addons/issues/815
and https://github.com/home-assistant/hassio-addons/blob/master/cec_scan/CHANGELOG.md 

I installed CEC Scanner for the first time 5 days ago. Back then version 2.2 was obviously already available for other people to install.

**Comment by waded** [comment]
I wasn't able to reproduce the issue on a clean install today (Feb 3). I got the same base:

```
~ $ hassio info
arch: armv7
channel: stable
hassos: "3.8"
homeassistant: 0.104.3
hostname: hassio
logging: info
machine: raspberrypi3
supervisor: "195"
supported_arch:
- armv7
- armhf
```

Then when I proceed to install the addon I get 2.2:

```
~ $ hassio addon info core_cec_scan | grep version
last_version: "2.2"
version: "2.2"
```

It could be helpful if someone familiar with how addons are managed in hassio could give us ideas for where to look. If this is an older install of hass.io perhaps there's a mechanism by which it'd get stuck on an old version or addon source.

**Comment by pvizeli** [comment]
Please post the supervisor logs after you reload the addons on store

**Comment by docholiday** [comment]
Sorry for the delayed answer, I was on vacation. Something was broken in my hassio installation. Other modules weren't the newest ones as well. I did a complete reinstall, now everything is working again.
