### ISSUE TITLE
Unable to logon and reset password

### ISSUE THREAD

**Issue by imanpeeman** [home-assistant/hassio-addons#1049]
Out of the blue (after auto update to Deconz 5.1?) i'm no longer able to logon to the phoscon app. my raspbee is detected, the logon screen is displayed, but i'm not able to logon. 
When resetting the password (within 10 minutes after boot) I got the reset password dialog, I can press it (the websites returns with 'The password is set to default') I can also click on the green button stating 'set new password' but nothing happens.

I'm using the Raspbee with FW 0x26330500 and HassOS 3.8 and Hass.IO 104.3.

maybe there is a relation / side effect  with #947 ?

Is there a way out?

**Comment by zaurak27** [comment]
I am experiencing the same issue as **imanpeeman**. Even the rollback to 5.0 did not doo the trick. Neither my old password nor the reset is working. I made a clean install without success.
Anybody knows a resolution?

**Comment by Flipper84** [comment]
same issue here,
 but when dongle connected to a win10 computer and  deconz addon the login works.

**Comment by mbo18** [comment]
Same here since this evening. 
I'm running HA 104.3 and I have just updated to Supervisior 198 and OS 3.9.

**Comment by LeonCB** [comment]
Same here.
Running OS 3.9, Supervisor 198.

**Comment by modestpharaoh** [comment]
Same issue here... I didn't even have auto update for deconz

**Comment by Luke95vl** [comment]
Same after updating to 0.105 and OS 3.9

**Comment by ukmgranger** [comment]
Same here

**Comment by fuzzysteve** [comment]
Same here

**Comment by mbo18** [comment]
I think it's related to Supervisor 198.
Have you all updated to this release?

**Comment by fuzzysteve** [comment]
I have

**Comment by brugk000** [comment]
#metoo

**Comment by Flipper84** [comment]
Supervisor 198
HassOs 3.9
core 104.3

**Comment by adromiscus** [comment]
Same problem after last update; password is not recognised, can't log in

**Comment by FlyingPersian** [comment]
Same here. I didn't even update, maybe it auto updated.

**Comment by Tungvall** [comment]
. I tried everything and once i managed to reset the password the default one (delight) didnt work at all.
I unplugged the Conbee from my rapsberry and installed it into my PC.
I booted it up and got into it. Once there i started the web app (same i see in in hass) and had some issues. I got back in and managed to pick a password.

I logged out and back in with the new one to confirm it worked, which it did. 
Back into HassIO (rpi3b+something) it's back to showing my "Login failed."
I also removed the Deconz addon but with no luck.

**Comment by rchamp26** [comment]
same thing literally happened to me just now. everything was working. just set this new add on now added devices, then went back to deconz web ui, and it didn't know the password i set. i tried resetting and same things as others. 

i only have a few lights, so tried uninstalling, rebooting whole server, nothing. somehow the 'password' is still saved somewhere. 

so i also just noticed 0.105.0 is out. so upgraded to that, tried installing deconz, nope, still seems to detect old settings somewhere.

**Comment by ymoona** [comment]
Same issue here. Yesterday all was working fine and tonight I cant login. Password reset seems to work but I still cant login. After I found that it did not work anymore I update hassio to new supervisor. Still broken, I also tried to restore from backup also does not work. The backup is fine I used it to restore my whole system yesterday and then It was working. 

In the logfile of hassio I see this when I try to logon:
`20-02-05 23:12:33 ERROR (MainThread) [hassio.api.security] Invalid token for access /ingress/1tKyMxTZlK3TE2hufIHqsTCVSywa0R6Bs_OG805tShI/api/`

And in the log of the addon:
`172.30.32.2 - - [06/Feb/2020:00:14:07 +0100] "GET /api/hassio_ingress/1tKyMxTZlK3TE2hufIHqsTCVSywa0R6Bs_OG805tShI/api/config?_=1580944446976 HTTP/1.1" 403 140 "blob:http://hassio.local:8123/cbd611f7-5e44-4694-a743-4cb47442c0de" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18363"`

Removing the addon and restoring from backup does also not help.

**Comment by cogneato** [comment]
I don't use deconz but I'm seeing more of this in discord along with
```ERROR (MainThread) [hassio.api.security] Invalid token for access /ingress/NR_foGYZmUZp7PGTbuA9nGaVxftgdyjpwp2siheZETU/api/```

 I would avoid tearing things apart/down for now and wait for devs to see.

**Comment by Luke95vl** [comment]
if you log in from [your home assistant ip address]:40850 it works and you can log in.
If you try to log in from the sidebar in Home Assistant log I get

`20-02-05 21:55:32 ERROR (MainThread) [hassio.api.security] Invalid token for access /ingress/sx8YEmeZuUvtxr978Uy75IzE4MgWbCZLMalO4ehQYcg/api/`

**Comment by hmbusch** [comment]
I got this issue too after upgrading to Hassio 0.105. When I connect via port 40850, everything works fine, when I use the deConz WEB-UI via Ingress, login is denied and I'm seeing a lot of these erros in the main log:

`2020-02-06 01:34:11 ERROR (MainThread) [pydeconz.websocket] Client connection error
2020-02-06 01:34:44 ERROR (MainThread) [pydeconz.websocket] Client connection error
2020-02-06 01:35:00 ERROR (MainThread) [pydeconz.websocket] Client connection error
2020-02-06 01:35:15 ERROR (MainThread) [pydeconz.websocket] Client connection error`

**Comment by Gawronnek** [comment]
Same here.
Running OS 3.9, Supervisor 198.

**Comment by 3ative** [comment]
Let's NOT fill up another thread with "Same here"'s we should assume we all have the same issue.
Solutions only please :)

**Comment by rchamp26** [comment]
> Let's NOT fill up another thread with "Same here"'s we should assume we all have the same issue.
> Solutions only please :)

understood. i did the workaround @hmbusch  mentioned. I just set up an external accessible port, and reconfigured my deconz integration to use that vs using the ingress and auto discovery. looks like the issues is the token that is hard coded in the official hassio addon.

**Comment by ymoona** [comment]
> 
> 
> if you log in from [your home assistant ip address]:40850 it works and you can log in.
> If you try to log in from the sidebar in Home Assistant log I get
> 
> `20-02-05 21:55:32 ERROR (MainThread) [hassio.api.security] Invalid token for access /ingress/sx8YEmeZuUvtxr978Uy75IzE4MgWbCZLMalO4ehQYcg/api/`

This works, but you need to expose the port in the settings on the dezonz addon.
Also my old password still works, so all my tries to reset the password did not work.

**Comment by Kirorus** [comment]
i have same issue.
my setup is Intel NUC (Ubuntu 19.10) with hassio image in Virtualbox. I can't login to conbee2.
Old addon from marthoc Hass.io Addons work stable.

**Comment by henkie86** [comment]
same here

**Comment by Gawronnek** [comment]
update do 0.105.1 nic  u mnie nie zmieniło, nadal nie mogę się zalogować ani zmienić hasła
90/5000
update to 0.105.1 has not changed anything, I still can't log in or change my password

**Comment by JamieP83** [comment]
> og in from [your home assistant ip address]:40850

im getting the same issue however this comment worked in the interim

**Comment by imanpeeman** [comment]
@pvizeli Thanks for the prompt response and the work you've done. 

To others: the fix isn't included in 105.1 so we have to wait a few more hours ;) https://github.com/home-assistant/home-assistant/releases/tag/0.105.1

**Comment by frenck** [comment]
@imanpeeman It is not related to the core, it is related to the supervisor. Supervisor 199 is now available. Go to the Supervisor panel -> System tab -> Reload the Supervisor. An update should now appear.

**Comment by MauricioXavier13** [comment]
This is happening again @frenck. 

Core 2024.5.2
Supervisor 2024.04.4
Operating System 12.2
Frontend 20240501.1
