### ISSUE TITLE
Deconz: unable to login with password

### ISSUE THREAD

**Issue by jjanderson** [home-assistant/hassio-addons#1051]
Hi,

Suddly (I don't login often) but possibly since the latest update, I am now no longer able to login to my conbee gateway via ingress.

I simply get a password incorrect. Yes, I do have the right password.

I dno't want to remove and then add the addon without doing a backup. I can't login to do the backup.

Please help?

Thanks

**Comment by frenck** [comment]
There has been an issue with Supervisor 198, this has been fixed just now.
Supervisor 199 is available that addresses this issue.

Go to the Supervisor panel -> System Tab -> Reload the Supervisor. An update should appear.

**Comment by jjanderson** [comment]
BINGO!

Thanks for your help.... All sorted

**Comment by imanpeeman** [comment]
Indeed, new supervisor solved the issue. i'm able to logon with the default password.

Thanks!
