### ISSUE TITLE
DuckDNS: Installation instructions does not mention how to enable https

### ISSUE THREAD

**Issue by Maximus97** [home-assistant/hassio-addons#1054]
As the addon includes Let's Encrypt and says it has integrated HTTPS support, it should be mentioned in the addon instructions that one must enter the following to the configurations.yaml in order to enable HTTPS.
```
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
```

I was stuck with only http working because I did not enter these details in my `configuration.yaml`, and there was no information about it in the addon details.

**Comment by frenck** [comment]
Unfortunately, that is not the only use case or method available.
The add-on provides SSL certificates, for use with HTTPS, however, it can be in Home Assistant Core, an add-on, a reverse proxy, etc.

**Comment by Maximus97** [comment]
Yeah, I understand that it has different use cases, but the ones you mentioned are not mentioned in the addon information. In the addon information it clearly states "Automatically update your Duck DNS IP address with **integrated** HTTPS support via Let's Encrypt.". For a beginner like me, it really sounds that https will be enabled after following the instructions which is not the case. I'm a beginner but that is just my two cents :)

**Comment by Toffi32** [comment]
Hi Maximus97,
had the same issue. Thanks for posting your solution.

After I modified my configuration.yaml with the above, I restarted.
I was in panic, because I could not enter Home Assistant then via local IP.
Only via [my_domain].duckdns.org I am able to reach the web interface.
Same for you?
Any idea how to solve this?

**Comment by Toffi32** [comment]
While typing the message above, I had an idea. Try "https://hassio:8123/" instead of local IP (192.168. ...).
Now I´m in again. 
Strange.

**Comment by Maximus97** [comment]
Hi Toffi32. Glad I could help you.

It's mentioned in this step 5 of this [guide](https://www.home-assistant.io/docs/ecosystem/certificates/lets_encrypt/) that the traditional way of accessing Home Assistant is no longer possible after making the change we did. Instead, one has to use https://***:8123 where *** is the local ip adress of the machine you are running home assistant on. Typing hassio like you seems to have the same effect, I have no idea why.

**Comment by Maximus97** [comment]
Hi Toffi32. Glad I could help you.

It's mentioned in step 5 of this [guide](https://www.home-assistant.io/docs/ecosystem/certificates/lets_encrypt/) that the traditional way of accessing HA is no longer possible after making the change we did. Instead, one has to use https://***:8123 where *** is the local ip adress of the machine you are running HA on. Typing Hassio like you seems to have the same effect, I have no idea why.

I should mention that I did not follow this guide to set it up but i found it when I tried to solve my original problem. The guide is linked in this wiki page: https://www.home-assistant.io/docs/configuration/remote/

**Comment by Maximus97** [comment]
Hi Toffi32. Glad I could help you.

It's mentioned in step 5 of this guide that the traditional way of accessing HA is no longer possible after making the change we did. Instead, one has to use https://***:8123 where *** is the local ip adress of the machine you are running HA on. Typing hassio instead like you did seems to have the same effect and I don't know why.

I should mention that I did not follow this guide to set it up but i found it when I tried to solve my original problem. The guide is linked in this wiki page: https://www.home-assistant.io/docs/configuration/remote/

**Comment by Maximus97** [comment]
Hi Toffi32. Glad I could help you.

It's mentioned in step 5 of this [guide](https://www.home-assistant.io/docs/ecosystem/certificates/lets_encrypt/) that the traditional way of accessing HA is no longer possible after making the change we did. Instead, one has to use https://**local ip**:**port** where **local ip** is the local ip adress of the machine you are running HA on and **port** is the external port you used in your port forward rule. Typing hassio instead of **local ip** like you did seems to have the same effect and I have no idea why.

I should mention that I did not follow this guide to set it up but i found it when I tried to solve my original problem. In case you wonder how I found it, the guide is linked in this wiki page: https://www.home-assistant.io/docs/configuration/remote/

**Comment by Maximus97** [comment]
Hi Toffi32. Glad I could help you.

It's mentioned in step 5 of this [guide](https://www.home-assistant.io/docs/ecosystem/certificates/lets_encrypt/) that the traditional way of accessing HA is no longer possible after making the change we did. Instead, one has to use https://**local ip**:**port** where **local ip** is the local ip adress of the machine you are running HA on and **port** is the external port you used in your port forward rule. Typing hassio instead of **local ip** like you did seems to have the same effect and I have no idea why.

I should mention that I did not follow this guide to set it up but i found it when I tried to solve my original problem. In case you wondering how I found it, the guide is linked in this wiki page: https://www.home-assistant.io/docs/configuration/remote/

**Comment by Maximus97** [comment]
Hi Toffi32. Glad I could help you.

It's mentioned in step 5 of this [guide](https://www.home-assistant.io/docs/ecosystem/certificates/lets_encrypt/) that the traditional way of accessing HA is no longer possible after making the change we did. Instead, one has to use https://**local ip**:**port** where **local ip** is the local ip adress of the machine you are running HA on and **port** is the external port you used in your port forwarding rule. Typing hassio instead of **local ip** like you did seems to have the same effect and I have no idea why.

I should mention that I did not follow this guide to set it up but i found it when I tried to solve my original problem. In case you wondering how I found it, the guide is linked in this wiki page: https://www.home-assistant.io/docs/configuration/remote/
