### ISSUE TITLE
About zte h108n my router is v2.5 how do i steup it ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [home-assistant/hassio-addons#1055]
![IMG_20200206_144204](https://user-images.githubusercontent.com/20546638/73937972-ec2cd980-48ee-11ea-81e7-4ee5cc11c89c.png)
![IMG_20200206_144219](https://user-images.githubusercontent.com/20546638/73937975-f222ba80-48ee-11ea-806e-521cc478d37c.png)

Which one should I chose?

**Comment by pvizeli** [comment]
Such question are for the discord forum
