### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by SteveRMann** [home-assistant/hassio-addons#1060]
I am trying to recover from a crash of my Home assistant installation.  I can't get Samba to start, so I decided to uninstall it and reinstall, basically start over.
But I get an error from Hass.io:
`Failed to uninstall addon, Unknown Error, see logs`

The logs on that screen are blank, and since there are a dozen log files in Hass.io, I don't know where else to look.

Any tips would be appreciated.

**Comment by frenck** [comment]
Can you provide the output of the supervisor log when that happens?
Supervisor panel -> System tab -> Logs

**Comment by SteveRMann** [comment]
Thanks, but I've decided to just start over with a new installation.
