### ISSUE TITLE
Disabling port 1883 & 1884 in HassIO for Mosquitto broker addon

### ISSUE THREAD

**Issue by mikelon** [home-assistant/hassio-addons#1062]
I've tried to disable ports 1883 and 1884 from the HA addon UI by blanking the two ports.
![image](https://user-images.githubusercontent.com/1365532/74105843-55b02080-4b59-11ea-91ef-86cff712c917.png)

When I save and restart the addon I see the ports are still in use
`1581263578: Opening ipv4 listen socket on port 1883.`
`1581263578: Opening ipv6 listen socket on port 1883.`
`1581263578: Opening websockets listen socket on port 1884.`

**Comment by frenck** [comment]
Yes, it will say that, but does not expose them to the outside world.

The port handling is handled on system level, not the application level.

**Comment by mikelon** [comment]
OK thanks for the clarification.
