### ISSUE TITLE
SSH freezing every few minutes

### ISSUE THREAD

**Issue by mmiller7** [home-assistant/hassio-addons#1064]
Since getting the v200 Home Assistant update today my SSH session keeps freezing after a few minutes.  I can open another session, but it does the same thing.

I've tried SSH from my computer directly as well as SSH thru the "web UI", both have the same problem.  I've tried restarting the SSH addon as well as rebooting the whole system.

Running HassOS on x86_64 (Linux KVM host)

There's nothing that I see printed in the /config/home-assistant.log and I can't find any other logs to check.

**Comment by pvizeli** [comment]
Look like an issue with your hypervisor host

**Comment by mmiller7** [comment]
How so?  Everything seems to work flawlessly except the SSH connection?
