### ISSUE TITLE
how duckdns add-on detect the ipv4 address?

### ISSUE THREAD

**Issue by zidane114** [home-assistant/hassio-addons#1070]
I am running HA in docker on openwrt system. I installed the duckdns add-on and nginx ssl proxy add-on for remote access by https, all is good. But I have a trouble when I use ShadowSocksR Plus+ package on openwrt to turn on the vpn. duckdns will detect my ipv4 address as vpn server's address, not my openwrt system's wan IP address. Any idea that how  I can solve this problem?

**Comment by frenck** [comment]
The IPv4 address is determined by DuckDNS, not the add-on.

For more information about DuckDNS, please consult the documentation and FAQ of DuckDNS itself.

The add-on allows you to override the IP address if you want to. The downside, of course, it that it is no longer dynamic. See the add-on documentation for information about that.
