### ISSUE TITLE
CEC Scanner "Open - vc_cec could not be initialised" (HassOS 3.10, Rpi3)

### ISSUE THREAD

**Issue by lucadentella** [home-assistant/hassio-addons#1081]
Hi

fresh install of Hassio:

- HassOS 3.10
- Supervisor 200
- CEC Scanner add-on 2.4

when I start:

`[17:02:00] INFO: Starting CEC client scan...`
`opening a connection to the CEC adapter...`
`ERROR:   [              58]	RegisterLogicalAddress - CEC is being used by another application. Run "tvservice --off" and try again.`
`ERROR:   [              58]	Open - vc_cec could not be initialised`
`ERROR:   [              58]	could not open a connection (try 1)`

thanks

**Comment by pvizeli** [comment]
Please post the `ha info`

**Comment by lucadentella** [comment]
~ $ ha info
arch: armv7
channel: stable
hassos: "3.10"
homeassistant: 0.105.4
hostname: hassio
logging: info
machine: raspberrypi3
supervisor: "200"
supported_arch:
- armv7
- armhf
timezone: Europe/Rome

**Comment by lucadentella** [comment]
Hi! Today I had the opportunity do some tests and this is what I discovered.

I'm using the latest OS (HassOS 3.12) and supervisor (209).

If I boot the Raspberry **without** connecting an external TV via HDMI, I always get the error reported in the first message, no matter if I connect an HDMI device later.

If I boot the Raspberry **with a TV connected** I can see boot messages and the CEC Scanner works fine. It works even if I disconnect the TV and connect a different HDMI device (for example a home theather system).

It seems that HDMI interface is initialized only if something is connected at boot.

Hope this can help... if the issue won't be fixed at least to give some hints to other users who'll be facing the same problem.
