### ISSUE TITLE
Tradfri & OSRAM not available after update to deCONZ 5.2 and HASS 0.105.5

### ISSUE THREAD

**Issue by larsteeke** [home-assistant/hassio-addons#1097]
Hi
I updated the HASS to the mentioned version and the deCONZ Add-In to 5.2. 

My TRADFRI and OSRAM components are now on unavailable in HASS, working in deCONZ.

Has anyone seen the problem, too??

Thx

**Comment by frenck** [comment]
I'm running those devices as well, everything up and running normally.

**Comment by pvizeli** [comment]
No issues. Look into logs, maybe deconz rebuild your network
