### ISSUE TITLE
Lets Encrypt Add-on run.sh: line 88

### ISSUE THREAD

**Issue by ThomasThomsen01** [home-assistant/hassio-addons#1102]
The below config 

email: me@mail.dk
domains:
  - ha.mydomain
certfile: fullchain.pem
keyfile: privkey.pem
challenge: http
dns: {}

Generates the error

[18:12:55] INFO: Selected http verification
/run.sh: line 88: DNS_PROVIDER: unbound variable

After upgrade to version 4.6

**Comment by BoneheadFraggle** [comment]
Same here after upgrade with same config.

**Comment by runew0lf** [comment]
same issue for me

**Comment by lupumihai** [comment]
Same for me, following this subject.
Thanks

**Comment by bkardol** [comment]
I noticed this aswell. The issue just got fixed by @pvizeli (thanks for that 👍). I can confirm it works now.

Refresh your addons and update Lets Encrypt to 4.7.

**Comment by frenck** [comment]
Please update the add-on, the issue has been addressed. 👍
