### ISSUE TITLE
UI=OK but cant connect to any of my zigbee devices.

### ISSUE THREAD

**Issue by hefal** [home-assistant/hassio-addons#1106]
**im about to cry my, entire house is stuck with all the lights set to ON and i have 100+ lights.**

All i did was to add three more bulbs to my setup, everything went fine and a couple of hr's later i rebooted HA to find the deconz didnt function properly. Cant use my switches/motions sensors/control my lights in any way.

ive tried to "alt+click" on my deconz gateway "advanced options" button and reset to my previous 

https://i.imgur.com/o36ue3B.png

But that didnt help, it also causes "http://192.168.1.225:8123/core_deconz" to display a white page reading " 502 Bad Gateway"

I tried unplugging the lights that i added, restarting several times both HA/deconz. Pulled the deconz usb in/out but no luck. Running latest versions of both as of today.

I have been at this for the past hours trying to google someone with a similar issue but the solutions they've applied dosen't do it for me. Any suggestions are welcome, i strongly feel this is above my technical expertise :(

This is a snapshot of my log from HA/deconz:

https://pastebin.com/k3VGsxL7

**Comment by pvizeli** [comment]
Just restart the add-on and remove the HA integration and readd it after you restart HA. You don't need full reboot the device if you don't pull out the stick.

> ive tried to "alt+click" on my deconz gateway

This is very high level and can damage you network. Do that only if you think that you have the skills to know what you exactly does.
