### ISSUE TITLE
FEATURE request: Support GoDaddy in the Letsencrypt add-on

### ISSUE THREAD

**Issue by JANogueira** [home-assistant/hassio-addons#1111]
Hi,
posting again as requested by @netweaver1970 on the #946:
GoDaddy also has an (by the looks of it) usable API to be used by the LetsEncrypt addon.
Here is a nice write-up on how to integrate/script it in a CertBot way so I think it can work also (if supported/coded accordingly) in the hassio addon.
http://pbxhacks.com/automating-lets-encrypt-ssl-certs-via-godaddy-dns-challenge/

Thanks for having a look at for inclusion in future versions.

Cheers,
Geert

**Comment by LanceMcCarthy** [comment]
I would love this option, thank you.

**Comment by RockNRollGeek** [comment]
Another +1 for this. Glad I looked to see if this was an existing request before putting a new one in. Due to GoDaddy's dns dominance in the market still, combined with the fact that I use let'sencrypt/certbot add-ons elsewhere (ie: pfsense) that have supported godaddy for some time now, was surprised that the HA Letsencrypt add-on didn't have that functionality. Would definitely be ecstatic to see this.

**Comment by JANogueira** [comment]
Hi All,

Please add this feature.

**Comment by shoguevara** [comment]
+1

**Comment by JANogueira** [comment]
Hi All,

Can you please confirm if Godaddy is on the roadmap?
Thanks

**Comment by LanceMcCarthy** [comment]
Team: If there's a not an inherent GoDaddy API, please share the work item and I can take a whack at it. 

I am a developer, but have not done any hassio addons, if you can also point me to the relevant docs (and an example of an existing letsecrypt source), I am happy to build this.

**Comment by ludeeus** [comment]
Hi 👋
This is the issue tracker for the add-ons, for feature requests please raise those on the forum https://community.home-assistant.io/c/feature-requests, thanks 👍 

@LanceMcCarthy Nice!, there is no "work item", the source is in this repo <https://github.com/home-assistant/hassio-addons/tree/master/letsencrypt>
General documentation for add-on development: <https://developers.home-assistant.io/docs/hassio_addon_index>
If you are stuck, there is a #devs_addons channel on discord.

**Comment by LanceMcCarthy** [comment]
Thanks Joakim! I'll dig deeper and see if certbot has any fundamental issues with Godaddy's API. My initial finds don't look good, there's still [a PR open](https://github.com/certbot/certbot/pull/6135).

However, I might be able to take the same approach shown here:

```
:
# cleanup
#
#   certbot GoDaddy DNS TXT challenge cleanup (get rid of record after use)
#
#   Usage:  certbot renew --manual --manual-auth-hook PATHTO/authenticate
#		--manual-cleanup-hook PATHTO/cleanup
#

############################################################
# GoDaddy API Credentials
GODADDY_API_KEY="6jQYEZTvqLE_UhmbcGZdEYsnw5gxYN6zA"
GODADDY_API_SECRET="Ubr4zeYzw7iy2M24ADxii"
GODADDY_URL="https://api.godaddy.com/"
############################################################

# Replace all of a Domain's type of DNS Records

DNS_REC_TYPE=TXT
DNS_REC_NAME="previous_acme-challenge"
DNS_REC_DATA="$CERTBOT_VALIDATION"
DNS_REC_TTL="600"

curl -X PUT "${GODADDY_URL}/v1/domains/${CERTBOT_DOMAIN}/records/${DNS_REC_TYPE}" -H  "accept: application/json" -H  "Content-Type: application/json" -H  "Authorization: sso-key ${GODADDY_API_KEY}:${GODADDY_API_SECRET}" -d "[{ \"data\": \"${DNS_REC_DATA}\", \"name\": \"${DNS_REC_NAME}\", \"ttl\": ${DNS_REC_TTL} }]"
```

Then, an auto renew script:

```
:
# Certbot cronjob script to renew certificates
#

# show certificates
/usr/bin/certbot certificates

# renew certificates near expiry
/usr/bin/certbot renew  --manual --manual-auth-hook /etc/letsencrypt/renewal-hooks/auth/authenticate --manual-cleanup-hook /etc/letsencrypt/renewal-hooks/auth/cleanup
```

Finally the CRON job itself:

```
# renew (if near expiry) SSL certificate(s)
22 0,12 * * * /etc/letsencrypt/cron_renew_script
```

CREDIT - http://pbxhacks.com/automating-lets-encrypt-ssl-certs-via-godaddy-dns-challenge/

**Comment by RockNRollGeek** [comment]
Not sure if it's helpful or not, but perhaps a solution can be found looking into pfsense's source code? I know they also use letsencrypt/acme for renewing certs, and the module just asks for your godaddy api key info to use one of your own domains on GD to renew the cert against, which is why I figured if they're using acme/letsencrypt to be able to use/challenge against godaddy it might be somewhat easy to implement for HA. *shrug*

**Comment by ludeeus** [comment]
@LanceMcCarthy  (I guess?) made a forum topic, please use that for further discussions about it 👍 
<https://community.home-assistant.io/t/godaddy-support-for-letsencrypt-add-on/194616/2>

**Comment by mrmichaelrb** [comment]
I created a GoDaddy DNS add-on which registers my public IP with my GoDaddy DNS hosting and also creates an SSL certificate with Let’s Encrypt:

[New Home Assistant Add-on: GoDaddy DNS](https://community.home-assistant.io/t/new-home-assistant-add-on-godaddy-dns/329052)
