### ISSUE TITLE
Configurator (File Explorer): no Copy & Paste in Safari.

### ISSUE THREAD

**Issue by uspino2** [home-assistant/hassio-addons#1113]
Ever since the last few upgrades I lost the ability to copy and paste bits of text code in Configurator (File Explorer now). Shortcuts work, but no copy/cut/paste option in the right-click menu. I'm using Safari.

**Comment by frenck** [comment]
Add-ons wrap existing applications, in this case the `hass-configurator`.

Please report the issue with the upstream repository:

<https://github.com/danielperna84/hass-configurator/issues> 

Thanks! 👍
