### ISSUE TITLE
Can't add repository to home assistant ([hassio.utils.json] Can't read json from /data/addons/git/e724ce20/repository.json

### ISSUE THREAD

**Issue by bigbroo2** [home-assistant/hassio-addons#1118]
Trying to add it to home assistant but the log gives this error
Can you please help?

20-02-20 10:12:11 INFO (MainThread) [hassio.store.git] Clone add-on https://github.com/home-assistant/hassio-addons repository
20-02-20 10:12:14 ERROR (MainThread) [hassio.utils.json] Can't read json from /data/addons/git/e724ce20/repository.json: [Errno 2] No such file or directory: '/data/addons/git/e724ce20/repository.json'
20-02-20 10:12:14 WARNING (MainThread) [hassio.store.data] Can't read repository information from /data/addons/git/e724ce20/repository.json
20-02-20 10:12:14 INFO (MainThread) [hassio.store] Load add-ons from store: 43 all - 0 new - 0 remove

**Comment by frenck** [comment]
The repository you are trying to add, is not maintained by Home Assistant.

Please contact the repository owner.
