### ISSUE TITLE
Configurator fails to load without internet access

### ISSUE THREAD

**Issue by unixispower** [home-assistant/hassio-addons#1123]
The Configurator add-on does not load if there is no internet access on the machine loading the web interface. My browser's inspector reports failed requests to cdnjs.cloudflare.com, code.jquery.com, drive.google.com, *.githubusercontent.com, and *.googleusercontent.com. I think the issue is caused by resources and scripts being loaded from various CDNs. Is it possible to embed the scripts and dependencies in the add-on so it can be used without the need to be online?

**Comment by pvizeli** [comment]
Please report here: https://github.com/danielperna84/hass-configurator

We deliver only the software
