### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by gronat** [home-assistant/hassio-addons#1124]
Unable to SSH when using a key nor using just a PWD. However, does work on RPi 3 B+, does not work on RPi 4 1GB.

**How to reproduce the error:**
flash the image RPi 4 B 32 bit (recommended)
https://github.com/home-assistant/operating-system/releases/download/3.11/hassos_rpi4-3.11.img.gz
Update
Install the Terimnal & SSH add-on
**Config:**
authorized_keys: []
password: 'test123test'

Save, Start

**Open terminal:**
ssh root@192.168.1.xxx

ssh: connect to host 192.168.1.xxx port 22: Connection refused

**Note:**
Does work on RPi 3 B+ with 32bit image

**Comment by wimpie007** [comment]
samen issue here, RPI3.
ssh: connect to host 192.168.x.y port 22: Connection refused
works in sidebar. Since i update to last version. (yesterday)

**Comment by frenck** [comment]
Yep, assigning a port is the solution for this 👍

**Comment by gronat** [comment]
Apparently, the port was disabled by default, my mistake.
