### ISSUE TITLE
feature request deconz: parameter for target deCONZ version

### ISSUE THREAD

**Issue by DAMEK86** [home-assistant/hassio-addons#1128]
Since deCONZ 2.05.73 beta is used, i have troubles pairing sensors of the same type (new sensor override old one).
It would be nice to manually select the target version of deCONZ to use a older version until a new version fix the problem.

**Comment by frenck** [comment]
That is not possible, add-ons ship pre-build and thus the version is already in the final image that gets downloaded.

If you want to run things differently, we either recommend extending the add-on image as a base for a new image, or, maintain your own version of the add-on.
