### ISSUE TITLE
use SSH Key with a passphrase

### ISSUE THREAD

**Issue by poudenes** [home-assistant/hassio-addons#1130]
Hi All,

is it possible to use SSH Key with a passphrase inside the File Editor

https://github.com/home-assistant/hassio-addons/tree/master/configurator

**Comment by frenck** [comment]
No, that is not possible, as there is no secure way to input such a passphrase.

Please note, we use GitHub for tracking issues, not for support or questions.
If you are in need of support, please use the community forum or the discord chat. Thanks! 👍
