### ISSUE TITLE
Build-In Homematic OCCU loose settings

### ISSUE THREAD

**Issue by xasz** [home-assistant/hassio-addons#1135]
## The Problem
OCCU Looses custom gateway settings on reboot
If you do not wish or can because of missing settings to configure the OCCU via the config file. The OCCU Gateway settings will be lost on reboot. 
I am not sure, if this is a bug or behavior by design.
It would be nice to set up settings in the Configuration of the OCCU via the Web-Interface.
For example if you add an Gateway like an "LAN Configuration HM-HFG-LAN" to the Gateways it works perfectly. As soon as you reboot the OCCU, the setting is not in the OCCU anymore.
I could not figure out in the code, why this happens and how to avoid this behavior.

## Environment
Tested on a fresh installation from HassIO on an Raspberry Pi 4
Installed Addons: File Explorer, Homematic OCCU

## Suggestions
Extend the homematic config section of the addon, to support all gateway types, which are supported by the occu or bring up a new flag like - Use_OCCU_Config = true and then do not overwrite these settings anymore.

**Comment by pvizeli** [comment]
Sorry, I don't understand what you said. You need use the add-on options to change connection property. Don't use the ReGaHss webinterface for add the gateway, they is just for pairing only. I have no LAN gateway, I did this implementation on a small paper from EQ3 and there are no documentations. So that means without reverse engeenering, I can't fix the bug maybe

**Comment by xasz** [comment]
Ok, when we cannot use the webinterface to configure it, we need to have an option in the config file.
As far as i understood, it should be enough to add an option for the RF Type on wired.
I am really not into docker and that kind of scripts, but i saw you set the interface to a fixed value HMWLGW in "hassio-addons/homematic/data/run.sh".
According to the webinterface which is included in the original, the option can be set to globalLGWTypes (HMLGW2,LANIF,HMWLGW). the other settings should be the same.
This information i have got from \occu-master\WebUI\www\webui\webui.js.
By any chance can you add an optional wired_type ? Or can i test this in my configuration?
I have now idea, where the run.sh is saved on my local hassio installation.
