### ISSUE TITLE
deCONZ v2.05.74

### ISSUE THREAD

**Issue by stickpin** [home-assistant/hassio-addons#1139]
New deCONZ has been released yesterday: https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_74

Any chance to update the addon?

Thanks in advance!

**Comment by pvizeli** [comment]
please update the changelog + version

**Comment by stickpin** [comment]
@pvizeli based on the phoscon [tweet](https://twitter.com/phosconde/status/1232691852232593415) there are many bug fixes.
They are not providing a normal changelog.

**Comment by stickpin** [comment]
Created PR for this issue: https://github.com/home-assistant/hassio-addons/pull/1140

**Comment by stickpin** [comment]
PR Merged: https://github.com/home-assistant/hassio-addons/pull/1140
Closing the issue.
