### ISSUE TITLE
USB Device not found

### ISSUE THREAD

**Issue by layer8df** [home-assistant/hassio-addons#1143]
I am trying to use the deCONZ integration but it constantly fails to find my ConbeeII Stick. If I access the container I can not even find a directory "serial" under /dev.

Here is my log output:
[18:56:51] INFO: Waiting for device...
[18:57:51] FATAL: No device /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2118569-if00 found!
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.

Is this a known issue? Is there a fix?
THX

**Comment by pvizeli** [comment]
Please more details about your system

**Comment by alex3305** [comment]
@pvizeli I have the same issue on my system (Intel NUC running Debian 10) with my ConBee II stick. 

I experience this issue after restarting the deCONZ container. If I wait a little longer (for instance a minute or two) the container starts just fine.

**Comment by alex3305** [comment]
@pvizeli Thanks for your release. It already seems a bit better. I've tested it out, but it didn't solve this issue completely though...

```
[13:58:55] INFO: Waiting for device...
[14:01:56] FATAL: No device /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1964507-if00 found!
```

After another manual restart of the container, the USB stick itself was found though:

```
[14:02:05] INFO: Waiting for device...
[14:03:18] INFO: Starting VNC server...
```

Doing a stat within the container reveals the following, which looks fine by me:

```
root@core-deconz:/# stat /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1964507-if00
  File: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1964507-if00 -> ../../ttyACM0
  Size: 13              Blocks: 0          IO Block: 4096   symbolic link
Device: 59h/89d Inode: 3397494     Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-03-05 14:03:36.168648701 +0100
Modify: 2020-03-05 14:03:25.736708402 +0100
Change: 2020-03-05 14:03:25.736708402 +0100
 Birth: -

root@core-deconz:/# stat /dev/ttyACM0
  File: /dev/ttyACM0
  Size: 0               Blocks: 0          IO Block: 4096   character special file
Device: 59h/89d Inode: 3395053     Links: 1     Device type: a6,0
Access: (0660/crw-rw----)  Uid: (    0/    root)   Gid: (   20/ dialout)
Access: 2020-03-05 14:05:20.736708402 +0100
Modify: 2020-03-05 14:05:20.736708402 +0100
Change: 2020-03-05 14:03:25.736708402 +0100
 Birth: -
```

Perhaps something fishy is going on when accessing the device by `/dev/serial/by-id/` instead of `/dev/tty*`?

**Comment by pvizeli** [comment]
Maybe it going into: https://github.com/home-assistant/supervisor/issues/1569 with udev is not correct running on the host.
