### ISSUE TITLE
FEATURE Request: Address settings Piface.

### ISSUE THREAD

**Issue by roland1970** [home-assistant/hassio-addons#1150]
Is it possible to make an address setting in the configuration, then is it possible to connect more then one piface.
For the MCP23017 (i2c) is these option integrated but for the MCP23S17SP which is used in the piface is this not integrated.

**Comment by frenck** [comment]
which add-on are we talking about here?

I'm kinda lost on where to place this.

**Comment by roland1970** [comment]
It’s for the piface.
Sorry, if I place this in the wrong group.

**Comment by frenck** [comment]
I guess? 

This is the repository for Home Assistant add-ons, and thus the issue tracker related to bug reports on those.

Sounds to me like you have an issue request for the Home Assistant Core. Please use the Community Forum for doing feature requests 👍
