### ISSUE TITLE
LetsEnrypt - MythicBeasts

### ISSUE THREAD

**Issue by Veldkornet** [home-assistant/hassio-addons#1159]
Would it be possible to add [MythicBeasts](https://www.mythic-beasts.com/support/api/dnsv2) to the list of DNS providers for the LetsEncrypt add-on?
Or at least help out in how to get it configured manually somehow?

**Comment by Veldkornet** [comment]
No bot 🤖 give the people time to work man

**Comment by Veldkornet** [comment]
No

**Comment by ludeeus** [comment]
Hi 👋
This is the issue tracker for the add-ons, for feature requests please raise those on the forum https://community.home-assistant.io/c/feature-requests, thanks 👍 

If you need support with the existing methods please use our forum or discord, thanks 👍 
https://www.home-assistant.io/help/
