### ISSUE TITLE
New version Google Assistant SDK 2.3.0 installation problem

### ISSUE THREAD

**Issue by fotisbaco** [home-assistant/hassio-addons#1161]
When i try to install v2.3.0 receive error "Failed to install addon, Unknown Error, see logs"

The error from system log is: 

ERROR (SyncWorker_14) [hassio.docker.interface] Can't install homeassistant/armv7-addon-google_assistant:2.3.0 -> 404 Client Error: Not Found ("manifest for homeassistant/armv7-addon-google_assistant:2.3.0 not found: manifest unknown: manifest unknown").

**Comment by neromatic** [comment]
First time setting up Home Assistant, running into issues left and right. First the NEST Thermostat and now this one here.

**Comment by frenck** [comment]
404 generally means you don't have enough disk space left to complete the update operation.
Can you make sure you have enough free?

**Comment by crwilcox** [comment]
@frenck I have the same issue.

```
20-03-03 17:50:21 INFO (SyncWorker_9) [supervisor.docker.interface] Pull image homeassistant/armv7-addon-google_assistant tag 2.3.0.
20-03-03 17:50:28 ERROR (SyncWorker_9) [supervisor.docker.interface] Can't install homeassistant/armv7-addon-google_assistant:2.3.0 -> 404 Client Error: Not Found ("manifest for homeassistant/armv7-addon-google_assistant:2.3.0 not found: manifest unknown: manifest unknown").
```

My disk usage is 6.7% with 25.4GiB Free. Memory free is 685 MiB.

**Comment by fotisbaco** [comment]
Hi @frenck  

Thanks for your reply. My disk usage is 19.6% and free memory 451mb

HasssOS 3.11
Supervisor 207

Regards

**Comment by khoss** [comment]
Maybe it will be helpful: hassio 3.11 supervisor 207, addon 2.3.0
not working. Log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:25:30] INFO: Installing/Updating service client_secrets file
./run: line 26: basio::log.info: command not found
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
tried to reinstall addon - no luck

**Comment by grunjol** [comment]
Public Images for 2.3.0 are not updated for armv7 nor armhf architectures

Check it
https://hub.docker.com/r/homeassistant/armv7-addon-google_assistant/tags

only amd64 arch was updated as you can see here
https://hub.docker.com/r/homeassistant/amd64-addon-google_assistant/tags
