### ISSUE TITLE
deCONZ Gateway Page is not loaded correctly on Safari 13.0.2 (15608.2.30.1.1)

### ISSUE THREAD

**Issue by akinomeroglu** [home-assistant/hassio-addons#1163]
Hello,

I am using deconz plugin (updated version on the opening date of issue) with Ingress support on my Tinker Board. When I am trying to reach gateway page it is not loaded correctly on Safari. I can see background is loaded but page does not show anything after that.

Here is console output

[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (settings-gateway2.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (developer.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (underscore-min.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (backbone-min.map, line 0)

Page loads correctly when I reach very same page via Google Chrome. I am using SSL (valid certificate from Let's encrypt) and I can provide any other info if you need.

Thanks,

**Comment by Viktor45** [comment]
got same issue again, i think this is reincarnation of #943 
ingress auth token somehow doesn't passes correctly to gateway2.js and a lot of js resources it loads.

**Comment by Viktor45** [comment]
got this error in system log every time while opening gateway settings in deconz

`WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None`

**Comment by jonskoglund** [comment]
Gateway page doesn’t load in any iOS browser. Not in Chrome and not in Safari. Homeassistant App has same issue.

**Comment by frenck** [comment]
Chrome on iOS = Safari. Apple does not allow other browser engines. So those applications on iOS devices all use Safari as the engine (including Chrome on iOS).

**Comment by rchl** [comment]
That problem seems to be reproducible after re-installing deconz addon.

**Comment by mpepping** [comment]
Still an issue.

**Comment by crosenkr** [comment]
Still an issue.

**Comment by akinomeroglu** [comment]
Still an issue
