### ISSUE TITLE
Unknown entity when using Xiaomi Smart Plug

### ISSUE THREAD

**Issue by alexlopezcifuentes** [home-assistant/hassio-addons#1164]
I have perfectly connected a Xiaomi Smart Plug into Deconz addon. It adds the following entities:

- The actual switch which can be on and off.
- Current power Sensor in Watts (W).
- Another sensor which is in kWh which I assume is power consumption.

However, this last sensor's value is always unknown. Any idea why?

**Comment by frenck** [comment]
We have no idea, the better place to ask this, is @ dresden/deconz.
Add-ons wrap existing software, we don't write or maintain the deconz/phoscon app.
