### ISSUE TITLE
Google Assistant SDK 2.3.1

### ISSUE THREAD

**Issue by TVDLoewe** [home-assistant/hassio-addons#1170]
After updating to Version 2.3.1 the Addon seams to have issues to start up.
I'm on a Raspberry Pi 3 (Hass.io)

Example of  Starting (The last 2 lines are repeated indefinitely):

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:49:29] INFO: Installing/Updating service client_secrets file
[11:49:29] INFO: Starting Home Assistant GAssisant SDK...
[11:49:31] INFO: Installing/Updating service client_secrets file
[11:49:31] INFO: Starting Home Assistant GAssisant SDK...
[11:49:33] INFO: Installing/Updating service client_secrets file
[11:49:33] INFO: Starting Home Assistant GAssisant SDK...

**Comment by fotisbaco** [comment]
I have the same issue. Any hint about this?

**Comment by samhaa** [comment]
Same issue here on Raspberry Pi 3b+. I'v tried to create new API with same results.

**Comment by nutellaismyname** [comment]
i have the same problem. 

 INFO: Installing/Updating service client_secrets file
 INFO: Starting Home Assistant GAssisant SDK...

this just keeps repeating

**Comment by mannte** [comment]
Same for me. I downgrade to an older version.

**Comment by samhaa** [comment]
> Same for me. I downgrade to an older version. Anyway we can help fixing it?

Is there a way to downgrade SDK without snapshot?

**Comment by mannte** [comment]
I am not sure if it is the best and most easy way but, you could download the old version from GitHub and add it as an local add-on. 

You can download the right version by clicking <> (Browse the repository at this point in the history) on this page: https://github.com/home-assistant/hassio-addons/commits/master
and then select download.
Then you basically follow this manual: https://developers.home-assistant.io/docs/hassio_addon_tutorial
But then use the files that you downloaded instead.

**Comment by TVDLoewe** [comment]
> I am not sure if it is the best and most easy way but, you could download the old version from GitHub and add it as an local add-on.
> 
> You can download the right version by clicking <> (Browse the repository at this point in the history) on this page: https://github.com/home-assistant/hassio-addons/commits/master
> and then select download.
> Then you basically follow this manual: https://developers.home-assistant.io/docs/hassio_addon_tutorial
> But then use the files that you downloaded instead.
> 
> I have not tested it but I think that should work.

i tried this but ran in some other issues.
with no change to the addons files the system log shows "Pull image homeassistant/armv7-addon-google_assistant tag 2.3.1."

in order to build the image from the addon files, rather than downloading it from somewhere, i removed the line "Pull image homeassistant/armv7-addon-google_assistant tag 2.3.1." from the config.json.

now the log shows "Start build local/armv7-addon-google_assistant:2.3.1" (takes around 25 min on raspberry py 4)

the resulting image seams to differ from the downloaded one. now i get different errors when starting this addon.

Anny suggestions, what went wrong? i am not much familiar with docker.

**Comment by TVDLoewe** [comment]
Hm got it working finally.
I changed the GOOGLE_SDK version back in build.json to this:
    "GOOGLE_GRPC_VERSION": "0.2.0",
    "GOOGLE_LIBRARY_VERSION": "1.0.0",
    "GOOGLE_SDK_VERSION": "0.5.0",
    "GOOGLE_AUTH_VERSION": "1.6.3",
    "REQUESTS_OAUTHLIB_VERSION": "1.2.0",
    "CHERRYPY_VERSION": "18.1.1"

**Comment by mannte** [comment]
> in order to build the image from the addon files, rather than downloading it from somewhere, i removed the line " "image": "homeassistant/{arch}-addon-google_assistant"." from the config.json.>

Sorry forgot to mention that part indeed. But good to hear that you got it working.

I have got another error now. Maybe you have any clue where it comes from?  Because unfortunately don't have time to look into it myself now.

`ALSA lib dlmisc.c:254:(snd1_dlobj_cache_get) Cannot open shared library /usr/lib/arm-linux-gnueabihf/alsa-lib/libasound_module_pcm_pulse.so
[FATAL:audio_input_stream.cc(47)] Input device could not be opened: default`

**Comment by KennyM86** [comment]
> Hm got it working finally.
> I changed the GOOGLE_SDK version back in build.json to this:
> "GOOGLE_GRPC_VERSION": "0.2.0",
> "GOOGLE_LIBRARY_VERSION": "1.0.0",
> "GOOGLE_SDK_VERSION": "0.5.0",
> "GOOGLE_AUTH_VERSION": "1.6.3",
> "REQUESTS_OAUTHLIB_VERSION": "1.2.0",
> "CHERRYPY_VERSION": "18.1.1"

Where can I find this ? Trying to do the same. (using Hassio)

**Comment by mannte** [comment]
In the build.json file:

[https://github.com/home-assistant/hassio-addons/blob/master/google_assistant/build.json](https://github.com/home-assistant/hassio-addons/blob/master/google_assistant/build.json)

**Comment by TVDLoewe** [comment]
I think the older version of this addon used some different method to interface the Sound system of the py (ALSA lib). This interface seams to be no longer supported. So i used the latest commit of this git repo and changed build.json and config.json as described. This way the i get the current working sound interface with the older but working GOOGLE_SDK_VERSION": "0.5.0

**Comment by slayorktc** [comment]
Where do I find the files on hass to update? With samba the addons folder was empty even though I have installed a few addons. Will this bug be fixed? Should I watch for an update to the GOOGLE ASSISTANT SDK addon?

**Comment by mannte** [comment]
> Where do I find the files on hass to update? 

You can download them from here

> With samba the addons folder was empty even though I have installed a few addons. 

Add-on installed trough hassio/the supervisor will not show in the samba folder.

> Will this bug be fixed? Should I watch for an update to the GOOGLE ASSISTANT SDK addon? 

Probably if somebody is willing to put the time in to find the bug. For now @TVDLoewe could make a pull request for the (temporary) downgrade solution he found.

**Comment by TVDLoewe** [comment]
> Probably if somebody is willing to put the time in to find the bug. For now @TVDLoewe could make a pull request for the (temporary) downgrade solution he found.

Yes i thought about that, but i am not quiet sure how this works. The Docker Image should be updated too, so you don't need to build it on the py.

**Comment by slayorktc** [comment]
> > Where do I find the files on hass to update?
> 
> You can download them from here
> 
> > With samba the addons folder was empty even though I have installed a few addons.
> 
> Add-on installed trough hassio/the supervisor will not show in the samba folder.
> 
> > Will this bug be fixed? Should I watch for an update to the GOOGLE ASSISTANT SDK addon?
> 
> Probably if somebody is willing to put the time in to find the bug. For now @TVDLoewe could make a pull request for the (temporary) downgrade solution he found.

Where the file located and how do I access them? I have visual studio and samba installed. Is it just the build.json file or another as well?

**Comment by mannte** [comment]
It think it will automatically rebuild if a new version is released, but I am not sure either. 

Here you can read how to make a pull request:
[https://developers.home-assistant.io/docs/development_submitting/](https://developers.home-assistant.io/docs/development_submitting/)

I hope you can figure it out! Because I don't have time to do it till somewhere next week.

**Comment by mannte** [comment]
> > > Where do I find the files on hass to update?
> > 
> > 
> > You can download them from here
> > > With samba the addons folder was empty even though I have installed a few addons.
> > 
> > 
> > Add-on installed trough hassio/the supervisor will not show in the samba folder.
> > > Will this bug be fixed? Should I watch for an update to the GOOGLE ASSISTANT SDK addon?
> > 
> > 
> > Probably if somebody is willing to put the time in to find the bug. For now @TVDLoewe could make a pull request for the (temporary) downgrade solution he found.
> 
> Where the file located and how do I access them? I have visual studio and samba installed. Is it just the build.json file or another as well?

You need to download all the files from git-hub and create a "new" add-on as I mentioned in one of my earlier posts (click on the link). Then make the changes to the build.json and the config.json as @TVDLoewe showed. Then you upload the complete folder of your "new" add-on to the samba folder. Or just wait for a fix.

**Comment by TVDLoewe** [comment]
you should be able to update to version 2.3.2

**Comment by slayorktc** [comment]
Did the update get pushed? Only see 2.3.1 inside hassio

**Comment by mannte** [comment]
I got the update (HassIO/supervisor) and it seems to work.

**Comment by slayorktc** [comment]
I got that update as well but google assistant SDK still shows 2.3.1 not 2.3.2

**Comment by slayorktc** [comment]
Log still showing:

[13:06:50] INFO: Installing/Updating service client_secrets file
[13:06:50] INFO: Starting Home Assistant GAssisant SDK...

**Comment by slayorktc** [comment]
reboot the whole hass box and update shows up now.

**Comment by slayorktc** [comment]
My log is still filling up every second with 
[13:06:50] INFO: Installing/Updating service client_secrets file
[13:06:50] INFO: Starting Home Assistant GAssisant SDK...

Did 2.3.2 fix it for others?

**Comment by mannte** [comment]
Yes mine is working fine again. I came from an older version (I think 2.2.0) because it downgraded through a snapshot. Maybe a reinstall works?

**Comment by slayorktc** [comment]
uninstall and reinstall worked. Great work.

**Comment by slayorktc** [comment]
The documentation says to confirm ENGINE Bus STARTED but I want to make sure the empty config message isn't a problem. Also, once this is installed how to I actually send commands? What should be added to my configuration.yaml? Should notify.google_assistant show up in services?

[22:34:34] INFO: Installing/Updating service client_secrets file
[22:34:34] INFO: Starting WebUI for handling OAuth2...
[30/Mar/2020:22:34:35] ENGINE Listening for SIGTERM.
[30/Mar/2020:22:34:35] ENGINE Listening for SIGHUP.
[30/Mar/2020:22:34:35] ENGINE Listening for SIGUSR1.
[30/Mar/2020:22:34:35] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.
[30/Mar/2020:22:34:35] ENGINE Started monitor thread 'Autoreloader'.
[30/Mar/2020:22:34:35] ENGINE Serving on http://0.0.0.0:9324
[30/Mar/2020:22:34:35] ENGINE Bus STARTED

**Comment by slayorktc** [comment]
I think I got the addons mixed up. Can I running google assistant commands, like broadcast with Google assistant SDK? After further researching, is the google assistant SDK for hooking a microphone to my hass instance only? I was hoping to send commands manually. I found this post.

https://community.home-assistant.io/t/community-hass-io-add-on-google-assistant-webserver-broadcast-messages-without-interrupting-music/37274/597

I didn't realize these were two different addons. Is this correct?

**Comment by slayorktc** [comment]
> uninstall and reinstall worked. Great work.

Spoke too soon. Had to re-authinicate with google using LOCAL_IP:9324. Logged into google and generated a key. Right when I went back to paste it and click submit the page errors out and says it can not connect. That normal? Well, regardless, the same bug spamming my log file is back.

[23:48:20] INFO: Installing/Updating service client_secrets file
[23:48:20] INFO: Starting Home Assistant GAssisant SDK...

**Comment by slayorktc** [comment]
I think this is what I am looking for.

https://github.com/Apipa169/Assistant-Relay-for-Hassio

**Comment by mannte** [comment]
This in not the right place to discuss this but...
The Google Assistant SDK add-on "creates" a google assistant on you devices similar to the Google Assistant on you phone or Home Mini. However, it is a bit limited so you are not able to do things like listen to Spotify, Google Music and I think broadcasting to the device is also not supported. You can however broadcast from it to another device.

If you want to control your lights and other Home Assistant stuff then you need to setup the Google assistant integration: https://www.home-assistant.io/integrations/google_assistant/ 
or the DialogFlow integration: https://www.home-assistant.io/integrations/dialogflow/

Through one of those it might also be possible to broadcast messages in combination with the Text-To-Speech integrating but the add-on you found could also work.

Regarding the missing configuration error. The add-on does need a configuration and an credentials file, so you probably did not follow al the steps correctly. Read carefully and make sure you do all of them!

**Comment by mannte** [comment]
Oh and off course your Home Assistant instance needs to be accessible from the outside world. For example with the DuckDNS add-on or through a NGIX proxy.

**Comment by Bram-diederik** [comment]
Its 2021 and I think i have this problem

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[23:58:09] INFO: Installing/Updating service client_secrets file
[23:58:09] INFO: Starting Home Assistant GAssisant SDK...
[23:58:11] INFO: Installing/Updating service client_secrets file
[23:58:11] INFO: Starting Home Assistant GAssisant SDK...
[23:58:13] INFO: Installing/Updating service client_secrets file
[23:58:13] INFO: Starting Home Assistant GAssisant SDK...
[23:58:15] INFO: Installing/Updating service client_secrets file
[23:58:15] INFO: Starting Home Assistant GAssisant SDK...
[23:58:17] INFO: Installing/Updating service client_secrets file
[23:58:17] INFO: Starting Home Assistant GAssisant SDK...
[23:58:19] INFO: Installing/Updating service client_secrets file
[23:58:19] INFO: Starting Home Assistant GAssisant SDK...
[23:58:21] INFO: Installing/Updating service client_secrets file
[23:58:21] INFO: Starting Home Assistant GAssisant SDK...```
