### ISSUE TITLE
Deconz Conbee 2 detected as Raspbee

### ISSUE THREAD

**Issue by mbo18** [home-assistant/hassio-addons#1172]
I don't know if it's the last update to the Deconz add-on or Supervisor release 208 but since one of those updates, my conbee 2 is detected as a Raspbee:

> 21:47:36:104 CTRL. 3.16.221:47:36:175 COM: --dev: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2133629-if00 **(RaspBee)**
...
> 21:47:40:862 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
21:47:40:892 COM: --dev: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2133629-if00 **(RaspBee)**
21:47:41:849 Announced to internet https://phoscon.de/discover
...
> 21:47:47:080 New websocket 172.30.32.1:46488 (state: 3) 
21:47:51:381 COM: --dev: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2133629-if00 **(RaspBee)**
21:47:51:410 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26490700.bin.GCF
21:47:51:471 Device firmware version 0x264A0700

I'm using HA 106.5, OS 3.11, Supervisor 209, Deconz add-on 5.3.1 on a Tinkerboard S

**Comment by fribse** [comment]
I've seen this as well, I removed the deconz integration and readded it, and then it saw it correctly again, not really sure whats going on

**Comment by frenck** [comment]
Hi!

Thanks for opening up an issue, the add-on does not determine the device, but deCONZ/Phoscon does. Please report this issue upstream with Dresden.

From our end, there is not much we can do about this.

Thanks 👍
