### ISSUE TITLE
File Editor Bug: Not possible to navigate folder structure after migrating onto SSD/USB

### ISSUE THREAD

**Issue by Tamadite** [home-assistant/hassio-addons#1174]
**ENVIRONMENT**
Home Assistant Core: 0.106.2
Host System: HassOS 3.12
Supervisor ver.: 209
File Editor ver: 4.7
Server: Raspberry Pi 3 B+

**ADD-ON BUG DESCRIPTION**
Add-on: File Editor
Short Description: not possible to navigate folders using File Editor

**BACKGROUND**
I migrated from SD to SSD/USB. I did a full snapshot and restored it on the new SSD/USB. I am booting and running HA on SSD/USB only (no SD card any longer).

**SITUATION**
After the migration I am not able to navigate the HA folder structure any longer. I have restarted the File Editor and reinstalled it without any positive result.
I am stuck in the `config/` folder.

**Comment by frenck** [comment]
This is not a bug, but a feature.

By default, the add-on will lock you into the `/config` folder. If you want to access more, you can disable the basepath enforcement.

For more information, see the add-on manual:

<https://github.com/home-assistant/hassio-addons/blob/master/configurator/README.md#option-enforce_basepath-required>
