### ISSUE TITLE
Feature request: Rename of automatically created groups

### ISSUE THREAD

**Issue by fribse** [home-assistant/hassio-addons#1175]
When I pair my IKEA controller directly with an IKEA bulb the deconz creates a group automatically.
They are not shown in the deconz interface.
As all the group names are the same, they are imported into HA as _2 _3 _4 etc.
If the integration is removed and then readded, the numbers will not be the same, and then any automations and such will be all wrong.

It would be great to be able to rename the groups, so they will remain the same.

**Comment by frenck** [comment]
This is not related to the add-on, but the integration.

We use GitHub for tracking issues, not for providing support or tracking feature requests.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
