### ISSUE TITLE
mosquitto addon not start

### ISSUE THREAD

**Issue by rplath** [home-assistant/hassio-addons#1179]
mosquitto addon not start    no log

**Comment by frenck** [comment]
Anything in the supervisor system logs?

**Comment by rplath** [comment]
hey

sorry my english is not the best.

how can i find this?

gruß
rené

**Comment by frenck** [comment]
Supervisor panel -> System tab -> Logs.

**Comment by rplath** [comment]
did you get my answer email?

**Comment by frenck** [comment]
Please use the public channels, thanks.

**Comment by rplath** [comment]
`20-03-11 14:16:19 INFO (SyncWorker_10) [supervisor.docker.interface] Restart homeassistant/raspberrypi4-homeassistant
20-03-11 14:16:46 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance
20-03-11 14:23:49 INFO (MainThread) [supervisor.addons] Create Home Assistant add-on data folder /data/addons/data/core_mosquitto
20-03-11 14:23:49 INFO (SyncWorker_3) [supervisor.docker.interface] Pull image homeassistant/armv7-addon-mosquitto tag 5.1.
20-03-11 14:24:34 INFO (MainThread) [supervisor.addons] Add-on 'core_mosquitto' successfully installed
20-03-11 14:27:51 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-03-11 14:28:05 ERROR (SyncWorker_12) [supervisor.docker] Can't start addon_core_mosquitto: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_core_mosquitto (2b0c4e13333e638bbff67142a8f74e9dd58dcf5ea1bc1df2e34a8fa2609bdeaf): Error starting userland proxy: listen tcp 0.0.0.0:1883: bind: address already in use")
20-03-11 14:30:31 INFO (SyncWorker_15) [supervisor.docker.interface] Clean addon_core_mosquitto application
20-03-11 14:30:34 ERROR (SyncWorker_15) [supervisor.docker] Can't start addon_core_mosquitto: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_core_mosquitto (488a211488f36e10da141ad87f92276b1198792d587085cd63c7e6e88e0e98bf): Error starting userland proxy: listen tcp 0.0.0.0:1883: bind: address already in use")`

**Comment by rplath** [comment]
`20-03-11 14:16:19 INFO (SyncWorker_10) [supervisor.docker.interface] Restart homeassistant/raspberrypi4-homeassistant
20-03-11 14:16:46 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance
20-03-11 14:23:49 INFO (MainThread) [supervisor.addons] Create Home Assistant add-on data folder /data/addons/data/core_mosquitto
20-03-11 14:23:49 INFO (SyncWorker_3) [supervisor.docker.interface] Pull image homeassistant/armv7-addon-mosquitto tag 5.1.
20-03-11 14:24:34 INFO (MainThread) [supervisor.addons] Add-on 'core_mosquitto' successfully installed
20-03-11 14:27:51 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-03-11 14:28:05 ERROR (SyncWorker_12) [supervisor.docker] Can't start addon_core_mosquitto: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_core_mosquitto (2b0c4e13333e638bbff67142a8f74e9dd58dcf5ea1bc1df2e34a8fa2609bdeaf): Error starting userland proxy: listen tcp 0.0.0.0:1883: bind: address already in use")
20-03-11 14:30:31 INFO (SyncWorker_15) [supervisor.docker.interface] Clean addon_core_mosquitto application
20-03-11 14:30:34 ERROR (SyncWorker_15) [supervisor.docker] Can't start addon_core_mosquitto: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_core_mosquitto (488a211488f36e10da141ad87f92276b1198792d587085cd63c7e6e88e0e98bf): Error starting userland proxy: listen tcp 0.0.0.0:1883: bind: address already in use")`

**Comment by rplath** [comment]
`20-03-11 14:16:19 INFO (SyncWorker_10) [supervisor.docker.interface] Restart homeassistant/raspberrypi4-homeassistant
20-03-11 14:16:46 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance
20-03-11 14:23:49 INFO (MainThread) [supervisor.addons] Create Home Assistant add-on data folder /data/addons/data/core_mosquitto
20-03-11 14:23:49 INFO (SyncWorker_3) [supervisor.docker.interface] Pull image homeassistant/armv7-addon-mosquitto tag 5.1.
20-03-11 14:24:34 INFO (MainThread) [supervisor.addons] Add-on 'core_mosquitto' successfully installed
20-03-11 14:27:51 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-03-11 14:28:05 ERROR (SyncWorker_12) [supervisor.docker] Can't start addon_core_mosquitto: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_core_mosquitto (2b0c4e13333e638bbff67142a8f74e9dd58dcf5ea1bc1df2e34a8fa2609bdeaf): Error starting userland proxy: listen tcp 0.0.0.0:1883: bind: address already in use")
20-03-11 14:30:31 INFO (SyncWorker_15) [supervisor.docker.interface] Clean addon_core_mosquitto application
20-03-11 14:30:34 ERROR (SyncWorker_15) [supervisor.docker] Can't start addon_core_mosquitto: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_core_mosquitto (488a211488f36e10da141ad87f92276b1198792d587085cd63c7e6e88e0e98bf): Error starting userland proxy: listen tcp 0.0.0.0:1883: bind: address already in use")`

**Comment by frenck** [comment]
`Error starting userland proxy: listen tcp 0.0.0.0:1883`

This means port 1883 on your system is already in use by another application. Ports cannot be re-used or shared by multiple applications. Either stop the application that is currently using that port, or change ports of the application you are trying to install to resolve that conflict.

**Comment by rplath** [comment]
i found an old iobroker setup on my rasp!   
delete iobroker and now works fine 

thx

**Comment by frenck** [comment]
Good to hear you got it resolved :+1:
