### ISSUE TITLE
Language send text to speaker

### ISSUE THREAD

**Issue by dannymertens** [home-assistant/hassio-addons#1180]
If I click on the media player then I have the option to send a text to a Sonos speaker works fine, but the language is in English and I need this in Dutch is this possible, tried a lot of things already but can't find it :-(

This is also for the normal media card so maybe there is an option to change this for the complete HA environment, but can't find anything :-(

I'm new in HA so probably something stupid from my side? below the code that I have now, not ready yet but we're getting there :-P

Thanks in advance!

Kind regards,

Danny

custom_header:
  editor_warnings: false
  exceptions:
    - conditions:
        user: custom_menu
      config:
        kiosk_mode: true
  hidden_tab_redirect: false
resources:
  - type: module
    url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
  - type: module
    url: /community_plugin/custom-header/custom-header.js
title: Mertens Geysen
views:
  - badges: []
    cards:
      - cards:
          - image: /local/images/hack.png
            tap_action:
              action: navigate
              navigation_path: /lovelace/sonos-woonkamer
            type: picture
          - image: /local/images/hack.png
            tap_action:
              action: navigate
              navigation_path: /lovelace/Sonos
            type: picture
          - image: /local/images/hack.png
            tap_action:
              action: navigate
              navigation_path: /lovelace/Sonos
            type: picture
          - image: /local/images/hack.png
            tap_action:
              action: navigate
              navigation_path: /lovelace/Sonos
            type: picture
          - image: /local/images/hack.png
            tap_action:
              action: navigate
              navigation_path: /lovelace/sonos-bureau
            type: picture
        type: horizontal-stack
      - artwork: full-cover
        entity: media_player.woonkamer
        hide:
          controls: true
          icon: true
          info: true
          name: true
          power: true
          progress: false
          source: true
          volume: true
        theme: blue_night
        type: 'custom:mini-media-player'
      - entity: media_player.woonkamer
        hide:
          icon: true
          name: true
          power: true
          progress: true
          shuffle: false
        info: scroll
        speaker_group:
          entities:
            - entity_id: media_player.woonkamer
              name: Sonos Woonkamer
            - entity_id: media_player.kast_woonkamer
              name: Sonos Woonkamer kast
            - entity_id: media_player.sonos_bureau
              name: Sonos Bureau
            - entity_id: media_player.sonos_one_badkamer
              name: Sonos Badkamer
            - entity_id: media_player.sonos_michael
              name: Sonos Michael
            - entity_id: media_player.master_slaap
              name: Master Slaapkamer
          expanded: false
          platform: sonos
          show_group_count: true
          sync_volume: true
        type: 'custom:mini-media-player'
    path: sonos-woonkamer
    title: Sonos Woonkamer
  - badges: []
    cards:
      - cards:
          - image: /local/images/hack.png
            tap_action:
              action: navigate
              navigation_path: /lovelace/Sonos
            type: picture
          - image: /local/images/hack.png
            tap_action:
              action: navigate
              navigation_path: /lovelace/Sonos
            type: picture
          - image: /local/images/hack.png
            tap_action:
              action: navigate
              navigation_path: /lovelace/Sonos
            type: picture
          - image: /local/images/hack.png
            tap_action:
              action: navigate
              navigation_path: /lovelace/Sonos
            type: picture
          - image: /local/images/hack.png
            tap_action:
              action: navigate
              navigation_path: /lovelace/Sonos
            type: picture
        type: horizontal-stack
      - content: '**Sonos Bureau**'
        theme: blackened
        type: markdown
      - artwork: full-cover
        entity: media_player.sonos_bureau
        hide:
          controls: true
          icon: true
          info: true
          name: true
          power: true
          progress: false
          source: true
          volume: true
        theme: blue_night
        type: 'custom:mini-media-player'
      - entity: media_player.sonos_bureau
        hide:
          controls: false
          icon: true
          name: true
          power: true
          progress: true
          shuffle: false
          source: false
          volume: false
        info: scroll
        speaker_group:
          entities:
            - entity_id: media_player.sonos_bureau
              name: Sonos Bureau
            - entity_id: media_player.woonkamer
              name: Sonos Woonkamer
            - entity_id: media_player.kast_woonkamer
              name: Sonos Woonkamer kast
            - entity_id: media_player.sonos_one_badkamer
              name: Sonos Badkamer
            - entity_id: media_player.sonos_michael
              name: Sonos Michael
            - entity_id: media_player.master_slaap
              name: Master Slaapkamer
          expanded: false
          platform: sonos
          show_group_count: true
          sync_volume: true
        type: 'custom:mini-media-player'
    icon: ''
    path: sonos-bureau
    theme: blackened
    title: Sonos Bureau

**Comment by frenck** [comment]
Hi there @dannymertens,

This is the GitHub issues repository for Home Assistant Add-ons. Your issue is related to integrations / the Home Assistant core, and is not a bug report, but a question.

We use GitHub solely for tracking bugs. If you are in need for support, please try our Discord chat server or our community forum.

<https://www.home-assistant.io/help/>

Thanks! 👍
