### ISSUE TITLE
Make NGINX able to handle custom locations / if it can improve the documentation.

### ISSUE THREAD

**Issue by SamPhoenix91** [home-assistant/hassio-addons#1181]
If this is possible then please improve the documentation on how to do so as it is not clear in the slightest.

Put a file in share folder or custom nginx folder which will allow for the creation of files either like adding more files to avaliable-sites folder in regular nginx or as an extension of the config file.

**Comment by frenck** [comment]
Is it already supported to load any custom nginx setup from the shares folder...
This is documented and part of the add-on configuration.

I'm kinda unsure what it is you are looking for / pin-point the exact issue you are trying to raise...

../Frenck

**Comment by SamPhoenix91** [comment]
All that is documented is the configuration options, not how to set up a configuration file or what is allowed and what isn't.

When I tried adding my configuration file I get 
nginx: [emerg] "server" directive is not allowed here in /share/nginx_proxy_default.conf:1

**Comment by frenck** [comment]
Not sure how to describe that, you are referring to a configuration question on NGINX, not the add-on now...

**Comment by SamPhoenix91** [comment]
I have copied the file from a working NGINX server, so clearly something is not the same in setting up said file as opposed to a regular server? 
Perhaps a different language that gets converted or something? But there is no example or anything of a customize file to base off so I do not know...
