### ISSUE TITLE
Mqtt add-on works but no discovery

### ISSUE THREAD

**Issue by Chuckame** [home-assistant/hassio-addons#1190]
Hi,

# Problem
Auto discovery not working. 
The link between Hass and mqtt add-on is working (can display received sensors states with manual sensor configuration with "mqtt" platform, can trigger automation depending on mqtt payload) 

# Actual configuration 
Steps:
- install mqtt add-on and start it
- goto configuration / integrations
- Add the waiting mqtt integration
- check to enable auto discovery

Following the docs at https://www.home-assistant.io/docs/mqtt/discovery/, 
On my arduino uno, I send this to mqtt : 
Topic: `homeassistant/sensor/mysensor/config`
Payload: `{"name": "mysensor","state_topic": "homeassistant/sensor/mysensor/state"}`

But nothing appears! 

But there is no logs on dev tools / logs interface...

# Note
There is no configured mqtt into the home assistant yaml config file. 
When I add the following config (https://www.home-assistant.io/docs/mqtt/discovery/) , according to the docs, Hass adds a notification indicating that there is a config typo on "mqtt" entry 
```
mqtt:
  discovery: true
  discovery_prefix: homeassistant
```

This is a bug or a configuration typo?

**Comment by frenck** [comment]
Hi there,

Thanks for raising an issue, however, you question is not add-on related, but related to the configuration of an integration of Home Assistant.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Or, if you are sure it is an issue with the MQTT integration, please raise an issue on the core project: <https://github.com/home-assistant/core/issues>

Thanks 👍
