### ISSUE TITLE
Deconz-Conbee2: Can't reconnect to network

### ISSUE THREAD

**Issue by noerstad** [home-assistant/hassio-addons#1192]
Deconz 5.3.2
HA 0.107.7

Suddenly happened after upgrade and restart. I can see mesh on VNC but Conbee can't connect to the network anymore

arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 4.4.0-70-generic
python_version | 3.7.7
timezone | Europe/Oslo
version | 0.107.7
virtualenv | false

08:08:26:584 try to reconnect to network try=9
08:08:26:597 Device protocol version: 0x010B
08:08:26:663 Current channel 15
08:08:26:680 CTRL ANT_CTRL 0x03
08:08:26:703 Device protocol version: 0x010B
08:08:26:754 Current channel 15
08:08:26:770 CTRL ANT_CTRL 0x03
08:08:26:793 NET ZDO start network status 0xC4
08:08:31:583 try to reconnect to network try=10
08:08:31:594 Device protocol version: 0x010B
08:08:31:670 Current channel 15
08:08:31:686 CTRL ANT_CTRL 0x03

**Comment by frenck** [comment]
The mesh can be cached.

It can happen on a custom operating system that has the ModemManager still enabled/installed. If that is your case, please refer to the installation manual of Home Assistant, as it has instructions on that.

Other cases I've seen (and rarely experienced myself), is simply the serial device locking up. Replugging the USB stick usually resolves that.

Another common cause for Conbee sticks is interference, which can be solved using a USB extension cord, allowing one to move the USB stick a little more away from the computer.

**Comment by rchl** [comment]
Exactly the same issue here. It stopped working one day. It could be related to rasbian updates that I was doing that day.

I've uninstalled addon and followed this https://phoscon.de/en/conbee/install#raspbian method of installing deconz, which worked fine. I was able to connect to network and see devices.

I'm yet to figure out how to make the addon work again.

**Comment by rchl** [comment]
OK, the addon started working after removing it once again, restarting raspberry-pi and re-installing.
I wonder if the `sudo gpasswd -a $USER dialout` command needed for manual installation made it work or it's definitively unrelated (what do you think @frenck?).

**Comment by frenck** [comment]
That should not be needed, but that is system depended.
If you run a manual setup, the working of the setup is your responsibility.

**Comment by rchl** [comment]
Yeah, but I'm not talking about manual setup. It's just that what was needed for manual setup, also helped to make HASSIO addon work. Or at least that's what it seemed like - I have no way of proving that that was indeed what resolved the issue.

(I guess I could revert that change and try again if you are interested in knowing for sure).

I'm on raspberry-pi 3 with the latest rasbian BTW.
