### ISSUE TITLE
Configurator - Errors in browser console - images hosted on drive.google.com

### ISSUE THREAD

**Issue by nickidw** [home-assistant/hassio-addons#1197]
The images for **jQuery** and **GitPython** on the **About Hass-Configurator** page  are hosted on drive.google.com. The google account appears to be rate-limited, so they don't display

**Comment by frenck** [comment]
Thanks for raising an issue, however, the File Editor add-on wraps an existing application. In this case hass-configurator.

Please raise this issue with the upstream project, which can be found here: <https://github.com/danielperna84/hass-configurator>

Thanks! 👍

**Comment by nickidw** [comment]
Apologies, I clicked a link which took me to this github project, and saw a
folder for configurator.
