### ISSUE TITLE
Check HA Config: Supervisor not listening

### ISSUE THREAD

**Issue by LongDono** [home-assistant/hassio-addons#1204]
## The problem

Check Home Assistant configuration v3.2.0 (with fix for #1194) complains that supervisor is not listening.

## Environment

- Home Assistant Core release with the issue: 0.107.5 - 0.107.7
- Last working Home Assistant Core release (if known): 
- Operating environment (Home Assistant/Supervised/Docker/venv): Supervised 214
- Integration causing this issue: Check Home Assistant configuration 3.2.0
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
starting version 3.2.9
[08:44:03] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[08:44:03] INFO: Setup udev devices

[08:44:05] INFO: Don't worry, this temporary installation is not overwriting your current one.
[08:44:05] INFO: Installing Home Assistant: latest...
[08:44:05] INFO: Please be patient, this might take a few minutes...
[08:44:33] INFO: Installed Home Assistant 0.107.7
[08:44:33] INFO: Making a copy of your configuration for checking...
[08:44:46] INFO: Checking your configuration against this version...
[08:46:54] INFO: Configuration check finished - no error found! :)
_s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal._
```

## Additional information

This error started happening when Check config component was updated and persists with the latest release of HA.

**Comment by rark-ha** [comment]
I get a similar fatal error (but it does also mention the sonoff component not found, which may be unrelated).

In the supervisor dashboard I wasn't getting the widget showing current/latest version. Had to run Check Home Assistant configuration to get this log result. I believe this occurred since HassOS 3.12 update.

````
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
starting version 3.2.9
[16:37:06] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:37:06] INFO: Setup udev devices
[16:37:08] INFO: Don't worry, this temporary installation is not overwriting your current one.
[16:37:08] INFO: Installing Home Assistant: latest...
[16:37:08] INFO: Please be patient, this might take a few minutes...
[16:40:37] INFO: Installed Home Assistant 0.107.7
[16:40:37] INFO: Making a copy of your configuration for checking...
[16:43:57] INFO: Checking your configuration against this version...
[16:55:26] ERROR: The configuration check did not pass!
[16:55:26] ERROR: See the output below for more details.
INFO: <-- all INFO lines culled from log paste
Failed config
  General Errors: 
    - Component error: sonoff - Integration 'sonoff' not found.

Successful config (partial)
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.`

**Comment by kaizersoje** [comment]
I am getting a similar error too.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
starting version 3.2.9
[09:15:26] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:15:39] INFO: Setup udev devices
parse error: Expected string key before ':' at line 1, column 4
[09:15:39] ERROR: Unknown HTTP error occured
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by enbrander** [comment]
Also seeing this error. I'm running HassOS 3.12, Supervisor 217, Home Assistant 107.6 On RPi3b, and trying to upgrade to 108.4. Running Check Home Assistant configuration 3.2.0 I get:

`[10:12:15] INFO: Installed Home Assistant 0.108.4
[10:12:15] INFO: Making a copy of your configuration for checking...
[10:12:18] INFO: Checking your configuration against this version...
[10:20:16] INFO: Configuration check finished - no error found! :)
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.`

I have also tried to run the upgrade to 108.3 and it always fails and I have to reboot the host to restore service back to the previous version.

**Comment by Spiffo** [comment]
subscribing, same here...

**Comment by LongDono** [comment]
After restarting HA 0.109.8, I can confirm it's fixed for me.

**Comment by traindriverrev** [comment]
I still have it on 111.4

**Comment by sahilanguralla** [comment]
I am also facing the same issue. Same error comes even after multiple restarts.

**Comment by dvesters** [comment]
Still have it ;-(

```
➜  ~ ha core info  |grep ^version && ha core logs |grep fatal
version: 0.114.4
version_latest: 0.114.4
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
```

**Comment by marcgarciamarti** [comment]
same here

**Comment by Sotaur** [comment]
I'm seeing it with docker as well.
Image: homeassistant/raspberrypi3-homeassistant:stable
Log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] udev.sh: executing... ,
starting version 3.2.9,
[18:10:23] INFO: Update udev information,
[cont-init.d] udev.sh: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] waiting for services.,
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening,

I used the provided docker run command, adding --restart=always and changing the timezone. Empty config file.

**Comment by Tahutipai** [comment]
Same issue here as well. Multiple restarts not helped.  Any suggestions what to try? 

> ~ $ ha core info | grep ^version && ha core logs | grep fatal
version: 0.118.4
version_latest: 0.118.5
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening

**Comment by markusressel** [comment]
I had the same problem while also facing issues with IPv6 and k3s on the same host. The system uses systemd-resolved and NetworkManager. As a workaround for the k3s issue I disabled IPv6 on the whole machine using the `ipv6.disable=1` parameter, and rebooted the system. After that both k3s and home assistant worked fine again. Note that this is merely a possible point for investigation, rather than a solution. **Do not disable IPv6 without thinking about the implications**. I am not 100% sure the IPv6 issues are related to this issue, but since both issues occurred at the same time I thought it might be a good idea to share my experience.
