### ISSUE TITLE
Cannot connect with VNC

### ISSUE THREAD

**Issue by vdiogo** [home-assistant/hassio-addons#1206]
This is my Deconz configuration and all devices are working fine (reporting status to Home Assistant):
![image](https://user-images.githubusercontent.com/24878195/78216282-645be980-74b1-11ea-9adc-060a4b4826ce.png)

But not being able to connect through VNC:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/24878195/78216381-9d945980-74b1-11ea-8072-274b934c36ac.png">

Any ideas please?

**Comment by frenck** [comment]
Anything in the logs?

**Comment by vdiogo** [comment]
@frenck can't find anything odd (VNC server reports as started)

**Comment by frenck** [comment]
Could you please share those anyway? Maybe there is a small hint in behavior that is unexpected.

**Comment by vdiogo** [comment]
I can, just don't know exactly how to get them (I see them on the UI)
![image](https://user-images.githubusercontent.com/24878195/78227146-c3772980-74c4-11ea-9f38-5477845e23d3.png)

**Comment by vdiogo** [comment]
Any thoughts?

**Comment by frenck** [comment]
Sorry I missed the posting of the screenshot of your log.

However, the screenshot is of the running part and contains no information on this. Please post a screenshot from the startup of the add-on and the logs of that.

On startup the VNC starts, so that should contain potentially helpful information.

**Comment by ludeeus** [comment]
@vdiogo any updates?

**Comment by bloodysolomon** [comment]
Same problem here.

**Comment by ludeeus** [comment]
@bloodysolomon That comment does not really help anyone, if you too see this, please post the logs that was asked earlier in this issue 👍

**Comment by bloodysolomon** [comment]
Sorry, i'm new here. And sorry for my english too.

Here the log:

![Log 01](https://user-images.githubusercontent.com/65145535/81582293-41610700-9386-11ea-840a-438668679cbf.jpg)

**Comment by bloodysolomon** [comment]
Any thoughts? Any other logs that I can send?

**Comment by sverleysen** [comment]
I'm having the same issue.

Logs from restarting the addon:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
starting version 237

[12:00:00] INFO: Waiting for device...
[12:00:01] INFO: Starting VNC server...
[12:00:07] INFO: Starting the deCONZ gateway...
libpng warning: iCCP: known incorrect sRGB profile
12:00:10:327 HTTP Server listen on address 0.0.0.0, port: 40850, root: /usr/share/deCONZ/webapp/
12:00:10:339 CTRL. 3.22.012:00:10:653 COM: --dev: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2122306-if00 (RaspBee)
12:00:10:653 ZCLDB init file /data/.local/share/dresden-elektronik/deCONZ/zcldb.txt
[12:00:10] INFO: Starting Nginx...
[12:00:10] INFO: Running Home Assistant discovery task...
[12:00:11] INFO: Running the deCONZ OTA updater...
[12:00:11] INFO: Running the IKEA OTA updater...
[12:00:11] INFO: Running the LEDVANCE/OSRAM OTA updater...
[12:00:11] INFO: deCONZ is set up and running!
12:00:11:476 parent process bash
12:00:11:477 gw run mode: docker/hassio
12:00:11:477 GW sd-card image version file does not exist: /data/.local/share/dresden-elektronik/deCONZ/gw-version
12:00:11:478 DB sqlite version 3.22.0
12:00:11:479 DB PRAGMA page_count: 43
12:00:11:479 DB PRAGMA page_size: 4096
12:00:11:479 DB PRAGMA freelist_count: 1
12:00:11:479 DB file size 176128 bytes, free pages 1
12:00:11:479 DB PRAGMA user_version: 6
12:00:11:479 DB cleanup
12:00:11:480 DB create temporary views
12:00:11:509 don't close database yet, keep open for 900 seconds
12:00:11:510 started websocket server at port 8081
12:00:11:518 found node plugin: libde_rest_plugin.so - REST API Plugin
2020/05/20 12:00:11 [notice] 615#615: using the "epoll" event method
2020/05/20 12:00:11 [notice] 615#615: nginx/1.14.0 (Ubuntu)
2020/05/20 12:00:11 [notice] 615#615: OS: Linux 3.10.105
2020/05/20 12:00:11 [notice] 615#615: getrlimit(RLIMIT_NOFILE): 524288:1048576
2020/05/20 12:00:11 [notice] 615#615: start worker processes
2020/05/20 12:00:11 [notice] 615#615: start worker process 647
12:00:11:609 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
12:00:16:044 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
12:00:16:263 COM: --dev: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2122306-if00 (RaspBee)
12:00:17:968 New websocket 127.0.0.1:49192 (state: 3) 
12:00:18:513 Announced to internet https://phoscon.de/discover
[12:00:21] INFO: Successfully send discovery information to Home Assistant.
12:00:26:164 New websocket 172.30.32.1:60630 (state: 3) 
12:00:26:979 COM: --dev: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2122306-if00 (RaspBee)

Screenshot from the TigerVNC app:
![image](https://user-images.githubusercontent.com/6018080/82433418-b1ac0e80-9a91-11ea-9fbe-788795386e52.png)

**Comment by bloodysolomon** [comment]
I update Deconz for version 5.3.3 (Bump deCONZ to 2.05.76) and the problem persists.

**Comment by bloodysolomon** [comment]
Sorry for my english.

I "resolved" the problem:

In the Documentation says:

_"The VNC service URL looks like **vnc://**homeassistant.local:5900. Adjust port and possibly hostname if you've changed it in Home Assistant host system settings."_

The error appears. But if i connect using homeassistant.local:5900 or thehomeassistantip:5900, without **vnc://** works!

A little confusion in the documentation that is misleading.
