### ISSUE TITLE
Upload file with File Editor (Configurator)

### ISSUE THREAD

**Issue by KTibow** [home-assistant/hassio-addons#1207]
In the file editor plugin (aka configurator) you can upload a file but you can't upload a whole folder. Are there any plans to add this? If that's too hard, you could add a unzip button for zip files. I hope somebody can do this.

**Comment by frenck** [comment]
Hi @KTibow,

Thanks for opening up an issue with us. However, add-ons wrap existing applications for easy installing and use.

In this case, the File Editor uses an application called `hass-configurator`. Feature requests should be asked at their repository:

<https://github.com/danielperna84/hass-configurator>


Thanks! 👍
