### ISSUE TITLE
File editor shows old version of file even is save is succesvol 

### ISSUE THREAD

**Issue by MarcHagen** [home-assistant/hassio-addons#1210]
HassOS 3.12
Supervisor version 214

Home Assistant 0.107.7
Configurator hass-addon version: 4.7
Chrome: 80.0.3987.163 

Issue:
When saving a file and i reopen that same file the "old" version is shown.
The file is saved correctly but the Chrome service-worker returns a `200 OK (from disk cache)`
So it's a cached version. Upon forcing to disable cache the "new" file is shown.

**Comment by MarcHagen** [comment]
@frenck @danielperna84 
I hate to ping people, but this is kinda a problem i have every day.

**Comment by danielperna84** [comment]
The standalone version doesn't have this problem. I just tried it, and every request fetches the most recent data.
Are you accessing the configurator through ingress or some other kind of reverse proxy setup (nginx, Apache, Cloudflare etc.) that may introduce caching?

**Comment by MarcHagen** [comment]
Hi there I use it in ingress hassio, and hassio it self is proxied thru Apache. 

Apache shouldn’t cache anything, I thought I had disabled that but will check that to be sure. It happened after the 108 release and haven’t had any issues before that.

**Comment by danielperna84** [comment]
> It happened after the 108 release and haven’t had any issues before that.

The configurator didn't get updated during that period. So it may be a setting that came with 108.

**Comment by MarcHagen** [comment]
So i have double checked and indeed apache only proxies the request to hassio.
Requests are coming from `BaseHTTP/0.6 Python/3.8.2`. So it's definitely the hass addon that is caching. But i dont have to know how to see why

**Comment by danielperna84** [comment]
@frenck 
I see you made some changes with 529ac8f93099650061a0a02a11a837e564f9749a. Could these changes result in the behavior this issue is about?

**Comment by MarcHagen** [comment]
So i forced the cache in my apache proxy. That worked.

```
    <LocationMatch "^/api/hassio_ingress/.*/api/(file|listdir)">
        Header set Cache-Control "max-age=0, no-cache, no-store, must-revalidate"
        Header set Expires "Wed, 12 Jan 1980 05:00:00 GMT"
    </LocationMatch>
```

**Comment by danielperna84** [comment]
So that confirms my initial thought, that the issue is not within the app. If it were, your changes wouldn't have changed anything after all I assume.

**Comment by MarcHagen** [comment]
Well Nginx or apache are just forwarding headers in proxy mode. So there is still a cache-control header being send. 
This just forces it no not exist. But i'm apparently the only person that has this issue. So my fault i guess.
