### ISSUE TITLE
Addon DuckDns not starting if there is no internet connection

### ISSUE THREAD

**Issue by McGiverGim** [home-assistant/hassio-addons#1211]
When I have an electric outage, Home Assistant starts faster than my router, and the Duck add-on seems to not start when there is no internet available.

More people with the same problem here: https://community.home-assistant.io/t/duckdns-not-starting/62856/5

Maybe can be added an option to retry the start if there is no connection? Or at least to push a persistent notification to Home Assistant to notice the problem and fix it?

Thanks!

**Comment by McGiverGim** [comment]
No comment about this? I only want to know if this is the expected behavior or is a bug.

**Comment by McGiverGim** [comment]
No comment about this? Is an expected behavior or a bug?
Thanks!

**Comment by PipeDeveloper** [comment]
I have the same problem. I have a good hosting for HA and my machine boots faster than my router.

![image](https://user-images.githubusercontent.com/35433329/92047434-1cd4d480-ed53-11ea-99f6-909129730129.png)

And Duckdns has the boot at start option marked

**Comment by McGiverGim** [comment]
This has been closed so maybe open a new issue to see if you have more luck than me with it...

I finally ended adding an automation that checks the state each 5 minutes and tries to start it if stopped.

**Comment by PipeDeveloper** [comment]
Can you share your automation please? This would help me a lot. Thank you in advance

**Comment by McGiverGim** [comment]
Yes, but it is a Node Red one, here you have a partial flow (I have more nodes after that sending a notification to the phone):

```json
[{"id":"c5641fa9.2189b","type":"http request","z":"bf90f97d.871fc8","name":"Info DuckDNS","method":"GET","ret":"obj","paytoqs":"ignore","url":"https://XXXXXXX.duckdns.org/api/hassio/addons/core_duckdns/info","tls":"","persist":false,"proxy":"","authType":"bearer","x":380,"y":1400,"wires":[["42167471.2114ac"]]},{"id":"556977c0.02b4a8","type":"inject","z":"bf90f97d.871fc8","name":"Cada 10 minutos","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"600","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":170,"y":1400,"wires":[["c5641fa9.2189b"]]},{"id":"42167471.2114ac","type":"switch","z":"bf90f97d.871fc8","name":"¿Está parado?","property":"payload.data.state","propertyType":"msg","rules":[{"t":"neq","v":"started","vt":"str"}],"checkall":"false","repair":false,"outputs":1,"x":580,"y":1400,"wires":[["62737104.d2572"]]},{"id":"66dcaf54.02aff","type":"api-call-service","z":"bf90f97d.871fc8","name":"Arrancar DuckDNS","server":"e03e6d0f.b2759","version":1,"debugenabled":false,"service_domain":"hassio","service":"addon_start","entityId":"","data":"{\"addon\":\"core_duckdns\"}","dataType":"json","mergecontext":"","output_location":"","output_location_type":"none","mustacheAltTags":false,"x":570,"y":1460,"wires":[["30089409.4f773c"]]},{"id":"62737104.d2572","type":"change","z":"bf90f97d.871fc8","name":"Borrar data","rules":[{"t":"delete","p":"payload.data","pt":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":370,"y":1460,"wires":[["66dcaf54.02aff"]]},{"id":"e03e6d0f.b2759","type":"server","z":"","name":"Home Assistant","legacy":false,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]
```

But if you want something simple, execute each X minutes the service `hassio.addon_start`  with the data `"addon":"core_duckdns"`.

And if you want to know the state, is an HTTP get petition to `https://XXXXXX.duckdns.org/api/hassio/addons/core_duckdns/info` with bearer authentication with a long life token.

I found the info in the Home Assistant forum, sorry if I don't post the link, I don't remember it.
