### ISSUE TITLE
Deconz - settings removed after re-installing addon

### ISSUE THREAD

**Issue by rchl** [home-assistant/hassio-addons#1212]
Deconz addon stores some data for Phoscon UI in `/data/.local/share/dresden-elektronik/deCONZ/`. That data is permanently lost when re-installing addon (which I did because I was investigating a problem).

I wonder if it would be possible to store that data in user (homeassistant) settings directory maybe?
I feel it's too easy to loose those settings right now. Even when moving to new server for HA, for example.

**Comment by frenck** [comment]
2 Options available:

- Make a backup inside the Phoscon app (gateway page).
- Make a snapshot of the add-on.

The config folder is not meant for storing add-on data.
