### ISSUE TITLE
configurator: add "git pull origin" to git menu

### ISSUE THREAD

**Issue by avdeevsv91** [home-assistant/hassio-addons#1213]
Add "git pull origin" to the git menu for get changes from the repository. Now you can run this command via "Execute shell command", but it is not as convenient as in the git menu.

**Comment by frenck** [comment]
Hi there @avdeevsv91,

Thanks for opening up an issue, however, add-ons wrap existing applications. In this case: `hass-configurator`.

Please raise your issue/request with the origin project:

<https://github.com/danielperna84/hass-configurator>

Thanks! 👍
