### ISSUE TITLE
"Check Home Assistant configuration" addon stops responding and Supervisor finally kills it

### ISSUE THREAD

**Issue by a94marbo** [home-assistant/hassio-addons#1214]
"Check Home Assistant configuration" addon stops responding and Supervisor finally kills it.
If you are lucky you manage to spot the final result when Supervisor finally kills it and clears the log. Like below.
It is like 15 minutes between the "Checking for errors..." log post to the final dump below.
Running on 0.107.5

```
[21:52:40] INFO: Configuration check finished - no error found! :)
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by markgaze** [comment]
I'm experiencing this on 0.108.0 on a Pi 3. It worked when I used it before upgraded to 0.108.0.

**Comment by pvizeli** [comment]
> INFO: Configuration check finished - no error found! :)
