### ISSUE TITLE
Addon MariaDB won't update since 2.1

### ISSUE THREAD

**Issue by GoSpursGoNL** [home-assistant/hassio-addons#1215]
I currently have the MariaDB addon v2.0. Since 2.1 and 2.1.1 came out, I see in the logging of the supervisor every now and then the following message when it checks for updates:

```
20-04-11 09:05:52 WARNING (MainThread) [supervisor.addons.addon] Add-on core_mariadb new schema is not compatible
20-04-11 09:05:52 WARNING (MainThread) [supervisor.tasks] Add-on core_mariadb will be ignored, schema tests fails
```
As a result, it won't attempt to update the addon. A bug?

**Comment by GoSpursGoNL** [comment]
I manually updated the addon to 2.1.2 and it still works. So it is unclear to me why the automatic mechanism didn't want to do it.

**Comment by frenck** [comment]
Have you tried using the "reset to defaults" button on the add-on options and set up the configuration from scratch?

**Comment by GoSpursGoNL** [comment]
I didn't as I wasn't aware of that option.

I just checked the difference between the standard configuration for the addon and my configuration. The only difference is that I specified a password as per the instructions.

Anyway, the addon still works after manually forcing the update. But still puzzling why it didn't want to update by itself.

**Comment by deftdawg** [comment]
Have this happening with both Zwave JS and DuckDNS addons, its a supervisor problem so opened an issue over there (https://github.com/home-assistant/supervisor/issues/3017). Would be curious to know if @GoSpursGoNL still sees this happening.

**Comment by GoSpursGoNL** [comment]
I don't use the MariaDB addon amymore, but have not seen this behaviour with other addons
