### ISSUE TITLE
deCONZ: URL to Web ui

### ISSUE THREAD

**Issue by MickL** [home-assistant/hassio-addons#1222]
I wonder how i may access the deCONZ / Phoscon web ui "standalone" outside of hassio? What is the URL?

**Comment by frenck** [comment]
You can assign a outside port to port 40850 in the Network section of the add-on.

Make sure you hit save and restart the add-on after that.

Next, the web interface will be available at `http://homeassistant.local:40850` (replace homeassistant.local with the internal address you normally use to access your machine).

👍
