### ISSUE TITLE
Addon Samba unable to connect since 9.1.0

### ISSUE THREAD

**Issue by SNoof85** [home-assistant/hassio-addons#1224]
Hi,

I updated samba addon to 9.1.0 and then the backup job that uses smb share to copy /backup folder to my NAS failed.
I tried to remove the connected smb share from NAS to HASS, and add it back without luck. I looked to the changes from 9.0.0 to 9.1.0 but i can't see why it's not working anymore. Downgrade to 9.0.0 works good.

Unfortunately i have no logs on the NAS when it fails (just say connection to the share failed) and in addon log nothing interresting comes up on connection tries from the NAS (only that auth worked). From my windows 10 PC it's working good with 9.1.0...

**Comment by brinzlee** [comment]
I have the same issue.....it also nocks out smb on my other two computers stopping sharing. As soon as the addon is reverted back to 9.0.0 it works perfectly

**Comment by arripeo** [comment]
I confirm the same issue, when I try to connect from my ubuntu18.04 pc the system say that it is not possible to create list of share folder and connection is refused. I've check the option.json file it seems ok. I tried different configuration with allow ip but nothing change. Please solve this issue as much as possible. My system is Hassio with HassOS on raspberry Pi4 4gb 32bit ver. Is it possible to downgrade the addon?

**Comment by gabeale** [comment]
I confirm the same issue (I'm currently using VM Box with Hassio installed).
Thanks!

**Comment by olapettersson** [comment]
My Synology NAS says that it cannot mount my /backup directory because the addon doesn't support SMB1. I know SMB1 shouldn't be used anymore, due to security issues, but Synology only seems to support SMB1, and in a controlled network, it should be possible to choose SMB1.

**Comment by Lynnpaskett** [comment]
I confirm the same issue, how do i revert back to 9.0.0 ? i did a lot of changes the same day and my snapshot is too old to go back. just for this. 9.0.2 please!

**Comment by SNoof85** [comment]
To revert to 9.0.0 i used a snapshot and only restore the addon (you can chose what you want to restore) so even it's an old one just restore only the addon !
Before restore anything, do a snapshot ;) I'm not responsible for any damage while downgrading this addonc via snapshots !

**Comment by fudu** [comment]
Same problem, I tried to revert to a 9.0 version snapshot but I get same error:
`20-04-20 13:29:30 ERROR (SyncWorker_16) [supervisor.docker] Can't start addon_core_samba: 403 Client Error: Forbidden ("endpoint with name addon_core_samba already exists in network host")`

**Comment by gabeale** [comment]
In my case I reverted back to 9.0 by using an older snapshot and restoring the samba addon only.
It worked smoothly.
Before doing anything it is always recommended to do the snapshot, you know, just in case! ;-)

**Comment by SNoof85** [comment]
@pvizeli @tathamoddie any suggestion as you were both behind the wheel for the last update on this addon ?

**Comment by pvizeli** [comment]
I have no issue, maybe wrong credentials? Do you have something like an error on a log?

**Comment by brinzlee** [comment]
@pvizeli are you using SMB1 Sharing Protocol on Windows 10. As soon as the latest addon 9.1.0 is used. Everything drops off the network. As soon as 9.0.0 is restored its reappears.

**Comment by olapettersson** [comment]
Nothing happens when I select only "Samba Share" and click "Restore Selected". No idea why. My snapshots are password protected. Anyone who has managed to to a partial restore of the "Samba Share" add-on from a password protected snapshot?

**Comment by arripeo** [comment]
I've solved with a partial restore from a snapshot. @olapettersson it's seem strange you couldn't restore, after restore your samba version is 9.0 or lower version? Anyway I haven't uderstood if samba is linked anyhow to appdeamon addon because after restore the old samba version I've found appdeamon addon activeted. Before I installed the addon but I never activated it in order to understand the best configuration. Good luck waitng for a new samba version

**Comment by tathamoddie** [comment]
There were two changes from 9.0 to 9.1.0.

1) The default `allow_hosts` list had `fe80::/10` added to it. This is covered in 8427d678ecd8d755c6c37eafa489b23fdcb0d3f5. You can revert this in your local environment by just removing that line from the runtime config of the extension; it's user-configurable, so you can add and remove this line to your heart's content. That changeset was the entire scope of pull request #1208 when I submitted it.

2) @pvizeli incorporated an extra change into the pull request before merging it, mainly with changeset e7877374b990f18f648b2846a4abea329a6f5b65. In this changset, `"init": false` was added to the extension's `config.json`. According to https://developers.home-assistant.io/docs/hassio_addon_config/#add-on-config, this would normally be defaulted to `true`, so this is a change in the configuration. It is not user-configurable, so you can't easily try toggling it back on. It relates to a Docker setting, so might indicate a link with the log event that @fudu shared in https://github.com/home-assistant/hassio-addons/issues/1224#issuecomment-616557967. I don't know why this non-IPv6-related change was added to pull request #1208.

**Comment by SNoof85** [comment]
@pvizeli no, unfortunately there's no log in addon nor in supervisor.

Here is a fresh log from upgrade from 9.0.0 to 9.0.1 + trying to connect from my NAS :
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:27:18] INFO: Hostname: hassio
No builtin backend found, trying to load plugin
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
tdb(/var/lib/samba/winbindd_idmap.tdb): tdb_open_ex: could not open file /var/lib/samba/winbindd_idmap.tdb: No such file or directory
tdb(/var/lib/samba/account_policy.tdb): tdb_open_ex: could not open file /var/lib/samba/account_policy.tdb: No such file or directory
account_policy_get: tdb_fetch_uint32_t failed for type 1 (min password length), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 2 (password history), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 3 (user must logon to change password), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 4 (maximum password age), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 5 (minimum password age), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 6 (lockout duration), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 7 (reset count minutes), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 8 (bad lockout attempt), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 9 (disconnect time), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 10 (refuse machine password change), returning 0
Added user snoof.
nmbd version 4.11.5 started.
Copyright Andrew Tridgell and the Samba Team 1992-2019
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
added interface ens18 ip=2a01:e0a:3a0:de50:341d:89ff:fe90:d77c bcast= netmask=ffff:ffff:ffff:ffff::
added interface ens18 ip=192.168.1.3 bcast=192.168.1.255 netmask=255.255.255.0
making subnet name:192.168.1.3 Broadcast address:192.168.1.255 Subnet mask:255.255.255.0
create_subnets: ignoring non IPv4 interface.
making subnet name:UNICAST_SUBNET Broadcast address:0.0.0.0 Subnet mask:0.0.0.0
making subnet name:REMOTE_BROADCAST_SUBNET Broadcast address:0.0.0.0 Subnet mask:0.0.0.0
load_lmhosts_file: Can't open lmhosts file /etc/samba/lmhosts. Error was No such file or directory
daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
smbd version 4.11.5 started.
Copyright Andrew Tridgell and the Samba Team 1992-2019
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Processing section "[config]"
Processing section "[addons]"
Processing section "[ssl]"
Processing section "[share]"
Processing section "[backup]"
added interface ens18 ip=2a01:e0a:3a0:de50:341d:89ff:fe90:d77c bcast= netmask=ffff:ffff:ffff:ffff::
added interface ens18 ip=192.168.1.3 bcast=192.168.1.255 netmask=255.255.255.0
INFO: Profiling support unavailable in this build.
No builtin backend found, trying to load plugin
tdb(/var/lib/samba/registry.tdb): tdb_open_ex: could not open file /var/lib/samba/registry.tdb: No such file or directory
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
waiting for connections
Closing idle connection
Processing section "[config]"
Processing section "[addons]"
Processing section "[ssl]"
Processing section "[share]"
Processing section "[backup]"
check_ntlm_password:  authentication for user [snoof] -> [snoof] -> [snoof] succeeded
Processing section "[config]"
Processing section "[addons]"
Processing section "[ssl]"
Processing section "[share]"
Processing section "[backup]"
check_ntlm_password:  authentication for user [snoof] -> [snoof] -> [snoof] succeeded
```

We can see the NAS connecting with correct credentials but on the other side, from the NAS : error connecting to the shared staorage.

@tathamoddie : thx for your answer, i was around the same point => init: false added to your PR. @pvizeli why this has been added ? Coult it be the problem ?

**Comment by SNoof85** [comment]
To compare : logs from 9.0.0 and a connection from the NAS : 
```
[11:35:55] INFO: Hostname: hassio
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
No builtin backend found, trying to load plugin
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
tdb(/var/lib/samba/winbindd_idmap.tdb): tdb_open_ex: could not open file /var/lib/samba/winbindd_idmap.tdb: No such file or directory
tdb(/var/lib/samba/account_policy.tdb): tdb_open_ex: could not open file /var/lib/samba/account_policy.tdb: No such file or directory
account_policy_get: tdb_fetch_uint32_t failed for type 1 (min password length), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 2 (password history), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 3 (user must logon to change password), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 4 (maximum password age), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 5 (minimum password age), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 6 (lockout duration), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 7 (reset count minutes), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 8 (bad lockout attempt), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 9 (disconnect time), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 10 (refuse machine password change), returning 0
Added user snoof.
nmbd version 4.10.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2019
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
added interface ens18 ip=2a01:e0a:3a0:de50:341d:89ff:fe90:d77c bcast= netmask=ffff:ffff:ffff:ffff::
added interface ens18 ip=192.168.1.3 bcast=192.168.1.255 netmask=255.255.255.0
making subnet name:192.168.1.3 Broadcast address:192.168.1.255 Subnet mask:255.255.255.0
create_subnets: ignoring non IPv4 interface.
making subnet name:UNICAST_SUBNET Broadcast address:0.0.0.0 Subnet mask:0.0.0.0
making subnet name:REMOTE_BROADCAST_SUBNET Broadcast address:0.0.0.0 Subnet mask:0.0.0.0
load_lmhosts_file: Can't open lmhosts file /etc/samba/lmhosts. Error was No such file or directory
daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
smbd version 4.10.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2019
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Processing section "[config]"
Processing section "[addons]"
Processing section "[ssl]"
Processing section "[share]"
Processing section "[backup]"
added interface ens18 ip=2a01:e0a:3a0:de50:341d:89ff:fe90:d77c bcast= netmask=ffff:ffff:ffff:ffff::
added interface ens18 ip=192.168.1.3 bcast=192.168.1.255 netmask=255.255.255.0
INFO: Profiling support unavailable in this build.
No builtin backend found, trying to load plugin
tdb(/var/lib/samba/registry.tdb): tdb_open_ex: could not open file /var/lib/samba/registry.tdb: No such file or directory
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
waiting for connections
setup_new_vc_session: New VC == 0, if NT4.x compatible we would close all old resources.
Processing section "[config]"
Processing section "[addons]"
Processing section "[ssl]"
Processing section "[share]"
Processing section "[backup]"
check_ntlm_password:  authentication for user [snoof] -> [snoof] -> [snoof] succeeded
idmap range not specified for domain '*'
192.168.1.5 (ipv4:192.168.1.5:52514) connect to service backup initially as user root (uid=0, gid=0) (pid 68)
192.168.1.5 (ipv4:192.168.1.5:52514) closed connection to service backup
setup_new_vc_session: New VC == 0, if NT4.x compatible we would close all old resources.
setup_new_vc_session: New VC == 0, if NT4.x compatible we would close all old resources.
Processing section "[config]"
Processing section "[addons]"
Processing section "[ssl]"
Processing section "[share]"
Processing section "[backup]"
check_ntlm_password:  authentication for user [snoof] -> [snoof] -> [snoof] succeeded
idmap range not specified for domain '*'
snoof-nas (ipv4:192.168.1.5:52538) connect to service backup initially as user root (uid=0, gid=0) (pid 69)
```

**Comment by tathamoddie** [comment]
Considering both logs show a successful container start and script execution, I think we can park the idea that the `init: false` change is the issue.

That leaves us with no clear change causing an issue though...

I note that your 9.0 logs contain references to `smbd version 4.10.8 started`

Your 9.1 logs contain references to `smbd version 4.11.5 started`

The samba server version has changed.

This isn't referenced in the Hass.io Add-on config I don't believe, so I'm not sure where the version selection comes from. That is, it doesn't seem that the add-on is pinned to any particular samba-server version.

This might be a samba server version change that's causing a different compatibility issue, and it's not 9.1 of the add-on breaking it, but just the fact that the add-on was reinstalled as a result of the update and then picked up a newer dependency?

**Comment by tathamoddie** [comment]
Yeah, samba-server 4.11 disables SMB1 by default now: https://www.samba.org/samba/history/samba-4.11.0.html

Something else has picked up that new version: not the code of the add-on v9.1 specifically, but maybe just the container being recreated or a HassOS update?

It seems that your challenge is now:
* You're trying to use the insecure, outdated SMB1 protocol
* The server component that the add-on uses now disables this version of SMB by default
* The add-on does not expose a way to turn the insecure old protocol back on
* That would be a new configuration flag that would have to be added

**Comment by brinzlee** [comment]
@tathamoddie Well done on your detective work....Guess we need a switch to be able to revert to SMB1 for the new Samba Addon to work as some of us old folk have NAS's that won't upgrade their firmware so the newer version of SMB isn't an option

**Comment by pvizeli** [comment]
I would think that people use the wrong credentials. "homeassistant" with here password. I think most is used the old "hassio" logging.

**Comment by pvizeli** [comment]
The samba version is pin to Alpine version. That was the move from 3.10 to 3.11

**Comment by pvizeli** [comment]
I'm fine to add a option to enable the old SMB1. But I currently focus to a new OS release, so I can't do that before next 2 weeks.

**Comment by olapettersson** [comment]
An SMB1-option would be lovely for us poor bastards stuck with Synology's archaic Samba/CIFS-mount implementation!

**Comment by frenck** [comment]
Yeah working on it already @olapettersson

**Comment by SNoof85** [comment]
Wow nice investigation work folks ! Thx :)
What's fun is that on my NAS i can use SMB 1 to 3 as server but only SMB 1 as client. QNAP you're doing it wrong...
