### ISSUE TITLE
Documentation needed: How to use File Editor git push with github

### ISSUE THREAD

**Issue by mariwing** [home-assistant/hassio-addons#1225]
Hi,

I am trying to use the File Editor git commands. I have made a git repository for my config folder and all git operations for it work as expected when doing it via ssh. The github clone url is an ssh url. Where/how do I tell the File Editor to use my ssh key?

**Comment by momab** [comment]
I would love to know the same thing. 
Pushing Issue.

**Comment by dunxd** [comment]
Me also - when I try to do git push from the web UI, I get an error (exit code 128).  Fatal: could not read from remote repository.  Works absolutely fine when logged in via ssh.

I had thought I could fix it by setting the git ssh command to specify the key - that didn't work.
Then I added the path to the key to the line ssh_keys in the add_on configuration - the addon log gives error file not found. I guess the add-on cannot reach files in the host machine?
