### ISSUE TITLE
deCONZ: This add-on is not available on your system

### ISSUE THREAD

**Issue by Viper2666** [home-assistant/hassio-addons#1230]
Hello,
I have a problem: i can't install deCONZ on my supervisor
"This add-on is not available on your system."
My Hassio run on a eepc 32bit  Intel Atom N270 - 1,60Ghz Ubuntu 16.04.6 LTS
Can i solve ?

**Comment by frenck** [comment]
We cannot solve this. The software from deCONZ is not available for 32 bits intel systems.

**Comment by Viper2666** [comment]
ok, thanks a lot
