### ISSUE TITLE
Check Home Assistant configuration save log file

### ISSUE THREAD

**Issue by jp181278** [home-assistant/hassio-addons#1231]
the Check Home Assistant configuration ADD-ON doesn't save the log in any file so if you leave for few minutes the platform and then come back a little bit later happens that you don't find anything in the log and you have to run the procedure again

**Comment by WirelessMind** [comment]
The same happens to me. Probably because I installed HASSIO on a docker.

**Comment by ludeeus** [comment]
Hi 👋

That is correct for all add-ons, they do not write to a file, for feature requests please raise those on the forum https://community.home-assistant.io/c/feature-requests, thanks 👍 

As for showing the log, the UI should now still show you the log even after the addon stops.

**Comment by frenck** [comment]
Actually I have recently adjusted this, haven't noticed this open.

The add-on now stored the output into the `/share` folder.

**Comment by ludeeus** [comment]
Neat! I was not aware of that 🎉
