### ISSUE TITLE
Unable to install Deconz Addon.

### ISSUE THREAD

**Issue by neuman1812** [home-assistant/hassio-addons#1236]
HA version 108.6

  | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 4.19.114-v7
python_version | 3.7.7
timezone | America/New_York
version | 0.108.6
virtualenv | false

Going to Superviser - Add on - Deconz.    Unable to install Addon.  

From the log:

```
Pull image homeassistant/armhf-addon-deconz tag 5.3.2.
20-04-19 18:10:49 ERROR (SyncWorker_19) [supervisor.docker.interface] Can't install homeassistant/armhf-addon-deconz:5.3.2 -> 500 Server Error: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument").
```

Im using a Conbee USB Stick.  I've tried installing the ZHA intergration,  but that also fails with " Unable to connect to ZHA device. .

I've tried the USB stick in all the usb ports.  with and without a zwave stick  also plugged in.  My zwave stick works fine in all ports.

**Comment by frenck** [comment]
`500 Server Error: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument")`

This indicates the corruption of your Docker filesystem and is thus not an add-on issue.

You can try repairing it by running `ha supervisor repair`. The Home Assistant Supervisor will try to restore/fix your Docker.
