### ISSUE TITLE
DuckDNS Add On instructions are incomplete

### ISSUE THREAD

**Issue by willidh74** [home-assistant/hassio-addons#1237]
There are a couple of areas that the novice user (e.g. me) doesn't appreciate when configuring the DuckDNS add-on:

1. You need to update configuration.yaml with content similar to:
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: https://<domain>.duckdns.org

2. You need to add port-forwarding rules to your router to allow 443 to forward to 8123

It was only through lots of research and some Discord conversations that I worked out what I had to do. So I suggest adding this information to the instructions.

**Comment by frenck** [comment]
It isn't that simple. Yes, you are correct, but there are many other methods.
E.g., personally, I would recommend using a reverse proxy (like the NGINX proxy add-on). That removes the configuration part for HA.

Furthermore, the port used, is a personal choice. Home Assistant uses port 8123 by default. Changing it to 443 is not a requirement for SSL to work.

**Comment by willidh74** [comment]
Then how explaining what some of the options are?
My point is that in its current state, the page leads the reader to believe that if you follow these instructions then you will have remote access. And that isn't the case.
So adding some more information would aid adoption.
What do you think?

**Comment by frenck** [comment]
I think this add-on provides DuckDNS with a Let's Encrypt certificate.
In general, add-ons provide services and do not affect Home Assistant.

Setting up SSL with Home Assistant is, in my opinion, more a place for the Home Assistant documentation.

**Comment by andre68723** [comment]
agree to both, the current instructions are not sufficient for RA + DuckDNS addon docu is not the perfect place for describing the setup

As a general starting point [securing](https://github.com/home-assistant/home-assistant.io/blob/next/source/_docs/configuration/securing.markdown) is fine but points to [letsencrypt](https://github.com/home-assistant/home-assistant.io/blob/next/source/_docs/ecosystem/certificates/lets_encrypt.markdown).

I'd suggest extending the securing docu with a tiny overview above both approaches ( letsencrypt +[nginx](https://github.com/home-assistant/home-assistant.io/blob/next/source/_docs/ecosystem/nginx.markdown))would be beneficial, but it's another repo

**Comment by ludeeus** [comment]
Contributions to the documentation are always welcome 👍 

But the purposed suggestion here does not fit in the addon documentation.
This addon updates the IP for the duckdns domain and can produce and update SSL certificates.
The possibilities of what you use those for are endless.

**Comment by andre68723** [comment]
> Contributions to the documentation are always welcome 👍
1st step - https://github.com/home-assistant/home-assistant.io/pull/13410

@willidh74 Please check https://github.com/home-assistant/hassio-addons/blob/master/duckdns/DOCS.md;  from my pov nginx could be mentioned there
