### ISSUE TITLE
SSH 502: Bad Gateway

### ISSUE THREAD

**Issue by leoyangt** [home-assistant/hassio-addons#1239]
Dear All:
I just install hassio on raspberry Pi 4, and install addon SSH & Web Terminal 7.3.2.
but I got error "502: Bad Gateway", after I click "Open web UI" in SSH page.
I did try uninstall this addon and reinstall it, still same problem.
also reboot HassOS,still same
attach log as below
 System: HassOS 3.13  (armv7 / raspberrypi4)
 Home Assistant Core: 0.108.6
==========================================
System log
========================================
20-04-21 11:03:06 INFO (SyncWorker_12) [supervisor.docker.interface] Clean addon_a0d7b954_ssh application
20-04-21 11:03:06 INFO (SyncWorker_12) [supervisor.docker.addon] Start Docker add-on hassioaddons/ssh-armv7 with version 7.3.2
20-04-21 11:03:08 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_ssh
20-04-21 11:05:06 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:62383 ssl:None [Connection refused]
20-04-21 11:05:10 INFO (SyncWorker_9) [supervisor.docker.interface] Clean addon_a0d7b954_ssh application
20-04-21 11:05:11 INFO (SyncWorker_9) [supervisor.docker.addon] Start Docker add-on hassioaddons/ssh-armv7 with version 7.3.2
20-04-21 11:05:13 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:62383 ssl:None [Connection refused]
20-04-21 11:05:13 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_ssh
20-04-21 11:05:41 WARNING (MainThread) [supervisor.api.addons] Protected flag changing for a0d7b954_ssh!
20-04-21 11:05:46 WARNING (SyncWorker_9) [supervisor.docker.addon] SSH & Web Terminal run with disabled protected mode!
20-04-21 11:05:46 INFO (SyncWorker_9) [supervisor.docker.interface] Clean addon_a0d7b954_ssh application
20-04-21 11:05:47 INFO (SyncWorker_9) [supervisor.docker.addon] Start Docker add-on hassioaddons/ssh-armv7 with version 7.3.2
20-04-21 11:05:49 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_ssh
20-04-21 11:05:51 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:62383 ssl:None [Connection refused]
20-04-21 11:07:06 INFO (SyncWorker_11) [supervisor.docker.interface] Clean addon_a0d7b954_ssh application
20-04-21 11:07:06 INFO (SyncWorker_11) [supervisor.docker.interface] Remove image hassioaddons/ssh-armv7 with latest and 7.3.2
20-04-21 11:07:09 INFO (MainThread) [supervisor.addons.addon] Remove add-on data folder /data/addons/data/a0d7b954_ssh
20-04-21 11:07:09 INFO (MainThread) [supervisor.homeassistant] Updated Home Assistant API token
20-04-21 11:07:09 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for a0d7b954_ssh
20-04-21 11:07:09 INFO (MainThread) [supervisor.addons] Add-on 'a0d7b954_ssh' successfully removed
20-04-21 11:07:17 INFO (MainThread) [supervisor.addons] Create Home Assistant add-on data folder /data/addons/data/a0d7b954_ssh
20-04-21 11:07:17 INFO (SyncWorker_18) [supervisor.docker.interface] Pull image hassioaddons/ssh-armv7 tag 7.3.2.
20-04-21 11:08:28 INFO (MainThread) [supervisor.addons] Add-on 'a0d7b954_ssh' successfully installed
20-04-21 11:08:35 INFO (SyncWorker_5) [supervisor.docker.addon] Start Docker add-on hassioaddons/ssh-armv7 with version 7.3.2
20-04-21 11:08:37 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_ssh
20-04-21 11:08:38 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:62383 ssl:None [Connection refused]
20-04-21 11:08:43 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:62383 ssl:None [Connection refused]
20-04-21 11:08:47 INFO (SyncWorker_8) [supervisor.docker.interface] Clean addon_a0d7b954_ssh application
20-04-21 11:08:48 INFO (SyncWorker_8) [supervisor.docker.addon] Start Docker add-on hassioaddons/ssh-armv7 with version 7.3.2
20-04-21 11:08:50 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_ssh
20-04-21 11:08:53 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:62383 ssl:None [Connection refused]
20-04-21 11:09:00 INFO (SyncWorker_0) [supervisor.docker.interface] Clean addon_a0d7b954_ssh application
20-04-21 11:09:00 INFO (SyncWorker_0) [supervisor.docker.addon] Start Docker add-on hassioaddons/ssh-armv7 with version 7.3.2
20-04-21 11:09:02 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_ssh
20-04-21 11:09:25 INFO (SyncWorker_3) [supervisor.docker.interface] Restart homeassistant/raspberrypi4-homeassistant
20-04-21 11:09:59 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance
20-04-21 11:11:29 INFO (SyncWorker_16) [supervisor.docker.interface] Clean addon_a0d7b954_ssh application
20-04-21 11:11:30 INFO (SyncWorker_16) [supervisor.docker.addon] Start Docker add-on hassioaddons/ssh-armv7 with version 7.3.2
20-04-21 11:11:32 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_ssh
20-04-21 11:11:57 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:62383 ssl:None [Connection refused]
20-04-21 11:13:24 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for a0d7b954_ssh
20-04-21 11:13:27 INFO (SyncWorker_10) [supervisor.docker.interface] Clean addon_a0d7b954_ssh application
20-04-21 11:13:28 INFO (SyncWorker_10) [supervisor.docker.addon] Start Docker add-on hassioaddons/ssh-armv7 with version 7.3.2
20-04-21 11:13:29 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_ssh
20-04-21 11:13:31 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:62383 ssl:None [Connection refused]
20-04-21 11:17:10 INFO (SyncWorker_6) [supervisor.docker.interface] Clean addon_a0d7b954_ssh application
20-04-21 11:17:11 INFO (SyncWorker_6) [supervisor.docker.addon] Start Docker add-on hassioaddons/ssh-armv7 with version 7.3.2
20-04-21 11:17:13 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_ssh
20-04-21 11:17:14 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:62383 ssl:None [Connection refused]
20-04-21 11:21:21 INFO (SyncWorker_4) [supervisor.docker.interface] Clean addon_a0d7b954_ssh application
20-04-21 11:21:22 INFO (SyncWorker_4) [supervisor.docker.addon] Start Docker add-on hassioaddons/ssh-armv7 with version 7.3.2
20-04-21 11:21:23 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_ssh
20-04-21 11:22:21 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:62383 ssl:None [Connection refused]
20-04-21 11:28:02 INFO (SyncWorker_7) [supervisor.docker.interface] Clean addon_a0d7b954_ssh application
20-04-21 11:28:02 INFO (SyncWorker_7) [supervisor.docker.addon] Start Docker add-on hassioaddons/ssh-armv7 with version 7.3.2
20-04-21 11:28:04 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_ssh
20-04-21 11:28:08 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:62383 ssl:None [Connection refused]
20-04-21 11:30:33 INFO (SyncWorker_10) [supervisor.docker.interface] Clean addon_a0d7b954_ssh application
20-04-21 11:30:34 INFO (SyncWorker_10) [supervisor.docker.addon] Start Docker add-on hassioaddons/ssh-armv7 with version 7.3.2
20-04-21 11:30:35 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_ssh
20-04-21 11:30:44 INFO (SyncWorker_4) [supervisor.docker.interface] Clean addon_core_check_config application
20-04-21 11:30:50 INFO (SyncWorker_4) [supervisor.docker.addon] Start Docker add-on homeassistant/armv7-addon-check_config with version 3.2.0
20-04-21 11:36:20 INFO (SyncWorker_6) [supervisor.docker.interface] Clean addon_a0d7b954_ssh application
20-04-21 11:36:21 INFO (SyncWorker_6) [supervisor.docker.addon] Start Docker add-on hassioaddons/ssh-armv7 with version 7.3.2
20-04-21 11:36:23 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_ssh
20-04-21 11:36:25 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:62383 ssl:None [Connection refused]
20-04-21 11:36:46 INFO (SyncWorker_0) [supervisor.docker.interface] Clean addon_a0d7b954_ssh application
20-04-21 11:36:46 INFO (SyncWorker_0) [supervisor.docker.interface] Remove image hassioaddons/ssh-armv7 with latest and 7.3.2
20-04-21 11:36:48 INFO (MainThread) [supervisor.addons.addon] Remove add-on data folder /data/addons/data/a0d7b954_ssh
20-04-21 11:36:48 INFO (MainThread) [supervisor.ingress] Update Ingress as panel for a0d7b954_ssh
20-04-21 11:36:48 INFO (MainThread) [supervisor.addons] Add-on 'a0d7b954_ssh' successfully removed
20-04-21 11:48:43 INFO (MainThread) [supervisor.addons] Create Home Assistant add-on data folder /data/addons/data/a0d7b954_ssh
20-04-21 11:48:43 INFO (SyncWorker_17) [supervisor.docker.interface] Pull image hassioaddons/ssh-armv7 tag 7.3.2.
20-04-21 11:50:05 INFO (MainThread) [supervisor.addons] Add-on 'a0d7b954_ssh' successfully installed
20-04-21 11:50:20 INFO (SyncWorker_8) [supervisor.docker.addon] Start Docker add-on hassioaddons/ssh-armv7 with version 7.3.2
20-04-21 11:50:22 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_ssh
20-04-21 11:50:36 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:62383 ssl:None [Connection refused]
20-04-21 12:08:30 INFO (SyncWorker_17) [supervisor.docker.interface] Clean addon_a0d7b954_ssh application
20-04-21 12:08:31 INFO (SyncWorker_17) [supervisor.docker.addon] Start Docker add-on hassioaddons/ssh-armv7 with version 7.3.2
20-04-21 12:08:33 INFO (MainThread) [supervisor.api.security] /host/info access from a0d7b954_ssh
20-04-21 12:08:37 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:62383 ssl:None [Connection refused]
-----------------------------------------------------------
SSH Log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] permissions: applying... 
[fix-attrs.d] permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: SSH & Web Terminal
 SSH & Web Terminal access to your Home Assistant instance
-----------------------------------------------------------
 Add-on version: 7.3.2
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
 System: HassOS 3.13  (armv7 / raspberrypi4)
 Home Assistant Core: 0.108.6
 Home Assistant Supervisor: 217
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] docker.sh: executing... 
[cont-init.d] docker.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] ssh.sh: executing... 
[20:08:35] FATAL: 
[20:08:35] FATAL: Configuration of this add-on is incomplete.
[20:08:35] FATAL: 
[20:08:35] FATAL: Please be sure to set a least a SSH password
[20:08:35] FATAL: or at least one authorized key!
[20:08:35] FATAL: 
[20:08:35] FATAL: You can configure this using the "ssh.password"
[20:08:35] FATAL: or the "ssh.authorized_keys" option in the
[20:08:35] FATAL: add-on configuration.
[20:08:35] FATAL: 
[cont-init.d] ssh.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
============================================

**Comment by frenck** [comment]
Hi there @leoyangt!

Thanks for opening an issue, however, that add-on is a community add-on. 

Repository for that add-on can be found here: <https://github.com/hassio-addons/addon-ssh/issues>

However, looking the logs, it seems like the answer is already in there:

```txt
[20:08:35] FATAL:
[20:08:35] FATAL: Configuration of this add-on is incomplete.
[20:08:35] FATAL:
[20:08:35] FATAL: Please be sure to set a least a SSH password
[20:08:35] FATAL: or at least one authorized key!
[20:08:35] FATAL:
[20:08:35] FATAL: You can configure this using the "ssh.password"
[20:08:35] FATAL: or the "ssh.authorized_keys" option in the
[20:08:35] FATAL: add-on configuration.
[20:08:35] FATAL:
```

**Comment by williamhelle** [comment]
Hi frenck, I'm back 😂, I get same problem but for me log looking good, he jsut won't start the web interface after 5mins.

Logs :
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/00-banner.sh
-----------------------------------------------------------
 Add-on: SSH & Web Terminal
 SSH & Web Terminal access to your Home Assistant instance
-----------------------------------------------------------
 Add-on version: 12.0.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.0  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2022.9.2
 Home Assistant Supervisor: 2022.09.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
cont-init: info: /etc/cont-init.d/00-banner.sh exited 0
cont-init: info: running /etc/cont-init.d/01-log-level.sh
cont-init: info: /etc/cont-init.d/01-log-level.sh exited 0
cont-init: info: running /etc/cont-init.d/docker.sh
[14:56:30] INFO: Docker support has been enabled.
cont-init: info: /etc/cont-init.d/docker.sh exited 0
cont-init: info: running /etc/cont-init.d/mosquitto.sh
cont-init: info: /etc/cont-init.d/mosquitto.sh exited 0
cont-init: info: running /etc/cont-init.d/mysql.sh
cont-init: info: /etc/cont-init.d/mysql.sh exited 0
cont-init: info: running /etc/cont-init.d/ssh.sh
[14:56:32] WARNING: 
[14:56:32] WARNING: Logging in with "root" as the username,
[14:56:32] WARNING: is security wise a bad idea!
[14:56:32] WARNING: 
[14:56:32] WARNING: Most attacks against SSH are attempts to login
[14:56:32] WARNING: using the "root" username.
[14:56:32] WARNING: 
[14:56:32] WARNING: 
[14:56:32] WARNING: Logging in with a SSH password is security wise, a bad idea!
[14:56:32] WARNING: Please, consider using a public/private key pair.
[14:56:32] WARNING: What is this? https://kb.iu.edu/d/aews
[14:56:32] WARNING: 
[14:56:33] NOTICE: SFTP access is enabled
[14:56:34] NOTICE: SSH is running in compatibility mode!
[14:56:34] WARNING: Compatibility mode is less secure!
[14:56:34] WARNING: Please only enable it when you know what you are doing!
cont-init: info: /etc/cont-init.d/ssh.sh exited 0
cont-init: info: running /etc/cont-init.d/user.sh
total 28
drwxr-xr-x    5 root     root          4096 Sep 25 14:56 .
drwxr-xr-x    4 root     root          4096 Sep 25 14:56 ..
drwxr-xr-x    3 root     root          4096 Sep 25 14:56 data
drwx-ws--T    2 root     root          4096 Sep 25 14:56 event
-rw-r--r--    1 root     root             2 Sep 25 14:56 notification-fd
-rwxr-xr-x    1 root     root           419 Sep 25 14:56 run
srwxrwxrwx    1 root     root             0 Sep 25 14:56 s
-rw-------    1 root     root             0 Sep 25 14:56 s.lock
drwx------    2 root     root          4096 Sep 25 14:56 supervise
cont-init: info: /etc/cont-init.d/user.sh exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun sshd (no readiness notification)
services-up: info: copying legacy longrun ttyd (no readiness notification)
s6-rc: info: service legacy-services successfully started
[14:56:35] INFO: Starting the ttyd daemon...
[14:56:35] INFO: Starting the SSH daemon...
Server listening on 0.0.0.0 port 654.
Server listening on :: port 654.
```



My config :
```
init_commands:
  - ls -la
packages: []
share_sessions: true
ssh:
  allow_agent_forwarding: true
  allow_remote_port_forwarding: true
  allow_tcp_forwarding: true
  authorized_keys: []
  compatibility_mode: true
  password: secret
  sftp: true
  username: root
zsh: false
```

I try to enable/disable some options but no, won't live, sorry ;)
