### ISSUE TITLE
Lets Encrypt Add-on - Redirecting to SSL page

### ISSUE THREAD

**Issue by SixFive7** [home-assistant/hassio-addons#1243]
Hi,

The addon needs to be bound to port 80 to respond to the challenges. However, when the certificate is correctly in place it would be nice to have the webserver forward to the 443 port.
Right now we cannot navigate to home.mydomain.tld from a browser. We need to explicitly navigate to HTTPS://home.mydomain.tld. Whereas most sites provide a 301 to the same site but on https on port 443.
Could the addon be configured to provide that capability?

**Comment by Jomik** [comment]
I am redirected to 443 by using https://github.com/home-assistant/hassio-addons/blob/master/nginx_proxy/README.md
Seems to be a better, more modular solution, than handling it in the Let's Encrypt add-on.

**Comment by frenck** [comment]
The let's encrypt add-on does not provide a webserver or proxies. Its sole goal is to provide let's encrypt SSL certificates.

The functionality you describe is indeed provided by the addon listed by @Jomik.

**Comment by SixFive7** [comment]
I completely agree the lets encrypt add-on should not provide any webserver or proxy capabilities. 

However, configuring nginx to forward to 443 seems to break automatic renewal for those of us that use the http challenge (because we don't want or need to use an external provider like duckdns). Also, configuring an nginx exception to route the http://<YOUR_DOMAIN>/.well-known/acme-challenge/ path to the let's encrypt add-on seems to be non trivial in the nginx_proxy add-on. And even if it can be configured, it seems a far cry from the plug and play experience adding https through letsencrypt could be.

Given that adding security to home assistant should always be a low friction and easy as possible. I'd argue redirecting from port 80 to 443 should definitely be in scope for those of use that don't need anything else other than adding https.
