### ISSUE TITLE
DHCP server not showing on Hassio Official add-ons

### ISSUE THREAD

**Issue by LewisW-J** [home-assistant/hassio-addons#1245]
I'm not sure if it's me but it looks like DHCP server isn't in the list of available add-ons even though my CPU arch is supported. Have I missed something? 

I can't seam to add this repo manually to see if it's listed under there, I just keep getting "Unknown"

**Comment by ludeeus** [comment]
It is an advanced add-on, you will only see it if you have the advanced toggle in your user profile enabled.

**Comment by LewisW-J** [comment]
So it is! Sorry for the silly question!
