### ISSUE TITLE
Addon Homematic configuration problems

### ISSUE THREAD

**Issue by mini-mi** [home-assistant/hassio-addons#1247]
I am trying to run home-assistant with the [homematic addon](https://github.com/home-assistant/hassio-addons/tree/master/homematic) and the [HM-MOD-RPI-PCB](https://www.elv.ch/homematic-funkmodul-fuer-raspberry-pi-bausatz.html) on a raspberry pi 4B 4gb.

I want to use it for several Homematic IP devices. At first I had it on two different devices and used [raspberrymatic](https://raspberrymatic.de/de/home/) this worked well. But I want to use only one device for it. 

I've tried a lot, but I can't get it to work.

So what I did:

1. put HM-MOD-RPI-PCB on the GPIOs
2. installed HassOS 3.13
3. added `dtoverlay=pi3-miniuart-bt` to the config.txt on the boot partition
3. installed homematic addon
4. addon configuration

> rf_enable: true
> rf:
>   - type: CCU2
>     device: "**/dev/ttyAMA0**"

> wired_enable: false
> wired:
>   - serial: xy
>     key: abc
>     ip: 192.168.0.0

> hmip_enable: true
> hmip:
>   - type: HMIP_CCU2
>     device: "**/dev/ttyUSB0**"

> regahss_reset: false

5. configuration.yaml

> homematic:
>   interfaces:
>     rf:
>       host: core-homematic
>       port: 2001
>     wired:
>       host: core-homematic
>       port: 2000
>     hmip:
>       host: core-homematic
>       port: 2010
>     group:
>       host: core-homematic
>       port: 9292
>       path: /groups

6. Network ports 1:1 container/host
7. started homematic addon

and it did not work. He did not found an interface.
So what I did I copied parts from the config.txt from raspberrymatic to homeassistant:

> `# make sure the uart is running at 48MHz`
> init_uart_clock=48000000

> `# switch the bluetooth UART to the miniuart for basic bluetooth support and fix core_freq`
> dtoverlay=pi3-miniuart-bt core_freq=250

> `# for disabling bluetooth alltogether you can uncomment the following two lines`
> dtoverlay=pi3-disable-bt
> dtparam=uart1=off

> `# add device tree overlay for RPI-RF-MOD`
> dtoverlay=rpi-rf-mod

and added the missing overlays from raspberrymatic.

Now as long as I deactivate HmIP it is working, but if I activate it in the config it won´t boot correctly. So I am not sure what I should use for the HmIP device. For sure it is not `/dev/ttyUSB0` but I only have `/dev/ttyS0` and with this it is not working. If I deactivate rf and use `/dev/ttyAMA0` it also does not work.

I hope someone can help me.

Greets mini-mi

**Comment by mini-mi** [comment]
**It seem as written in the following post that it is not possible to run HM-MOD-RPI-PCB for HmIP with the homematic addon.**

It don´t understand why, because if I am running it with raspberrymatic it works and the offical readme does not document this.

Further that is ok but can you please update the readme so that people who want to use this not have to buy the wrong adapter?

> Yes, we don't support HmIP with HM-MOD-RPI-PCB because we don't want to integrate the kernel hack for this device.
> 
> Use the USB adapter for HmIP.
> 

_Originally posted by @pvizeli in https://github.com/home-assistant/hassio-addons/issues/499#issuecomment-453120059_

**Comment by pvizeli** [comment]
If you want maintain the kernel patches, feel free to jump into project 👍 but that is a long time promise because people are not happy if we remove it later because there is no maintainer for it anymore and I have not the time for this.

**Comment by mini-mi** [comment]
I understand your problem and I am sorry for that, but I can not speak any programming language and I am not that familiar with linux.
I am very happy to have people like you, @frenck and all the other users and developer doing such great open source projects. 

But what I can do is to make such problems public, so that nobody has to search as long as I did.
Because if you read the readme, it sounds like it should work.

Both transmitter and homematic itself are from the same company.
And I thougt that raspberrymatic and the addon are both forks from occu which is also from the same company so it could not be that difficult to get this running.

**Comment by wettermann32** [comment]
hi all,
too bad, just received my HM-MOD-RPI-PCB and now having trouble set it up. But it seems not even work without HmIP. I am running in the same problems like [https://github.com/home-assistant/hassio-addons/issues/842](url)
I thought this adapter is the best choice because documentation said "HassOS versions 1.11 and later support the HmIP-RFUSB by default and don't need any configuration".

Do you recommend to buy a different adapter?

Best

**Comment by mini-mi** [comment]
I would recommend HmIP-RFUSB or use raspberrymatic on a second device.
It took a while to get it running.

**Comment by jackob007** [comment]
> I would recommend HmIP-RFUSB or use raspberrymatic on a second device.
> It took a while to get it running.

Could you please paste your Homematic configuration?
Cannot pair with my Weather Station via RF :/

Best regards!

**Comment by Robbilie** [comment]
currently running a setup just like the author, got myself some hm ip products in addition to normal ones and run them on a raspberrymatic, took me some time to figure out that i wont be able to drop that second pi in favor of the homematic addon :(
