### ISSUE TITLE
Backup specific databases in MariaDB addon

### ISSUE THREAD

**Issue by mdegat01** [home-assistant/hassio-addons#1249]
Is there a way to schedule backups of specific databases within the MariaDB add-on?  Now that the [Nginx Proxy Manager addon](https://github.com/hassio-addons/addon-nginx-proxy-manager) stores its config in the MariaDB add-on I want to back up that config.  But I don't want to just take a snapshot of the MariaDB add-on since that includes the Homeassistant DB with all the recorder data which is huge and not really necessary to backup.

Homeassistant doesn't seem to have mysqldump in its docker image so even though it can connect to the MariaDB add-on there's no easy way to create a script that does a backup and have HA run it on a schedule. And I don't think there's anyway to install mysqldump on another machine and connect to the MariaDB add-on from there is there?

Would be nice if the addon had an option to export backup files of specific DBs nightly. Or a way to do this from a [shell command](https://www.home-assistant.io/integrations/shell_command/) in HA so it could be automated.

**Comment by frenck** [comment]
We don't provide this functionality. Alternatively, you could look at the SSH & Web Terminal add-on (Community version), which provides the MySQL CLI tools out of the box.

**Comment by mdegat01** [comment]
Oh I didn't know that.  Yea I already use that addon and now I see mysqldump is installed already.  Ok I'm pretty sure I can make this work then, thanks!
