### ISSUE TITLE
Google_Assistant_SDK addon dont support ru_Ru (and other) languages

### ISSUE THREAD

**Issue by Bratan9600** [home-assistant/hassio-addons#1250]
I install and configure Google Assistant SDK addon.
When add Google Project in Overview tab i select Russian language, but assistant detect and answer in English.
On my android mobile Settings - Google - Services - Search and Assistant - Google Assistant - Languages menu i choose "Russian" (Русский), but below this i see notification "This language doesnt support on all your devices. Choose language for this devices" and selected "English".
If i try change English language to Russian, i cant see Russian in dropdown box. It contains only English, Espanol, Francais, Indonesia, Italiano, Nederlands, Portugues, Svenska, and some asian languages

Is it possible to add support other languages?

**Comment by frenck** [comment]
Hi there @Bratan9600! Thanks for opening up an issue.

Add-ons wrap existing software, in this case: `google-assistant-sdk`.

For feature requests, please check the upstream project:

<https://github.com/googlesamples/assistant-sdk-python>

Thanks 👍
