### ISSUE TITLE
mosquitto security - option to disable auth plugin, deny a user or best fail2ban

### ISSUE THREAD

**Issue by codemunin** [home-assistant/hassio-addons#1251]
### Motivation
I have a really weak user/password for guests in my homeassistant. Therefor I searched for options to disable the access from outside to this user.

### Problem
As i want to use mqtt for location tracking outside my home, I have to open it to the Internet (At least the MQTT-SSL-Port). For security i really miss 2 options:
- **fully disable auth plugin** (don't know if thats possible)
- **deny specific users to access** mqtt

I'm aware of ACL from MQTT, but this can still leave the possibility to bruteforce the homeassistant user/password.
Otherwise it would be nice to have a **bruteforce protection** on this plugin (like fail2ban).

### Closing
If there are other option I've not considered, I'm happy for advise.
Thanks for all the work!

**Comment by ludeeus** [comment]
Hi 👋
This is the issue tracker for the add-ons, for feature requests please raise those on the forum https://community.home-assistant.io/c/feature-requests, thanks 👍
