### ISSUE TITLE
Samba share connection failed after update

### ISSUE THREAD

**Issue by Amathagma** [home-assistant/hassio-addons#1252]
Hi,
I can't make samba share to work after update. I think everything was fine in 8.3.0 version (not really sure if that was the version I had before the update) but after update to 9.2.0 can't anymore login to hassio.
Tried to restart, uninstall and reinstall, nothing worked. I can see my hassio exposed to network but can't login. Just connection failed, that's all.
Log file is big enough, tell me if you need any info from this. Last log file says:
Could not find child 289 -- ignoring

**Comment by frenck** [comment]
please provide the full log. Thanks 👍

**Comment by Amathagma** [comment]
Ok, here it is (I hope I didn't hide too much ip's):
`Log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] samba.sh: executing... 
[18:41:06] INFO: Hostname: hassio
No builtin backend found, trying to load plugin
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
account_policy_get: tdb_fetch_uint32_t failed for type 1 (min password length), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 2 (password history), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 3 (user must logon to change password), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 4 (maximum password age), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 5 (minimum password age), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 6 (lockout duration), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 7 (reset count minutes), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 8 (bad lockout attempt), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 9 (disconnect time), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 10 (refuse machine password change), returning 0
Added user my_name.
[cont-init.d] samba.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
nmbd version 4.11.5 started.
Copyright Andrew Tridgell and the Samba Team 1992-2019
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
added interface enp0s3 ip=xxxx:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx bcast= netmask=ffff:ffff:ffff:ffff::
added interface docker0 ip=172.xx.x.x bcast=172.xx.xxx.xxx netmask=255.xxx.x.x
added interface hassio ip=172.xx.xx.x bcast=172.xx.xx.xxx netmask=255.255.254.0
added interface enp0s3 ip=192.168.x.xxx bcast=192.168.1.255 netmask=255.255.255.0
making subnet name:192.168.x.xxx Broadcast address:192.168.1.255 Subnet mask:255.255.255.0
making subnet name:172.xx.xx.x Broadcast address:172.xx.xx.xxx Subnet mask:255.255.254.0
making subnet name:172.xx.x.x Broadcast address:172.xx.xxx.xxx Subnet mask:255.255.0.0
create_subnets: ignoring non IPv4 interface.
making subnet name:UNICAST_SUBNET Broadcast address:0.0.0.0 Subnet mask:0.0.0.0
making subnet name:REMOTE_BROADCAST_SUBNET Broadcast address:0.0.0.0 Subnet mask:0.0.0.0
daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
smbd version 4.11.5 started.
Copyright Andrew Tridgell and the Samba Team 1992-2019
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Processing section "[config]"
Processing section "[addons]"
Processing section "[ssl]"
[services.d] done.
Processing section "[share]"
Processing section "[backup]"
added interface enp0s3 ip=xxxx:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx bcast= netmask=ffff:ffff:ffff:ffff::
added interface docker0 ip=172.xx.x.x bcast=172.xx.xxx.xxx netmask=255.255.0.0
added interface hassio ip=172.xx.xx.x bcast=172.xx.xx.xxx netmask=255.255.254.0
added interface enp0s3 ip=192.xxx.x.xxx bcast=192.168.1.255 netmask=255.255.255.0
INFO: Profiling support unavailable in this build.
No builtin backend found, trying to load plugin
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
waiting for connections
check_for_master_browser_fail: Forcing election on workgroup WORKGROUP subnet 172.xx.x.x
check_for_master_browser_fail: Forcing election on workgroup WORKGROUP subnet 172.xx.xx.x
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.xx.x.x
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.xx.xx.x
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.xx.x.x
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.xx.xx.x
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.xx.x.x
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.xx.xx.x
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.xx.x.x
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.xx.xx.x
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.xx.x.x
run_elections: >>> Won election for workgroup WORKGROUP on subnet 172.xx.x.x <<<
become_local_master_browser: Starting to become a master browser for workgroup WORKGROUP on subnet 172.xx.x.x
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.xx.xx.x
run_elections: >>> Won election for workgroup WORKGROUP on subnet 172.xx.xx.x <<<
become_local_master_browser: Starting to become a master browser for workgroup WORKGROUP on subnet 172.xx.xx.x
*****
Samba name server HASSIO is now a local master browser for workgroup WORKGROUP on subnet 172.xx.x.x
*****
*****
Samba name server HASSIO is now a local master browser for workgroup WORKGROUP on subnet 172.xx.xx.x
*****
Could not find child 289 -- ignoring
Could not find child 292 -- ignoring`

**Comment by jackob007** [comment]
Hello!

I have the same problem.
Today's fresh installation of hassio on Proxmox.
Cannot migrate from RPi via snapshots :(

Thanks for your help!

**Comment by goprojojo** [comment]
Having the same issue. Any solution on this issue yet?

**Comment by jdbrookes** [comment]
I had this same issue after updating core to 109.3 this week.

Solution for me was to reset the Samba Share config entirely, ensure the IP range in allowed_hosts was correct, and then reconfigure my samba share password (including quotes).

**Comment by tre4b** [comment]
Just getting back into HA after a break and, well did all the updates and found I could no longer access Samba.  Heck I can no longer even figure out where the config is as the config section that was there no longer seems to exist and I can find no other way to locate the config.  

Do I now need to access on the linux level to do the config or something?

**Comment by jdbrookes** [comment]
> Just getting back into HA after a break and, well did all the updates and found I could no longer access Samba. Heck I can no longer even figure out where the config is as the config section that was there no longer seems to exist and I can find no other way to locate the config.
> 
> Do I now need to access on the linux level to do the config or something?

They've broken AddOns into tabs, so you should see tabs for Configuration, Logs etc along the top when you open the AddOn in the Supervisor page.

**Comment by tre4b** [comment]
Ta  JBrookes,

Problem with coming back to it after a while 😉  Thanks for being tolerant.

Trev

________________________________

**Comment by tdejneka** [comment]
I am experiencing a nearly identical problem with the Samba Add-On.  I have it running on an RPI3 and I can connect to it using MacOS and Windows but _not_ with Ubuntu (neither 18.04 or 20.04).

The Home Assistant server appears in the Networks list. Login attempts are denied (message is "Permission denied"). The same credentials work with MacOS and Windows.

In addition, if you attempt to browse the Home Assistant's server's available samba shares (by entering `smb://servername`), it reports it is unable to acquire the list.

> **Unable to access location.**
> Failed to receive share list from server. Connection timed out.

Curiously, the Samba Add-On's log does not report anything concerning the failed connection attempt. It reports successful connections but shows nothing when I repeatedly try, but fail, to connect from the Ubuntu machine.

More details can be found in this post:
https://community.home-assistant.io/t/denied-access-to-samba-add-on-from-ubuntu-machine/197910

**Comment by bobthiel** [comment]
I have a similar problem. When i installed Samba share ver 9.2.0 from the ad-on store and selected start it never started.; nothing in the log.
Bob

**Comment by johanson** [comment]
@tdejneka If you're on Linux try connecting `smb://homeassistant.local` or try from cli `smbclient -L homeassistant` if you get errors that are more informative.

**Comment by tdejneka** [comment]
@johanson 

Thank you for your reply.


I can connect to the Samba Add-on from Windows or Mac, just not from Ubuntu's File Manager (neither 18.04.4 or Ubuntu 20.04). Ubuntu's File Manager (formerly known as Nautilus) displays  Home Assistant server's name in its "Networks" list. Clicking it presents a dialog box to supply username and password. However, it rejects the supplied credentials. If I use `smb://hapi` or `smb.hapi.local` (server's name was changed to `hapi`; it can be pinged by either name) I receive a different error message (posted above).

 I installed`smbclient` and executed the suggested command. This is the result:
```text
redacted@server:~$ smbclient -L hapi -U homeassistant
WARNING: The "syslog" option is deprecated
Enter WORKGROUP\homeassistant's password: 

	Sharename       Type      Comment
	---------       ----      -------
	config          Disk      
	addons          Disk      
	ssl             Disk      
	share           Disk      
	backup          Disk      
	IPC$            IPC       IPC Service (Samba Home Assistant)
Reconnecting with SMB1 for workgroup listing.
protocol negotiation failed: NT_STATUS_INVALID_NETWORK_RESPONSE
Failed to connect with SMB1 -- no workgroup available
```
I found this suggestion https://askubuntu.com/a/1071182 and added `client min protocol = SMB2` to `/etc/samba/smb/conf` in the `[global]` section. Then I executed the same command with this result:
```text
redacted@server:~$ smbclient -L hapi -U homeassistant
WARNING: The "syslog" option is deprecated
Enter WORKGROUP\homeassistant's password: 

	Sharename       Type      Comment
	---------       ----      -------
	config          Disk      
	addons          Disk      
	ssl             Disk      
	share           Disk      
	backup          Disk      
	IPC$            IPC       IPC Service (Samba Home Assistant)
SMB1 disabled -- no workgroup available
```
The Samba Add-on is configured like this:
```yaml
workgroup: WORKGROUP
username: homeassistant
password: redacted
interface: ''
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 'fe80::/10'
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false
```
I hope this information reveals some clues for you.

**Comment by bobthiel** [comment]
My problem could have been operator error , noob, Working ok now.
