### ISSUE TITLE
google asssistant error config 500 internal server error first config

### ISSUE THREAD

**Issue by ramkumargang** [home-assistant/hassio-addons#1254]
i am  newbie in home assistant, i recently installed google assistant sdk in adds on then i having issue when tokken passing to google assistant page the error are 500 internal server error and then after restart home assistant i found issue are below   
**
> making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> [10:16:11] INFO: Installing/Updating service client_secrets file
> [10:16:11] INFO: Starting Home Assistant GAssisant SDK...
**
cant open WEB UI nothing happens ,what to do,sorry for poor English,advance Thanks!

**Comment by ericmatte** [comment]
@ramkumargang if you update Google Assistant SDK to the latest version, is your issue fixed with the new OAuth UI? https://github.com/home-assistant/hassio-addons/pull/1267

**Comment by ramkumargang** [comment]
thanks, i try it
