### ISSUE TITLE
Can't find ssh-server addon in add-on store

### ISSUE THREAD

**Issue by lanfearselene** [home-assistant/hassio-addons#1256]
I've installed 0.108.9 on my Raspberry Pi 3 Model B and B+ 32bit and I couldn't find the SSH/Web Terminal add-on in the store. 

Is there another way to ssh into Home Assistant or have I missed a step? 

Thanks!

**Comment by frenck** [comment]
SSH is an advanced add-on, please make sure you've enabled advanced mode in your user profile.
