### ISSUE TITLE
Can't connect to DB after update

### ISSUE THREAD

**Issue by AratKruglik** [home-assistant/hassio-addons#1257]
I have updated this addon in my HA but now I got an error
Couldn't connect using mysql://hass:hass@core-mariadb/homeassistant?charset=utf8 DB_URL: (MySQLdb._exceptions.OperationalError) (2002, "Can't connect to MySQL server on 'core-mariadb' (115)")

**Comment by frenck** [comment]
Please provide details on your system, versions, add-ons logs and anything else you have on this.

Unfortunately, just this line doesn't provide the information we can use.

Thanks 👍

**Comment by AratKruglik** [comment]
Now it works. Sorry.
