### ISSUE TITLE
SSH & Web Terminal cross site fingerprinting & access refused

### ISSUE THREAD

**Issue by wayne47git** [home-assistant/hassio-addons#1260]
Hassio 0.108.09
SSH & Web Terminal 8.5.4
===== Issue 1 =====
**It appears that the Web GUI is using Cross-site fingerprinting.**

If I use the Brave browser, the WebUI fails in the default configuration, resulting in a black window. To get it to work, I have to enable “Cross-site fingerprinting” which concerns me.

===== Issue 2 =====
**ssh refuses logins**

Network is set to 22 to re-enable ssh 

Using ssh-rsa with my key generated on FreeBSD (client)
Problem exists with both UserID@host.domain.com as well as UserID@IPaddress following the key

ssh root@IPaddress_of_hassio generates
> Connection closed by authenticating user root IPaddressOfClient port 28049 [preauth]

in the plugin log and 
> debug1: Offering RSA public key: /home/UserID/.ssh/id_rsa
> debug3: send_pubkey_test
> debug3: send packet: type 50
> debug2: we sent a publickey packet, wait for reply
> debug3: receive packet: type 51

on the client with ssh -vvv. This feels like a permissions issue on sshd but I can't see what the addon is setting the .ssh/* protections to.

I tried setting a password and the addon does not drop to password after rsa fails.

**Comment by ludeeus** [comment]
Hi 👋 

From your title, it looks like you are using <https://github.com/hassio-addons/addon-ssh> and not <https://github.com/home-assistant/hassio-addons/tree/master/ssh>.

You should open an issue here instead <https://github.com/hassio-addons/addon-ssh> 👍
