### ISSUE TITLE
Addons File Editor caracters are shifted form cursor

### ISSUE THREAD

**Issue by guiguid** [home-assistant/hassio-addons#1261]
Hi,
With the 5.0 update of the File Editor Addons, I've a 5/6 caracter shift with the cursor !

![HA-FileEditor5 0-caracterbug](https://user-images.githubusercontent.com/71406/80712625-823d5e00-8af2-11ea-8173-10652b0ab801.gif)

This strange bug isn't présent in previous release.
It's fonts related ?

Tested with : 
Firefox 75, with -safe-mode + cache cleaning on linux manjaro 20 
Chromium Version 81.0.4044.122 on linux manjaro 20

HA : 0.109.1
File editor : 5.0.0

arch  | x86_64
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 5.6.5-3-MANJARO
python_version | 3.7.7
timezone | Europe/Paris
version | 0.109.1
virtualenv | false

I've uninstall and reinstall File editor addon with no succes.

**Comment by frenck** [comment]
Hi there @guiguid!

Add-ons wrap existing applications, in this case the hass-configurator.

Please report this issue upstream:

<https://github.com/danielperna84/hass-configurator>

If it is fixed in that application, the add-on will be updated accordingly.

Thanks! 👍
