### ISSUE TITLE
Addon RPC Shutdown : install Pb 

### ISSUE THREAD

**Issue by phd59** [home-assistant/hassio-addons#1262]
Hello,
Installing the addon RPC Shutdown doesn't work for me...
As said I installed it, added computers in configuration.yaml, then started it 
When checking the config I get the error message : Component error: computers - Integration 'computers' not found.

Any help ? Someone already got that ? And where is the add-on log output ?

Great thanks by advance, I really would like to use it ! 

My install : 
|arch |x86_64|
|dev |false|
|docker |true|
|hassio |true|
|os_name |Linux|
|os_version |5.4.0-26-generic|
|python_version |3.7.7|
|timezone |Europe/Paris|
|version |0.109.1|
|virtualenv |false|

**Comment by frenck** [comment]
The `computers` are defined in the add-on configuration.

Go to the Supervisor panel -> Click the add-on -> setting show.

Check the add-on documentation for more information.

👍

**Comment by phd59** [comment]
I see, the solution was right under my nose... I'm confused.
Great thanks for answering such a question !
