### ISSUE TITLE
Add WSDD support to Samba Addon

### ISSUE THREAD

**Issue by ajw107** [home-assistant/hassio-addons#1264]
HI
Since windows removed support for SMB1 a lot of people are having trouble finding their shares in Networks.  To get around this people either use the direct ip address or install SMB1 via windows features (bad)!  The more modern solution is to support WSDD which will make everything work as before without the security implications.  
Would it be possible to add the following python script (no configuration needed, it 'Just Works') to the SAMBA Docker container (running as a service within it) to make a lot of peoples headaches go away:
[WSDD Python Script Github Repo](https://github.com/christgau/wsdd)
I use it on my main Ubuntu Server without issue.
Alex

**Comment by jokerigno** [comment]
I'm in! and support this.

**Comment by qnxxxx** [comment]
I am absolutely FOR adding WSDD support.
Enabling SMB1 in 21st century ... ???

**Comment by hotchkj** [comment]
While this hasn't been fixed, I created a sidecar [addon](https://github.com/hotchkj/hass-ws-discovery/tree/main) that should fix WS Discovery - has for me anyway. Hopefully it helps someone. I've never created an addon before, so if anyone encounters any issues feel free to raise an issue or a PR for it.
