### ISSUE TITLE
Let's Encrypt addon fails to start when emulated_hue in running

### ISSUE THREAD

**Issue by yonz2** [home-assistant/hassio-addons#1268]
Hi all,
(Not really a bug, just something that should find its way into the documentation)

there is a conflict between the `Let's Encrypt` addon and the `emulated_hue` integration. Both try to bind to port 80 on the server. With `emulated_hue` running, `Let's Encrypt Addon` will not start. In the Log file you'll see:
`[supervisor.docker] Can't start addon_core_letsencrypt: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_core_letsencrypt (53b8380a6220142caee27549507eeed05996d452282db042b8750b4f8ab35e31): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use")
`

Checking on the Home Assistant Server (ssh to port 22222) you get:
```
# netstat -tulpn | grep :80
tcp        0      0 192.168.178.30:80       0.0.0.0:*               LISTEN      5086/python3

```

If you then (temporarily) remove the `emulated_hue`, reboot and check again:
```
ha > login
 netstat -tulpn | grep :80
 exit
```
Port 80 is not in use, and the `Let's Encrypt` addon will start and renew the Certificates.

Afterwards, enable `emulated_hue` again, and all is good for another three months.

Best regards
Yonz

**Comment by frenck** [comment]
This is not just emulated hue. Anything can use a port and thus cause a port collision. Documenting everything that could be using port 80 would be kinda impossible...

**Comment by phillprice** [comment]
Oh well this explains why I can't get this working at the moment :)
