### ISSUE TITLE
Let's Encrypt addon requires port 80 when using DNS verfication

### ISSUE THREAD

**Issue by sepulworld** [home-assistant/hassio-addons#1269]
Why does the Let's Encrypt add-on require port 80 for DNS challenge configuration?  Where is the source code of the add-on I can look and submit a PR

**Comment by frenck** [comment]
You can disable the port if you like?

**Comment by sepulworld** [comment]
The port is in use by another app. And the LE add-on fails to run. I looked into certbot and it looks like it might not be possible to prevent this when DNS verification is preferred. One option might be to test out the —manual flag.

**Comment by sepulworld** [comment]
> You can disable the port if you like? Just make the port field empty in the Network section of the add-on configuration.

Oh, I can try that. I misread what you wrote initially. I think for now, Im going to move over the the Nginx Proxy Manager plugin and consolidate setup there.
