### ISSUE TITLE
Nginx SSL Proxy: customize.active but nothing found in /share

### ISSUE THREAD

**Issue by simonlock** [home-assistant/hassio-addons#1271]
Hi 
I've set the customise.active option to true as shown below:

customize:
  active: true
  default: nginx_proxy_default*.conf
  servers: nginx_proxy/*.conf

I've restarted homeassistant, but no files are created for editing within /share.

I'm hoping to add an additional subdomain to the reverse proxy for a docker container (homebridge) I want to create in homeassistant using portainer.

Should files be created in /share?

Thanks

Simon

Hostname | homeassistant
System | HassOS 3.13
Deployment | production

**Comment by simonlock** [comment]
The fault above still stands as far as I can see. However, a better solution to getting verified https for a docker container running within homeassistant might be to reference the container on the homeassistant https url as a path (e.g. https://homeassistantdomain.com/dockercontainername ). In the same way as the add-ons work. Is this possible?

**Comment by ludeeus** [comment]
Hi 👋
The files will not be created, you need to create them, this is by design and not a bug.

If you need support setting that up, please use our forum or discord, thanks 👍 
https://www.home-assistant.io/help/
