### ISSUE TITLE
A lot of linked devices in Google Home

### ISSUE THREAD

**Issue by Bratan9600** [home-assistant/hassio-addons#1272]
Hello !
I configure Google Assistant Integration (https://www.home-assistant.io/integrations/google_assistant/) and configure Google Assistant SDK Addon. And it works well together.

But after each reboot of my Raspberry Pi, in Google Home app (android) adds a link device which names like device i configured in Google Project for Google Assistant SDK

Is it possible to delete this linked devices from Google Home app/account? and not add it after each reboot of Raspberry Pi?

Platform: Raspberry Pi 4
System: Raspbian Buster
Hass: HassIO 0.109.3 installed in Docker
Google Assistant SDK Addon v2.3.2 

![3AJZvGgHu9s](https://user-images.githubusercontent.com/62903232/81144480-33297a00-8f85-11ea-87e7-8a3e30b5bd7c.jpg)

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
