### ISSUE TITLE
samba dont work 

### ISSUE THREAD

**Issue by Dorkan88** [home-assistant/hassio-addons#1274]
i cant install samba 

workgroup: WORKGROUP
username: homeassistant
password: 12345
interface: ''
allow_hosts:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 'fe80::/10'
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false

Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'workgroup': 'WORKGROUP', 'username': 'homeassistant', 'password': 12345, 'interface': '', 'allow_hosts': ['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16', 'fe80::/10'], 'veto_files': ['._*', '.DS_Store', 'Thumbs.db', 'icon?', '.Trashes'], 'compatibility_mode': False}

why this hapend ?

**Comment by frenck** [comment]
Seems like you didn't enquote the "password" ?

**Comment by Dorkan88** [comment]
thx yes it was that

thx for answer
