### ISSUE TITLE
File editor: line numbering jumping

### ISSUE THREAD

**Issue by wojtek14a** [home-assistant/hassio-addons#1275]
## File editor line numbering jumping
When scrolling down a long file after passing `99th line` (and `999th line` respectively etc.) the bar with line numbers is extending its width in order to fit longer values whereas there is a lot of unused space before the number.
Could this behavior be somehow fixed e.g. by locking the width of the bar for a good enough 5 digit number or in another appropriate way?

### Gif showing the moment of the jump while scrolling 
![f5a4e53b-c118-4aa7-9ee4-3b4261873b91](https://user-images.githubusercontent.com/10120476/81238591-bd63f380-9002-11ea-8b2e-5e5ba228d768.gif)

**Comment by ludeeus** [comment]
Hi, 

The file editor only wraps existing software, you should open an issue with the software that it runs 👍 
https://github.com/danielperna84/hass-configurator
