### ISSUE TITLE
MariaDB Addon wrong real database size

### ISSUE THREAD

**Issue by shirou93** [home-assistant/hassio-addons#1276]
HA database have wrong size in phpmyadmin/heidiSQL. 

![image](https://user-images.githubusercontent.com/59237288/81317884-b59d6100-908d-11ea-994f-2d74b72bb4b7.png)
![image](https://user-images.githubusercontent.com/59237288/81317924-c3eb7d00-908d-11ea-98ac-a1a7f3f5859e.png)

Size stuck on 53 MB when real size have more than 600mb. Database work normal no error logs etc.

![image](https://user-images.githubusercontent.com/59237288/81318575-c4d0de80-908e-11ea-8c40-76cfb4ee935a.png)

I see new records in tables when refresh phpmyadmin, but size stuck on 53mb. 

Delete and create new database not fix this issue. Size work and will stuck on couples days.

**Comment by frenck** [comment]
That is expected. Please read into the InnoDB engine on more information about this. 👍
