### ISSUE TITLE
OpenZwave: This add-on is not available on your system.

### ISSUE THREAD

**Issue by bryanjgill** [home-assistant/hassio-addons#1278]
System Specs:
Lenovo ThinkCentre M72e
 Intel i5-3470T @2.9GHz
16GB DDR3
500GB HDD
Ubuntu Desktop 20.04 LTS 64-bit
Aeotec ZW090 Z Stick

Can the OpenZwave add-on be installed while the Zwave integration is active?

Any thoughts?

**Comment by frenck** [comment]
This add-on is not yet available as it depends on a future release of Home Assistant (and thus not compatible with your current system yet).
