### ISSUE TITLE
DuckDNS effectively fails to renew SSL cert

### ISSUE THREAD

**Issue by KBrownConsulting** [home-assistant/hassio-addons#1280]
Twice in the last 2 years my SSL cert for HA has expired which has been confusing since I'm using the DuckDNS addon and to quote from the readme:

"This add-on includes support for Let’s Encrypt and **automatically creates and renews your certificates.**"

After a bunch of research & some discussions in discord I believe I discovered the source of my problem. 

Basically, while the quote above is _technically_ correct, DuckDNS does automatically renew your cert, it appears the new cert can not be used until the web service is restarted. Which for the average user **effectively means the new cert won't be usable until HA is rebooted**! (This is based on both some testing I've now done & [this comment in issue 858](https://github.com/home-assistant/hassio-addons/issues/858#issuecomment-562324420) from @frenck ) 

If there really is no way to get the web server to dynamically load the new cert, then I'd like to propose a couple suggestions on ways to better handle this situation so that hopefully others won't have to repeat my hours of research thinking there's some problem with my config or a bug in the addon.  

Here are my suggestions / requests, in descending order of preference:

1. Add a user configurable option for "web_service_restart_time" (or similar) 
The idea being that if simply restarting the web service (as opposed to completely rebooting HA) is enough to pick up the new cert, the user could specify a time of day that the web service should be restarted after a new cert has been acquired. This way we could specify a time like 3am when the odds of someone being logged in are low. (I realize that due to the way HA addons are isolated from each other, it may not be possible for the DuckDNS addon to restart the web server, but if it's possible this would be my preference as it would make the cert renewal fully transparent to the user.)

1. Notify the user a reboot is required
If automatically reloading the web service isn't an option then being notified that a new cert has been acquired & a reboot is necessary would be really appreciated. I'm thinking using HA's "Persistent Notifications" would be a perfect solution to alert any admins that login to HA that a new cert has been acquired and that HA needs to be rebooted before [Old-Cert-Expiration-Date].

1. Update the DuckDNS readme file
If neither of the two options above can be implemented, at the very least could something be added to the DuckDNS readme file noting this reboot requirement? While I understand that technically the DuckDNS addon is successfully renewing your cert, the current readme is a little misleading since effectively the process isn't fully "automatic". (At least as far as the average user is concerned.)

Hope that makes sense. 
Thanks

**Comment by Henk72** [comment]
I have the same issue already for a long time. It seems the DuckDNS plugin is not updating the certificate in the docker shared /ssl directory. I verified this at OS level (date time of the file). 

The result is that DuckDNS thinks the certificate is valid (probably a local file is updated), but it does not end up in de browser. In my case a reboot of HA does not help. **The only workaround is to reinstall DuckDNS which indeed writes to the /ssl directory.**

Maybe somthing is not workjng with symlinks?

A search in the DuckDNS docker gives these files:
/data/letsencrypt/xxx.duckdns.org/privkey.pem
/ssl/privkey.pem

Probably the first is updated, but does not end in the /ssl directory. Something with symlinks and docker??

I'm running HASSIO in docker on a PI3 with OS: Raspbian GNU/Linux 9 (stretch)

**Comment by johanson** [comment]
Looks like mine can't validate the challenge, the certs in  /root/ssl dir are in fact new.

`services.d] done.
# INFO: Using main config file /data/workdir/config
+ Generating account key...
+ Registering account key with ACME server...
+ Fetching account ID...
+ Done!
[22:36:09] WARNING: 
# INFO: Using main config file /data/workdir/config
 + Creating chain cache directory /data/workdir/chains
Processing xxx.duckdns.org
 + Creating new directory /data/letsencrypt/xxx.duckdns.org ...
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 1 authorizations URLs from the CA
 + Handling authorization for xxx.duckdns.org
 + 1 pending challenge(s)
 + Deploying challenge tokens...
OK + Responding to challenge for xxx.duckdns.org authorization...
 + Cleaning challenge tokens...
OK + Challenge validation has failed :(
ERROR: Challenge is invalid! (returned: invalid) (result: {
  "type": "dns-01",
  "status": "invalid",
  "error": {
    "type": "urn:ietf:params:acme:error:dns",
    "detail": "DNS problem: SERVFAIL looking up TXT for _acme-challenge.xxx.duckdns.org - the domain's nameservers may be malfunctioning",
    "status": 400
  },
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/4707175651/6zpjHQ",
  "token": "-w_XT6eXBsCHDSu-Pee2Jj5I0Tri7_wkWqJ-RF84Ri8"
})`

**Comment by remcotjeerdsma** [comment]
I am experiencing the same issue. After a restart of Home Assistant, the renewed certificate is picked up. But this is a manual action and it should not be. 

The other comments on this issue seem to be on other topics actually. In the issue described here, the renewal takes place, the new cert is there, but the webserver still serves content using the old certificate.

**Comment by Elendilon** [comment]
This issue just happened for me as well, using Duck DNS 1.14.0 . The duckdns log said:

Valid till Jan 16 00:47:45 2022 GMT (Longer than 30 days). Skipping renew!

But the cert actually being used by the web service expired 11/16/2021. A reboot of HA caused the correct cert to be served up.

My install is on an odroid c2, from the image found at https://www.home-assistant.io/installation/odroid/ . I have installed the addons: File editor (5.2.0), Terminal & SSH (9.1.0), Duck DNS (1.14.0).

If this is a limitation and not just a bug, it would be good to add to the "Known issues and limitations" of the documentation please!

**Comment by ManOnWire** [comment]
Same issue here; happened for the second or third time. It's an annoyance, and should preferably be handled automatically.

How should / can this be fixed? If anyone knows, please point me in the right direction so I can try and fix this myself.

**Comment by lmjohansen** [comment]
Same issue: happen third time for me. Should be handled automatic.
Please reopen issue.

**Comment by jektvik** [comment]
+1 but it doesn't sound like asking yet again for repoen of issue will make it happen so I'll just create a new thread altogether.
