### ISSUE TITLE
no devices created with homematic integration

### ISSUE THREAD

**Issue by FranknStone** [home-assistant/hassio-addons#1281]
I have homeassistant 0.109.6 with homematic integration and hmip-rfusb.
I habe 2 hmip-bwth, web ui of homematic is working and there are created 2 entities for each hmip-bwth with correct values. I can change the values in home assistant but for these entities there are no devices so that i cannot change the room for example.
Why are the devices missing but entities are present?

My config of add in:
1 rf_enable: false
2 wired_enable: false
3 hmip_enable: true
4 rf:
5  - type: CCU2
6 device: /dev/ttyAMA0
7 wired:
8 - serial: xy
9  key: abc
10 ip: 192.168.0.0
11 hmip:
12  - type: HMIP_CCU2
13 device: /dev/ttyUSB0
14 regahss_reset: false

and in configuration.yaml:
homematic:
  interfaces:
  hmip:
      host: core-homematic
      port: 2010
      username: Admin
      password: xxxxxxx
      resolvenames: json
    groups:
      host: core-homematic
      port: 9292
      username: Admin
      password: xxxxxxx
      resolvenames: json
      path: /groups

**Comment by ludeeus** [comment]
Hi 👋 

This is the issue tracker for the addon however, it seems like you have an issue with the integration inside Home Assistant, please open an issue in this repo: https://github.com/home-assistant/core/issues, thanks 👍
