### ISSUE TITLE
HA Nginx SSL Proxy errors

### ISSUE THREAD

**Issue by bmcclure** [home-assistant/hassio-addons#1282]
I am using the LetsEncrypt addon to generate the SSL cert, which works. I am then referencing that same cert from my Nginx SSL Proxy configuration, which also seems to work. I can access Home Assistant just just fine via the domain I configure, and the SSL is valid.

However, every 5 minutes or so I receive the following errors repeated over and over again in the addon config:

```
2020/05/09 17:41:39 [crit] 33#33: *1060 SSL_read() failed (SSL: error:14191044:SSL routines:tls1_enc:internal error) while processing HTTP/2 connection, client: 192.168.86.1, server: 0.0.0.0:443
2020/05/09 17:41:39 [crit] 33#33: *1061 SSL_read() failed (SSL: error:14191044:SSL routines:tls1_enc:internal error) while waiting for request, client: 192.168.86.1, server: 0.0.0.0:443
```

192.168.86.1 is my Google WiFi router which has the port forwarding set up. Is this indicating that my router is making some sort of request to this Nginx SSL Proxy every 5 minutes which is failing?

**Comment by ludeeus** [comment]
This is not an issue with the addon, this is something that tries to connect to it.
If you need support troubleshooting that, please use our forum or discord, thanks 👍 

https://www.home-assistant.io/help/
