### ISSUE TITLE
Feature request: Add a "Test Config" option to the Nginx HA SSL Proxy addon

### ISSUE THREAD

**Issue by bmcclure** [home-assistant/hassio-addons#1283]
One of nginx's incredibly important functions is the ability to verify that you have a valid configuration before actually making that configuration active.

It would be awesome if there was a way to fire off the "nginx configtest" command from within HA so that before you click "Restart" you can confirm that your proxy server won't go down due to a config error.

**Comment by ludeeus** [comment]
Hi 👋
This is the issue tracker for addons, for feature requests please raise it on the forum https://community.home-assistant.io/c/feature-requests, thanks 👍

**Comment by bmcclure** [comment]
Do you accept pull requests for new features, or does that need to be voted on by the community first?

**Comment by ludeeus** [comment]
If you are up to the task, please do 👍
