### ISSUE TITLE
DOC.md doesn't seems available in the UI [add-on: google_assistant]

### ISSUE THREAD

**Issue by ericmatte** [home-assistant/hassio-addons#1284]
## The problem

The documentation about [Presenting your addon](https://developers.home-assistant.io/docs/hassio_addon_presentation/#adding-documentation) specified that the documentation should reside in a `DOC.md` file in the project.

After merging https://github.com/home-assistant/hassio-addons/pull/1265, I've tried to access the updated documentation within the Supervisor UI without success.

I just don't see the documentation, and if I click on the `Click here for the full documentation` link (which works on GitHub), it redirects me to the same page (`/hassio/addon/core_google_assistant/info`) with a double side-panels:

![image](https://user-images.githubusercontent.com/9013072/81178502-4a14a000-8f76-11ea-876a-9887cbe6486c.png)

@pvizeli mentioned that the UI support for this is pretty new. Unless I am missing something, it doesn't seems to show at all in the UI.

## Environment

I tested with Home Assistant Core versions 0.109.1 and 0.109.6.

## Additional information

If you want, I can also make a PR to revert back the `DOC.md` into the `README.md`.

**Comment by ludeeus** [comment]
The reason this is an issue is that it looks for "DOCS.md" and not "DOC.md", I've added a PR to correct it.
as well as a PR for the documentation to change it there https://github.com/home-assistant/developers.home-assistant/pull/502

**Comment by ericmatte** [comment]
The [documentation](https://developers.home-assistant.io/docs/hassio_addon_presentation/#adding-documentation) says:
> This file containing the documentation is usually referred to as the "DOC", which is generally published as the DOC.md file.

But the file should be named `DOCS.md`?

**Comment by ludeeus** [comment]
Yes, didn't you read my response?

I have added a PR to change the documentation website and the file in this repo.

- <https://github.com/home-assistant/developers.home-assistant/pull/502>
- <https://github.com/home-assistant/hassio-addons/pull/1285>

**Comment by ericmatte** [comment]
Sorry, you had not linked https://github.com/home-assistant/hassio-addons/pull/1285 in your first response, but the link was already made with that issue earlier.

It's all good thank you 👍

**Comment by ludeeus** [comment]
Yeah, did not think to do that since GitHub already had linked it above my comment 👍
