### ISSUE TITLE
Check config / File Configurator does not flag duplicate sections

### ISSUE THREAD

**Issue by hampshire-al** [home-assistant/hassio-addons#1291]
I've just reported this issue in the wrong area - please see: https://github.com/home-assistant/core/issues/35493

The issue I have is that the Android app spots duplicate sections in configuration.yaml - in my case I had duplicated the "sensor:" section to include two different devices - but the main File Configurator does not seem to spot this and it would be helpful to relative beginners (me!!) to replicate this behaviour in the Configurator. 

While I now understand from Frenck that the YAML is not technically wrong as duplicate sections are allowed for overrides, etc., it caused an issue in my case as my sensors disappeared as a result of the duplication.

Finding the problem would not have been obvious to me if I hadn't seen the issue flagged in the Android app.

Could this be considered/fixed in Configurator?  Is it supposed to happen anyway?

Thanks.

**Comment by ludeeus** [comment]
Thanks for opening this issue @hampshire-al  👍 
However, what @frenck meant in home-assistant/core#35493 was that you opened an issue in this repository <https://github.com/danielperna84/hass-configurator>
