### ISSUE TITLE
file editor corrupt?

### ISSUE THREAD

**Issue by Userofhomeassistant** [home-assistant/hassio-addons#1317]
I experienced that at a certain moment (about two weeks ago) the file editor 5.0.0 stopped functioning . Removal and reinstalling does not recover it. It looks as if all icons are gone. I get only a long list of a kind of hyperlinks, of which most give no responds.

Here a screenshot:

![afbeelding](https://user-images.githubusercontent.com/65350580/81942442-66f64680-95fa-11ea-92d6-19609074f9bf.png)

Anyone that knows how to get it working again?

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/81946723-ffdb9080-95ff-11ea-87c4-20d314686d65.png)


Is blocking it.

**Comment by ondoteam** [comment]
Hello! I think that there is a problem with cloudflare CDN . I am getting a ERR_SSL_VERSION_OR_CIPHER_MISMATCH with every browser.

Example: https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.8/ext-language_tools.js

**Comment by PierreScerri** [comment]
I'm getting the same on Safari, Chrome & Brave:

![Screenshot 2020-08-12 at 12 56 52](https://user-images.githubusercontent.com/34303331/90007769-9a994900-dc9b-11ea-9bcf-807dcf282e36.png)

**Comment by ondoteam** [comment]
> I'm getting the same on Safari, Chrome & Brave:
> 
> ![Screenshot 2020-08-12 at 12 56 52](https://user-images.githubusercontent.com/34303331/90007769-9a994900-dc9b-11ea-9bcf-807dcf282e36.png)

Cloudflare fixed it right now.
