### ISSUE TITLE
Mosquitto broker not creating an entry into HA Devices or Entities list

### ISSUE THREAD

**Issue by elbueno222** [home-assistant/hassio-addons#1318]
I am using zigbee2mqtt and Mosquitto broker in hassio (HassOS 3.13) and I am having an issue with zigbee devices, because every time I remove one device from Home Assistant and add it again, Home Assistant doesn’t create an entry in the Entities or Devices list for the device.

I am removing the device using topic zigbee2mqtt/bridge/config/force_remove, and then when I add the device again, zigbee2mqtt recognise it (I can see the message {"type":"pairing","message":"interview_successful","meta":{"friendly_name":"xxxxxxxxxxxx","model":"xxxxxxxx","vendor":"xxxxxx","description":"xxxxxxxxx","supported":true}} and any other subsequent message sent by the device in the zigbee2mqtt log, so pairing is successful), but Home Assistant doesn’t create an entry in the Entities or Devices list for the device.

These are the steps I am following:

1. Remove zigbee device from HA using topic zigbee2mqtt/bridge/config/force_remove
2. Restart HA
3. Confirm zigbee device has been completely removed and it´s not appearing in the zigbee map (also zigbee2mqtt is not capturing any message sent from the device, so device has been removed)
4. Enable zigbee option “permit_join = true” to allow zigbee devices to join
5. Add the zigbee device to Ha using the reset button in the device
After this process I can see the “interview_successful” message and also any new message sent from the device in zigbee2mqtt log, but the device doesn´t appear in HA devices list or entities list

I already checked the option “Enable newly added entities” is enable within MQTT system options, so I don’t understand why the device is not added to the devices/entities list, is there any log where I can see why Mosquitto broker is not adding the device to HA properly?

**Comment by frenck** [comment]
Mosquitto broker is not part of this. It simply passes along messages. The processing of this either is on the end of the Home Assistant MQTT integration or zigbee2mqtt itself. The add-on has no knowledge of any of this, as it is just a MQTT broker.

If you suspect an issue on the Home Assistant integration, please file an detailed issue on the Core repository.

Thanks! 👍
