### ISSUE TITLE
add-on " deCONZ" conbee 2 lost connect with all zigbees

### ISSUE THREAD

**Issue by leoyangt** [home-assistant/hassio-addons#1323]
Problem : suddenly , add-on " deCONZ" conbee 2 lost connect with all zigbee.

Plz help on this problem.
Attached 2 logs= deCONZ log/ System log
[deCONZ log](https://github.com/home-assistant/hassio-addons/files/4639347/deCONZ.log)
[System log](https://github.com/home-assistant/hassio-addons/files/4639348/System.log)

--------------------------------------------------------
This HA system in Docker and enable add on Deconz.
---------------------------------------------------------
Environment
deCONZ
Current version: 5.3.2
Raspberry Pi 4
Conbee-2 installed on USB-2 with extend cable
arch | aarch64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 5.4.0-1008-raspi
python_version | 3.7.7
timezone | Asia/Taipei
version | 0.109.6
virtualenv | false

**Comment by axilleas** [comment]
Have you by any chance connected another USB device to the rpi? I have the same issue when I add another external USB drive for example.

**Comment by GubbDump** [comment]
Same issue, this just happened this morning for me.  Conbee II and deConz completely stopped working.  Have yet to figure out how to fix yet
