### ISSUE TITLE
MariaDB Addon - cant restore database from mysql dump

### ISSUE THREAD

**Issue by FaserF** [home-assistant/hassio-addons#1324]
First thanks for the MariaDB Addon. I am currently writing my own addon and want [my new addon ](https://github.com/FaserF/hassio-addons/tree/master/apache2)to integrate with your MariaDB Addon. Unfortunatly I am unable to restore a mysql dump (sql file) into your addon.
I have created the database in the mariadb addon.

The following command works, but unfortunatly displaying tables, and entrys doesnt return anything. 

`
host=$(bashio::services "mysql" "host")
    password=$(bashio::services "mysql" "password")
    port=$(bashio::services "mysql" "port")
    username=$(bashio::services "mysql" "username")

    bashio::log.info "Creating database $mariadb_filename on MariaDB Addon $host if required"
    mysql \
        -u "${username}" -p"${password}" \
        -h "${host}" -P "${port}" \
        -e "CREATE DATABASE IF NOT EXISTS \`$mariadb_filename\` ;"
    if [ -f /share/$mariadb_filename.sql ]; then
    bashio::log.info "Listing current Tables of $mariadb_filename Database with user ${username}"
    mysql \
        -u "${username}" -p"${password}" \
        -h "${host}" -P "${port}" \
        -e "SHOW TABLES FROM $mariadb_filename ;"
    bashio::log.info "Importing file  /share/$mariadb_filename.sql on MariaDB Addon $host with user ${username}"
    mysql \
        -u "${username}" -p"${password}" \
        -h "${host}" -P "${port}" \
        -e "--database=$mariadb_filename < /share/$mariadb_filename.sql ;"
`

**Comment by frenck** [comment]
I'm not really sure where the problem is with just this piece of information.
I do have an example on where I have done something similar with a migration from an internal add-on hosted MySQL instance to the MySQL service:

<https://github.com/hassio-addons/addon-nginx-proxy-manager/blob/master/proxy-manager/rootfs/etc/cont-init.d/mysql.sh>

**Comment by FaserF** [comment]
Okay, I am sorry. Looks like I used the worng commands. Your link helped me.
Thank you!
