### ISSUE TITLE
git pull erase all configuration on install

### ISSUE THREAD

**Issue by MLKiiwy** [home-assistant/hassio-addons#1325]
No joking, installing git pull erase the full config directory. 

What I did:
- install git pull
- add my ssh key + repo URL to the configuration file 
- start

Here is the log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Check SSH connection
[Warn] No valid SSH connection for git@github.com
[Info] Start adding SSH key
[Info] Setup deployment_key on id_rsa
[Warn] Git repostory doesn't exist
[Info] Backup configuration to /tmp/config-2020-05-17_13-42-07
[Info] Start git clone
Cloning into '/config'...
[Info] Checking if something has changed...
[Info] Something has changed, checking Home-Assistant config...
Error: Testing configuration at /config
Failed config
  General Errors: 
    - File configuration.yaml not found.
Successful config (partial)
[Error] Configuration updated but it does not pass the config check. Do not restart until this is fixed!
[cmd] /run.sh exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

Also the backup `/tmp/config-2020-05-17_13-42-07` disappear also.

### Possible explanation
- my git repo was empty (of course, I try to create a first sav) so the plugin does not support empty repo at the start ?
- the backup system is not working, I have checked the code https://github.com/home-assistant/hassio-addons/blob/master/git_pull/data/run.sh#L58 seems try to copy back from the backup ... problem the backup does not exist. But few lines before the backup is created, maybe a process clear it?

### Possible fix

If you have to do the backup manually first before starting the plugin, add a clear section on the installation readme.

**Comment by rik-coenders** [comment]
Seems like the directories starting with a dot are not copied. That's why `.storage` is not backed up.

**Comment by dbijman** [comment]
I had the exact same thing happening to me... maybe the add-on could create a system snapshot before attempting to wipe the whole system

**Comment by OptimusGREEN** [comment]
same here. this should really be noted in the documentation prior to a fix being released.

**Comment by Swahjak** [comment]
+1, how is this not mentioned in the docs with some proper highlighting. Was not expecting this at all.

**Comment by scolastico** [comment]
Sure by now it's in the docs, but seriously who got up on the wrong side of the bed and was too fine to write the 5 lines so that the init process creates a backup before ALL MY DATA IS DELETED?! I hope the developer of this plugin steps on lego.
