### ISSUE TITLE
Home Assistant Add-on: OpenZwave - can't add configuration

### ISSUE THREAD

**Issue by sanderlv** [home-assistant/hassio-addons#1330]
Using openzwave as add-on.
Current version: 0.2.1

Can't get the correct configuration in:

Configuration:
```
device: /dev/serial/by-id/usb-0658_0200-if00
network_key: null
```

Getting error:
`Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'device': '/dev/serial/by-id/usb-0658_0200-if00', 'network_key': None}`

**Comment by konradwalsh** [comment]
chiming in to say I have the same issue

**Comment by frenck** [comment]
You need to set a network key. If you don't want to use a network key, make it an empty string e.g., `network_key: ""`

**Comment by sanderlv** [comment]
Thank you. Tip: put this in the documentation
