### ISSUE TITLE
How do I access files outside the container

### ISSUE THREAD

**Issue by LovelyMengstar** [home-assistant/hassio-addons#1334]
pi@raspberrypi:~ $ docker run -it -v ~/Desktop/music:/opt hassioaddons/node-red-armv7:6.2.0
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
parse error: Invalid numeric literal at line 1, column 10
parse error: Invalid numeric literal at line 1, column 10

-----------------------------------------------------------
parse error: Invalid numeric literal at line 1, column 10
parse error: Invalid numeric literal at line 1, column 10
 Add-on: 
 
-----------------------------------------------------------
 Add-on version: 
 You are running the latest version of this add-on.
parse error: Invalid numeric literal at line 1, column 10
parse error: Invalid numeric literal at line 1, column 10
parse error: Invalid numeric literal at line 1, column 10
parse error: Invalid numeric literal at line 1, column 10
 System:   ( / )
 Home Assistant Core: 
 Home Assistant Supervisor: 
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
parse error: Invalid numeric literal at line 2, column 0
parse error: Invalid numeric literal at line 2, column 0
/var/run/s6/etc/cont-init.d/01-log-level.sh: line 41: log_level: unbound variable
[cont-init.d] 01-log-level.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by frenck** [comment]
Hi there @LovelyMengstar,

This is the tracker for the official Home Assistant add-ons, Node-RED is a community add-on, so it should be reported at that repository.

That said, you can't run add-ons directly via Docker. Add-ons can be installed via Home Assistant itself: Supervisor -> Add-on Store.

Please note, add-on are not available on Home Assistant Core installation types.
