### ISSUE TITLE
OpenZwave: Polling Devices

### ISSUE THREAD

**Issue by CTLS** [home-assistant/hassio-addons#1336]
Older Z wave switches require polling to be set at some interval.  There is currently no way that I see documented that allows you to set polling for these devices and now any device requiring this show incorrect states if a user uses the physical switch.

**Comment by kpine** [comment]
Polling can be enable via MQTT and the setting is for each value you want to poll. https://github.com/OpenZWave/qt-openzwave/blob/master/docs/MQTT.md#enablepoll

This addon would not be able to configure it.
