### ISSUE TITLE
DuckDNS will no longer start

### ISSUE THREAD

**Issue by stuarts0011** [home-assistant/hassio-addons#1337]
When I try to start, it exits as follows:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
# INFO: Using main config file /data/workdir/config
ERROR: Lock file '/data/workdir/lock' present, aborting.
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by Krojack** [comment]
I'm getting this too and I think because of this my SSL cert expired. I can't get the add-on working thus  it won't renew the CERT though Let’s Encrypt.

**Comment by Krojack** [comment]
UPDATE. Mine is working now. I did the following simple steps.

1. Saved my DuckDNS config to a note pad file for a short backup.
2. Uninstalled the DuckDNS add-on.
3. Restarted HA. (Don't think this is needed but it's quick)
4. Reinstalled the DuckDNS and put my saved config back in.
5. Started DuckDNS and it seems to be working now.

15 minutes later however and my SSL files have not been updated. I'll wait a few hours and check again. If cert is still expired I'll report back.

**Comment by stuarts0011** [comment]
Yep. Same here.

**Comment by scop** [comment]
Seeing this as well: I have the lockfile but no "live" certificate, guess the cert was expired. Quick workaround in a ssh session to the ssh community addon in unprotected mode:
```
docker exec -it hassos_supervisor rm /data/addons/data/core_duckdns/workdir/lock
```
