### ISSUE TITLE
Cann't remove the repository what I added

### ISSUE THREAD

**Issue by cachenow** [home-assistant/hassio-addons#1338]
I have added a repository from github before. When I tried to remove it from the "Manage add-on repositories" now, It doesn't respond ( when  I clicked the REMOVE button ).  and I tried to delete the folder via "addons/git" then reboot hassio, It also displays in the list. What should I do now?

**Comment by frenck** [comment]
This is currently fixed in the beta of Supervisor 224, which will be generally available soon.
