### ISSUE TITLE
UPNP

### ISSUE THREAD

**Issue by andymarden** [home-assistant/hassio-addons#1340]
using this and finally got everything working ok. What would be very useful if you could include a config option to programmically open port 80 on the router for renewal and close afterwards. 

Useful? Possible? What do you think?

**Comment by frenck** [comment]
I think UPnP should never be enabled on any router for port handling. It works almost never and if it does, it causes major security concerns (as any application can open up your network to the outside world...)

**Comment by boos** [comment]
It would be good to automate it for letsencrypts, open up the port, renew the certificate, close it.
