### ISSUE TITLE
Aqara Opple switches still not working

### ISSUE THREAD

**Issue by ashwin2101** [home-assistant/hassio-addons#1342]
Aqara Opple switches still not working
I'am unable to pair the switches

**Comment by frenck** [comment]
Hi there @ashwin2101,

I'm assuming this is about the deCONZ add-on?

Add-ons wrap existing applications, in this case deCONZ. Please report these types of issues with the upstream application. When the upstream application updates/releases, we'll update the add-on to have that fix.

deCONZ GitHub repository: <https://github.com/dresden-elektronik/deconz-rest-plugin>

Thanks 👍
