### ISSUE TITLE
DuckDNS: Need SAN (Subject Alteranate Name) added to config. if possible.

### ISSUE THREAD

**Issue by MithUK1** [home-assistant/hassio-addons#1343]
This is for DUCKDNS Addon:

If there was a way to add SAN to the certificate, this would allow us to add our local dns name to ther HASS duckdns name - 
With this the cert would show correctly when you go to for example myhass.local

May not be possible - but would be great addition (especially for ios app as it forces you to use external name as it won;t allow an incorrect certificate if trying to set up to use local address  (will only allow valid https address.

thank you

**Comment by altaic** [comment]
I'd very much like to know the answer to this. Any pointers?
