### ISSUE TITLE
dns-transip not working

### ISSUE THREAD

**Issue by MJLHThomassen** [home-assistant/hassio-addons#1345]
I'm trying to use the transip integrationf or this plugins, but it is not working.

The logs shows the following:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] file-structure.sh: executing... 
[cont-init.d] file-structure.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:53:14] INFO: Selected DNS Provider: dns-transip
[13:53:14] INFO: Use propagation seconds: 60
usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...
Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: unrecognized arguments: --dns-transip --dns-transip-credentials /data/dnsapikey
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by miketaal** [comment]
I have got the same issue...Someone any ideas?

**Comment by pansink** [comment]
for me the same issue...

**Comment by gnissahr** [comment]
Same issue here. To me it seems that the documentation is up to date wit github, but version in homeassistant is behind. So documentation describes what will be in next revision.

**Comment by pansink** [comment]
> Same issue here. To me it seems that the documentation is up to date wit github, but version in homeassistant is behind. So documentation describes what will be in next revision.

You could be right, so we just wait for a new version

**Comment by k-van-man** [comment]
Same issue here.

**Comment by k-van-man** [comment]
When I try to fix the issue ...
- download addons
- docker build hassio-addons-master/letsencrypt
- remove the current container
- Start via http://xxx.xxx.xxx.xxx:8123/hassio/addon/core_letsencrypt/info
then it's working, so the current image doesn't support transip

**Comment by bpwats** [comment]
FWIW: updating to HassOS 4.8 does not solve the issue.

**Comment by bpwats** [comment]
Version 4.9 does not produce this error anymore.

**Comment by k-van-man** [comment]
It works! Thanks
Maybe you can also update the version of Certbot in the future
Got this message, because the cert was create on another system before.
Plugins selected: Authenticator certbot-dns-transip:dns-transip, Installer None
Attempting to parse the version 1.4.0 renewal configuration file found at /data/letsencrypt/renewal/<redacted>.conf with version 1.2.0 of Certbot.
