### ISSUE TITLE
OpenZwave /dev/serial/by-id issue

### ISSUE THREAD

**Issue by detxm80** [home-assistant/hassio-addons#1348]
Hi, i try to set my aeonzwave stick with topic address and get this error:
Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'device': '/dev/serial/by-id/myaeonstick,  'network_key': None}

have you try to do that? thanks

**Comment by frenck** [comment]
You have to set a `network_key`. Set it to an empty string when you don't want to have it, e.g., `network_key: ""`.
