### ISSUE TITLE
Mosquitto broker logs timestamp

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [home-assistant/hassio-addons#1349]
Mosquitto broker add-on do not use correct timestamp on logging, for example it log this messsage which the time is not human readable.
`1590392657: New connection from 192.168.1.101 on port 1883`

**Comment by frenck** [comment]
Yeah that should be possible, as the Mosquitto broker has implemented it.

For reference: <https://github.com/eclipse/mosquitto/issues/299#issuecomment-504025328>
