### ISSUE TITLE
Deconz Ikea blind not updating state in Home Assistant

### ISSUE THREAD

**Issue by pdgithub78** [home-assistant/hassio-addons#1350]
The state of the blind has stopped updating for the Ikea blind. The slide bar works but if you check the position it aways states 100 for the cover. Also the slide will revert back to 100 after a restart. This has been the case since 0.110.0 of home assistant and in Deconz 5.3.3 and 5.3.2

**Comment by frenck** [comment]
Hi there @pdgithub78,

Add-ons wrap existing applications, in this case, the deCONZ application by dresden. This is considered a bug with deconz itself, which we cannot address.

Please report the issue with deCONZ:

<https://github.com/dresden-elektronik/deconz-rest-plugin>

If the deCONZ application updated, the add-on will follow that.

../Frenck
