### ISSUE TITLE
Run MQTT-Broker before HA

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [home-assistant/hassio-addons#1354]
https://github.com/home-assistant/hassio-addons/blob/80da6e8aafdfbdf4b7e395e7752d6e76640250d9/mosquitto/config.json#L8
Looks like currently MQTT-Broker use `system` for `startup` parameter which 
> is for things like databases and not dependent on other things [#](https://developers.home-assistant.io/docs/add-ons/configuration/#add-on-config)
But when HA will try to setting up integrations and entities related to MQTT before MQTT-Broker completed the setup this will cause error and does not load entities.

I looked at [documents](https://developers.home-assistant.io/docs/add-ons/configuration/#add-on-config) and think `services` is better value to use for `startup`, which 
> will start before Home Assistant

Also: https://github.com/home-assistant/core/issues/35858

**Comment by emontnemery** [comment]
HA has been improved and will now behave better if the MQTT server can't be reached when HA is starting.

**Comment by frenck** [comment]
Both `system` and `service` will start before Home Assistant, so the request in the title of this issue has already been fulfilled.

And indeed, the integration has been improved to handle this better.
