### ISSUE TITLE
MariaDB not accessible through localhost

### ISSUE THREAD

**Issue by khorne01** [home-assistant/hassio-addons#1358]
MariaDB addon seems only accessible from"inside" hassos through core-mariadb .
I mean, it works if I use 
```
recorder:
  db_url: mysql://user:password@core-mariadb/homeassistant?charset=utf8
```
but fails if using 
```
recorder:
  db_url: mysql://user:password@localhost/homeassistant?charset=utf8
```
or
```
recorder:
  db_url: mysql://user:password@xxxxx/homeassistant?charset=utf8
```
where xxxxx is the hassos ip.
It also makes not possible to access mariaDB database remotely, i.e. HeidiSQL...

**Comment by frenck** [comment]
By default, MariaDB only exposes the port internally.

If you want to expose it remotely, one can assign a port to it:

![image](https://user-images.githubusercontent.com/195327/82999791-d3654280-a009-11ea-8c52-72b625261120.png)

Replace `null` with, e.g., `3306`, hit save and restart the add-on.

**Comment by khorne01** [comment]
Thank you very much @frenck !!
So obvious mistake I missed it completely. Sorry for the noob issue, but I invested like 5 hours previously to open this "fake" issue.
