### ISSUE TITLE
checking config failed, but doesn't make it clear why

### ISSUE THREAD

**Issue by thomasvs** [home-assistant/hassio-addons#1366]
This is the output.

[13:13:44] ERROR: The configuration check did not pass!
[13:13:44] ERROR: See the output below for more details.
Testing configuration at /tmp/config
grep: write error: Broken pipe
Failed config
  scene: 
    - Invalid config for [scene]: Invalid platform specified. Got OrderedDict([('frontend', {}), ('config', {}), ('http', OrderedDict([('ssl_certificate', '/ssl/fullchain.pem'), ('ssl_key', '/ssl/privkey.pem'), ('login_attempts_threshold', -1), ('cors_allowed_origins', ['https://cast.home-assistant.io']), ('ip_ban_enabled', True), ('ssl_profile', 'modern'), ('server_port', 8123), ('server_host', '0.0.0.0')])), ('updater', {'include_used_components': False, 'reporting': True}), ('conversation', {}), ('history', {}), ('logbook', {}), ('map', {}), ('sun', {}),.... (See /tmp/config/configuration.yaml, line 346). 
    - alert: ?
        leak_herb_garden_left: ?
          can_acknowledge: True
          done_message: Template("Herb Garden Left Dry")
          entity_id: sensor.leak_hs_ls100_herb_garden_left_flood
          name: Herb Garden Left Leaking
          notifiers: [source /tmp/config/configuration.yaml:412]
            - mobile_app_pixel_2_xl
            - thomas_mail
          repeat: ?
            - 30.0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

The output given doesn't help figure out the problem.  As best as I can tell, I have a scene using an invalid platform, but it's not telling me which scene or which platform.  

I don't think the notifiers at the end of the output are related.  

The output is shortened, so the actual problem is most likely hidden.

**Comment by frenck** [comment]
It says it should be on line 346 in your configuration.yaml file...?
