### ISSUE TITLE
Request: SSH logins in Detail and create homeassistant sensor with logins

### ISSUE THREAD

**Issue by biejay** [home-assistant/hassio-addons#1367]
I cant find proper log-data of the ssh and terminal addon. Recently I got many bruteforce-style login attempts to my ssh Server. 
 So I want to See exact dates&times of All logins.
Furthermore it would be awesime to have a sensor in homeassistant, that changes state on failed logins and one sensor for successfull logins for example. 

In terms of security that would be great!

**Comment by cogneato** [comment]
This should be submitted to the community forums if it is a request, and as a post if you are looking for help. In terms of security, there is little need to expose the ssh add-on to the outside, and authorized_keys should definitely be in use if this is the case.
