### ISSUE TITLE
Request: dns-namecheap support for LetsEncrypt

### ISSUE THREAD

**Issue by andreicek** [home-assistant/hassio-addons#1368]
Can you please add support for namecheap dns provider?

**Comment by sopelt** [comment]
It would be really nice to have a more broad support especially for dns challenges. I was thinking if https://github.com/acmesh-official/acme.sh could provide a more general approach to letsencrypt without bringing heavy dependencies. I could not find any discussion on something like that but acme.sh has a really broad range on supported integrations. I am just not sure on how to elegantly and securely integrate the configuration options ....

**Comment by carvan** [comment]
same here, it would be really nice, that's the only thing holding use this addon.
