### ISSUE TITLE
File editor / Configurator: Dark themes not applying to left and top bar

### ISSUE THREAD

**Issue by jensuffhaus** [home-assistant/hassio-addons#1370]
Selecting a dark theme in the settings for the editor only applies to the actual text edit panel and not the side or top panels of the editor.

![image](https://user-images.githubusercontent.com/1774160/83348277-58fb3200-a32b-11ea-931c-f08d296160ee.png)

**Comment by frenck** [comment]
Hi there @jensuffhaus!

Thanks for opening up an issue. However, add-ons wrap existing applications, in this case: <https://github.com/danielperna84/hass-configurator>

Please report the issue upstream. Once it has been fixed, the add-on will update after that.

Thanks 👍

**Comment by almighty059** [comment]
@jensuffhaus did you ever get the dark theme to work with the File Editor and if so how.? Thanks

**Comment by schmitto29** [comment]
> @jensuffhaus did you ever get the dark theme to work with the File Editor and if so how.? Thanks

good question!
any answer here?

**Comment by NightMean** [comment]
See https://github.com/danielperna84/hass-configurator/issues/199
