### ISSUE TITLE
Need to increase proxy timeouts for HA updates

### ISSUE THREAD

**Issue by lcasale** [home-assistant/hassio-addons#1371]
Need to increase proxy timeout parameters so 504s during HA updates when using NGINX URL. Will open a PR to fix this

`Error: <html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx/1.16.1</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->`

**Comment by pvizeli** [comment]
sure
