### ISSUE TITLE
Ikea round remote can't change colour temp correctly

### ISSUE THREAD

**Issue by hell1337hound** [home-assistant/hassio-addons#1374]
Hey so i have the config in deconz setup so that the left button is colder and the right button is warmer but both buttons only make the bulb warmer. Can change colour temp in software fine - let me know if you need more info

**Comment by frenck** [comment]
Hi there @hell1337hound,

Add-ons implement/wrap existing software. In this case the Phoscon/deCONZ application. 

This issue you are reporting it within the application itself. Please report your issue with the authors of the software, as from an add-on perspective, there is not much we can do.

If a bug gets fixed, and the software updated, the add-on will be updated as well.

Thanks 👍
