### ISSUE TITLE
deCONZ failed to reconnect to network

### ISSUE THREAD

**Issue by 10bias** [home-assistant/hassio-addons#1376]
Hello, after a update a few days ago the deCONZ Addon does not work any more. I use the RaspBee 2. I think the addon can not connect to the RaspBee 2. In the addon UI the items like the lights are lost. Here is the log:

```
20:36:07:784 device disconnected reason: 1, index: 0
20:36:08:278 failed to reconnect to network try=3
20:36:08:278 wait reconnect 15 seconds
20:36:08:278 void zmMaster::handleStateIdle(zmMaster::MasterEvent) not connected goto OFF state
20:36:08:278 device state timeout ignored in state 1
20:36:09:277 wait reconnect 14 seconds
20:36:10:278 wait reconnect 13 seconds
20:36:10:318 dev /dev/ttyAMA0
20:36:11:277 wait reconnect 12 seconds
20:36:12:277 wait reconnect 11 seconds
20:36:13:278 failed to reconnect to network try=4
20:36:13:278 wait reconnect 10 seconds
20:36:14:277 wait reconnect 9 seconds
20:36:15:278 wait reconnect 8 seconds
20:36:16:278 wait reconnect 7 seconds
20:36:17:278 wait reconnect 6 seconds
20:36:18:278 failed to reconnect to network try=5
20:36:18:278 wait reconnect 5 seconds
20:36:19:278 wait reconnect 4 seconds
20:36:20:278 wait reconnect 3 seconds
20:36:20:321 dev /dev/ttyAMA0
20:36:21:278 wait reconnect 2 seconds
20:36:22:278 wait reconnect 1 seconds
20:36:22:314 dev /dev/ttyAMA0
20:36:22:314 COM: /dev/ttyAMA0 / serialno: 
20:36:22:314 COM: --dev: /dev/ttyAMA0 (RaspBee)
20:36:22:810 device state timeout ignored in state 2
20:36:23:277 try to reconnect to network try=6
20:36:24:778 device state timeout ignored in state 2
20:36:25:777 device state timeout ignored in state 2
20:36:26:778 device state timeout ignored in state 2
20:36:27:777 device state timeout ignored in state 2
20:36:28:278 try to reconnect to network try=7
20:36:29:778 device state timeout (handled)
20:36:29:785 device disconnected reason: 1, index: 0
20:36:30:278 wait reconnect 15 seconds
20:36:30:278 void zmMaster::handleStateIdle(zmMaster::MasterEvent) not connected goto OFF state
20:36:30:278 device state timeout ignored in state 1
20:36:30:317 dev /dev/ttyAMA0
20:36:31:277 wait reconnect 14 seconds
```

And here my config:

```
device: /dev/ttyAMA0
vnc_password: changeme
```

Any ideas to solove this problem?

**Comment by Marcootten** [comment]
I have the same issue, first my lights disapeared and now my sensors are offline as well. I tried removing the raspbee module and adding it back.

I also found the following in my system log:

20-06-03 17:35:04 INFO (SyncWorker_5) [supervisor.docker.addon] Start Docker add-on homeassistant/armhf-addon-deconz with version 5.3.5
20-06-03 17:35:04 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.1:8099 ssl:None [Connection refused]

**Comment by rtirelli** [comment]
Just upgraded to the 5.3.5
All sensors are now offline! How to go back to the previous release?

**Comment by Fabian1185** [comment]
I also had that issue, but I fixed it using the following configuration:

`device: /dev/ttyS0`
`vnc_password: '' `

Before I had this config:

`device: /dev/ttyAMA0`
`vnc_password:  ''`

**Comment by Marcootten** [comment]
> I also had that issue, but I fixed it using the following configuration:
> 
> `device: /dev/ttyS0`
> `vnc_password: '' `
> 
> Before I had this config:
> 
> `device: /dev/ttyAMA0`
> `vnc_password: ''`

This worked for me as well, thanks! I didn't change anything in the hardware, why would the device ID/name change?

**Comment by 10bias** [comment]
Changing it to /dev/ttyS0 does not work for me. I have no device /dev/ttyS0. In the HA supervisor I only have /dev/ttyAMA0 as a serial device.

**Comment by Fabian1185** [comment]
> > I also had that issue, but I fixed it using the following configuration:
> > `device: /dev/ttyS0`
> > `vnc_password: '' `
> > Before I had this config:
> > `device: /dev/ttyAMA0`
> > `vnc_password: ''`
> 
> This worked for me as well, thanks! I didn't change anything in the hardware, why would the device ID/name change?

I also didn‘t change anything in the hardware. I only tested the other serial devices in the HA supervisor (There are 4 in my supervisor: /dev/ttyAMA0; /dev/ttyACM0 (ZWave Stick); /dev/serial/by-id/usb-0658_0200-if00; /dev/ttyS0)

**Comment by samuelemarazzita** [comment]
Same problem here!

**Comment by samuelemarazzita** [comment]
Oh, another thing. This is what is telling me in the Gateway page.

<img width="726" alt="Schermata 2020-06-04 alle 17 36 22" src="https://user-images.githubusercontent.com/5025182/83777721-09e63180-a68a-11ea-84ee-cb6e307b296f.png">

**Comment by finim** [comment]
Same for me. Nothing is working anymore for days. All my ZigBee devices are offline and I cannot use it.
First I thought my RasbBee is broken so I ordered a brand new "RaspBee II" that I received today., But here's the same: Nothing works anymore, no connection to network, discovery failed, all ZigBee devices offline.
I tried to delete the addon and all integrations manually for at least 10 times, reset home Assistant to a previously working snapshot: Not working at all. 

Something broke here, seriously!

**Comment by samuelemarazzita** [comment]
For me it was the first configuration and lost. hours looking online for issues like mine. I'm happy that I've found this! I'm not alone!

**Comment by 10bias** [comment]
The Gateway page looks the same for me. I think the problem correlates with this issues:
https://github.com/home-assistant/hassio-addons/pull/1375
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2875
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2874

**Comment by alexdepalex** [comment]
@samuelemarizzata Did you install the latest update?

**Comment by samuelemarazzita** [comment]
@alexdepalex Guess yes.

<img width="1008" alt="Schermata 2020-06-04 alle 19 01 55" src="https://user-images.githubusercontent.com/5025182/83788668-ddd0ad80-a695-11ea-8251-0827d8bdf57e.png">

**Comment by alexdepalex** [comment]
@samuelemarazzita Yeah, that seems to break existing connections to devices. I'm trying to find a solution for this, but currently, my entire environment is broken.

**Comment by finim** [comment]
> @samuelemarazzita Did you install the latest update?

yes, still not working :(

**Comment by finim** [comment]
I just succeeded to get my "RaspBee II" system back to a working state for me, doing the following things in order:

**Attention: This will reset the gateway and will delete any light / switch / sensor but resolves the 
device disconnected reason: x" errors and the gateway could connect successfully afterwards on my system.**

**First of all: Create a full snapshot in Hass.io so you can always go back to the current state!**

1. Delete the "Phoscon" Integration in Hass.io Integrations site
2. Uninstall the deconZ addon in Hass.io
3. Remove all occurencies of "deconZ" and "ZigBee" entities / devices in the files located in "/config/storage/" **(be very careful editing these files as a mistake can break anything!)**
4. Reboot the Hass.io Host system
5. Install the deconZ Plugin again, and configure the device as "/dev/ttyS0" **(not /dev/ttyAMA0 !)** 
6. Start the deconZ addon
7. Login into the deconZ addon Web-UI
8. Set a new Login password for the gateway on first login
9. Within the deconZ Web-UI, go to "Gateway" and chose "Reset gateway". **You will loose all your entities within but it was needed on my system to get the connections back!**
10. Log out of deconZ
11. Reboot the Hass.io Host again
After the reboot of the Host the deconZ Gateway was connected an online and I was able to re-assign all my entities / create them new.

**Comment by Marcootten** [comment]
Hi have Deconz back working, all the sensors are there but I'm just not able to control my lights in HA. They are working in the Deconz UI though.

**Comment by samuelemarazzita** [comment]
> I just succeeded to get my "RaspBee II" system back to a working state for me, doing the following things in order:
> 
> **Attention: This will reset the gateway and will delete any light / switch / sensor but resolves the "device disconnected reason: x" errors and the gateway was able to connect successfully afterwards on my system.**
> 
> **First of all: Create a full snapshot in Hass.io so you can always go back to the current state! (at least for Hass.io)**
> 
> 1. Delete the "Phoscon" Integration in Hass.io Integrations site
> 2. Uninstall the deconZ addon in Hass.io
> 3. Remove all occurencies of "deconZ" and "ZigBee" entities / devices in the files located in "/config/storage/" **(be very careful editing these files as a mistake can break anything!)**
> 4. Reboot the Hass.io Host system
> 5. Install the deconZ Plugin again, and configure the device as "/dev/ttyS0" **(not /dev/ttyAMA0 !)**
> 6. Start the deconZ addon
> 7. Login into the deconZ addon Web-UI
> 8. Set a new Login password for the gateway on first login
> 9. Within the deconZ Web-UI, go to "Gateway" and chose "Reset gateway". **You will loose all your entities within but it was needed on my system to get the connections back!**
> 10. Log out of deconZ
> 11. Reboot the Hass.io Host again
>     After the reboot of the Host the deconZ Gateway was connected an online and I was able to re-assign all my entities / create them new.
> 
> I write this here because maybe it's useful for somebody who just wants to get the system back to work and does not care about loosing all configured lights, sensors and switches (as me), but, as said, **this approach will definitely delete everything configured in deconZ!**

Not working for me. This is the log when I start the addon:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
starting version 232
[12:18:25] INFO: Waiting for device...
```
I went to **Supervision > System > Hardware** and saw that the serial is setted to **/dev/ttyAMA0** and not to /dev/ttyS0.

When I put in the device configuration **/dev/ttyAMA0** the addon starts correctly with this log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
starting version 232
[12:21:20] INFO: Waiting for device...
[12:21:21] INFO: Starting the deCONZ gateway...
libpng warning: iCCP: known incorrect sRGB profile
```
libpng warning: iCCP: known incorrect sRGB profile
[12:21:23] INFO: Starting Nginx...
[12:21:23] INFO: Running Home Assistant discovery task...
[12:21:23] INFO: Running the deCONZ OTA updater...
[12:21:23] INFO: Running the IKEA OTA updater...
[12:21:23] INFO: Running the LEDVANCE/OSRAM OTA updater...
[12:21:23] INFO: deCONZ is set up and running!
Error: no such table: auth
2020/06/05 12:21:23 [notice] 487#487: using the "epoll" event method
2020/06/05 12:21:23 [notice] 487#487: nginx/1.10.3
2020/06/05 12:21:23 [notice] 487#487: OS: Linux 4.19.114-v7
2020/06/05 12:21:23 [notice] 487#487: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2020/06/05 12:21:23 [notice] 487#487: start worker processes
2020/06/05 12:21:23 [notice] 487#487: start worker process 517
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
12:21:22:701 HTTP Server listen on address 0.0.0.0, port: 40850, root: /usr/share/deCONZ/webapp/
12:21:22:992 CTRL. 3.16.212:21:23:193 dev /dev/ttyAMA0
12:21:23:193 COM: /dev/ttyAMA0 / serialno: 
12:21:23:193 COM: --dev: /dev/ttyAMA0 (RaspBee)
12:21:23:193 ZCLDB init file /data/.local/share/dresden-elektronik/deCONZ/zcldb.txt
12:21:23:571 parent process bash
12:21:23:571 gw run mode: docker/hassio
12:21:23:571 GW sd-card image version file does not exist: /data/.local/share/dresden-elektronik/deCONZ/gw-version
12:21:23:572 sd-card cid: 1b534d454231514c30ffffffff013407
12:21:23:603 DB sqlite version 3.16.2
12:21:23:604 DB PRAGMA page_count: 0
12:21:23:604 DB PRAGMA page_size: 4096
12:21:23:604 DB PRAGMA freelist_count: 0
12:21:23:604 DB file size 0 bytes, free pages 0
12:21:23:604 DB PRAGMA user_version: 0
12:21:23:604 DB upgrade to user_version 1
12:21:24:236 DB write sqlite user_version 1
12:21:24:245 DB PRAGMA user_version: 1
12:21:24:245 DB upgrade to user_version 2
12:21:24:299 DB write sqlite user_version 2
12:21:24:306 DB PRAGMA user_version: 2
12:21:24:306 DB upgrade to user_version 6
12:21:24:374 DB write sqlite user_version 6
12:21:24:385 DB PRAGMA user_version: 6
12:21:24:385 DB cleanup
12:21:24:386 DB create temporary views
12:21:24:400 don't close database yet, keep open for 900 seconds
12:21:24:401 don't close database yet, keep open for 900 seconds
12:21:24:403 started websocket server at port 8081
12:21:24:406 create default username and password
12:21:24:417 found node plugin: libde_rest_plugin.so - REST API Plugin
12:21:24:421 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
12:21:24:498 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
12:21:24:540 dev /dev/ttyAMA0
12:21:24:540 COM: /dev/ttyAMA0 / serialno: 
12:21:24:541 COM: --dev: /dev/ttyAMA0 (RaspBee)
12:21:29:690 don't close database yet, keep open for 900 seconds
12:21:29:779 dev /dev/ttyAMA0
12:21:30:987 Announced to internet http://dresden-light.appspot.com/discover
12:21:30:988 discovery server date: Fri, 05 Jun 2020 10:21:30 GMT
12:21:30:988 	 local time seems to be ok
12:21:30:988 discovery found version 2.04.35 for update channel stable
12:21:34:807 dev /dev/ttyAMA0
12:21:34:807 COM: /dev/ttyAMA0 / serialno: 
12:21:34:807 COM: --dev: /dev/ttyAMA0 (RaspBee)
12:21:35:306 device state timeout ignored in state 2
12:21:36:260 device state timeout ignored in state 2
12:21:37:261 device state timeout ignored in state 2
12:21:38:260 device state timeout ignored in state 2
12:21:39:260 device state timeout ignored in state 2
12:21:39:810 dev /dev/ttyAMA0
12:21:40:260 device state timeout (handled)
12:21:40:272 device disconnected reason: 1, index: 0
12:21:40:760 wait reconnect 15 seconds
12:21:40:760 void zmMaster::handleStateIdle(zmMaster::MasterEvent) not connected goto OFF state
12:21:40:761 device state timeout ignored in state 1
12:21:41:761 wait reconnect 14 seconds
12:21:42:761 wait reconnect 13 seconds
12:21:43:760 wait reconnect 12 seconds
12:21:44:260 start reconnect to network
12:21:44:760 wait reconnect 11 seconds
12:21:45:761 wait reconnect 10 seconds
12:21:46:761 wait reconnect 9 seconds
12:21:47:761 wait reconnect 8 seconds
12:21:48:760 wait reconnect 7 seconds
12:21:49:510 failed to reconnect to network try=1
12:21:49:760 wait reconnect 6 seconds
12:21:49:805 dev /dev/ttyAMA0
12:21:50:761 wait reconnect 5 seconds
12:21:51:760 wait reconnect 4 seconds
12:21:52:760 wait reconnect 3 seconds
12:21:53:760 wait reconnect 2 seconds
12:21:54:761 failed to reconnect to network try=2
12:21:54:761 wait reconnect 1 seconds
12:21:54:797 dev /dev/ttyAMA0
12:21:54:797 COM: /dev/ttyAMA0 / serialno: 
12:21:54:797 COM: --dev: /dev/ttyAMA0 (RaspBee)
12:21:55:320 device state timeout ignored in state 2
12:21:56:270 device state timeout ignored in state 2
12:21:57:261 device state timeout ignored in state 2
12:21:58:260 device state timeout ignored in state 2
12:21:59:260 device state timeout ignored in state 2
12:21:59:761 try to reconnect to network try=3
12:21:59:803 dev /dev/ttyAMA0
```
And, if I open the Web-UI and go to **Settings > Gateway** I still see **Firmware: Not Connected**.

**Comment by SwoopX** [comment]
Although I don't use HA, I'm happy to share my experience as it resolved the issue and was non-inversive. However, it might not work flawlessly in case any docker instance is used.

1. Power down the whole system and remove Conbee for at least 10 secs. Insert back and power on. Eventually, this is already sufficient.
2. In case that didn't help, use GCFFlasher that comes with deconz package.
3. Stop deconz `sudo systemctl stop deconz` (Headless version), or
`sudo systemctl stop deconz-gui` (GUI version)
`sudo GCFFlasher_internal -l` to see the device details. I had an error back in the days which ended up in me deciding to re-flash the firmware that was installed (firmwares can be found here http://deconz.dresden-elektronik.de/deconz-firmware/). I used `sudo GCFFlasher_internal -d /dev/ttyACM0 -t 60 -f deCONZ_ConBeeII_0x264a0700.bin.GCF` (for ConbeeII)

After that, everything was back up and running again and it didn't impact any paired devices.

There might also be a chance to retain your devices if you back up your deconz database file for the method as described by @finim. That file is typically found in the home directory of the user running deconz `.local/share/dresden-elektronik/zcl/zll.db` (might be found elsewhere depending on your setup). If you restore it back, the devices are probably recognized again.

**Comment by samuelemarazzita** [comment]
Just an update for me that solved my issue:

- Toke off the SD card from the raspberry
- Placed the SD into a Linux base hardware
- Wrote into `config.txt` (at the end of the doc) this code:
```
enable_uart=0
dtoverlay=pi3-miniuart-bt-overlay
```

After this, deConz recognized my device correctly and everything started working.

**Comment by xbmcnut** [comment]
> 
I had an error back in the days which ended up in me deciding to re-flash the firmware that was installed (firmwares can be found here http://deconz.dresden-elektronik.de/deconz-firmware/). I used `sudo GCFFlasher_internal -d /dev/ttyACM0 -t 60 -f deCONZ_ConBeeII_0x264a0700.bin.GCF` (for ConbeeII)
> 
Any reason why you didn't go with `deCONZ_ConBeeII_0x26580700.bin.GCF`?

**Comment by SwoopX** [comment]
Very simple: I've a Raspbee I ;)

**Comment by xbmcnut** [comment]
> Very simple: I've a Raspbee I ;)

I'm a dumb ass!

**Comment by Bunnyoverlord** [comment]
As @SwoopX already mention. Workaround: Downgrade/upgrade your firmware to 0x264a0700 and you will be back up and running again. Don't forget to backup you Conbee stick. My system: Intel NUC with ConBee II stick.

**Comment by Puntoboy** [comment]
I'm having the same issue here, but downgrading the firmware doesn't work. I still cannot connect to the ConbeeII. :(

**Comment by potemy** [comment]
I have the same issue since update deConz ....

**Comment by samvanh** [comment]
Same issue since FW update of Conbee II

**Comment by frenck** [comment]
This is not an issue addressable for the add-on, as the problem lies in the deCONZ software itself.

Since add-ons wrap existing applications, there is not much we can do. 

Please report these issues with dresden itself.

Thanks 👍
