### ISSUE TITLE
Cannot start DNSMasq in 0.110

### ISSUE THREAD

**Issue by kmycek** [home-assistant/hassio-addons#1391]
Add-In is completely unresponsive. Nothing in the logs. Cannot start it up - even with the minimalist amount of config.

Home Assistant 0.110.7
HassOS 4.10

**Comment by kmycek** [comment]
Oh, I see that AdGuard is using tcp port 53.... Is there any way to configure them both to work? I just want a local DNS for some of my local services with static IPs....

**Comment by frenck** [comment]
That is not possible unless you assign them both different ports 👍
