### ISSUE TITLE
openzwave update to 4.0 seems to have broken ability to amend configuration settings

### ISSUE THREAD

**Issue by Grynneman** [home-assistant/hassio-addons#1398]
running hassio on ubuntu x86.

Just upgraded to openzwave version 4.0, and I'm trying to amend the device location from /dev/ttyACM4 to /dev/serial/by-id/usb-0658_0200-if00 and the following error is appearing 

**"Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'device': '/dev/serial/by-id/usb-0658_0200-if00', 'network_key': ''}"**

Thought there was an issue with the update, so uninstalled the add-on, restarted HA server and reinstalled addon.  Tried to amend the device location from null to /dev/ttyACM4, and now this is being rejected with same error as above (except for different portname).

**Comment by frenck** [comment]
Fixed in 0.4.1
