### ISSUE TITLE
OpenZwave Beta DanFoss TRV Heating element missing in Home assistant auto detect.

### ISSUE THREAD

**Issue by hossface** [home-assistant/hassio-addons#1401]
OpenZWave 4.01
Home Assistant 0.111.0

All my Danfoss TRV`s arent showing the heat set point inside Home assitant but are viewable on the Openzwave app.

![Capture](https://user-images.githubusercontent.com/26310046/84437355-bd23cd00-ac2c-11ea-93ae-e4554be9a25a.JPG)

**Comment by frenck** [comment]
Hi there @hossface,

The issue you are reporting is related to the Home Assistant OpenZWave beta integration. Please report your issue with the Home Assistant Core project.

<https://github.com/home-assistant/core/issues>


Thanks 👍
