### ISSUE TITLE
Remotec ZRC-90 not working with OpenZWave addon

### ISSUE THREAD

**Issue by gcorgnet** [home-assistant/hassio-addons#1402]
I've moved my Z-Wave network from the built-in Z-Wve integration into this addon and my ZRC-90 Z-Wave remote is no longer working with HA

It is being recognised by HA but doesn't offer any useful entity that lets me detect which buttons are being pressed.

![image](https://user-images.githubusercontent.com/4731735/84469170-899c7d80-acd4-11ea-8350-3d776526c78c.png)

![image](https://user-images.githubusercontent.com/4731735/84469214-a0db6b00-acd4-11ea-933f-624a0e1966f2.png)

Now, when I press on one of the buttons, I can see in the OWZ UI that the press is being picked up.
The problem is there is no entity being created by HA to let me access this press.

What can I do?

**Comment by Technikte** [comment]
@gcorgnet Could you share how you have done it in the end ? Is there any way to use the button press (1x, 2x times) in homeassistant with the offical Openzwave mqtt solution ?
