### ISSUE TITLE
Openzwave addon doesn't start on bootup

### ISSUE THREAD

**Issue by HFeenstra** [home-assistant/hassio-addons#1404]
Supervisor: 227
HassOS: 4.10
Home Assistant Core: 0.111.1

Installed the OpenZwave addon, removed the other integration: Zwave. Add USB and network key. Start is working fine, after reboot it won't auto-start, toggle "Start on boot" is on.

I know it is still in progress but want to share this issue I have.

**Comment by frenck** [comment]
Anything in the logs?

**Comment by HFeenstra** [comment]
Morning @frenck yesterday 13-6-2020, I noticed there was an update 0.4.3. Installed double checked the settings and logs nothing notable. 
I then restarted Hass and all came up normally. So I close it for now.

Am really happy with this addon, nice straight forward. Also adoption is really nice and quick done!

**Comment by HFeenstra** [comment]
Hello,

Sorry, but the issue hasn't gone.

After a reboot it won't auto-start, toggle "Start on boot" is on.

I know it is still in progress but want to share this issue I have.

**Comment by kmpm** [comment]
Still not working after update to v0.5.0

**Comment by MartinHjelmare** [comment]
Please update the add-on to 0.5.2 and try again. We need more information to be able to respond to this issue.

**Comment by HFeenstra** [comment]
Hello @MartinHjelmare I just updated to 0.5.2 as requested.
It did come up, so I then rebooted Hassio to make sure it still works after a reboot: it does works as would be aspected. 
It looks like the 0.5.2 also doesn't prompt for the Open device window, it straight went to the overview of the Zwave devices, nice! Keep up the work, I do love it.
Hopefully this works for others as well?

**Comment by MartinHjelmare** [comment]
Ok, I'll close here for now then. Please open a new issue with updated information if there are more problems. :+1:
