### ISSUE TITLE
add an option to allow using network key from the documentation

### ISSUE THREAD

**Issue by rubenfiszel** [home-assistant/hassio-addons#1406]
Recently, it was introduced a check to make sure users were not using the network-key from the documentation https://github.com/home-assistant/hassio-addons/blob/master/zwave/rootfs/etc/cont-init.d/network_key.sh#L5

I am in the unfortunate situation of having a big zwave mesh using the network key from the documentation (which was already used in the previous documentation) which mean that I am unable to use this new official add-on. I know it is my fault and I should not have done that but I do not want to have to reset my whole network and I'm comfortable with the fact that my network is not really secure because of that key.

Could you please evaluate two solutions:
- either provide the possibility to force this network key even though it is dangerous (the 'know-what-i-am-doing' option)
- modify the network key from the documentation (and the one checked in that script) so that it only affect new users and not users that had an integration not failing at start with the previous zwave component and built a big zwave mesh.

I know it is my fault but I would really appreciate if this was considered so I can migrate to this new add-on. Thanks for the great work btw

**Comment by rubenfiszel** [comment]
If you were to accept the second proposal, I made a PR in #1407

**Comment by frenck** [comment]
I'm sorry to hear that, but this key has been documented and used in several examples for a long time already.

Just changing it to save your situation, seems like a generally bad idea. This check has been added for the reason you are experiencing right now. Changing it, defeats that purpose.

**Comment by rubenfiszel** [comment]
@frenck It is somewhat a breaking change to make using this key impossible when it was possible before. 

> this key has been documented and used in several examples for a long time already.

So ? What is a con of changing the documented key ? When it was used in example in before, one was able to use without having it being a failure at start so it would go unnoticed. The behavior change warrant a reset of that key imho.

The only con I see is if someone is already using that generated key but the odds are extremely thin (near impossible) considering collision odds given the size of the key.

Otherwise, could you make this check non-fatal (or an option to make it non fatal) as proposed in solution 1.

Sure it is my fault in the end, I should not have blindly copy pasted that key, but would be nice to have some tolerance for mistakes if there are alternatives.

**Comment by frenck** [comment]
I'm sorry to hear you feel that way.

This add-on is marked experimental, the integration is beta.
I'm sorry to hear you are having problems, but it is part of the running beta.

The change was logged in the changelog and the version of the add-on has been adjusted accordingly, following semantic versioning for version still below 1.0.

That said, that key should not be used. The cons it that it defeats security, as it is a published, known key. The fact you have publicly stated now you are using that key... I would highly recommend on changing it as fast as possible.

**Comment by rubenfiszel** [comment]
I am not arguing that semantic versioning was improperly used, I am arguing that this is an unnecessary breaking change. Since there seems to be no want to change that behavior, it will be the same after beta.

About the security of my setup, yes it's insecure but no it doesn't matter, there is no confidential data nor lock on my network. At the end of the day, one should be allowed to do insecure things if he want to.

Anyway, it's up to you and I find the response very holier than though and as a fellow software engineer, I find it saddening. Software is designed for people I am likely not the only one affected. There is very low downside to implement an escape hatch. I can implement it myself if it's just a question of time constraint.

It's not very important in the end, I can keep the old integration forever, it works well for me.
