### ISSUE TITLE
addon-ssh: Configurator saves malformed SSH key

### ISSUE THREAD

**Issue by sharkyP** [home-assistant/hassio-addons#1409]
Unsure if this is the right place to post however the below issue appears to be affecting the SSH addon and seems unaddressed in this repository

https://github.com/hassio-addons/addon-ssh/issues/144

**Comment by DanskerUS** [comment]
Is this related: Using either Putty or WinSCP I get connection refused from HA (with either of the SSH addon's)  I see the following in the HA console:
“nf_conntrack: default automatic helper assignment has been turned off for security reasons and CT-based firewall rule not fund. Use the iptables CT target to attach helpers instead.” Ping works.  Running HA under VirtualBox. Any suggestions?  Anyway to install an older version of SSH & Web Terminal ?
