### ISSUE TITLE
hassio.addon_stdin

### ISSUE THREAD

**Issue by Giancky79** [home-assistant/hassio-addons#1411]
Hi, i'm try to use hassio.addon_stdin with core_ssh, not working with hassio_addons? i'm try with
addon: core_ssh
input: 'ha core restart'
or 
addon: core_ssh
input:  {"command": "ha core update" }
but anything happens
thx

**Comment by frenck** [comment]
That is an experimental feature of the community SSH & Web Terminal add-on. 

It is not a feature of the core SSH add-on.

**Comment by Giancky79** [comment]
![example](https://user-images.githubusercontent.com/46261713/85285900-fc0a1c00-b491-11ea-820e-db2ec5e1766a.png)
Thanks for your answer, but in service i have this example

**Comment by frenck** [comment]
Yes, it depends on that add-on if it implements this feature. The add-on you reference to, does not implement that feature.

**Comment by Giancky79** [comment]
ok thanks for all
