### ISSUE TITLE
Cannot use external MQTT broker

### ISSUE THREAD

**Issue by tomdh76** [home-assistant/hassio-addons#1414]
Hello,
I have an external MQTT broker on a NAS on which several MQTT messages are published. I would like to use that broker for the addon and not to setup another broker
thx
tom

**Comment by frenck** [comment]
Hi Tom,

Could you please share which add-on we are talking about here?
As this repository you are reporting an issue too, contains all add-ons...

**Comment by tomdh76** [comment]
Hi Frenck, 
Sorry i’m not that experienced with github. I have this problem with the open zwave addon (beta)

**Comment by frenck** [comment]
This add-on does not support that. Would recommend on running the [qt-openzwave](https://github.com/OpenZWave/qt-openzwave) (what powers this add-on) yourself in that case.

**Comment by tomdh76** [comment]
thx, but I think I can not use that docker because I run HassOS

**Comment by Petro31** [comment]
This just came up again on the forums.  Might just want to expose port/ip for mqtt broker.

**Comment by thexperiments** [comment]
Same problem here, I would like to use it with an external MQTT server that I run anyway which is password protected and currently don't se a way to provide a username/password

**Comment by frenck** [comment]
@Petro31 That is not how the design of the add-on is. Next up would be documentation and even with that, it would still not use an external broker.

Adding configuration parameters would be a better option, but that might interfere with the integration roadmap. That needs to be checked with the team that implements the integration.

This is on my radar.

**Comment by Petro31** [comment]
@frenck sounds like a good plan.

**Comment by frenck** [comment]
not stale

**Comment by dsbaars** [comment]
Could you make this is more clear in the README / instructions that this is not supported (yet)? 
Was searching quite a long time for MQTT broker settings, the dependency on the Mosquitto was small hint but it was only until I found this issue this is not possible with the add-on.
