### ISSUE TITLE
Unable to Open ozw-admin version 0.4.4

### ISSUE THREAD

**Issue by schildgenb** [home-assistant/hassio-addons#1415]
I updated the OpenZwave addon to version 04.4 and now I am unable to open the ozw-admin in all the methods as it keeps killing the add-on and stating connection refused. Below is the log:
>1592494485: Socket error on client qt-openzwave-1, disconnecting.
>[cont-finish.d] executing container finish scripts...
>[cont-finish.d] done.
>[s6-finish] waiting for services.
>1592494485: mosquitto version 1.6.8 terminating
>1592494485: Saving in-memory database to /data/mosquitto.db.
>[s6-finish] sending all processes the TERM signal.
>[s6-finish] sending all processes the KILL signal and exiting.

**Comment by schildgenb** [comment]
I was able to get a screenshot of an error that occured:
![OZW-ADMIN Error](https://user-images.githubusercontent.com/31838470/85048817-787ec100-b159-11ea-92f5-cf8d0dc4721a.png)

**Comment by Kurisutian** [comment]
Same here. Any known solutions exist yet?

**Comment by kpine** [comment]
Did you try changing the configuration setting as described in the error message?

**Comment by Kurisutian** [comment]
How? Couldn't find the option to set in the configuration.

**Comment by kpine** [comment]
Go to File -> Preferences -> Network in the tool.

**Comment by Kurisutian** [comment]
Well, I was so focused on the configuration of the addon itself, I didn't check the UI... thanks for the hint. Unfortunately when going there the VNC screen gets disconnected right away. Can't get it to open the settings.

**Comment by kpine** [comment]
Are you using version 0.4.4 of the addon?

**Comment by Kurisutian** [comment]
> Are you using version 0.4.4 of the addon?

Yes, I just updated. Worked with 0.4.3

**Comment by schildgenb** [comment]
It happens the same here with the addon webui it disconnects right away. I tried the OZW-ADMIN tool download and it works with that one when I change the settings. I am also on 0.4.4.

**Comment by natekspencer** [comment]
Same issue here. 0.4.3 worked, but 0.4.4 results in this error. Can't change settings in the web-ui, but I can change the setting in the downloaded tool and get it to work.

**Comment by kpine** [comment]
There was a [bug](https://github.com/OpenZWave/ozw-admin/issues/42) that would result in the application crashing if opening preferences before connecting, kind of sounds like that, but the fix was included in 0.4.4, so I guess not. I don't use the addon, but the allinone docker image, and it works OK.

**Comment by cree8** [comment]
@kpine I attempted to open preferences to change the settings and the addon crashed immediately afterwards. Sounds like the patch maybe wasnt fully successful in rectifying the issue..

**Comment by kahnman** [comment]
I too am getting the "Please Increase the Network Cache Size in the Configuration. Current Setting: 1000 Remote Max Records: 1294" error. 

I am also unable to change the cache size because just like @Kurisutian, VNC disconnects immediately after clicking on "Preferences" with the error: "Connection reset by peer (10054)". I am using version 0.4.4 of the Add-On.

**Comment by kahnman** [comment]
With the help of freshcoast in the zwave channel on the Home Assistant Discord, we found a work around for this issue. 

Download the [OpenZWave Admin program](http://bamboo.my-ho.st/bamboo/browse/OZW-OZW/latest). I downloaded the Windows version (OpenZwave Admin-0.1.0-installer.exe). Version 0.1.63 didn't seem to work for me. 

In Home Assistant, on the configuration tab of the OpenZWave addon, make sure that the host value for "ozw-admin port" is changed from "null" to "1983". That opens port 1983 on the addon container. 

Open the OpenZWave Admin program.
Click File > Preferences
Click the Network tab
Change the value of "Network Object Cache" to a number higher than the error you're getting. My error said "Remote Max Records: 1294" so I changed Network Object Cache to 2000.
Click OK.
The program will close. 
Reopen the OpenZWave Admin program.
Click "Open"
Type the IP address or host name of your Home Assistant instance in the "Remote Host" field. 
Set the port field to "1983".
You should likely leave the Authentication Key field blank. 
Click Start

**Comment by Veldkornet** [comment]
I have the same problem, and then my OpenZWave add-on immediately crashed right after.

**Comment by Fishwaldo** [comment]
The crash on clicking Ok on the preferences/config window has been fixed upstream. 

As for the actual message about increasing the Cache Size - its a work around for a upstream bug. Until thats fixed, you have to manually adjust the value in the "File" -> "Preferences" -> Network window and restart ozwadmin

**Comment by SirDeadlystrike** [comment]
Same issue, but I can't edit the settings. If i click "File" -> "Preferences" the vnc viewer disconnects immediately every time

**Comment by jef-pearlman** [comment]
Just a me too post.  

I get the same error and configuration menu option crashes the app in 0.4.4.  I was already using a Windows ozwadmin sometimes, and was able to update that configuration and make it work, but the windows client is not always available to me for other reason.  Thanks!

**Comment by abmantis** [comment]
With 0.5 (https://github.com/home-assistant/hassio-addons/pull/1444) I'm now able to access the Preferences menu and increase the cache size.

**Comment by wrkn4alivn** [comment]
Just updated to 0.5, and I can also report that the Preferences menu now works. I increased the network cache size and can successfully connect to the remote daemon. However, as soon as the admin UI populates, VNC disconnects the session (Error: Network connection lost). This happens whether I use the Supervisor web client or separate VNC client to port 5900. Are there logs I can check for this, and/or should I file a separate bug?

**Comment by MartinHjelmare** [comment]
I'll close here since it now works to access preferences and change cache size to get the admin running. The background to this workaround is an upstream bug, as per https://github.com/home-assistant/hassio-addons/issues/1415#issuecomment-646523535.

Please open new issues for any other problems.
