### ISSUE TITLE
OpenZwave periodically crashes when opening the admin UI

### ISSUE THREAD

**Issue by anthonyangel** [home-assistant/hassio-addons#1419]
When I try and open the admin UI I get the following error message and the whole addon stops.

![image](https://user-images.githubusercontent.com/2271981/85143877-3b422e00-b242-11ea-87d8-3ea1be6f353c.png)

**Comment by frenck** [comment]
Duplicate of https://github.com/home-assistant/hassio-addons/issues/1415
