### ISSUE TITLE
samba: Please add a share for accessing add-on persistent data

### ISSUE THREAD

**Issue by j9brown** [home-assistant/hassio-addons#1420]
I'd like to be able to access persistent data belonging to add-ons just like I can access the main configuration files in the config share.  I've found it useful to examine and modify these files to debug and customize add-on behaviors.  I currently use SSH to access them but I would like a more convenient solution.

Essentially, can we make /mnt/data/supervisor/addons/data visible as a samba share?

Thanks.

**Comment by j9brown** [comment]
This would still be useful to me.

**Comment by ReenigneArcher** [comment]
I would like this feature as well.

**Comment by Krocko** [comment]
Yes, me too.
