### ISSUE TITLE
OpenZwave add-on crashes when trying to use new device type xml

### ISSUE THREAD

**Issue by mike240se** [home-assistant/hassio-addons#1421]
I have a lock (kwikset 888) that requires a refresh of the lock when the alarm event comes in for manual lock, same as the 914c.xml.  I created a working 888.xml that works perfectly in ozw-admin running in local server mode on a linux machine.  it fixes the lock issue and works perfectly.

when i try to add this 888.xml to the kwikset folder and then attach it to the lock device type it updates the lock name to Smartcode 888 when the add-on is restarted.  It does not add the refresh to the ozwcache so refreshnode is required.  However, when I refresh node it crashes every time and will continue to crash the add-on every startup until i remove the device from manufcatuer_specific.xml.

It also crashes when I excldue and re-include and again continues to crash every startup until the device xml is no longer assosciated with the device id.

since it works perfectly with ozw-admin i assume the issue must be the add-on.

Crash Log: https://hastebin.com/carimihiyu.md

**Comment by mike240se** [comment]
just want to add i switched to the qt-openzwave all in one docker and the xml is working perfect so the issue seems to definitely be with the add-on.

**Comment by mosjonathan** [comment]
Probably the same as #1403 i switched to all in one also.
