### ISSUE TITLE
IKEA TRADFRI bulb E27 WS opal 1000lm (V2.0.022) color temperature

### ISSUE THREAD

**Issue by EarlOfBurton** [home-assistant/hassio-addons#1423]
Hello,

IKEA TRADFRI bulb E27 WS opal 1000lm (V2.0.022) color temperature value does not show up as parameter (although it can be set manually at the light).
So it is not possible to save values with scenes.
See Screenshots. Known issue for rest-api (not home assistant):
dresden-elektronik/deconz-rest-plugin#2526
dresden-elektronik/deconz-rest-plugin#1861
(those issues are not referred to hassio addon but the rest-api).
This issue is still open because the hassio-addon is not updated.

Could somebody update the hassio-addon so that we also do have that fix, that is in deczon rest-api 2.05.76/.77? Or tell me how to do that manually without the "normal" update system of home assistant?
I could not find any more recent updates via home assistant:
Hassio addon deCONZ Current version: 5.3.5
deconz Version: 2.05.75 / 8.3.2020
Firmware of Raspbee: 26350500
![Bildschirmfoto 2020-06-21 um 13 40 03](https://user-images.githubusercontent.com/16398996/85224022-a5381000-b3c7-11ea-8f0a-996ab34bddf8.png)
![Bildschirmfoto 2020-06-21 um 13 40 48](https://user-images.githubusercontent.com/16398996/85224024-a6693d00-b3c7-11ea-91eb-a2548a9af505.png)
![Bildschirmfoto 2020-06-21 um 13 41 48](https://user-images.githubusercontent.com/16398996/85224025-a701d380-b3c7-11ea-9b65-97884f9b819b.png)
![Bildschirmfoto 2020-06-21 um 13 50 58](https://user-images.githubusercontent.com/16398996/85224026-a8330080-b3c7-11ea-887e-ff41325c5a6b.png)

**Comment by DrKatozzo** [comment]
Hello,
I don't know if the problem I'm having is related to this.
I noticed that it is no longer possible to  set the temperature of the ikea bulbs using the sliders in the lovelace interface. As soon as the switch is moved slightly, the bulb go to the "yellow" color. (color temp 65535)
Using the slider directly in the addon deconz screen, everything works correctly.

**Comment by Mimiix** [comment]
@DrKatozzo RTelated to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3018 and should be fixed with next update.

@EarlOfBurton Is it solved?

**Comment by EarlOfBurton** [comment]
> @EarlOfBurton Is it solved?

Yes, thank you very much.
