### ISSUE TITLE
DuckDNS - incorrect URL for IP lookup in Documentation

### ISSUE THREAD

**Issue by TheGroundZero** [home-assistant/hassio-addons#1426]
The Documentation of DuckDNS mentions an incorrect URL for IPv4 lookup.

> **Option: `ipv4` (optional)**
> 
> By default, Duck DNS will auto detect your IPv4 address and use that. This option allows you to override the auto-detection and specify an IPv4 address manually.
> 
> If you specify a URL here, contents of the resource it points to will be fetched and used as the address. This enables getting the address using a service like _https://api4.ipify.org/_ or https://ipv4.wtfismyip.com/text
> 
> **Option: `ipv6` (optional)**
> 
> By default, Duck DNS will auto detect your IPv6 address and use that. This option allows you to override the auto-detection and specify an IPv6 address manually.
> 
> If you specify a URL here, contents of the resource it points to will be fetched and used as the address. This enables getting the address using a service like https://api6.ipify.org/ or https://ipv6.wtfismyip.com/text

Please note that the correct URLs should be:

IPv4:

- https://api.ipify.org/ (Notice `api` instead of `api4`)
- https://ipv4.wtfismyip.com/text

IPv6
- https://api6.ipify.org/
- https://ipv6.wtfismyip.com/

Looking at the [source code of wtfismyip](https://github.com/wtfismyip/wtfismyip/blob/master/wtf/wtf.go), I would even suggest using these (`text` subdomain):
- https://ipv4.text.wtfismyip.com
- https://ipv6.text.wtfismyip.com

In the past, I've also had good results with https://ifconfig.me/ip for IPv4 (using cURL you don't even need the `/ip`)

**Comment by thedoginthewok** [comment]
You're right! 

But are the ipv4 and ipv6 options working for you? 

It does not work for me.

Config:
```yaml
lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
token: token
domains:
  - mydomainname.duckdns.org
aliases: []
seconds: 300
ipv4: 'https://ipv4.text.wtfismyip.com/'
ipv6: 'https://ipv6.text.wtfismyip.com/'
```

Log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
# INFO: Using main config file /data/workdir/config
+ Account already registered!
[23:51:14] INFO: KO
# INFO: Using main config file /data/workdir/config
Processing thedoginthewok.duckdns.org
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Sep 12 20:50:25 2020 GMT Certificate will not expire
(Longer than 30 days). Skipping renew!
```


"[23:51:14] INFO: KO" is the response of the curl call, that updates the ip addresses and this is only returned, if something wrong is in the ipv4 or ipv6 url parameters.

**Comment by TheGroundZero** [comment]
I'm afraid I can't help you with that one, since I haven't used the DuckDNS addon yet. I just noticed the error in the Documentation.

**Comment by thedoginthewok** [comment]
The issue is still current and valid.
