### ISSUE TITLE
LetsEncrypt - Cannot obtain certificate via dns-ovh

### ISSUE THREAD

**Issue by TheGroundZero** [home-assistant/hassio-addons#1427]
Hi all,

I'm trying to use the LetsEncrypt addon with the dns challenge to provide SSL certs for my Home Assistant.
I want to use DNS-OVH as my DNS provider.

This is a censored version of the config I want to use:

```yaml
email: email@example.org
domains:
  - sub.parent.tld
certfile: fullchain.pem
keyfile: privkey.pem
challenge: dns
dns:
  - dnsprovider: dns-ovh
  - dns_ovh_endpoint: ovh-eu
  - dns_ovh_application_key: application_key_123
  - dns_ovh_application_secret: application_secret_123
  - dns_ovh_consumer_key: consumer_key_123
```

The moment I add the dns-options, I'm getting errors.
![image](https://user-images.githubusercontent.com/2406013/85400306-7ef5aa00-b558-11ea-9d73-2b22ac58c741.png)

Sticking with the default `dns: {}` I'm not getting errors, but I suppose the DNS challenge would then fail since it cannot connect to my DNS provider (OVH).

---

Also, the documentation on getting the OVH key (especially the consumer key) isn't very clear and the permissions are a bit too wide.

To get the key:
- register a new app via https://eu.api.ovh.com/createApp/  
   This will give you `application_key` and `application_secret`
- go to the API console at https://eu.api.ovh.com/console/#/auth/credential#POST
  - Add the necessary access rules  
     I limited my permissions to GET/POST/PUT/DELETE on `/domain/zone/parent.tld` instead of `/domain/zone/*`.
  - Enter a redirection URL, e.g. your own domain name, e.g. `https://example.org`
  - Click execute
  - Copy the consumerKey from the output
- Browse to the validationURL and authenticate to active your key

**Comment by TheGroundZero** [comment]
I captured these error logs in Supervisor > System > System Log

```
20-06-23 21:37:37 INFO (MainThread) [supervisor.addons] Create Home Assistant add-on data folder /data/addons/data/core_letsencrypt
20-06-23 21:37:37 INFO (SyncWorker_7) [supervisor.docker.interface] Pull image homeassistant/amd64-addon-letsencrypt tag 4.10.0.
20-06-23 21:37:54 INFO (MainThread) [supervisor.addons] Add-on 'core_letsencrypt' successfully installed
20-06-23 21:38:21 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/security.py", line 157, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 61, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/addons.py", line 294, in options
    body = await api_validate(addon_schema, request, origin=[ATTR_OPTIONS])
  File "/usr/src/supervisor/supervisor/api/utils.py", line 121, in api_validate
    data_validated = schema(data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 386, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 205, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 250, in _exec
    return func(path, v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 205, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 285, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/src/supervisor/supervisor/addons/validate.py", line 355, in validate
    options[key] = _nested_validate_dict(coresys, typ, value, key)
  File "/usr/src/supervisor/supervisor/addons/validate.py", line 437, in _nested_validate_dict
    for c_key, c_value in data_dict.items():
AttributeError: 'list' object has no attribute 'items'
```

**Comment by marauder37** [comment]
I had the same error, seems to be related to YAML parsing. I removed the dashes from the options in the `dns` section.

This config worked for me:

````
email: homeassistant@example.com
domains:
  - '*.example.com'
certfile: fullchain.pem
keyfile: privkey.pem
challenge: dns
dns:
  provider: dns-route53
  aws_access_key_id: AKIADEADBEEF
  aws_secret_access_key: SRweQHrYCAFEBABE
````

**Comment by TheGroundZero** [comment]
Based on #1491, I fixed my configuration

Using the more restrictive permissions, I didn't manage to get LE to work (yet).

> GET/POST/PUT/DELETE on `/domain/zone/parent.tld` instead of `/domain/zone/*`

Retry with more open permissions:

1. Create a new app at https://eu.api.ovh.com/createApp/  
    Login with OVH account, pick a name and add a description
2. Request a new credential for this application at https://api.ovh.com/console/#/auth/credential#POST
    - GET /domain/zone/*
    - POST /domain/zone/*
    - PUT /domain/zone/*
    - DELETE /domain/zone/*
    - redirection: enter a URL
3. Note the consumerKey
4. Visit the validationUrl in the response and authenticate with OVH account
5. Validate existence of application
    - Get applicationId at https://api.ovh.com/console/#/me/api/application#GET
    - Get application properties at https://api.ovh.com/console/#/me/api/application/%7BapplicationId%7D#GET
6. Install Let's Encrypt add-on in Home Assistant
7. Edit configuration to match docs for OVH DNS provider
    ```yaml
    email: email@example.org
    domains:
      - sub.domain.tld
    certfile: fullchain.pem
    keyfile: privkey.pem
    challenge: dns
    dns:
      provider: dns-ovh
      ovh_endpoint: ovh-eu
      ovh_application_key: xxxxxxxxxxxxxxxx
      ovh_application_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      ovh_consumer_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    ```
8. Start add-on and follow Log
    ```
    [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
    [s6-init] ensuring user provided files have correct perms...exited 0.
    [fix-attrs.d] applying ownership & permissions fixes...
    [fix-attrs.d] done.
    [cont-init.d] executing container initialization scripts...
    [cont-init.d] file-structure.sh: executing... 
    [cont-init.d] file-structure.sh: exited 0.
    [cont-init.d] done.
    [services.d] starting services
    [services.d] done.
    [21:25:49] INFO: Selected DNS Provider: dns-ovh
    [21:25:49] INFO: Use propagation seconds: 60
    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    Plugins selected: Authenticator dns-ovh, Installer None
    Obtaining a new certificate
    Performing the following challenges:
    dns-01 challenge for sub.domain.tld
    Cleaning up challenges
    Error determining zone identifier for sub.domain.tld: 403 Client Error: Forbidden for url: https://eu.api.ovh.com/1.0/domain/zone/. (Are your Application Key and Consumer Key values correct?)
    [cont-finish.d] executing container finish scripts...
    [cont-finish.d] done.
    [s6-finish] waiting for services.
    [s6-finish] sending all processes the TERM signal.
    [s6-finish] sending all processes the KILL signal and exiting.
    ```

:(

**Comment by TheGroundZero** [comment]
So I dug a bit further...

To activate the correct credential, you will need to use cURL as you have to set a HTTP header.  
Didn't get it to work on Windows, so I used a linux box.

```bash
$ curl -XPOST -H"X-Ovh-Application: IzL*************" -H "Content-type: application/json" https://eu.api.ovh.com/1.0/auth/credential  -d '{
>     "accessRules": [
>         {
>             "method": "GET",
>             "path": "/domain/zone/domain.tld"
>         },
>         {
>             "method": "POST",
>             "path": "/domain/zone/domain.tld"
>         },
>         {
>             "method": "PUT",
>             "path": "/domain/zone/domain.tld"
>         },
>         {
>             "method": "DELETE",
>             "path": "/domain/zone/domain.tld"
>         }
>     ],
>     "redirection":"https://www.domain.tld"
> }'
```

If you now visit the validationUrl and authenticate, you should have properly activated the credential.  
You can verify this at https://eu.api.ovh.com/console/#/me/api/credential/{credentialId}#GET

- First get the applicationId at https://eu.api.ovh.com/console/#/me/api/application#GET
- Then get the credentialId at https://eu.api.ovh.com/console/#/me/api/credential#GET
- Finally verify the credentials at https://eu.api.ovh.com/console/#/me/api/credential/{credentialId}#GET

![image](https://user-images.githubusercontent.com/2406013/88865350-2e2c3d80-d1f7-11ea-9f98-f7a69eb4aa33.png)
![image](https://user-images.githubusercontent.com/2406013/88865401-4ef49300-d1f7-11ea-9a72-1aa661a823f8.png)
![image](https://user-images.githubusercontent.com/2406013/88865428-62076300-d1f7-11ea-8538-85211071f920.png)
![image](https://user-images.githubusercontent.com/2406013/88865514-a266e100-d1f7-11ea-9ce5-5659ddd2e1f1.png)

**Comment by ludeeus** [comment]
So this is now working for you @TheGroundZero ?

**Comment by TheGroundZero** [comment]
> So this is now working for you @TheGroundZero ?

While the token is definitely correct and valid, I still cannot get LetsEncrypt certificates with the dns-ovh provider in this plugin.

**Comment by ludeeus** [comment]
Since you get a 403 error the issue is with authentication (permissions to update)
<https://certbot-dns-ovh.readthedocs.io/en/stable/#credentials>
The docs say you need `/domain/zone/*` for all 4, try that.

**Comment by TheGroundZero** [comment]
I deleted the previous credential linked to my application and requested a new one using `/domain/zone/*` instead of `/domain/zone/domain.tld`. This resulted in a new `ovh_consumer_key` so I updated that one as well.

Note that in the meantime I had already created a `subdomain.domain.tld` A entry in my OVH DNS config.  
No idea if that is in any way related.

```log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] file-structure.sh: executing... 
[cont-init.d] file-structure.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:22:31] INFO: Selected DNS Provider: dns-ovh
[14:22:31] INFO: Use propagation seconds: 60
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-ovh, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for subdomain.domain.tld
Waiting 30 seconds for DNS changes to propagate
Waiting for verification...
Cleaning up challenges
Non-standard path(s), might not work with crontab installed by your operating system package manager
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /data/letsencrypt/live/subdomain.domain.tld/fullchain.pem
   Your key file has been saved at:
   /data/letsencrypt/live/subdomain.domain.tld/privkey.pem
   Your cert will expire on 2020-11-02. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - If you like Certbot, please consider supporting our work by:
   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

Success 👍 

Using * might be mandatory, so it seems.  
I had however read some Reddit posts of people using the more limited credential set, for obvious security reasons.

The documentation however does need to be updated to fit with the steps that need to be taken to obtain the correct API credentials.
