### ISSUE TITLE
Stopped updating deCONZ?

### ISSUE THREAD

**Issue by michfield** [home-assistant/hassio-addons#1431]
I've noticed that we are 3 version behind deCONZ. What is reasoning for that? "issues for several users"?

There a lot more than "several" users that want the LATEST version of deCONZ.
Can we have some kind of explanation?

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

There is already an issue open for this as well, see: #1428

Thanks! 👍
