### ISSUE TITLE
Deconz add-on: specify external URL instead of internal docker

### ISSUE THREAD

**Issue by etique57** [home-assistant/hassio-addons#1433]
Hello,

Would it be possible for the Deconz addon to be able to specify an external URL for Deconz instead of the internal docker URL?

My use-case is the following. I have a dedicated Deconz installation (on a TinkerBoard) because I don't want the lights to stop working whenever I mess with Home-Assistant (WAF...).

I can of course access Deconz directly from my internal network. But I would like to access it through the Home Assistant framework (using the Ingress feature).

Is this something that could be done?

Thanks a lot!

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by etique57** [comment]
sure! thanks a lot!
