### ISSUE TITLE
LetsEncrypt(rfc): Add a generic manual-auth-hook provider (for DNSexit) 

### ISSUE THREAD

**Issue by Rick-Jongbloed** [home-assistant/hassio-addons#1434]
I've just migrated to Home Assistant and I would like to migrate my DNS exit wildcard certificate request Kubernetes job to Home Assistant, using the Lets Encrypt add-on.

_DNS exit is a dynamic DNS provider where you can dynamically update the IP of your domain for free. Unlimited subdomains can be created and set as an alias for your own registered domain. See www.dnsexit.com for more information._

At the moment the required DNS hook is not supported. However due to the work of @jpconver it is possible to support this provider via the manual-auth-hook at his repo: https://github.com/jpconver/dnsexit_dnshook.

See for example my current one-liner to renew a wildcard certificate. The script directory is mounted as /opt/dnshook/:
```
command: ["sh"]
          args: ["-c", "cd /opt/dnshook && apk add --no-cache curl grep bind-tools bash && certbot  renew -vvv -n --manual-public-ip-logging-ok --agree-tos -m myemail@mail.com --manual --preferred-challenges=dns --manual-auth-hook=/opt/dnshook/authenticator.sh --manual-cleanup-hook=/opt/dnshook/cleanup.sh"]
```

I do realize it might be too much work to add and maintain these scripts. Therefore I would like to propose that we create a generic manual-auth-hook provider where:
- A custom DNShook directory can be mapped from an accessible place to the LetsEncrypt add-on container.
- The argument manual-auth-hook can be configured.
- The argument manual-cleanup-hook can be configured.
- A username can be configured (exposed to the authenticator hook and the cleanup hook) (ie manual-auth-hook_username)
- A password can be configured (exposed to the authenticator hook and the cleanup hook) (ie manual-auth-hook_password)
- The option --manual is set.
- No other conflicting options are configured.

Extra variables that might be required could be set in a separate config file, and anyone can script their own DNS hook solution.

Would opening an issue on Github be the correct way to request such a change? 
And how can I help?

**Comment by Rick-Jongbloed** [comment]
I've created my own addon, based on the DuckDNS addon. Will upload it to my repository soon.

**Comment by mmiller7** [comment]
What is the status of this?

I'm using a privately hosted acme-dns DNS server for DNS-01 challenge of systems on my LAN to get LetsEncrypt certificates, I would like to do the same with HomeAssistant but it requires having a hook to auto-renew the DNS challenge.

Here's the server I'm running: https://github.com/joohoi/acme-dns

Here's the hook I've used on other systems: https://github.com/joohoi/acme-dns-certbot-joohoi
