### ISSUE TITLE
deconz devices becoming unavailable

### ISSUE THREAD

**Issue by aguilaair** [home-assistant/hassio-addons#1438]
## The problem

My ZigBee devices connected to deConz are becoming constantly unavailable without any apparent reason. I have multiple brands including Phillips and Aqara. They're all bettery-run so none are acting as repeaters.

## Environment

docker_version | 19.03.8
host_os | HassOS 4.10
os_version | 4.19.126-v8
python_version | 3.7.7
supervisor | 228
version | 0.112.0
frontend |  20200603.3 - latest
deconz | 5.3.6

## Logs
Nothing shows up on the logs

## Images
![imagen](https://user-images.githubusercontent.com/29983481/86396174-ba534f80-bca1-11ea-8850-22791b666306.png)
![imagen](https://user-images.githubusercontent.com/29983481/86396215-cccd8900-bca1-11ea-8e84-ece15a44a9cd.png)
![imagen](https://user-images.githubusercontent.com/29983481/86396244-dd7dff00-bca1-11ea-82b5-9e3c5b61add8.png)

**Comment by jappish84** [comment]
I've been having the same issues on and off since I upgraded to 5.3.4 an above. I'm now on 5.3.6 and keep getting this in the logs

```
10:37:11:408 COM: /dev/ttyACM0 / serialno: redacted
10:37:11:408 COM: --dev: /dev/ttyACM0 (ConBee II)
10:37:11:924 device state timeout ignored in state 2
10:37:12:875 device state timeout ignored in state 2
10:37:13:868 device state timeout ignored in state 2
10:37:14:368 try to reconnect to network try=6
10:37:15:869 device state timeout ignored in state 2
10:37:16:869 device state timeout ignored in state 2
10:37:17:869 device state timeout (handled)
10:37:17:931 device disconnected reason: 1, index: 0
10:37:18:368 wait reconnect 15 seconds
10:37:18:368 void zmMaster::handleStateIdle(zmMaster::MasterEvent) not connected goto OFF state
10:37:18:368 device state timeout ignored in state 1
10:37:19:368 failed to reconnect to network try=7
10:37:19:368 wait reconnect 14 seconds
```

**Comment by frenck** [comment]
The initial issue by @aguilaair should be reported for the integration, not the add-on. Which was already done I see, so that makes this issue an duplicate.


@jappish84 That is the log from deCONZ itself. Please report that with dresden. 👍
