### ISSUE TITLE
Osram Smart+ Swicht Mini with conbee II

### ISSUE THREAD

**Issue by gotsila** [home-assistant/hassio-addons#1439]
Hello, i own a Conbee II with six Xiaomi Sensors and Osram Motion Sensor. Now i bought the Osram Smart+ Switch Mini ( 3 Buttons) they are super cheap. 
But i can't recognize them?
Any one who use this switch?

thanks for nice codding, zigbee rock it

have a nice day

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
