### ISSUE TITLE
Samba: Possible to use it as NAS with freely configurable User and Shares?

### ISSUE THREAD

**Issue by Forcefx** [home-assistant/hassio-addons#1440]
Hi,

is there something to be said against using the samba Plugin and Hass.io Server as an NAS?

Add some more shares with specific user and permissions?

The samba services works great for me but I want to store our data separately to the home-assistent files currently accessible via the samba addon.

best regards

**Comment by frenck** [comment]
Hi there,

That is not the goal of the add-on. It provide access to the configuration files of the Home Assistant eco system.

If you are in need for such a thing, you probably better of using your NAS itself for that.
