### ISSUE TITLE
deconz regular dropouts

### ISSUE THREAD

**Issue by digidude** [home-assistant/hassio-addons#1446]
After months of great connectivity with deconz, I'm seeing regular dropouts.

Home Assistant 0.112.3
HassOS 4.11 
os_version 4.19.127-v7l
Supervisor v 228

dresden elektronik
RaspBee
Version 2.05.78 5/22/2020
Firmware 264A0700
Phoscon-GW 172.30.33.0 

Devices become unavailable in HA
Later they reappear as "restored"

![](https://i.imgur.com/44T4R0O.png)
https://imgur.com/a/7uatJge

### **DROPOUTS**
Notice the "unavailable" through every device on regular (but not exact) intervals through the night.

![](https://i.imgur.com/IOuB3Ty.png)

### **DETAIL**

![](https://i.imgur.com/XGNqET2.png)

----
### **LOGS**
Not sure what is connecting on port 8099. may be not-relevant

**Supervisor logs show:**
20-07-07 20:45:08 ERROR (MainThread) [supervisor.api.ingress] Ingress error: None
20-07-07 20:46:07 ERROR (MainThread) [supervisor.api.ingress] Ingress error: None
20-07-07 20:52:16 ERROR (SyncWorker_3) [asyncio] Unclosed connection
client_connection: Connection<ConnectionKey(host='172.30.33.0', port=8099, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None)>

**And several of these**
20-07-08 12:02:06 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session 5e4aa3ace6802bdc39e766b882c1d072833c1b3c0274db41a9ccd5830930f5960b75674fbb61420d717d7c7fa2523da020c84c3d3fe7a1e5992bd8fdcf3df12e

**Comment by frenck** [comment]
This is either an issue with the deconz integration in Home Assistant or deconz itself. The add-on wraps an existing application. From an add-on perspective, there is not much we can do about this.

Please report your issue with the Home Assistant core. Thanks 👍
