### ISSUE TITLE
Smart Implant + DHT22 on Openzwave Beta 

### ISSUE THREAD

**Issue by Veuchez** [home-assistant/hassio-addons#1447]
I have a Fibaro Smart Implant with DHT22 sensor connected on OpenZwave Beta.
I set the parameters for the temperature and humidity report so that they update every 60s and every 0.1 ° C.
These values never update.

Home Assistant 0.112.3
System HassOS 4.11
Supervisor 228
OpenZWave beta 0.4.4
Dongle Z-wave: Aeotec Z-stick 5

**Comment by frenck** [comment]
Hi there @Veuchez,

That is not something the add-on can fix. Maybe the integration or else, the openzwave project.

Please raise an issue on the Home Assistant Core project. Thanks! 👍
