### ISSUE TITLE
deCONZ ct control broken with latest update

### ISSUE THREAD

**Issue by djryan012** [home-assistant/hassio-addons#1452]
[Deconz reporting CT parameter as invalid #3018](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3018)

Not able to go to previous version using addon.

**Comment by Mimiix** [comment]
Should be fixed in next version:) Comming up for beta this 15th.

**Comment by jon6fingrs** [comment]
Hi, how do I install the beta version of the addon? I haven't been able to find any info anywhere. Thanks!

**Comment by Mimiix** [comment]
@jon6fingrs Addon needs to be compiled. I have no clue who does that or manages it.

Beta should be out late tonight for all native installations.
