### ISSUE TITLE
Osram Mini Switch 3 buttons won't work, but a new REST-API libde_rest_plugin.so will be come

### ISSUE THREAD

**Issue by gotsila** [home-assistant/hassio-addons#1456]
Hello, the Osram Mini Switch 3 buttons don't work at this time. But here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/2917

is the the solution. it will be a new REST-API libde_rest_plugin.so 

original-text from there:
Smanar commented 5 hours ago • 
This code have just been merged, if you can wait for some day you will have it on official/beta version.

Now my Question: will it be find his way to the HA deCONZ?? 

Hope i can hope
THX

**Comment by ludeeus** [comment]
It will be there when there is a new release for deconz, and the addon is updated to use that version.
currently, that addition to deconz is not released.
