### ISSUE TITLE
Consider temporal tables in MariaDB

### ISSUE THREAD

**Issue by domoritz** [home-assistant/hassio-addons#1459]
MariaDB now has support for tables with timestamps: https://mariadb.com/kb/en/temporal-data-tables/. It could be faster to use temporal tables than adding timestamps manually.

**Comment by frenck** [comment]
That is not an add-on concern, but a concern of the recorder integration of the Home Assistant core.

Nevertheless, thank you for your suggestion 👍

**Comment by domoritz** [comment]
Ahh, thanks. I created https://community.home-assistant.io/t/use-mariadb-temporal-tables-in-recorder-integration/211502 to note down the idea.
