### ISSUE TITLE
IKEA Blind has stopped working

### ISSUE THREAD

**Issue by Puntoboy** [home-assistant/hassio-addons#1460]
In the last couple of days, by IKEA blind has stopped responding. 

I have factory reset the blind, re-paired it to Deconz, and recharged the battery. Nothing has worked. I then tried updating Deconz to the latest but that hasn't helped either. 

I can see the device in VNC and on the web app. but if I try to adjust it from the web app or from home assistant nothing happens. On Home Assistant I get a "Failed to call service cover/close_cover. /lights/2 resource, /lights/2, not available" and on Node-Red I get an API error. 

I'm running my system in Docker. It has been working fine for a while. 

If I manually call the "cover" service in HA, I see this error in the logs:

![image](https://user-images.githubusercontent.com/11718878/87407485-22ffcd80-c5ba-11ea-8da9-b5d9f6a82dc9.png)

I also see this in the logs constantly.

![image](https://user-images.githubusercontent.com/11718878/87407566-3f036f00-c5ba-11ea-95b9-e77e9b1fafca.png)

How can I troubleshoot please?

**Comment by Puntoboy** [comment]
Also, in VNC, the device is sitting with a green flashing indicator. All over devices flash blue.

![image](https://user-images.githubusercontent.com/11718878/87407792-8ab61880-c5ba-11ea-9e52-6a9d19d24ccf.png)

**Comment by frenck** [comment]
Hi there,

Thanks for opening up an issue @Puntoboy!

However, this is the issue tracker for the add-on, the logs you've provided are from the Home Assistant Core. Please raise an issue here:

<https://github.com/home-assistant/core/issues>

Please search the current issues first, as it might be a known one already.

Thanks 👍
