### ISSUE TITLE
Deconz addon log setting --dbg-http=X.

### ISSUE THREAD

**Issue by vegetate7** [home-assistant/hassio-addons#1465]
Please make the deconz option '--dbg-http=X' can be set with addon configuration.
Usually HTTP (Phoscon Webapp) logs are completely useless, but flooding 'addon log' output.

**Comment by MattBN001** [comment]
Yes, that would be great!
My logs are growing too fast...

**Comment by frenck** [comment]
Logs do not grow, as it is managed by syslog (at least in terms of diskspace, it really doesn't matter, as it is automatically managed).

As for those logs you refer to, those are access logs, which are helpful in case of debugging (which the logs are for). Those are not provided by deconz, but Nginx.

Could you please clarify the issue at hand?

**Comment by vegetate7** [comment]
> Those are not provided by deconz, but Nginx

Yep. I see now. You are right, deCONZ binary started without --dbg-http=1 option. So this is Nginx logs.
Then, ok, would be nice to have an option to disable Nginx access logs. May be logs do not grow, but definitely flooding the "Logs" tab.

**Comment by frenck** [comment]
Yes, but I don't get what the problem is with the logs?

**Comment by vegetate7** [comment]
problem is when the Phoscon Webapp  connected, http logs flooding the "Logs" tab quickly. Making hard to read other deconz output regarding devices, network, etc..
