### ISSUE TITLE
Unable to Install MQTT Broker on HA Supervised

### ISSUE THREAD

**Issue by two5kid** [home-assistant/hassio-addons#1467]
I was trying to install the MQTT Broker add on through Add-Ons. It's the v5.1, however, upon clicking install, all I got was
'Failed to Install add on, unknown error, see logs'. The interesting part is that there is no 'Log' next to the Documentation tab on the header, which was usually there for the other things I installed (Grafana, Node-Red) and the error is usually related to SSL 'true'. So I went to the HA logs to have a look, and again, no issues detected. I'm attaching the screenshot of the error message and the lack of 'Logs' for clicking. Thanks
![Screenshot 2020-07-16 at 12 59 47 PM](https://user-images.githubusercontent.com/68181567/87633975-fd67f500-c76e-11ea-9924-9af466d6ce08.png)

**Comment by frenck** [comment]
Please check the supervisor log, after doing an installation attempt. Supervisor Panel -> System Tab -> log: Supervisor.

**Comment by two5kid** [comment]
Sorry for the delayed reply, I did what you asked and it sent me on a rabbit hole, I will try to explain what happened, I have exactly no idea what I did, just following what was suggested.

1) The error did actually showed up on the System Logs, not the HA logs. The error was that the installer was trying to get to 127.0.0.1 but somehow, what it found was 127.0.0.53.
2) Seems like be resolv.conf was showing this 127.0.0.53, so had to went through hoops to edit the resolv.conf file to show an 8.8.8.8 nameserver. I'm also not sure why that was the suggestion.
3) Then I was able to install the MQTT broker, but it hit a snag again, this time there was actually a 'Log' panel next to the Documentation panel. Now, it seems that something is taking over port 1883.
4) I did a netstats | grep command and found it was Mosquitto using that port. Not sure which Mosquitto was using it though, maybe the one I just installed? So I had to 'kill' that port. Freeing up the port 1883.
5) Which finally led to my success in installing the MQTT Broker.

P.S. I hope what I did, editing the resolv.conf file and killing the 1883 port did not break other parts of the system.

**Comment by two5kid** [comment]
Today I checked again my resolv.conf file, lo and behold, it is back to 127.0.0.53 again.

**Comment by frenck** [comment]
This is a host network configuration issue on a Home Assistant Supervised installation type and not a problem with the add-on or the Home Assistant ecosystem.

There is not much we can do to fix this. Please consult the documentation or support resources of the operating system you are using.
