### ISSUE TITLE
openzwave "open web ui" doesn't work on Mac/iOS

### ISSUE THREAD

**Issue by dsegantx** [home-assistant/hassio-addons#1472]
Running openzwave 0.5.0.
I’m running 112.4 HassOS 4.11 Supervisor 228 on Raspberry PI - all current.

Unable to “open web ui”. Returns the screen with a black background/grey swoosh at the bottom. Says “loading” at the top. 
Safari - MacOS - problem as described
             iOS - problem as described
Chrome - MacOS - works (interesting)
               - iOS - problem as described
Edge - Windows - works

Note this in supervisor log when it fails.
20-07-17 19:31:14 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None
20-07-17 19:31:14 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None

**Comment by frenck** [comment]
I'm not able to reproduce this on a plain Safari on macOS.

![image](https://user-images.githubusercontent.com/195327/88179615-7b734280-cc2c-11ea-94bb-da9aaec5fd97.png)

Running Safari Version 13.1.1 (15609.2.9.1.2)
Running macOS Catalina: 10.15.5

**Comment by dsegantx** [comment]
Odd.  Must be something specific in my environment.  It is across multiple Mac devices not just one.  I currently can’t diagnose further as I backed off of ozw due to crashes on .51 and wanting play with Inovelli scenes which might now be supported in ozw (maybe I’ll jump back into ozw again).  Maybe someone else can pursue this and provide repeatability confirmations.

Tnx

**Comment by dsegantx** [comment]
Franck-
By luck I backed off of 113 and am running 112.4.  I had OZW running in that restore so I upgraded to 0.52 OZW.  It boots fine and runs stable thus far.

My point here is I've tested this issue again and it's still happening for me.
Version 13.1.2 (15609.3.5.1.3)
macOS Catalina: 10.15.6

I get the ingress error (twice).

Any ideas on what other debugging/research I can provide?  I've seen others report this on the HA forum.  
I can run the tool via VNC from my Mac but not HA.  And I have two Mac's and an iPad and all have the problem.  

To make it more intriguing I run Parallels and WIndows10 on one of the Mac's.  Within that OS, using MS Edge, I have zero problems and am able to pull up the embedded/vnc and mange my devices.  And Chrome allows it to work

So it really seems related to Mac/Safari..

Same user id, that has admin privs..

**Comment by charlietomo** [comment]
I am having the same issue.

- macOS Catalina 10.15.6 with Safari 13.1.2
- Home Assistant 0.113.3 with OpenZWave 0.5.2
- running on Intel NUC

I cannot open the webUI in Safari; gets stuck on "loading" (see screenshot) but I don't see anything in the logs.
Using Chrome on the same machine works fine, same credentials etc.

In the short term (recognising that this is beta etc) a note in the documentation would be helpful e.g. "Some users have issues accessing the OpenZWave web interface using Safari on macOS. Try using Chrome or VNC connection". I spent a lot of time thinking it was my setup, when I should have used a different browser!

<img width="1792" alt="openzwave-loading" src="https://user-images.githubusercontent.com/19795112/89119467-d6e1e200-d502-11ea-9a4c-66b1ff17be16.png">

**Comment by frenck** [comment]
@charlietomo Documentation is not for recording bugs, bugs are tracked in an issue like this one.

**Comment by sibbl** [comment]
I also encountered this issue today in MS Edge while I had the dev tools open with "disable cache" enabled.

Exactly one of the JavaScript imports always failed with a 502 server error without any body. It were always different files and unfortunately I couldn't find any pattern. It couldn't load all JS files in 20 tries.

Disabling the "disable cache" option and/or closing the dev tools helped the first time I reloaded the page.

Perhaps this is related to the issue, maybe not...

**Comment by natwilson** [comment]
I have the same issue on my Mac, but I noted that it works if accessed via the Nabu Casa cloud.  If I access it directly using: homeassistant.local it never loads but throws console errors:

[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (webutil.js, line 0) http://homeassistant.local:8123/api/hassio_ingress/O8g4i2IO<redacted>WvmHg/app/webutil.js
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (rfb.js, line 0) http://homeassistant.local:8123/api/hassio_ingress/O8g4i2IO<redacted>WvmHg/core/rfb.js

Where O8g4i2IO<redacted>WvmHg is my Nuba Casa URL.  It seems the web UI is trying to use the cloud even if I'm accessing it locally.

**Comment by dsegantx** [comment]
Upgraded to 0.5.4 and still problematic/not working.
20-09-16 15:07:15 WARNING (MainThread) [supervisor.api.ingress] No valid ingress session None

FYI


rch | armv7l
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.13
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7l
python_version | 3.8.3
supervisor | 244
timezone | America/Chicago
version | 0.114.4
virtualenv | false

**Comment by charlietomo** [comment]
I haven't made many changes to my config (not current Home Assistant yet, major Safari release) but this is now working i.e. the OpenZWave interface loads in Safari.

- macOS Catalina 10.15.7 (up from .6) with Safari 14 (up from 13.1.2)
- Home Assistant 0.114.2 (up from 0.113.3) with OpenZWave 0.5.2 (same)
- running on Intel NUC (same)

**Comment by natwilson** [comment]
Started working for me too after upgrading to version 0.5.2.

**Comment by dsegantx** [comment]
I concur - it is working and seemed to be related for me to a Supervisor upgrade a few versions back.  
I'll wait another day or two and close this if no one else speaks up....

**Comment by dsegantx** [comment]
Magically not happening anymore across my footprint so closing.
