### ISSUE TITLE
ozwadmin segfault at 38 ip... Intel Nuc Vmbox start 

### ISSUE THREAD

**Issue by TomBrandt** [home-assistant/hassio-addons#1474]
I don't know if this issue or not. but get this every time I restart the Host.
![VirtualBox_HassProduction_18_07_2020_12_44_48](https://user-images.githubusercontent.com/42679845/87861200-f1a83a00-c8f8-11ea-96f0-87fa0f2b3b2e.png)

**Comment by suppnet** [comment]
Same here, 0.114.0
Version | 232
System | HassOS 4.12

<img width="703" alt="Screenshot 2020-08-15 at 08 16 19" src="https://user-images.githubusercontent.com/32219919/90306696-ed5b4680-decf-11ea-8aa3-0cb58f185023.png">

**Comment by lrybak** [comment]
I have the same everytime I restart host

**Comment by Levivb** [comment]
Same here. Can't seem to boot HA anymore in VmBox 😬

**Comment by Levivb** [comment]
I just tried to boot some backups from August en July and even those are bricket in the same manner 😰

**Comment by Levivb** [comment]
A reïnstall of virtual box seems have fixed the issue 🤷

**Comment by soleen** [comment]
Same issue: QEMU/KVM VM  with 003:002 Silicon Labs HubZ Smart Home Controller USB device attached to VM.

**Comment by dherran** [comment]
Same issue: VirtualBox on Ubuntu 20.04 with a Conbee II

**Comment by pvizeli** [comment]
> A reïnstall of virtual box seems have fixed the issue
