### ISSUE TITLE
deconz 6.1.0 doesnt start on Raspberry Pi 4

### ISSUE THREAD

**Issue by fti7** [home-assistant/hassio-addons#1480]
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] firmware.sh: executing... 
/usr/bin/GCFFlasher_internal: line 71: /usr/bin/GCFFlasher_internal.bin: No such file or directory
[16:39:03] INFO: 
[cont-init.d] firmware.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] vnc.sh: executing... 
[cont-init.d] vnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[14:39:04] INFO: Starting udevd...
[14:39:04] INFO: Running the OSRAM LEdvance OTA updater...
[14:39:04] INFO: Running the deCONZ OTA updater...
[services.d] done.
[16:39:04] INFO: Waiting for device...
[14:39:04] INFO: Running the IKEA OTA updater...
[14:39:04] INFO: Can't fetch data from osram!

[16:39:08] INFO: Starting VNC server...
[16:39:11] INFO: Waiting for VNC to start
[16:39:11] INFO: Starting the deCONZ gateway...
./run: line 71: /usr/bin/deCONZ: No such file or directory
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

homeassistant/armhf-addon-deconz:6.0.1 

EDIT: FIXED in 6.1.0 - But still not starting - see bugreports below

**Workround:**
For 6.1.0 with the "qt.qpa.screen: QXcbConnection: Could not connect to display :0" Error:

Under Configure, remove the Host Port mapping for 5900/tcp.
After this, VNC will not be started

@pvizeli can you maybe look into this? thx

**Comment by mjhcdk** [comment]
Have a similar problem , Deconz upgraded to Version 6.0.0 on Hass.io on PI4.  and now it can't start.  Have also tried to reboot PI 

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] firmware.sh: executing... 
[16:58:17] INFO: GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyACM0     | 0x1CF1 | 0x0030  |            | ConBee II 
/dev/ttyAMA0     | 0x0000 | 0x0000  |            | RaspBee 
[cont-init.d] firmware.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] vnc.sh: executing... 
[cont-init.d] vnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[14:58:18] INFO: Running the deCONZ OTA updater...
[services.d] done.
[14:58:18] INFO: Starting udevd...
[14:58:18] INFO: Running the IKEA OTA updater...
[14:58:18] INFO: Running the OSRAM LEdvance OTA updater...
[16:58:18] INFO: Waiting for device...
[16:58:24] INFO: Starting VNC server...

[16:58:29] INFO: Waiting for VNC to start
[16:58:29] INFO: Starting the deCONZ gateway...
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by gerbenp** [comment]
Have also an problem with DeCONZ 6.1.0 on Home Assistant (Hass.io) on an Raspberry Pi 4 with 2 GB of RAM. 

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] firmware.sh: executing... 
[17:16:20] INFO: GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyACM0     | 0x1CF1 | 0x0030  |            | ConBee II 
/dev/ttyAMA0     | 0x0000 | 0x0000  |            | RaspBee 
[cont-init.d] firmware.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] vnc.sh: executing... 
[cont-init.d] vnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:16:21] INFO: Running the deCONZ OTA updater...
[15:16:21] INFO: Starting udevd...
[15:16:21] INFO: Running the OSRAM LEdvance OTA updater...
[15:16:21] INFO: Running the IKEA OTA updater...
[17:16:21] INFO: Waiting for device...
[17:16:21] INFO: Starting VNC server...
[17:16:24] INFO: Waiting for VNC to start
[17:16:25] INFO: Starting the deCONZ gateway...
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

**Comment by althaus** [comment]
For me 6.1 fails on Hassio@Synology

~~~
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] firmware.sh: executing... 
/usr/bin/GCFFlasher_internal.bin: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
[17:14:29] INFO: 
[cont-init.d] firmware.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] vnc.sh: executing... 
[cont-init.d] vnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:14:31] INFO: Running the deCONZ OTA updater...
[15:14:31] INFO: Running the OSRAM LEdvance OTA updater...
[15:14:31] INFO: Running the IKEA OTA updater...
[17:14:31] INFO: Waiting for device...
[15:14:31] INFO: Starting udevd...
[17:14:32] INFO: Starting VNC server...
[17:14:37] INFO: Waiting for VNC to start
[17:14:38] INFO: Starting the deCONZ gateway...
deCONZ: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.

[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by posavasos** [comment]
After uptading to deCONZ 6.0.1, the add-on doesn't start on my Raspberry Pi 3 Model B+ 32bit with ConBee USB gateway

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] firmware.sh: executing... 
/usr/bin/GCFFlasher_internal: line 71: /usr/bin/GCFFlasher_internal.bin: No such file or directory
[17:35:14] INFO: 
[cont-init.d] firmware.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] vnc.sh: executing... 
[cont-init.d] vnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:35:15] INFO: Running the deCONZ OTA updater...
[15:35:15] INFO: Running the OSRAM LEdvance OTA updater...
[15:35:15] INFO: Starting udevd...
[17:35:15] INFO: Waiting for device...
[15:35:15] INFO: Running the IKEA OTA updater...
[15:35:15] INFO: Can't fetch data from osram!
[17:35:20] INFO: Starting the deCONZ gateway...
./run: line 71: /usr/bin/deCONZ: No such file or directory
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by fti7** [comment]
the armhf Issues seems to be fixed with 6.1.0 (https://github.com/home-assistant/hassio-addons/commit/9e67f09875b4c8213748e24146ac6c9216ed4be3)

Unfortunately, my Supervisor UI doesnt offer me this Version yet

**Comment by knallt** [comment]
Same here for 6.0. Unfortunately I tried to uninstall, but didn't help.
Hope data is still there.

**Comment by fti7** [comment]
Upgraded to 6.1.0 (Reload @ Supervisor Menu)

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] firmware.sh: executing... 
[17:53:06] INFO: GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyACM0     | 0x1CF1 | 0x0030  |            | ConBee II 
/dev/ttyACM1     | 0x1CF1 | 0x0030  |            | ConBee II 
/dev/ttyAMA0     | 0x0000 | 0x0000  |            | RaspBee 
[cont-init.d] firmware.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] vnc.sh: executing... 
[cont-init.d] vnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:53:07] INFO: Waiting for device...
[15:53:07] INFO: Running the deCONZ OTA updater...
[15:53:07] INFO: Starting udevd...
[15:53:07] INFO: Running the OSRAM LEdvance OTA updater...
[15:53:07] INFO: Running the IKEA OTA updater...
[15:53:07] INFO: Can't fetch data from osram!

[17:53:11] INFO: Starting VNC server...
[17:53:14] INFO: Waiting for VNC to start
[17:53:15] INFO: Starting the deCONZ gateway...
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by gerbenp** [comment]
@fti7 

> the armhf Issues seems to be fixed with 6.1.0 ([9e67f09](https://github.com/home-assistant/hassio-addons/commit/9e67f09875b4c8213748e24146ac6c9216ed4be3))
> 
> Unfortunately, my Supervisor UI doesnt offer me this Version yet

You can force it in the Supervisor UI if you want. Go to the add-on store, click on the three-dots menu and select 'Reload'. That forced the 6.1.0 update for me.

**Comment by posavasos** [comment]
The 6.1.0 version solved the problem on my Raspberry Pi 3 Model B+

**Comment by QuadNL** [comment]
> Have a similar problem , Deconz upgraded to Version 6.0.0 on Hass.io on PI4. and now it can't start. Have also tried to reboot PI
> 
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] firmware.sh: executing...
> [16:58:17] INFO: GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
> Path | Vendor | Product | Serial | Type
> -----------------+--------+---------+------------+-------
> /dev/ttyACM0 | 0x1CF1 | 0x0030 | | ConBee II
> /dev/ttyAMA0 | 0x0000 | 0x0000 | | RaspBee
> [cont-init.d] firmware.sh: exited 0.
> [cont-init.d] nginx.sh: executing...
> [cont-init.d] nginx.sh: exited 0.
> [cont-init.d] vnc.sh: executing...
> [cont-init.d] vnc.sh: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [14:58:18] INFO: Running the deCONZ OTA updater...
> [services.d] done.
> [14:58:18] INFO: Starting udevd...
> [14:58:18] INFO: Running the IKEA OTA updater...
> [14:58:18] INFO: Running the OSRAM LEdvance OTA updater...
> [16:58:18] INFO: Waiting for device...
> [16:58:24] INFO: Starting VNC server...
> 
> [16:58:29] INFO: Waiting for VNC to start
> [16:58:29] INFO: Starting the deCONZ gateway...
> qt.qpa.screen: QXcbConnection: Could not connect to display :0
> Could not connect to any X display.
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.

Idem at Pi4 4GB after update from 6.0.1 to 6.1.0.

**Comment by fti7** [comment]
For 6.1.0 with the "qt.qpa.screen: QXcbConnection: Could not connect to display :0" Error:
Workround:
Under Configure, remove the Host Port mapping for 5900/tcp.
After this, VNC will not be started

**Comment by dhartmann84** [comment]
My deconz addon has not started since the update from 5.3.6 to 6.1.0.  I have a Raspberry 4 with 4GB Ram.

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] firmware.sh: executing... 
[18:22:03] INFO: GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyACM0     | 0x1CF1 | 0x0030  |            | ConBee II 
/dev/ttyUSB0     | 0x0403 | 0x6015  |            | ConBee 
/dev/ttyAMA0     | 0x0000 | 0x0000  |            | RaspBee 
[cont-init.d] firmware.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] vnc.sh: executing... 
[cont-init.d] vnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[16:22:03] INFO: Starting udevd...
[16:22:03] INFO: Running the OSRAM LEdvance OTA updater...
[services.d] done.
[16:22:03] INFO: Running the deCONZ OTA updater...
[16:22:03] INFO: Running the IKEA OTA updater...
[18:22:03] INFO: Waiting for device...
[16:22:04] INFO: Can't fetch data from osram!
[18:22:08] INFO: Starting VNC server...
[18:22:11] INFO: Waiting for VNC to start
[18:22:11] INFO: Starting the deCONZ gateway...
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal. `

**Comment by dhartmann84** [comment]
> My deconz addon has not started since the update from 5.3.6 to 6.1.0. I have a Raspberry 4 with 4GB Ram.
> 
> `[s6-init] making user provided files available at /var/run/s6/etc...exited 0. [s6-init] ensuring user provided files have correct perms...exited 0. [fix-attrs.d] applying ownership & permissions fixes... [fix-attrs.d] done. [cont-init.d] executing container initialization scripts... [cont-init.d] firmware.sh: executing... [18:22:03] INFO: GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh Path | Vendor | Product | Serial | Type -----------------+--------+---------+------------+------- /dev/ttyACM0 | 0x1CF1 | 0x0030 | | ConBee II /dev/ttyUSB0 | 0x0403 | 0x6015 | | ConBee /dev/ttyAMA0 | 0x0000 | 0x0000 | | RaspBee [cont-init.d] firmware.sh: exited 0. [cont-init.d] nginx.sh: executing... [cont-init.d] nginx.sh: exited 0. [cont-init.d] vnc.sh: executing... [cont-init.d] vnc.sh: exited 0. [cont-init.d] done. [services.d] starting services [16:22:03] INFO: Starting udevd... [16:22:03] INFO: Running the OSRAM LEdvance OTA updater... [services.d] done. [16:22:03] INFO: Running the deCONZ OTA updater... [16:22:03] INFO: Running the IKEA OTA updater... [18:22:03] INFO: Waiting for device... [16:22:04] INFO: Can't fetch data from osram! [18:22:08] INFO: Starting VNC server... [18:22:11] INFO: Waiting for VNC to start [18:22:11] INFO: Starting the deCONZ gateway... qt.qpa.screen: QXcbConnection: Could not connect to display :0 Could not connect to any X display. [cont-finish.d] executing container finish scripts... [cont-finish.d] done. [s6-finish] waiting for services. [s6-finish] sending all processes the TERM signal.`

Disable VNC fix the Problem on my RP4.

**Comment by QuadNL** [comment]
> For 6.1.0 with the "qt.qpa.screen: QXcbConnection: Could not connect to display :0" Error:
> Workround:
> Under Configure, remove the Host Port mapping for 5900/tcp.
> After this, VNC will not be started

Thanks, this workaround let's my Deconz addon start.

**Comment by vdiogo** [comment]
Same issue after upgrading to 6.1.0

**Comment by frenck** [comment]
Guys the issue is clear. Please, instead of "same issue" or "me too", please just use the 👍  emoji on the initial issue report/description. Thanks 👍

**Comment by frenck** [comment]
My current feeling says this is limited to ARMHF installations like the Raspberry Pi.
I'm currently unable to reproduce this on other platforms, so will move over to a Pi for further testing. If someone reads this with an AMD64, for example, I would love to know if it breaks for you.

**Comment by Mimiix** [comment]
If a Intel Celeron J3355 with 64 arch counts for AMD64: No issues on that (synology DS218+ VM with HA generic install and Addon).

**Comment by GitHubxtsnl** [comment]
I've also upgraded deCONZ to the 6.1.0 release.
running on a Pi4 with 4GB RAM, running Home Assistant 0.112.4
I've disabled the VNC port in the configuration of deCONZ but this does not solve my issue.
I can access the and log in to Phoscon app and I can see my bulbs and sensors here, I can see the status off lights, some are on and some are off.
The deCONZ add-on is now started but none of my bulbs or sensors are online and available within HA. 
Hope this helps in solving the issue.

here is a snippet of the log:

```
22:20:55:909 don't close database yet, keep open for 900 seconds
22:21:02:092 don't close database yet, keep open for 900 seconds
22:21:09:085 don't close database yet, keep open for 900 seconds
22:21:15:272 don't close database yet, keep open for 900 seconds
22:21:22:063 don't close database yet, keep open for 900 seconds
22:21:29:087 don't close database yet, keep open for 900 seconds
22:21:30:086 Current channel 25
22:21:30:094 Device TTL 2062 s flags: 0x7
22:21:35:195 don't close database yet, keep open for 900 seconds
22:21:41:937 don't close database yet, keep open for 900 seconds
22:21:47:088 don't close database yet, keep open for 900 seconds
22:21:55:083 don't close database yet, keep open for 900 seconds
22:22:00:882 don't close database yet, keep open for 900 seconds
22:22:06:086 don't close database yet, keep open for 900 seconds
22:22:07:658 ZCL attribute report 0xEC1BBDFFFEA684B5 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
22:22:07:674 ZCL attribute report 0xEC1BBDFFFEA684B5 for cluster: 0x0008, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
22:22:07:873 ZCL attribute report 0xEC1BBDFFFEA7F6C7 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
22:22:07:878 ZCL attribute report 0xEC1BBDFFFEA7F6C7 for cluster: 0x0008, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
22:22:12:093 don't close database yet, keep open for 900 seconds
22:22:17:998 don't close database yet, keep open for 900 seconds
22:22:22:468 ZCL attribute report 0x00158D0004C0A818 for cluster: 0x0001, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
22:22:25:125 don't close database yet, keep open for 900 seconds
22:22:30:087 Current channel 25
22:22:30:094 Device TTL 2002 s flags: 0x7
22:22:31:088 don't close database yet, keep open for 900 seconds
22:22:36:655 ZCL attribute report 0xEC1BBDFFFEA6CCEF for cluster: 0x0008, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
22:22:39:083 don't close database yet, keep open for 900 seconds
22:22:45:085 don't close database yet, keep open for 900 seconds
22:22:51:085 don't close database yet, keep open for 900 seconds
22:22:57:085 don't close database yet, keep open for 900 seconds
22:23:03:073 don't close database yet, keep open for 900 seconds
22:23:09:084 don't close database yet, keep open for 900 seconds
22:23:15:264 don't close database yet, keep open for 900 seconds
22:23:20:845 don't close database yet, keep open for 900 seconds
22:23:27:086 don't close database yet, keep open for 900 seconds
22:23:30:087 Current channel 25
22:23:30:095 Device TTL 1942 s flags: 0x7
22:23:33:087 don't close database yet, keep open for 900 seconds
22:23:38:769 ZCL attribute report 0xEC1BBDFFFEA6CCEF for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
22:23:39:266 don't close database yet, keep open for 900 seconds
22:23:45:084 don't close database yet, keep open for 900 seconds
22:23:51:089 don't close database yet, keep open for 900 seconds
22:23:57:133 dev /dev/ttyAMA0
22:23:57:134 GW firmware version: 0x26580700
22:23:57:134 GW firmware version is up to date: 0x26580700
22:23:58:087 don't close database yet, keep open for 900 seconds
22:24:05:025 don't close database yet, keep open for 900 seconds
22:24:11:255 don't close database yet, keep open for 900 seconds
22:24:17:969 don't close database yet, keep open for 900 seconds
22:24:25:087 don't close database yet, keep open for 900 seconds
22:24:30:087 Current channel 25
22:24:30:095 Device TTL 1882 s flags: 0x7
22:24:31:088 don't close database yet, keep open for 900 seconds
22:24:32:646 no button map for: lumi.sensor_magnet ep: 0x01 cl: 0x0000 cmd: 0x0A pl[0]: 002
22:24:32:646 ZCL attribute report 0x00158D00042E766B for cluster: 0x0000, ep: 0x01, frame control: 0x1C, mfcode: 0x1234 
22:24:32:647 0x00158D00042E766B extract Xiaomi special attribute 0xFF02
22:24:32:647 	64 on/off 1
22:24:32:647 	01 battery 3025 (0x0BD1)
22:24:32:647 	04 unknown 17320 (0x43A8)
22:24:32:647 	06 LQI (?) 4294967296 (0x0100000000)
22:24:32:647 	Struct index 05 unknown (counter?) 29 (0x001D)
22:24:32:647 	Struct index 06 unknown (counter?) 89 (0x59)
22:24:36:188 don't close database yet, keep open for 900 seconds
22:24:41:983 don't close database yet, keep open for 900 seconds
22:24:47:093 don't close database yet, keep open for 900 seconds
22:24:55:087 don't close database yet, keep open for 900 seconds
22:25:00:892 don't close database yet, keep open for 900 seconds
22:25:06:085 don't close database yet, keep open for 900 seconds
22:25:07:657 ZCL attribute report 0xEC1BBDFFFEA684B5 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
22:25:07:675 ZCL attribute report 0xEC1BBDFFFEA684B5 for cluster: 0x0008, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
22:25:07:873 ZCL attribute report 0xEC1BBDFFFEA7F6C7 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
22:25:07:877 ZCL attribute report 0xEC1BBDFFFEA7F6C7 for cluster: 0x0008, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
22:25:12:084 don't close database yet, keep open for 900 seconds
22:25:18:090 don't close database yet, keep open for 900 seconds
22:25:26:087 don't close database yet, keep open for 900 seconds
22:25:30:087 Current channel 25
22:25:30:095 Device TTL 1822 s flags: 0x7
22:25:33:087 don't close database yet, keep open for 900 seconds
22:25:36:653 ZCL attribute report 0xEC1BBDFFFEA6CCEF for cluster: 0x0008, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
22:25:39:997 don't close database yet, keep open for 900 seconds
22:25:46:263 don't close database yet, keep open for 900 seconds
22:25:52:973 don't close database yet, keep open for 900 seconds
22:26:00:091 don't close database yet, keep open for 900 seconds
22:26:06:089 don't close database yet, keep open for 900 seconds
22:26:11:180 don't close database yet, keep open for 900 seconds
22:26:16:974 don't close database yet, keep open for 900 seconds
22:26:22:089 don't close database yet, keep open for 900 seconds
22:26:30:088 don't close database yet, keep open for 900 seconds
22:26:30:099 Current channel 25
22:26:30:107 Device TTL 1762 s flags: 0x7
22:26:35:889 don't close database yet, keep open for 900 seconds
22:26:38:773 ZCL attribute report 0xEC1BBDFFFEA6CCEF for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
22:26:41:088 don't close database yet, keep open for 900 seconds
22:26:47:086 don't close database yet, keep open for 900 seconds
22:26:52:996 don't close database yet, keep open for 900 seconds
22:26:59:194 don't close database yet, keep open for 900 seconds
22:27:06:087 don't close database yet, keep open for 900 seconds
22:27:11:181 don't close database yet, keep open for 900 seconds
22:27:16:087 don't close database yet, keep open for 900 seconds
22:27:22:087 don't close database yet, keep open for 900 seconds
```

**Comment by frenck** [comment]
@GitHubxtsnl That issue is not related to this one. However, it looks like an issue with deCONZ itself, which should be reported with dresden/deCONZ.

**Comment by frenck** [comment]
A workaround for the VNC issue has been found, currently testing an implemented change.

**Comment by vdiogo** [comment]
Issue remains after update to 6.1.1: Deconz add-on starts and I can open UI, and IKEA lights are detected, but cannot trigger any action on them. Also cannot add new lights from discovery.

Tried to restart Hassio and behaviour is the same

**Comment by jvyoralek** [comment]
I can confirm for aarch64 (Cortex-A53) the last version 6.1.1 resolved issue with VNC - had exactly as described in the issue description - and everything works fine now. Thanks for the quick fix.

**Comment by frenck** [comment]
@vdiogo That is not the problem reported in this issue. Please don't stack different problems, instead open up separate issues with details for each problem. Thanks 👍

**Comment by vdiogo** [comment]
@frenck noted 👍

**Comment by GitHubxtsnl** [comment]
after I preformed the update to 6.1.1, enabled VNC again all seems to be working. I had to add the deCONZ integration again allowing it to pair with the ConBeeII.

**Comment by averstappen** [comment]
> My current feeling says this is limited to ARMHF installations like the Raspberry Pi.
> I'm currently unable to reproduce this on other platforms, so will move over to a Pi for further testing. If someone reads this with an AMD64, for example, I would love to know if it breaks for you.

My error seems very similar to what is reported in this issue, but in my case on amd64 platform. Logging below is from a local ly installed version where I added the ARCH info:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] firmware.sh: executing... 
/usr/bin/GCFFlasher_internal.bin: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
[22:23:10] INFO: 
[cont-init.d] firmware.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] vnc.sh: executing... 
[cont-init.d] vnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:23:10] INFO: Running the deCONZ OTA updater...
[22:23:10] INFO: Waiting for device...
[22:23:10] INFO: Running the IKEA OTA updater...
[22:23:10] INFO: Starting udevd...
[22:23:10] INFO: Running the OSRAM LEdvance OTA updater...
[22:23:10] INFO: ARCH = amd64
ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu//usr/lib/x86_64-linux-gnu/libQt5Core.so.5.11.3' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
[22:23:10] INFO: Starting VNC server...

ERROR: ld.so: object '/usr/lib/x86_64-linux-gnu//usr/lib/x86_64-linux-gnu/libQt5Core.so.5.11.3' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
[22:23:14] INFO: Waiting for VNC to start
```
If I remove the VNC port mapping the output changes, but the addon still fails to start:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] firmware.sh: executing... 
/usr/bin/GCFFlasher_internal.bin: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
[22:27:40] INFO: 
[cont-init.d] firmware.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] vnc.sh: executing... 
[cont-init.d] vnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[22:27:40] INFO: Starting udevd...
[22:27:40] INFO: Running the OSRAM LEdvance OTA updater...
[22:27:40] INFO: Running the IKEA OTA updater...
[22:27:40] INFO: Running the deCONZ OTA updater...
[22:27:40] INFO: Waiting for device...
[22:27:40] INFO: Starting the deCONZ gateway...
deCONZ: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by labaland** [comment]
Upgraded deconz thru hassio addons on my synology today and now i cant start it. reinstall did not help.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] firmware.sh: executing... 
/usr/bin/GCFFlasher_internal.bin: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
[20:53:03] INFO: 
[cont-init.d] firmware.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] vnc.sh: executing... 
[cont-init.d] vnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:53:05] INFO: Starting udevd...
[18:53:05] INFO: Running the IKEA OTA updater...
[20:53:05] INFO: Waiting for device...
[18:53:05] INFO: Running the deCONZ OTA updater...
[18:53:05] INFO: Running the OSRAM LEdvance OTA updater...
[20:53:05] INFO: Starting the deCONZ gateway...
deCONZ: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
Error: writing output failed: Broken pipe
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by labaland** [comment]
Same error as above with 6.1.2  When restoring back to 5.3.6 it works again!

**Comment by pvizeli** [comment]
For synology user or people with old EOL kernel 3 -> https://github.com/home-assistant/hassio-addons/issues/1487
