### ISSUE TITLE
deconz 6.1.0 - Unable to read/write HomeAssistant entities from Node Red

### ISSUE THREAD

**Issue by HypoxiaSE** [home-assistant/hassio-addons#1482]
When upgrading to 6.1.0, support for manipulating deCONZ HomeAssistant entities from Node Red seem to have stopped working. At least several of my automations involving units connected via deCONZ stopped working.

Reading/writing from/to deCONZ Home Assistant entities (e.g. a light) result in state=unavailable.

I can't say for sure when it actually stopped working as I took a big leap in versions when upgrading to 6.1.0. Looking back in the release notes for earlier releases I haven't found any notes about the support being removed.

To put the issue in retrospect:
The reason for me to use Home Assistant entities in NodeRed instead of node-red-contrib-deconz is that several light operations are still not supported in the Node Red implementation (at least not for Ikea TRADFRI, e.g. color setting).

**Comment by stigvi** [comment]
Look here, [https://github.com/home-assistant/hassio-addons/issues/1480](url) , and see if your deconz is started or not

**Comment by HypoxiaSE** [comment]
> Look here, [#1480 (comment)](https://github.com/home-assistant/hassio-addons/issues/1480#issue-661903072) , and see if your deconz is started or not

Yes, it's running. I had to use the disable-VNC-workaround as a first step to get deCONZ to work at all, but this problem still remain.

**Comment by ludeeus** [comment]
Are the entities in Home Assistant?

**Comment by HypoxiaSE** [comment]
> Are the entities in Home Assistant?

Yes, they are there.
However, the issue disappeared when upgrading to 6.1.1. Since 6.1.0 is no longer relevant we can close this issue.
