### ISSUE TITLE
Deconz devices disconnection every 30 minutes

### ISSUE THREAD

**Issue by jybi89** [home-assistant/hassio-addons#1497]
Hello !
I am on Home Assistant and I have signal cuts between my Deconz key and all my sensors (Xiaomi Aqara opening sensor, Honeywell smoke detector, motion detector ...)

Home Assistant Core 0.113.0
Deconz 6.1.1
deConz Version 2.05.79 / 05/22/202
Firmware 26580700

Despite these last updates, I still have this disconnection reconnection problem for several weeks.
These outages occur approximately every 30 minutes.

I'm french, sorry for my english! and thank you for your help and advice :)

![image](https://user-images.githubusercontent.com/54111386/88337162-874b2b80-cd36-11ea-94c2-04c31b1fd9da.png)

![image](https://user-images.githubusercontent.com/54111386/88339871-18bc9c80-cd3b-11ea-8604-8b4e5d40c8ce.png)

**Comment by Mimiix** [comment]
Duplicate of https://github.com/home-assistant/core/issues/37372

**Comment by jybi89** [comment]
thanks, but this issue was closed 15 days ago when I looked ... apparently still not solved…. :'(

**Comment by pvizeli** [comment]
With 6.x.x the firmware work again because we fix the GLIBC version issue with the new flasher binary.

I can just provide updates and look that the binary inside work. I don't know why i.e. my conbee2 doesn't offer me a firmware update. Maybe the new firmware is only for tests and not for all

**Comment by jybi89** [comment]
Thank you for your answer. I just updated the add-on to version 6.1.2. Unfortunately I still have the same problem but only one disconnection in an hour, to be continued ....

![image](https://user-images.githubusercontent.com/54111386/88454050-d98e6880-ce6c-11ea-95d4-9ce0334d067f.png)

**Comment by Mimiix** [comment]
@pvizeli https://github.com/home-assistant/hassio-addons/issues/1347#issuecomment-664093542 say's it still fails. Check your PM on discord if you can:).

However, What version of deCONZ / Phoscon are you running? Phoscon mentions it at its gateway page.

**Comment by jybi89** [comment]
hi,

i use :
Home Assistant Core 0.113.0
Deconz 6.1.1
deConz Version 2.05.79 / 05/22/2020
Firmware 26580700

I made the update but it does not seem to have been supported and stay permanently at deconz version 05/22/2020

**Comment by RenzoBeux** [comment]
Having same problem here, really frustrating :(

**Comment by kedante** [comment]
Hi,

I also have the same problem. 
Disconnections approximately every hour. 
I really tried everything to solve the problem.

```
DEBUG (MainThread) [pydeconz.websocket] Websocket starting
DEBUG (MainThread) [pydeconz.websocket] Reconnecting to deCONZ in 15.
DEBUG (MainThread) [pydeconz.websocket] Websocket starting
DEBUG (MainThread) [pydeconz.websocket] Websocket running
```

Home Assistant 0.112.4
HassOS 4.11
Raspberry Pi 3 Model B
ConBee II (Firmware 26580700)
deCONZ 6.2.3 (2.05.79)

ZigBee components: 
- TRÅDFRI bulb GU10 WS 400lm
- TRÅDFRI Signal Repeater
- Xiaomi Aqara (motion sensor, switch)

**Comment by Mimiix** [comment]
As i said before:
duplicate of https://github.com/home-assistant/core/issues/37372
