### ISSUE TITLE
Feature request - can we add MQTT Explorer to Mosquitto add on

### ISSUE THREAD

**Issue by foxy82** [home-assistant/hassio-addons#1500]
Can we add MQTT Explorer (http://mqtt-explorer.com/) to the mosquitto add on in a similar way that we have access to ozw-admin on the zwave addon via NoVNC I believe?

**Comment by frenck** [comment]
While nice, I think this might be over the top for the add-on.
Adding features like this makes an add-on way more complicated to maintain but even more important, way heavier to run.

**Comment by foxy82** [comment]
The flip side is it makes it easier to debug issues. E.g. I'm suffering from several OpenZwave issues at the moment - being able to more easily look at what is on MQTT would be very handy but I take your point on the complexity.

**Comment by MartinHjelmare** [comment]
MQTT explorer just needs access to the broker that is publishing messages. You can run it from another computer and connect to the broker. So it should be easy to run it standalone.
