### ISSUE TITLE
Check Home Assistant configuration Error 

### ISSUE THREAD

**Issue by stringy92** [home-assistant/hassio-addons#1502]
I've tried running the check for 0.113.1, and get the following error. Dont believe this is linked with the HA install, as i am running Python 3.7.7

I have attached the error as a link - https://hastebin.com/aqekuyojew.js

```15:20:12] INFO: Please be patient, this might take a few minutes...
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpamw0_dx8
       cwd: /tmp/pip-install-5efe02k0/yarl
  Complete output (39 lines):
  **********************
  * Accellerated build *
  **********************
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/yarl
  copying yarl/_url.py -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/__init__.py -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/_quoting.py -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/_quoting_py.py -> build/lib.linux-x86_64-3.7/yarl
  running egg_info
  writing yarl.egg-info/PKG-INFO
  writing dependency_links to yarl.egg-info/dependency_links.txt
  writing requirements to yarl.egg-info/requires.txt
  writing top-level names to yarl.egg-info/top_level.txt
  reading manifest file 'yarl.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.cache' found anywhere in distribution
  warning: no previously-included files found matching 'yarl/_quoting.html'
  warning: no previously-included files found matching 'yarl/_quoting.*.so'
  warning: no previously-included files found matching 'yarl/_quoting.pyd'
  warning: no previously-included files found matching 'yarl/_quoting.*.pyd'
  no previously-included directories found matching 'docs/_build'
  writing manifest file 'yarl.egg-info/SOURCES.txt'
  copying yarl/__init__.pyi -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/_quoting_c.c -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/_quoting_c.pyi -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/_quoting_c.pyx -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/py.typed -> build/lib.linux-x86_64-3.7/yarl
  running build_ext
  building 'yarl._quoting_c' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/yarl
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.7m -c yarl/_quoting_c.c -o build/temp.linux-x86_64-3.7/yarl/_quoting_c.o
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for yarl

ERROR: Could not build wheels for yarl which use PEP 517 and cannot be installed directly
[15:20:39] ERROR: An error occurred while installing Home Assistant:
Looking in links: https://wheels.home-assistant.io/alpine-3.11/amd64/
Collecting homeassistant
  Downloading homeassistant-0.113.1-py3-none-any.whl (8.7 MB)
Collecting async-timeout==3.0.1
  Downloading async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting python-slugify==4.0.0
  Downloading https://wheels.home-assistant.io/alpine-3.11/amd64/python_slugify-4.0.0-py2.py3-none-any.whl (5.5 kB)
Collecting ciso8601==2.1.3
  Downloading https://wheels.home-assistant.io/alpine-3.11/amd64/ciso8601-2.1.3-cp37-none-any.whl (30 kB)
Requirement already satisfied: pip>=8.0.3 in /usr/local/lib/python3.7/site-packages (from homeassistant) (20.0.2)
Collecting jinja2>=2.11.1
  Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting PyJWT==1.7.1
  Downloading PyJWT-1.7.1-py2.py3-none-any.whl (18 kB)
Collecting ruamel.yaml==0.15.100
  Downloading https://wheels.home-assistant.io/alpine-3.11/amd64/ruamel.yaml-0.15.100-cp37-none-any.whl (781 kB)
Collecting attrs==19.3.0
  Downloading attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting aiohttp==3.6.1
  Downloading https://wheels.home-assistant.io/alpine-3.11/amd64/aiohttp-3.6.1-cp37-none-any.whl (1.3 MB)
Collecting certifi>=2020.4.5.1
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting voluptuous==0.11.7
  Downloading https://wheels.home-assistant.io/alpine-3.11/amd64/voluptuous-0.11.7-py3-none-any.whl (28 kB)
Collecting requests==2.24.0
  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting astral==1.10.1
  Downloading astral-1.10.1-py2.py3-none-any.whl (29 kB)
Collecting voluptuous-serialize==2.4.0
  Downloading voluptuous_serialize-2.4.0-py3-none-any.whl (6.7 kB)
Collecting cryptography==2.9.2
  Downloading https://wheels.home-assistant.io/alpine-3.11/amd64/cryptography-2.9.2-cp37-none-any.whl (1.4 MB)
Collecting pyyaml==5.3.1
  Downloading https://wheels.home-assistant.io/alpine-3.11/amd64/PyYAML-5.3.1-cp37-none-any.whl (44 kB)
Collecting bcrypt==3.1.7
  Downloading https://wheels.home-assistant.io/alpine-3.11/amd64/bcrypt-3.1.7-cp37-none-any.whl (67 kB)
Collecting pytz>=2020.1
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting importlib-metadata==1.6.0; python_version < "3.8"
  Downloading importlib_metadata-1.6.0-py2.py3-none-any.whl (30 kB)
Collecting text-unidecode>=1.3
  Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Collecting MarkupSafe>=0.23
  Downloading https://wheels.home-assistant.io/alpine-3.11/amd64/MarkupSafe-1.1.1-cp37-none-any.whl (36 kB)
Collecting chardet<4.0,>=2.0
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.5.0.tar.gz (172 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting multidict<5.0,>=4.5
  Downloading https://wheels.home-assistant.io/alpine-3.11/amd64/multidict-4.7.6-cp37-none-any.whl (144 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib/python3.7/site-packages (from cryptography==2.9.2->homeassistant) (1.14.0)
Collecting six>=1.4.1
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting zipp>=0.5
  Downloading zipp-3.1.0-py3-none-any.whl (4.9 kB)
Collecting typing-extensions>=3.7.4
  Downloading typing_extensions-3.7.4.2-py3-none-any.whl (22 kB)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography==2.9.2->homeassistant) (2.20)
Building wheels for collected packages: yarl
  Building wheel for yarl (PEP 517): started
  Building wheel for yarl (PEP 517): finished with status 'error'
Failed to build yarl
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting
```

**Comment by J-Lindvig** [comment]
Same error on my setup ( RPi 3B+ running 0.113.0 )....

**Comment by edwardscaleb9** [comment]
Same issue here (HA Core 0.112.3 on ESXi 6.7).

`warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.cache' found anywhere in distribution
  warning: no previously-included files found matching 'yarl/_quoting.html'
  warning: no previously-included files found matching 'yarl/_quoting.*.so'
  warning: no previously-included files found matching 'yarl/_quoting.pyd'
  warning: no previously-included files found matching 'yarl/_quoting.*.pyd'
  no previously-included directories found matching 'docs/_build'
  writing manifest file 'yarl.egg-info/SOURCES.txt'
  copying yarl/__init__.pyi -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/_quoting_c.c -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/_quoting_c.pyi -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/_quoting_c.pyx -> build/lib.linux-x86_64-3.7/yarl
  copying yarl/py.typed -> build/lib.linux-x86_64-3.7/yarl
  running build_ext
  building 'yarl._quoting_c' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/yarl
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/local/include/python3.7m -c yarl/_quoting_c.c -o build/temp.linux-x86_64-3.7/yarl/_quoting_c.o
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for yarl
ERROR: Could not build wheels for yarl which use PEP 517 and cannot be installed directly
[11:41:21] ERROR: An error occurred while installing Home Assistant:
Looking in links: https://wheels.home-assistant.io/alpine-3.11/amd64/
Collecting homeassistant
  Downloading homeassistant-0.113.1-py3-none-any.whl (8.7 MB)
Collecting voluptuous-serialize==2.4.0
  Downloading voluptuous_serialize-2.4.0-py3-none-any.whl (6.7 kB)
Collecting certifi>=2020.4.5.1
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting requests==2.24.0
  Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting aiohttp==3.6.1
  Downloading https://wheels.home-assistant.io/alpine-3.11/amd64/aiohttp-3.6.1-cp37-none-any.whl (1.3 MB)
Collecting attrs==19.3.0
  Downloading attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting python-slugify==4.0.0
  Downloading https://wheels.home-assistant.io/alpine-3.11/amd64/python_slugify-4.0.0-py2.py3-none-any.whl (5.5 kB)
Collecting importlib-metadata==1.6.0; python_version < "3.8"
  Downloading importlib_metadata-1.6.0-py2.py3-none-any.whl (30 kB)
Collecting pytz>=2020.1
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting voluptuous==0.11.7
  Downloading https://wheels.home-assistant.io/alpine-3.11/amd64/voluptuous-0.11.7-py3-none-any.whl (28 kB)
Collecting bcrypt==3.1.7
  Downloading https://wheels.home-assistant.io/alpine-3.11/amd64/bcrypt-3.1.7-cp37-none-any.whl (67 kB)
Collecting async-timeout==3.0.1
  Downloading async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting astral==1.10.1
  Downloading astral-1.10.1-py2.py3-none-any.whl (29 kB)
Collecting PyJWT==1.7.1
  Downloading PyJWT-1.7.1-py2.py3-none-any.whl (18 kB)
Collecting ruamel.yaml==0.15.100
  Downloading https://wheels.home-assistant.io/alpine-3.11/amd64/ruamel.yaml-0.15.100-cp37-none-any.whl (781 kB)
Collecting jinja2>=2.11.1
  Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting cryptography==2.9.2
  Downloading https://wheels.home-assistant.io/alpine-3.11/amd64/cryptography-2.9.2-cp37-none-any.whl (1.4 MB)
Requirement already satisfied: pip>=8.0.3 in /usr/local/lib/python3.7/site-packages (from homeassistant) (20.0.2)
Collecting ciso8601==2.1.3
  Downloading https://wheels.home-assistant.io/alpine-3.11/amd64/ciso8601-2.1.3-cp37-none-any.whl (30 kB)
Collecting pyyaml==5.3.1
  Downloading https://wheels.home-assistant.io/alpine-3.11/amd64/PyYAML-5.3.1-cp37-none-any.whl (44 kB)
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
Collecting multidict<5.0,>=4.5
  Downloading https://wheels.home-assistant.io/alpine-3.11/amd64/multidict-4.7.6-cp37-none-any.whl (144 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.5.0.tar.gz (172 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting text-unidecode>=1.3
  Downloading text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Collecting zipp>=0.5
  Downloading zipp-3.1.0-py3-none-any.whl (4.9 kB)
Requirement already satisfied: cffi>=1.1 in /usr/local/lib/python3.7/site-packages (from bcrypt==3.1.7->homeassistant) (1.14.0)
Collecting six>=1.4.1
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting MarkupSafe>=0.23
  Downloading https://wheels.home-assistant.io/alpine-3.11/amd64/MarkupSafe-1.1.1-cp37-none-any.whl (36 kB)
Collecting typing-extensions>=3.7.4
  Downloading typing_extensions-3.7.4.2-py3-none-any.whl (22 kB)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/site-packages (from cffi>=1.1->bcrypt==3.1.7->homeassistant) (2.20)
Building wheels for collected packages: yarl
  Building wheel for yarl (PEP 517): started
  Building wheel for yarl (PEP 517): finished with status 'error'
Failed to build yarl
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.`

**Comment by ercsey** [comment]
Same issue with Home Assistant Supervised 0.112.4 on Intel Nuc with Ubuntu.

**Comment by wsdavis** [comment]
+1

Also tried uninstalling and reinstalling the Check Configuration adding, but I still see the same error others are reporting. I’m currently running 0.112.3

**Comment by ioannispelelis** [comment]
Same issue here curently running 0.113.0 and this happens when checking for 0.113.1
I am running HA on a VM on a Freebox

**Comment by dancrevier** [comment]
I'm seeing the same. Has anyone gone ahead and updated? I'm assuming it doesn't mean my update will fail, but just wanted to check with others.

**Comment by surpasstop** [comment]
Same issue. 0.112.4 on Raspberry pi 4B, HassOS
Cannot Update to 0.113.1
CRITICAL (MainThread) [supervisor.homeassistant] HomeAssistant update fails -> rollback!

**Comment by mikekreisher** [comment]
Same here. I'm currently running 0.110.0 HA Core in a VM on Unraid. I get this error for every version that I check (0.111 and 0.112), not just 0.113. I have tried a number of the sub releases and the same result.

**Comment by dancrevier** [comment]
Verified that it's fixed for me. Thanks @frenck !
