### ISSUE TITLE
Deconz updated now it won't run.

### ISSUE THREAD

**Issue by Puntoboy** [home-assistant/hassio-addons#1503]
I was running 5.3.6 of the Hassio add-on and I just upgraded to 6.1.2. Now the add-on doesn't run for longer than a few seconds. The logs show this:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] firmware.sh: executing...
/usr/bin/GCFFlasher_internal.bin: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
[13:27:28] INFO:
[cont-init.d] firmware.sh: exited 0.
[cont-init.d] nginx.sh: executing...
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] vnc.sh: executing...
[cont-init.d] vnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:27:29] INFO: Running the deCONZ OTA updater...
[12:27:29] INFO: Running the OSRAM LEdvance OTA updater...
[12:27:29] INFO: Running the IKEA OTA updater...
[12:27:29] INFO: Starting udevd...
[13:27:29] INFO: Waiting for device...

[13:27:35] INFO: Starting VNC server...
[13:27:39] INFO: Waiting for VNC to start

[12:28:29] INFO: Starting Nginx...
2020/07/27 12:28:29 [notice] 350#350: using the "epoll" event method
2020/07/27 12:28:29 [notice] 350#350: nginx/1.14.2
2020/07/27 12:28:29 [notice] 350#350: OS: Linux 3.10.105
2020/07/27 12:28:29 [notice] 350#350: getrlimit(RLIMIT_NOFILE): 524288:1048576
2020/07/27 12:28:29 [notice] 350#350: start worker processes
2020/07/27 12:28:29 [notice] 350#350: start worker process 2611
[13:28:39] INFO: Starting the deCONZ gateway...
deCONZ: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
2020/07/27 12:28:39 [notice] 350#350: signal 15 (SIGTERM) received from 338, exiting
2020/07/27 12:28:39 [notice] 2611#2611: exiting
2020/07/27 12:28:39 [notice] 2611#2611: exit
2020/07/27 12:28:39 [notice] 350#350: signal 17 (SIGCHLD) received from 2611
2020/07/27 12:28:39 [notice] 350#350: worker process 2611 exited with code 0
2020/07/27 12:28:39 [notice] 350#350: exit
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.`

What have I done wrong?

**Comment by Puntoboy** [comment]
Additional information.

I am running this on Synology NAS using Docker. This seems to be the problem. :(

**Comment by Puntoboy** [comment]
How do I reinstall 5.3.6? I seem to be only able to install the latest version.

**Comment by Puntoboy** [comment]
> 
> 
> How do I reinstall 5.3.6? I seem to be only able to install the latest version.

I restored a snapshot of Deconz and now back to 5.3.6.

**Comment by gdellefoglie** [comment]
Hi, same problem for me running hassio on synology ds1512+. Mine is a new install so i can't downgrade, how can i do? any idea on how can i found old versions? libQt5Core.so.5 error with a log identical to the Puntoboy's one.

**Comment by tane64** [comment]
Same probleem here. Also running HA DS218+
Restore to 5.3.6 did not solve the probleem.

**Comment by frenck** [comment]
> /usr/bin/GCFFlasher_internal.bin: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory

This is caused by an old kernel version, that is not supported. It only happens on setups Home Assistant does not support (e.g., running a Home Assistant Supervised directly on a Synology NAS device).

It is strongly advised to switch to use a VM with HassOS instead.

For more information about the supported methods for a Supervised installation, see here: <https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md>

**Comment by Puntoboy** [comment]
Shame that 5.3.6 works perfectly. :(

**Comment by pvizeli** [comment]
Read more about outdated systems: https://github.com/home-assistant/hassio-addons/issues/1487
