### ISSUE TITLE
Deconz 6.2.0 faills to start

### ISSUE THREAD

**Issue by pergolafabio** [home-assistant/hassio-addons#1508]
hi,

updated from 6.1.2 to 6.2.0 , but the container doesnt want to start, it just stops?
running HassOS 4.11 , esxi

here is log : 
`
"""

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] firmware.sh: executing... 
[15:21:24] INFO: GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyUSB0     | 0x0403 | 0x6015  |            | ConBee 
[cont-init.d] firmware.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] novnc.sh: executing... 
[cont-init.d] novnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:21:24] INFO: Running the deCONZ OTA updater...
[13:21:24] INFO: Starting udevd...
[13:21:24] INFO: Running the IKEA OTA updater...
[13:21:24] INFO: Running the OSRAM LEdvance OTA updater...
[15:21:24] INFO: Websockify waiting for VNC to start
[15:21:24] INFO: Starting VNC server (local/no)...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
"""

**Comment by docgalaxyblock** [comment]
I'm having the same issue
quick fix would be perfect 👌

**Comment by KoltesPunti** [comment]
Quick Fix: delete the 5900 in the vnc section

**Comment by docgalaxyblock** [comment]
@KoltesPunti THX it works again

**Comment by pergolafabio** [comment]
maybe, thats missing in the documentaion, and its indeed NEEDED to disable VNC ?

**Comment by docgalaxyblock** [comment]
seems like that
now you can choose at the web ui between phoscon and deconz(vnc before)

**Comment by grayve** [comment]
Shit I'm deeply sorry I opened another issue I assume missplaced: if someone can delete it... It would be nice https://github.com/hassio-addons/repository/issues/192

**Comment by fi-sch** [comment]
> maybe, thats missing in the documentaion, and its indeed NEEDED to disable VNC ?

Why is this issue closed? That's still an issue because it is impossible to configure the add-on to use external VNC. For me that's really a problem.
Please reopen this issue as I don't want to create another duplicate.

**Comment by pergolafabio** [comment]
Ah, ok so, it's a bug? Where did frenck reply?

**Comment by docgalaxyblock** [comment]
Guy what ar you doing
At my perspective this Issue is a hint to the devs that there is some documentation missing
It could be that the devs do not want to open the VNC port anymore because they integrated that to the web ui
Or they really produced a bug
So @pergolafabio leave it open (my opinion)
I will ping frenk if it is right so

**Comment by frenck** [comment]
Please upgrade to 6.2.1 of the add-on, it was fixed in that version.

**Comment by paulot88** [comment]
Everything worked with 6.1.2. Upgraded to 6.2.0 and deconz didn't start and then tried to snapshot back to 6.1.2 but ended up with 6.2.1 and still no deconz. Removed 5900.

This is extract from log:
20-07-28 20:40:55 INFO (SyncWorker_5) [supervisor.docker.interface] Cleanup images: ['homeassistant/raspberrypi3-homeassistant:0.113.1']
20-07-28 20:42:33 WARNING (MainThread) [supervisor.addons.validate] Unknown options vnc_password
20-07-28 20:42:33 ERROR (SyncWorker_2) [supervisor.docker] Can't create container from addon_core_deconz: 404 Client Error: Not Found ("No such image: homeassistant/armhf-addon-deconz:6.2.1")

Where to go next?

**Comment by fi-sch** [comment]
For me 6.2.1 worked well but I found out that old-fashioned VPN access is not protected anymore. It's a pity but I can live with it – I'll just open the 5900 port whenever it's needed...

Thank you, Frenck!

**Comment by edwinoonk** [comment]
WARNING (MainThread) [supervisor.addons.validate] Unknown options vnc_password

here as well, after upgrade to hass.io 4.12
