### ISSUE TITLE
deCONZ plug-in doesn't start in Home Assistant

### ISSUE THREAD

**Issue by Tuur77** [home-assistant/hassio-addons#1509]
HomeAssistant version 0.113.1
DeCONZ firmware version 6.2.0

Problem:
DeCONZ plug in won't start.
After pressing Start, unable to open WEB UI

All lights, switches are unavailable.

Log from DeCONZ:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] firmware.sh: executing... 
[17:17:24] INFO: GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyACM0     | 0x1CF1 | 0x0030  |            | ConBee II 
/dev/ttyAMA0     | 0x0000 | 0x0000  |            | RaspBee 
[cont-init.d] firmware.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] novnc.sh: executing... 
[cont-init.d] novnc.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[15:17:24] INFO: Running the deCONZ OTA updater...
[services.d] done.
[15:17:24] INFO: Running the IKEA OTA updater...
[15:17:25] INFO: Running the OSRAM LEdvance OTA updater...
[17:17:25] INFO: Websockify waiting for VNC to start
[15:17:25] INFO: Starting udevd...
[17:17:25] INFO: Waiting for device...
[15:17:25] INFO: Can't fetch data from osram!
[17:17:29] INFO: Starting VNC server (local/no)...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

Log from HomeAssistant:
20-07-28 14:05:40 WARNING (MainThread) [supervisor.addons.validate] Unknown options vnc_password
20-07-28 14:05:40 INFO (SyncWorker_3) [supervisor.docker.interface] Clean addon_core_deconz application
20-07-28 14:05:42 ERROR (SyncWorker_3) [supervisor.docker] Can't start addon_core_deconz: 500 Server Error: Internal Server Error ("error gathering device information while adding custom device "/dev/ttyACM0": no such file or directory")
20-07-28 14:05:47 WARNING (MainThread) [supervisor.addons.validate] Unknown options vnc_password
20-07-28 14:05:47 INFO (SyncWorker_0) [supervisor.docker.interface] Clean addon_core_deconz application
20-07-28 14:05:49 INFO (SyncWorker_0) [supervisor.docker.addon] Start Docker add-on homeassistant/armhf-addon-deconz with version 6.2.0
20-07-28 14:05:52 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.1:8099 ssl:None [Connection refused]
20-07-28 14:28:34 WARNING (MainThread) [supervisor.addons.validate] Unknown options vnc_password
20-07-28 14:28:34 INFO (SyncWorker_1) [supervisor.docker.interface] Clean addon_core_deconz application
20-07-28 14:28:44 INFO (SyncWorker_1) [supervisor.docker.addon] Start Docker add-on homeassistant/armhf-addon-deconz with version 6.2.0
20-07-28 14:43:46 INFO (MainThread) [supervisor.updater] Fetch update data from https://version.home-assistant.io/stable.json
20-07-28 15:11:33 WARNING (MainThread) [supervisor.addons.validate] Unknown options vnc_password
20-07-28 15:11:33 INFO (SyncWorker_3) [supervisor.docker.interface] Clean addon_core_deconz application
20-07-28 15:11:35 INFO (SyncWorker_3) [supervisor.docker.addon] Start Docker add-on homeassistant/armhf-addon-deconz with version 6.2.0
20-07-28 15:14:33 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.1:8099 ssl:None [Host is unreachable]
20-07-28 15:17:22 WARNING (MainThread) [supervisor.addons.validate] Unknown options vnc_password
20-07-28 15:17:22 INFO (SyncWorker_1) [supervisor.docker.interface] Clean addon_core_deconz application
20-07-28 15:17:23 INFO (SyncWorker_1) [supervisor.docker.addon] Start Docker add-on homeassistant/armhf-addon-deconz with version 6.2.0
20-07-28 15:17:27 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.1:8099 ssl:None [Connection refused]
20-07-28 15:22:41 WARNING (MainThread) [supervisor.addons.validate] Unknown options vnc_password
20-07-28 15:22:41 INFO (SyncWorker_2) [supervisor.docker.interface] Clean addon_core_deconz application
20-07-28 15:22:43 INFO (SyncWorker_2) [supervisor.docker.addon] Start Docker add-on homeassistant/armhf-addon-deconz with version 6.2.0

**Comment by alexdepalex** [comment]
Did you check this issue? https://github.com/home-assistant/hassio-addons/issues/1508

**Comment by Tuur77** [comment]
> Did you check this issue? #1508
> 
> It's "fixed" by removing port 5900 from the vnc section in the add on configuration.

Yes! Thanks! I did miss that one. 
It's now working again.
