### ISSUE TITLE
deCONZ noVNC view doesn't work on Safari/WebKit on MacOS and iOS

### ISSUE THREAD

**Issue by alexdepalex** [home-assistant/hassio-addons#1511]
As of 6.2.0, noVNC is used to access the deCONZ gui. This doesn't work with Safari on both MacOS and iOS. The ingress url results in a 401. When opening the url in a separate tab, in the same browser, it does work.

<img width="1680" alt="Schermafbeelding 2020-07-28 om 18 16 33" src="https://user-images.githubusercontent.com/713019/88692590-892e3980-d0fe-11ea-84f6-748f3e047ca9.png">

**Comment by alexdepalex** [comment]
Then why not make deCONZ through noVNC optional through a switch in the add-on configuration? Currently, I cannot configure the external port for deCONZ VNC since the container then just stops.

**Comment by frenck** [comment]
> Currently, I cannot configure the external port for deCONZ VNC since the container then just stops.

That is a different bug that has been fixed in 6.2.1 of the add-on.

**Comment by alexdepalex** [comment]
Closing issue since workaround has been added to 6.2.1.
