### ISSUE TITLE
Deconz 6.2.0 exit after start

### ISSUE THREAD

**Issue by QuaySo** [home-assistant/hassio-addons#1512]
Just updated Deconz to the latest version. For some reason the addon quits after it is started. In the logs I see these lines:

```
[19:08:51] INFO: Starting VNC server (local/no)...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
No change was made to the configuration. I don't know what is causing this behavior. Anyone??
--QuaySo

**Comment by davidrustingha** [comment]
Same here. Rebooted everything but it doesnt help.

**Comment by chris-nite** [comment]
same here as well

**Comment by QuaySo** [comment]
Is there a way to revert to the previous version of Deconz?

**Comment by davidrustingha** [comment]
@QuaySo No idea. Not sure if its a good idea to delete and reinstall. Nothing is working so a fix would be great

**Comment by tbloth** [comment]
Same here. And that is a desaster as it controls a lot in my HomeAssistant environment.

**Comment by davidrustingha** [comment]
Reinstalling Deconz does not fix a thing. Can't even start it right now.

**Comment by chris-nite** [comment]
i just sucessfully restored the plugin through a snapshot i did two days ago (only selected to restore the plugin itself). This seems to work properly, so i hope you all got your backups right :-/

This update should be pulled ASAP so there won't be any more damage.

**Comment by QuaySo** [comment]
> i just sucessfully restored the plugin through a snapshot i did two days ago (only selected to restore the plugin itself). This seems to work properly, so i hope you all got your backups right :-/

I did exactly the same. Glad to have nightly backups...

**Comment by chris-nite** [comment]
I can offer to upload the old plugin-version itself in V6.1.2 as Snapshot, but i don't know if it comes with any personal data. Anyone knows more about partial backups?

**Comment by maqf12** [comment]
Same here... 👎

**Comment by al-wi** [comment]
Same here... and no snapshot since over a month ☹️

**Comment by ahd71** [comment]
Same issue here. Awaiting an upgrade soon or will revert to a backup.

**Comment by davidrustingha** [comment]
If anyone is interested, I have made a deconz backup. You can download it [here](https://wetransfer.com/downloads/4b163fb20fce87eb44467444172889ee20200728180336/077f281de1ca21da2d6b8b963af703cd20200728180433/34ebe3)

Its only available for 7 days, so lets hope its solved by then

**Comment by frenck** [comment]
Please upgrade to 2.6.1 of the add-on.

**Comment by ahd71** [comment]
Confirm 6.2.1 resolved the issue. I'm up and running again without restoring snapshot (just upgraded again!). Thanks for quick resolution!

**Comment by maqf12** [comment]
How to upgrade to 6.2.1 ?
I don´t have that option yet ?

**Comment by mario-tux** [comment]
To force update from the store: from the SSH plugin use `ha addons reload` then the 6.2.1 should be available from the web interface of HASS.
