### ISSUE TITLE
Setting VNC-Password deprecated?

### ISSUE THREAD

**Issue by chris-nite** [home-assistant/hassio-addons#1514]
Hello dear deconz-maintainers,
since the last update deconz 6.2.0/6.2.1 it's not possible to provide a vnc-password anymore to kinda "secure" the vnc-access itself. (i know the traffic is still cleartext...)
When starting the deconz-docker-container the log speaks of unsecure access to the vnc, which i would prefer to at least secure it a little bit (or alternatively providing an IP, which is allowed to connect).

Is the setting "vnc-password" now deprecated in the current release, because right now it's possible to connect without any password directly to the VNC-UI, which additionally now is also on by default. In my opinion this is pretty dangerous, to let it stay like that, as advanced settings are made available in the deconz-ui through VNC.

Thanks in advance and best regards
Chris

**Comment by frenck** [comment]
The direct access to VNC can be opened if one like, but is indeed unsecured. For secure access use the ingress exposed version, as that one is protected by the Home Assistant authentication and the traffic encrypted (in case you use SSL) as it uses WebSocket for transport.
