### ISSUE TITLE
Phoscon Web App stays empty

### ISSUE THREAD

**Issue by Br3b** [home-assistant/hassio-addons#1521]
hi there,
i just moved my deconz from a pi 2b raspian to my homeassistant pi 4b. 
i managed to get everything working including my phoscon backup i did before.

today i updated  to the new HA version and its not working anymore.
i can access Deconz and the devices are there but if i open Phoscon Web the site keeps empty.

i already tried to reinstall the addon serveral times and restart the pi/HA.. 

like this i cant control any lights :/
Please help!

![1](https://user-images.githubusercontent.com/49213470/88907702-3b7a1400-d259-11ea-8b08-a234c019a9a3.PNG)
![2](https://user-images.githubusercontent.com/49213470/88907833-63697780-d259-11ea-97cf-5f76a55393ea.PNG)

**Comment by Btullis11** [comment]
If you are still having issues, here is what I did
Click on the phoscon "P" icon
It should give you a screen that is partially functional.
Click on the 3 horizontal bars icon in the upper left hand corner and select logout
Go back to any other menu in home assistant such as overview
Click on the deconz app. 
Mine then prompted me to enter a new password twice 
Once it logged in everything was functional, however the entity names had changed so I had to rename everything to get Hass entities working again.
It seems to have been changes to the conbee firmware that necessitated the reset.
I hope this helps.

**Comment by Sirezul** [comment]
I'm facing the same issue, I think it's due a lack of **https support**  on the Deconz/Phoscon side.
Try to access it over http, it'll work.

**Comment by Mimiix** [comment]
@Sirezul It is party that, but it also is partly to the fact you can't access it over the external IP if your port isn't open.

**Comment by Br3b** [comment]
thank you very much for your answers.
i just did everything new and changed to the conbee stick.
