### ISSUE TITLE
Feature request deConz styling of <p> tag

### ISSUE THREAD

**Issue by LeonCB** [home-assistant/hassio-addons#1522]
The text on the ingress entry page in deCONZ 6.2.2 is almost unreadable on dark themes.
Is it possible to change the styling of the paragraph tag to use the primary-text-color variable?

Thanks!

**Comment by fi-sch** [comment]
+1 here, I was just about to open same request by myself :) It would be perfect if --primary-text-color or --secondary-text-color variable would be used.

It would also be great if e.g top bar could use the common variable that's used though all HA (--primary-color). Same thing about buttons.

Anyways, this UI improvement looks fantastic. Thank you!

**Comment by frenck** [comment]
We can expose themes to ingress pages, however, a background color was added in #1523, to prevent those issues.

Releases as v6.2.3 should be available for an update at any moment now.

**Comment by fi-sch** [comment]
You're the man, Frenck!

**Comment by frenck** [comment]
Actually, I'm not, this is Bram's work.
