### ISSUE TITLE
OpenZwave (beta)

### ISSUE THREAD

**Issue by Wiftavarf** [home-assistant/hassio-addons#1524]
Poor handling in UI.
From time to time either switches or dimmer are set on on or off. But they aren’t, worst is dimmer, got a few Fibaro dimmer. (Both early and later) both perform bad.
Dimmer can report as OFF, UI says OFF, node shows 0 in config, but the light is actually ON. And both UI and config reporting that there is Power floating throug dimmer.
Sending a new OFF signal does not help.
Sending a new ON and after that an OFF, can sometimes turn it off after a few minutes... Oh, and trying to do this by UI is not possible. 

My system:
Intel nuc with Ubuntu 20.04 desktop.
Hass.io in a docker container.
AeoTec Z-wave stick.
Conbee II
80 z-wave units
30 zigbee units

Had to roll back to Hass.io default Z-wave to get all to work again.

This is not worth a ”Beta” status.

**Comment by balloob** [comment]
Thanks for your feedback. This sounds like an issue with Open Z-Wave. I suggest you open an issue there. When you do, try to be more constructive. Things like "Poor handling UI" or your opinion on what a beta status reflect poorly.
