### ISSUE TITLE
conbee2 running phoscon detects Ledvance flex rgbw but cant switch strip to white

### ISSUE THREAD

**Issue by Btullis11** [home-assistant/hassio-addons#1525]
i have a conbee2 and hassio running on a raspberry pi4.
phoscon discovers and configures the LED strip light but only allows color control and not switching to white.
I looked in vain for somewhere to contact the phoscon developer directly as I think the issue is in there app.
sadly these work perfectly on my Wink hub.

**Comment by Mimiix** [comment]
Please open a issue [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/new?assignees=&labels=Bug+report&template=bug_report.md&title=)

**Comment by frenck** [comment]
@Mimiix Is correct @Btullis11. From an add-on point of view, there is not much we can do about this. This should be reported upstream.
