### ISSUE TITLE
deconz device missing after upgrade to hass.io 4.12

### ISSUE THREAD

**Issue by edwinoonk** [home-assistant/hassio-addons#1533]
Log says:

WARNING (MainThread) [supervisor.addons.validate] Unknown options vnc_password

All deconz connected devices are gone :-(

What to do?

**Comment by frenck** [comment]
Remove `vnc_password` from your add-on configuration, as that option has been removed.

Please supply full logs, as this warning is not a root cause.

**Comment by edwinoonk** [comment]
I finally found it.

before upgrade to 4.12 I had in the deconz config file:

**device: /dev/ttyS0**

changed that to:

**device: /dev/ttyAMA0**

all lights etc. connected again

removed vnc_password as you said as well now, so that's solved too

**Comment by frenck** [comment]
Great!

Please note, you should use a serial-by-id device instead. That will prevent these kind of issues.

e.g., `/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_XXXXXXXX-if00`

See the add-on documentation for more information.

**Comment by edwinoonk** [comment]
how can I find that value, I'm on a Raspberry with the hass.io image

**Comment by frenck** [comment]
Please see the add-on documentation, as it provides that information.
