### ISSUE TITLE
Cant remove groups?

### ISSUE THREAD

**Issue by JamieP83** [home-assistant/hassio-addons#1534]
hey all,
love the addon - thanks for the effort that goes into it.

deCONZ Current version: 6.2.3
Home Assistant 0.113.3

I had a group "bar" in Deconz which loaded into HA.
I then decided i didnt want Deconz groups anymore.

first i tried to turn off the "load groups" settings, with a reboot - didnt work
then i delete the group in deconz and rebooted - didnt work

ive called the refresh service too

now i dont know what to do?

![image](https://user-images.githubusercontent.com/48566948/89729316-52c0ba80-da2c-11ea-9e5d-bcd2363d9533.png)

![image](https://user-images.githubusercontent.com/48566948/89729319-5ce2b900-da2c-11ea-889e-31b553bb8a0e.png)

**Comment by Mimiix** [comment]
I think you should open a issue here: https://github.com/home-assistant/core/

This is not addon related but integration.

**Comment by frenck** [comment]
@Mimiix Is correct in this case @JamieP83 
Please open an issue on the core repository, as this is not add-on related. 

Thanks 👍
