### ISSUE TITLE
Samba share does not show in Windows Network folder  

### ISSUE THREAD

**Issue by SamuelCarson** [home-assistant/hassio-addons#1537]
## The problem

Installed Samba share add-on. Samba share does not show in Windows File Explorer Network folder. Both Win7 and Win10 (1909) have this problem. Files are accessible via \\HA.ip.address. Compatibility_mode: true makes no difference. Without network visibility one cannot assign a drive letter to the server.  

## Environment

- Add-on with the issue: Samba Share
- Add-on release with the issue:  9.2.0
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): hassio 0.113.3

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by compujunk** [comment]
I have the same problem after a update of windows 10

**Comment by compujunk** [comment]
I can assign a drive letter when i go to \\ha.ipadress\ without a share. I get then all the shares and ken assign a drive letter.

**Comment by socbutter** [comment]
New to HA, just installed add-on samba after adding user password, file explorer can't find HA. tried \\ip.address.ha and  \\ip.address.ha:8123 without success.

**Comment by Heathy65** [comment]
Running "Samba share" 9.5.1 and I have the same problem.  In the Netwrok vis on a W10 machine I cannot see the HA host.  However if I type it's name "\\HA" I can connect to it.
