### ISSUE TITLE
supervisor not listening

### ISSUE THREAD

**Issue by allenlarkins** [home-assistant/hassio-addons#1539]
## The problem
Trying to confirm that my configuration will work when I upgrade from Home Assistant Core 0.113.0 to Home Assistant Core 0.114.1. Starting the add-on and then monitoring the logs, I can see some errors. I get a confirmation that the config is valid (even though the supervisor was not listening)

## Environment
Running on a Pi 3B+
System uptime at present: 4h30

- Add-on with the issue: Check Home Assistant configuration
https://github.com/home-assistant/hassio-addons/tree/master/check_config
- Add-on release with the issue: 3.4.0 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): HassOS version 4.10 with Home Assistant Core 0.113.0 

## Problem-relevant configuration
version: latest

## Traceback/Error logs
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
starting version 3.2.9
[14:56:34] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:56:35] INFO: Setup udev devices
[14:56:37] INFO: Don't worry, this temporary installation is not overwriting your current one.
[14:56:37] INFO: Installing Home Assistant: latest...
[14:56:37] INFO: Please be patient, this might take a few minutes...
[15:01:52] INFO: Installed Home Assistant 0.114.1
[15:01:52] INFO: Making a copy of your configuration for checking...
[15:03:14] INFO: Checking your configuration against this version...
[15:16:34] INFO: Configuration check finished - no error found! :)
**s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening**
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by pvizeli** [comment]
`[15:16:34] INFO: Configuration check finished - no error found! :)`
