### ISSUE TITLE
Home Assistant Add-on: Mosquitto broker v 5.1 - how to enable bridge mode?

### ISSUE THREAD

**Issue by udgithub** [home-assistant/hassio-addons#1545]
## Can't enable bridge mode as I can do with normal mosquitto server

I'm using the standard config of the  addon Mosquitto broker v 5.1 :
```
logins: []
anonymous: false
customize:
  active: true
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```
I only changed active: false to true according to the documentation saying:
```
Option: customize.active
   If set to true additional configuration files will be read, see the next option.
   Default value: false
Option: customize.folder
   The folder to read the additional configuration files (*.conf) from.
```

With the file editor of HA I added a folder named "mosquitto" to the home assistant config-dir.
Inside mosquitto I placed two files.
The mqtt-ca.pem from The Things Network which is necessary for a TLS connection.
And the file mqtt-bridge.conf with the bridge config (see below).

## Environment

- Add-on with the issue: Mosquitto broker
- Add-on release with the issue: 5.1
- Last working add-on release (if known): none
- Operating environment (OS/Supervised): Windows 10, Virtualbox 6.1, freshly installed OVA-file with Home Assistant 0.114.2

## Problem-relevant configuration

mqtt-bridge.conf
```
connection ttn
address eu.thethings.network:8883
bridge_cafile ttn-mqtt-ca.pem
remote_username <ttn-user>
remote_password <ttn-password>
topic readwrite #   (I also tried topic # in 0)
```

```yaml

```

## Traceback/Error logs

```
1597847468: Error: Unable to open include_dir '/share/mosquitto'.
1597847468: Error found at /etc/mosquitto.conf:29.
```

## Additional information
Such a bridge-config works very well, when using HA with an external mosquitto server (for example on a raspberry pi).

It would be great if anybody could give me a hint. Perhaps bridge mode isn't possible at all with this addon.

Thanks a lot in advance !

Just a little bit more info about my installed appliance which I got via this link https://github.com/home-assistant/operating-system/releases/download/4.12/hassos_ova-4.12.ova
```
arch	        x86_64
chassis	        vm
dev             false
docker	        true
docker_version  19.03.11
hassio	        true
host_os	        HassOS 4.12
install..-_type	Home Assistant OS
os_name	        Linux
os_version      5.4.56
python_version	3.8.3
supervisor      235
timezone        Europe/Berlin
version         0.114.2
virtualenv      false
```

**Comment by epictechlab** [comment]
Hey there, I've the exact same issue! I'm triying to connect my Hisense TV  which has an internal MQTT Broker to my Mosquitto Add-on on my Home Assistant instance.

Add-on config:
`logins:
  - username: ****
    password: ****
require_certificate: false
certfile: fullchain.pem
keyfile: privkey.pem
customize:
  active: true
  folder: mosquitto`

Config of my hisense mqtt:
`connection hisensetv
address ***.***.***.***:36669
username hisenseservice
password  multimqttservice
clientid HomeAssistant
bridge_tls_version tlsv1.2
bridge_cafile hisense.crt
bridge_certfile rcm_certchain_pem.cer
bridge_keyfile rcm_pem_privkey.pkcs8
bridge_insecure true
start_type automatic
try_private true
topic /remoteapp/# both 0 hisense ""`

Mosquitto Logs:
`Error: Unable to open include_dir '/share/mosquitto'.
Error found at line /etc/mosquitto/mosquitto.conf:33.`
