### ISSUE TITLE
Update to deCONZ 2.05.80

### ISSUE THREAD

**Issue by ArniPL** [home-assistant/hassio-addons#1558]
## The problem

Hello.

Is the upgrade to [deCONZ 2.05.80](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_80) planned? This release adds support for a lot of new devices and adds deduplication of clusters which might fix one [specific Heiman relay/switch](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3008).

Additionally, is there any documentation for manually building and testing the addon with a different deCONZ version?

## Environment

- Add-on with the issue: deCONZ
- Add-on release with the issue: 6.2.3
- Last working add-on release (if known): N/A
- Operating environment (OS/Supervised): HassOS 5.1

## Problem-relevant configuration

```yaml
N/A
```

## Traceback/Error logs

```txt
N/A
```

## Additional information
N/A

**Comment by ArniPL** [comment]
[I have been informed](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3008#issuecomment-684022316), that 2.05.80 isn't ready for HA integration due to disabled Phoscon firmware update feature. We'll have to wait for a future release then.

**Comment by frenck** [comment]
Furthermore, it is a pre-release/beta and not available as a final release.
