### ISSUE TITLE
Deconz Add on shuts down by itself

### ISSUE THREAD

**Issue by arifroni** [home-assistant/hassio-addons#1560]
## The problem
  Deconz add on was closed and never started. this happened 2 times in the last one month.

## Environment
  HassOS 4.12

## Traceback/Error logs
![image](https://user-images.githubusercontent.com/59896374/91837035-e82a2580-ec4b-11ea-884e-0ce18767c3ba.png)

**Comment by migo-dev** [comment]
Duplicate of: https://github.com/home-assistant/hassio-addons/issues/1546
