### ISSUE TITLE
DuckDns not starting if there is no internet connection

### ISSUE THREAD

**Issue by PipeDeveloper** [home-assistant/hassio-addons#1563]
## The problem
The addon DuckDNS is not starting when there is no internet conection. This happen when when there was an electrical cut at my home. My Home Assistant server starts more faster, about 30seconds than my router that tooks about 3 minutes in boot.

## Environment
Docker Hassio

- Add-on with the issue: Duck DNS
- Add-on release with the issue: Current version: 1.12.1
- Last working add-on release (if known):  I dont know
- Operating environment (OS/Supervised):  Ubuntu 18.04 TLS / 235

## Problem-relevant configuration

This is my DuckDNS config
lets_encrypt:
  accept_terms: true
  certfile: fullchain.pem
  keyfile: privkey.pem
token: MY TOKEN...
domains:
  - DOMAIN1...
  - DOMAIN2...
aliases: []
seconds: 300

## Traceback/Error logs
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
# INFO: Using main config file /data/workdir/config
ERROR: Problem connecting to server (get for https://acme-v02.api.letsencrypt.org/directory; curl returned with 6)
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by McGiverGim** [comment]
I have the same problem, please a fix for this is important. The server is not accesible any more from outside. If I'm out on holidays I can't access to my cameras, alarms, etc.

**Comment by darionic** [comment]
Yes, that's true. It happens everytime after an electrical cut.

**Comment by McGiverGim** [comment]
> Enable the "watchdog" toggle for the add-on and it will never stop.

@ludeeus this toggle has been always there???? I think I'm blind 😱

**Comment by ludeeus** [comment]
Nope, It was added in supervisor version 236

**Comment by PipeDeveloper** [comment]
Excelent!!! Well it didnt exist on last week hahaha
Closing this issue
