### ISSUE TITLE
Bump deCONZ version to latest stable release

### ISSUE THREAD

**Issue by fi-sch** [home-assistant/hassio-addons#1571]
## The problem
deCONZ add-on was not updated (bumped) for a long time now. Would it be possible to update to the latest version that was released today? https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_81_stable

Thanks!

**Comment by frenck** [comment]
2.05.81 is the stable version of 2.05.80 rc/beta version.

We won't be upgrading to this version. See: <https://github.com/home-assistant/hassio-addons/pull/1541#issuecomment-675330382>

**Comment by fi-sch** [comment]
I don't get it to be honest. What is the reason to not upgrade it?
From what I can see 2.05.81 re-enables firmware update in Phoscon (and there was one released yesterday) and fixes a lot of issues. Even LQI issue that was there for a long long time.

**Comment by frenck** [comment]
> From what I can see 2.05.81 re-enables firmware update in Phoscon 

I'm not seeing that one listed, furthermore, the release explicitly mentions a manual upgrade is needed.

**Comment by fi-sch** [comment]
> > From what I can see 2.05.81 re-enables firmware update in Phoscon
> 
> I'm not seeing that one listed, furthermore, the release explicitly mentions a manual upgrade is needed.

That is said in PR mentioned in release notes:
> Improved firmware update #3256 
Heres the link to PR: https://github.com/dresden-elektronik/deconz-rest-plugin/pull/3256

I'm not sure why the release notes states the opposite in firmware section. Maybe that's just a firmware thing.

**Comment by fi-sch** [comment]
@frenck 
That's cleared out in this issue that I've created in DE repository: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3266

So the manual update requirement isn't the case with the latest deCONZ.
