### ISSUE TITLE
OpenZwave add-on does not startup

### ISSUE THREAD

**Issue by bakboord4** [home-assistant/hassio-addons#1572]
OpenZwave does not startup or update. 

Error first visible when updating 0.5.2 to 0.5.3. 

Error msg: 
Can't install homeassistant/armv7-addon-zwave:0.5.3 -> 404 Client Error: Not Found ("manifest for homeassistant/armv7-addon-zwave:0.5.3 not found: manifest unknown: manifest unknown").
This error is often caused by not having enough disk space available. Available space in /data is: 20.8 GiB

Bypassing the update by deleting and (re) installing OpenZwave add-on, gives the same error.

Result error: Zwave network is not accessible.

## Environment

Raspberry Pi 4:

arch | armv7l
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.13
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v7l
python_version | 3.8.3
supervisor | 243
timezone | Europe/Amsterdam
version | 0.114.4
virtualenv | false

- Home Assistant Core release with the issue: 0.114.4
- Last working Home Assistant Core release (if known): 
- Operating environment (OS/Container/Supervised/Core): 
- Integration causing this issue:   OpenZwave 0.5.3
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

Error msg: 20-09-15 09:11:08 INFO (SyncWorker_1) [supervisor.docker.interface] Pull image homeassistant/armv7-addon-zwave tag 0.5.3.
20-09-15 09:11:10 ERROR (SyncWorker_1) [supervisor.docker.interface] Can't install homeassistant/armv7-addon-zwave:0.5.3 -> 404 Client Error: Not Found ("manifest for homeassistant/armv7-addon-zwave:0.5.3 not found: manifest unknown: manifest unknown").
20-09-15 09:11:10 INFO (SyncWorker_1) [supervisor.docker.interface] This error is often caused by not having enough disk space available. Available space in /data is: 20.8 GiB
20-09-15 09:18:24 INFO (SyncWorker_0) [supervisor.docker.interface] Pull image homeassistant/armv7-addon-zwave tag 0.5.3.
20-09-15 09:18:25 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install homeassistant/armv7-addon-zwave:0.5.3 -> 404 Client Error: Not Found ("manifest for homeassistant/armv7-addon-zwave:0.5.3 not found: manifest unknown: manifest unknown").
20-09-15 09:18:25 INFO (SyncWorker_0) [supervisor.docker.interface] This error is often caused by not having enough disk space available. Available space in /data is: 20.8 GiB

**Comment by MartinHjelmare** [comment]
The docker builds for three architectures, armv7, armhf and i386 failed for version 0.5.3. We currently don't know why.

**Comment by tolookah** [comment]
Watching this thread, can't install for the same reason.

**Comment by nemith** [comment]
Seems to be failing on just 32-bit architectures and the CI error seems to be looking for a 64-bit time value.

```
/usr/lib/gcc/armv6-alpine-linux-musleabihf/9.3.0/../../../../armv6-alpine-linux-musleabihf/bin/ld: /usr/lib/gcc/armv6-alpine-linux-musleabihf/9.3.0/../../../libunwind.so: undefined reference to `__fstat_time64'
collect2: error: ld returned 1 exit status
```

**Comment by dsegantx** [comment]
I have same update error but have not uninstalled.  I am running on Rpi4 64bit Hassos with lots of space.  If there's any other logs or actions I can perform to assist diagnose please advise.  Not sure if the above 32/64 bit is a compile/build error or what but wanted to indicate 64bit HA isn't able to upgrade to 0.5.3 either.

Tnx

**Comment by edvanr** [comment]
Is there a workaround until the build gets fixed? Could someone possibly copy the docker image of 0.5.2 to 0.5.3 so we can at least install OpenZWave... https://hub.docker.com/r/homeassistant/armv7-addon-zwave/tags?page=1&ordering=last_updated

**Comment by bakboord4** [comment]
> Is there a workaround until the build gets fixed? Could someone possibly copy the docker image of 0.5.2 to 0.5.3 so we can at least install OpenZWave... https://hub.docker.com/r/homeassistant/armv7-addon-zwave/tags?page=1&ordering=last_updated

In my case a snapshot of two days ago was helpful.

**Comment by MartinHjelmare** [comment]
We think we have solved the build issues now. A new release and build is underway. Stay tuned.

**Comment by AndrewGWalsh** [comment]
0.5.4 is available on the store and has installed, I'm off to try it out...

**Comment by bakboord4** [comment]
Implemented 0.5.4 successfully.
My ZWave device are accessible again.
Thanks to the developers for the quick response.

**Comment by tolookah** [comment]
Agreed, I was too busy setting up my zwave network after it worked, because it works. 

Thanks for the efforts

**Comment by dsegantx** [comment]
Confirm installed 0.5.4 and working.  Thank you.

**Comment by sanderlv** [comment]
Guys!! 0.5.4 worked well (as did 0.5.3). But 0.6.0 does not start!!! 

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] auth.sh: executing... 
[22:48:06] INFO: Auth database exists
[cont-init.d] auth.sh: exited 0.
[cont-init.d] mqtt.sh: executing... 
[22:48:09] INFO: Connected to internal MQTT service
[cont-init.d] mqtt.sh: exited 0.
[cont-init.d] network_key.sh: executing... 
[cont-init.d] network_key.sh: exited 0.
[cont-init.d] novnc.sh: executing... 
sed: /usr/share/novnc/vnc_lite.html: No such file or directory
[cont-init.d] novnc.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] mqtt.sh: executing... 
[22:48:10] INFO: Ensure upstream MQTT server has the correct OZW status
[cont-finish.d] mqtt.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

Deleted the openzwave topic via mqtt explorer.... nothing! Help!

**Comment by gcorgnet-vista** [comment]
same here

**Comment by sanderlv** [comment]
restoring from a vmware snapshot 22:00 (1:18) but sooo slow (waiting takes long)

**Comment by gcorgnet-vista** [comment]
is there an easy way to downgarde?

**Comment by sanderlv** [comment]
Don't know and don't think so... unless you use the native containers instead off the add-on I think you must be able to with a new (old) docker pull (but not the expert here).

**Comment by GeertvanHorrik** [comment]
Created separate ticket for 0.6.0: #1582

**Comment by sanderlv** [comment]
@GeertvanHorrik thank you, that seems indeed the issue. I successfully restored my vmware snapshot all fine again... holding my updates for a few days for now...

**Comment by bakboord4** [comment]
0.5.3 issue is solved. Therefore this issue is closed.
for 0.6.0 problems; see ticket https://github.com/GeertvanHorrik
