### ISSUE TITLE
Install from Supervisor Fails

### ISSUE THREAD

**Issue by nprill** [home-assistant/hassio-addons#1574]
Go to Supervisor>Add-On Store>Search for OpenZwave and click install. Returns: Failed to install addon Unknown error, see logs
Supervisor Log Entry:
20-09-16 01:44:55 ERROR (SyncWorker_7) [supervisor.docker.interface] Can't install homeassistant/armv7-addon-zwave:0.5.3 -> 404 Client Error: Not Found ("manifest for homeassistant/armv7-addon-zwave:0.5.3 not found: manifest unknown: manifest unknown").

**Comment by OverZealous** [comment]
I'm getting the same thing for 0.6.0 as well. This is installed on a Raspberry Pi 3b.

**Comment by nprill** [comment]
I successfully pulled the image directly with Portainer, and then attempted to install the add-on and has the same result. Pi 3b here as well.

**Comment by frenck** [comment]
This was due to a release that failed building. We have rolled back for now, so this issue is no longer an issue.

Closing.
