### ISSUE TITLE
Port conflict 8883 

### ISSUE THREAD

**Issue by jphucke** [home-assistant/hassio-addons#1585]
Change the default port of 8883? It is conflicting with the myQ service.

**Comment by frenck** [comment]
Hi @jphucke,

Could you maybe tell us a bit more? Like, what add-on are you talking about here?

**Comment by jphucke** [comment]
https://www.home-assistant.io/integrations/myq

https://support.chamberlaingroup.com/s/article/Recommended-router-settings-for-the-MyQ-Wi-Fi-products-1484145723404

**Comment by frenck** [comment]
@jphucke Thank you for responding, but I got the myQ part. byt myQ is not an add-on, but an integration. Is myQ conflicting with an add-on? If so, which one? You disabled a network port? of what?

**Comment by jphucke** [comment]
Ah, apologies. Mosquitto MQTT broker has a default port. I assumed when I selected the link in the mosquitto add on it would take me to the mosquitto directed forum section. 

 Disabled port 8883 in the mosquitto network configuration.

**Comment by frenck** [comment]
This is not going to change. MQTT uses that port, so do many other things. There is more software in the world than the number of ports possible.

Hence we provide configuration options for this. Using a software default, is important, as it matches the expected and documented experience with bot our project, but also the documentation upstream.

**Comment by jphucke** [comment]
It did not solve the collision, tried to change the port in the Network config but was still bound to that port. So I was forced to disable until a permanent resolution is determined. 

Yes obviously more software than ports, I'm sure HA is not going to integrate every software available in the world so it would make sense to strive to eliminate as many conflicts as possible when known. Just trying to bring that to HA/mqtt attention.
