### ISSUE TITLE
Deconz FW is way behind

### ISSUE THREAD

**Issue by dedepene** [home-assistant/hassio-addons#1586]
## The problem

I'm unable to update Deconz software version to the latest available from manufacturer.

## Environment

- Add-on with the issue: Deconz
- Add-on release with the issue: 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): 

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information
I have manually updated my conbee stick's FW on another machine but the Deconz software is behind, stuck at .79. The deconz people say there's no manual upgrade path and the HA addon needs to be updated so we can get .82 version. @pvizeli , @frenck   could you possibly look into this please? Thanks!

**Comment by mario-tux** [comment]
> As a workaround I did update the stick on a Win10 machine, but as soon as I plug it back into the HA supervised machine it reverts to the ancient FW version :(

This is quiet strange: upon update on another machine, the stick should keep the current firmware. I don't think the Deconz addon tries anyway to update the firmware automatically (overwriting with an old firmware)... To update the stick using the addon is difficult, I agree, so I usually update the firmware on my linux laptop and replug the device on my NUC.

Yes, the addon should be updated to the last Deconz version.

**Comment by dedepene** [comment]
I know, right? I would think the updated FW will stick, but it won't - not only it shows the old version in Phoscon, but deconz won't add devices that are being already supported in the latest version. Here's after the update on a win10 machine:

![on_pc](https://user-images.githubusercontent.com/6883390/93665319-3168da80-fa7e-11ea-8566-26718e89320b.PNG)

And this is when I plug it back into the HA supervised:

![image](https://user-images.githubusercontent.com/6883390/93665328-434a7d80-fa7e-11ea-8154-836e61b067e3.png)

**Comment by ArniPL** [comment]
There's already a [pull request](https://github.com/home-assistant/hassio-addons/pull/1573) solving this issue. Should be merged soon.

**Comment by mario-tux** [comment]
@dedepene, as said was strange that the firmware "jump back" when plugged on the "old Deconz" installation. On your Win10 machine you installalled Deconz 2.5.81, in Hass you still have 2.5.79. Deconz doesn't stay on the usb key.

**Comment by inconsx** [comment]
@mario-tux same issue here

**Comment by Mimiix** [comment]
Just follow this guide:
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

We recommend using a native installation for best results.

**Comment by pvizeli** [comment]
We follow now the stable line which we take up to date.
