### ISSUE TITLE
Terminal and SSH configuration page is too broken to actually enable ssh access.

### ISSUE THREAD

**Issue by deddc23efb** [home-assistant/hassio-addons#1588]
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Running homeassisatant 115.2
Terminal and SSH is supposed to enable SSH. Shockingly the default configuration doesn't do that. It's impossible to ssh to homeassistant when configuring Terminal and SSH. A WEB UI is not ANY good when the WEB UI Is broken - that's why people install ssh.

Second: The Network Configuration for Terminal and SSH is incorrectly labelled so that SSH stays broken because it will only forward port 22 if the HOST field is configured with a PORT number. This is ridiculously broken UI and should never have been released like this let alone be the Official SSH tool.

## Expected behavior

The expected behaviour is that enabling the Terminal and SSH Add-on would by default enable SSH.

## Steps to reproduce

1. To reproduce - install the Terminal and SSH add-on and try to ssh from another device.  Watch it not work. Next , hunt for the PORT field and find it not present to reproduce the no network access for real SSH problem.

## Environment

homeassistant 0.115.2
chromium
ssh from linux mint 19

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by frenck** [comment]
Thank you for opening an issue, however, you are not posting an issue, but doing a feature requested and pack it as an issue.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

SSH was disabled by default on purpose. It makes the use more complex than needed, as for most uses cases it isn't directly needed. Nevertheless, it has been documented in the add-on manual.

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍

**Comment by reneklacan** [comment]
I couldn't make it work until I read this rant which is 100% true but this was important info to me:

> The Network Configuration for Terminal and SSH is incorrectly labelled so that SSH stays broken because it will only forward port 22 if the HOST field is configured with a PORT number.

Putting 22 into "Host" field makes it work, who would have guessed that...

@deddc23efb Thanks!

**Comment by frenck** [comment]
@reneklacan Sorry, but that part is documented. Was the documentation unclear on that part?

**Comment by deddc23efb** [comment]
The fact is that many users are confused by the documentation for the Add-on and how it functions.  Take a look at the repeated questions in the hassio forums asking about it.  The documentation isn't clear.  I've already pushed a PR with some changes that address the things that I found unclear - hopefully it helps.

**Comment by justbennett** [comment]
The documentation wasn't clear to me at first either

Perhaps something like this would have made that clear.
> If you want to connect to Home Assistant using an SSH client, such as PuTTY via the network, you need to specify which port to use on the Home Assistant host. The number you enter will be used to map that port from the host into the running "Terminal & SSH" add-on. The standard port used for the SSH protocol is 22.

The configuration page UI was also a little confusing to me.
![image](https://user-images.githubusercontent.com/28458839/94363959-8d89bb00-008b-11eb-921b-c59cc048fc9a.png)

I'm not sure what "Container   Host   Description" is for.  Maybe I'm misunderstanding.

**Comment by ekendra-nz** [comment]
How is this closed? It's still a major point of un-useability for this add-on.
