### ISSUE TITLE
core_ssh addon's README should mention it's only available for advanced users.

### ISSUE THREAD

**Issue by coaxial** [home-assistant/hassio-addons#1589]
## The problem

It took me a good while to figure out that I had to go to my user's profile and enable advanced addons to even see and install this addon. I think it should be added in theREADME, because that's the only thing users see when linked from the documentation on the home assistant website.

## Environment

- Add-on with the issue: core_ssh
- Add-on release with the issue: 
- Last working add-on release (if known): 
- Operating environment (OS/Supervised): 

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by frenck** [comment]
It is in the documentation:

![image](https://user-images.githubusercontent.com/195327/93989767-9e37e980-fd8a-11ea-8f0f-88dd9063cdd0.png)

Furthermore, the add-on store will hint this when the advanced mode is disabled:

![image](https://user-images.githubusercontent.com/195327/93989914-c32c5c80-fd8a-11ea-9482-13d38714ebad.png)

If you have another improvement possibility, please feel free to open up a PR. 👍
