### ISSUE TITLE
Duck DNS not committed to set ip address

### ISSUE THREAD

**Issue by ClearlyDazed** [home-assistant/hassio-addons#1601]
Duck DNS ver 1.12.1 is set up for a static ip address (ipv4) in the configuration but the logs show it connecting to my secondary network interface card on occasion and then reconnecting to my primary interface card. This occurs a number of times throughout the day. Using HA ver 115.2

**Comment by jonasem** [comment]
ipv4 hasnt been read correctly from the config before, meaning that duckdns would try to dynamically guess ip even though config is set. A fix is on the way #1659. Try again when version 1.12.3 is released (might be pretty soon)
