### ISSUE TITLE
QUERY: Creating Hass.io MQTT Broker

### ISSUE THREAD

**Issue by jodi319** [home-assistant/hassio-addons#1611]
I’m new 5o all of this.
In your read me; when you talk about creating mqtt users and using hass.io users:
Do you mean: if I have a user (Let’s say name and username is pia)  in Hass Users. When I install MQTT Broker and not change anything in its config and start it. When when going to Hass integration and link Hass and PIA, setting autodiscovery - broker will automatically pick up pia user created in Hass Users?

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍
