### ISSUE TITLE
deCONZ 6.4.0 breaks STD OTAU plugin?

### ISSUE THREAD

**Issue by scop** [home-assistant/hassio-addons#1620]
## The problem

After upgrading the deCONZ addon to 6.4.0, the STD OTAU plugin in the deCONZ app no longer seems to work. All devices are shown as vendor 0x0000 and image 0x0000, the query button does not appear to do anything, and assinging an OTAU file to a device and clicking update just brings the progress to "Paused".

This used to work with 6.3.0 and earlier as far back as I can remember. It's possible that I'm just impatient and the vendor and image ids get populated with a delay, will report back if that happens.

## Environment

- Add-on with the issue: deconz
- Add-on release with the issue: 6.4.0
- Last working add-on release (if known): 6.3.0
- Operating environment (OS/Supervised): HassOS 4.13, RPi 3B

## Traceback/Error logs

None found in docker logs. Any other place to check?

```txt

```

**Comment by scop** [comment]
Update: the info does populate eventually to the plugin view, but it appears to take a loooong time. Likely longer than it used to, but I cannot verify that. I also haven't been able to do any OTA updates with this version whereas with earlier I did several, nothing happens when clicking the update button. Firmware is correct, with an earlier version I did upgrade and downgrade the exact same thing (device+blob) I'm trying to upgrade now with the new version.

**Comment by scop** [comment]
Works, but is quite sluggish. Can't compare to an older version easily, and could be that I just misremember or something else has changed, so closing for now.

**Comment by frenck** [comment]
This is not something the add-on can do anything about. Please report this issue with dresden/deconz as the software this add-ons wraps, is created by them.

**Comment by scop** [comment]
If a newer deCONZ version breaks something, this add-on certainly **can** do something about it: revert back to an older version. Not necessary in this case though.

**Comment by frenck** [comment]
Reverting back break other things and for deCONZ, in most cases, not an option.
Please, report it with dresden, that is the most viable route to take.
