### ISSUE TITLE
vscode  Missing property "off_delay"

### ISSUE THREAD

**Issue by MYLE-01** [home-assistant/hassio-addons#1631]
getting this message in vscode
![image](https://user-images.githubusercontent.com/4362345/96503586-fb528c80-12af-11eb-9122-dade0909bf5d.png)

It has  **off** code shouldnt need to tell  about the off_delay

**Comment by frenck** [comment]
This is an upstream issue with the Home Assistant VSCode extension.

See: <https://github.com/keesschollaart81/vscode-home-assistant/pull/717>

Furthermore, this is not the issue tracker to report this in. This is the issue tracker for the core/official add-ons maintained by the Home Assistant project.
