### ISSUE TITLE
Binding ikea remote with ikea lamp

### ISSUE THREAD

**Issue by wes1993** [home-assistant/hassio-addons#1633]
## The problem

Hello, i'm trying to find a way fot binding the remote with light but i can't find how...
Did someone can help me? I'm Using homeassistant and deconz addon in hassio.
Best Regards
Stefano

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by wes1993** [comment]
Sorry for the bad creation of the issues :-(
thanks a lot for the link to the discord chat
Stefano :-D
