### ISSUE TITLE
Mosquitto Broker Add-On Typo

### ISSUE THREAD

**Issue by IIAIronWolf** [home-assistant/hassio-addons#1673]
## The problem

I believe the Mosquitto Broker Add-On contains a typo that is misleading to newbies. Towards the end of the setup section, it says 
``` 
To use the Mosquitto as a **broker**, go to the integration page and install the configuration with one click:

Navigate in your Home Assistant frontend to Configuration -> Integrations.
MQTT should appear as a discovered integration at the top of the page
Select it and check the box to enable MQTT discovery if desired, and hit submit. 
```

However, the integrations page Mosquitto is for the Mosquitto Client and not the Broker. 

mosquitto/DOCS.md

**Comment by frenck** [comment]
I'm confused, it is correct?

"To use the Mosquitto as a broker"

Tell this is about using the broker with Home Assistant and how to set that up, right?

**Comment by IIAIronWolf** [comment]
I'm not sure I fully understand your reply but:

The page I supplied the link for, is for the actual broker. However, in the readme for settling up Mosquitto broker, there is a line that tells you 'in order to use mosquitto as a broker' to go to the HA Integrations page and search for MQTT.
If you were to do that, you would actually be setting up the client and not the broker. The addon is the broker. 

So I think the addon instructions should say, "To use Mosquitto as a client" or something of that nature. The current directions would mislead a newbie to believe that going to the integrations page,and setting up MQTT that way, would create the MQTT broker for them. That is not true. To get the broker, you have to use the add-on. If you additionally want to use HA as an MQTT client, then you would go to the integrations page.

**Comment by frenck** [comment]
Yes, the add-on runs Mosquitto, that is a broker, which you can use with Home Assistant...

Mosquitto can also be used as a client, which is the other way around (and not want is meant here).

**Comment by IIAIronWolf** [comment]
I understand that the add-on is a broker. That is my point. The add on Readme says 'to use the Mosquitto as a broker' add the integration (NOT the add on). 
However, the only way to get the broker is to get the add on. 
So the add-on instruction should say:
'To use the mosquitto as a client' add the integration.

**Comment by IIAIronWolf** [comment]
It is confusing wording.

**Comment by frenck** [comment]
`To use the mosquitto as a client` no, as mosquitto is acting as a broker, not a client (it can do that too, but that isn't the use case).
