### ISSUE TITLE
jq: command not found when starting let's encrypt addon

### ISSUE THREAD

**Issue by mrtruebeliever** [home-assistant/hassio-addons#232]
Hi, in my logs I am seeing this error:

`starting version 3.2.4`
`/run.sh: line 8: jq: command not found`

Let's Encrypt has worked before on this machine.

**Comment by Gnaget2** [comment]
same here, installation was working fine before 2.x

**Comment by r-jordan** [comment]
The same in my installation of hassio. It ran correctly yesterday with the 1.2 version. 
In supervisor logs it complais about the challenge option:

> 18-01-17 08:38:48 WARNING (MainThread) [hassio.addons.validate] Unknown options challenge
> 18-01-17 08:38:48 WARNING (SyncWorker_13) [hassio.addons.validate] Unknown options challenge
> 

Now it doesn't start and it shows this log:

> starting version 3.2.4
> /run.sh: line 8: jq: command not found
> 

It seems that the jq command is not in the py2-future package.

**Comment by pvizeli** [comment]
solve with 2.2
