### ISSUE TITLE
Nginx: Increase server_names_hash_bucket_size

### ISSUE THREAD

**Issue by richardwiden** [home-assistant/hassio-addons#243]
When using "long" dns server name from for example duckdns nginx won't start and prints an error message:

`nginx: [emerg] could not build server_names_hash, you should increase server_names_hash_bucket_size: 32`

Setting `server_names_hash_bucket_size 32;` in the http part of nginx.conf should fix the issue.

Setting domain to `*.duckdns.org` works in the meantime.

`{
  "domain": "*.duckdns.org",
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}`

**Comment by pvizeli** [comment]
Can you  make a PR with requested changes?

**Comment by ciotlosm** [comment]
This used to be a problem on bestlibre nginx https://github.com/bestlibre/hassio-addons/issues/29
The fix there was: https://github.com/bestlibre/hassio-addons/commit/ed8a5c96c1867f3e53f404ba57df16aee0fe6167
