### ISSUE TITLE
Dnsmasq Front End Issue

### ISSUE THREAD

**Issue by Notrial** [home-assistant/hassio-addons#248]
I have a weird issue with Dnsmasq "Options" text field in the front end (Chrome latest version).
Whatever I try to fill in, when I click save, it doesn't save the values. It reports no error, but when I leave the tab and go back in my entry is replaced by the default one.
Syntax is correct, so it's not a typo, and save button it not grayed out.

**Comment by Notrial** [comment]
I still can't save configuration in the Config text box for some reason, no matter what I write in, when I click save and restart the plugin, it just reverts back to default values. I'm on latest version of Hass.io.

Any clues people?

**Comment by frenck** [comment]
Does the text in the box turn red?

**Comment by Notrial** [comment]
Nope the syntax is correct as far as I know...this is what I have:

```
{
  "defaults": [
    "8.8.8.8",
    "8.8.4.4"
  ],
  "forwards": ["xxx.duckdns.org"],
  "hosts": ["192.168.1.39"]
}
```

**Comment by pvizeli** [comment]
That is not correct. Do you look into documentation?

**Comment by Notrial** [comment]
OK, first of all I apologize since I really thought something was wrong with the editor itself.

When I copy/paste the default settings (like below) it accepts and saves. Although I'm really confused which values goes where in my case. I only have my HA IP address and duckdns URL and there are 4 settings in the default configuration that I have to fill in. Can someone help please, I don't think documentation explains it very well (not a network pro myself).

`{
  "defaults": ["8.8.8.8", "8.8.4.4"],
  "forwards": [
    {"domain": "mystuff.local", "server": "192.168.1.40"}
  ],
  "hosts": [
    {"host": "home.mydomain.io", "ip": "192.168.1.10"}
  ],
  "interface": "eth1"
}`
