### ISSUE TITLE
New snips addon build needed using snips 0.52.7

### ISSUE THREAD

**Issue by rychardeh** [home-assistant/hassio-addons#253]
Snips.ai now produces models with version 0.12.0.  Any attempt to use these with the current build of the snips addon results in model mismatch error and fails to run.  I did a local docker build of the snips addon using 0.52.7 and can confirm that it works as expected.  Obviously the bundled assistant.zip would need to be updated as well...

**Comment by pvizeli** [comment]
I can't update the `assistant.zip` - > @tschmidty69 ?

**Comment by tschmidty69** [comment]
Updated at this link https://github.com/tschmidty69/hassio-snips/releases/download/0.1-pre1/assistant.zip

**Comment by rolie31** [comment]
Hi,
I have the same issue, I updated my assistant.zip file yesterday and the nlu engine version is 0.13 now and that can't work with actual 0.9 snips hassio addon, that expect 0.12 nlu engine
How can I make it work ?
Regards
