### ISSUE TITLE
Mosquitto, missing ssl certs

### ISSUE THREAD

**Issue by andyinno** [home-assistant/hassio-addons#260]
I would like to configure mosquitto as bridge,
actually I can do that adding my configuration via the samba addon as stated in the configuration.

If the other mosquitto instance is running with ssl I am unable to connect to it because in the configuration file must be present the bridge_cafile configuration option.
Inspecting the addon I cannot find the /ssl/certs/ca-certificates.crt needed for this configuration.

My first attempt was 

> ln -s /etc/ssl/certs /resin-data/ssl/

in the hassio root but this is not optimal because it requires access to the underlying os.

Am I missing something about the ssl connection?
There is other routes?

I never tryed to work with the hassio addons, if it can be an interesting advance in the configuration I can try to help if someone can point me in the right direction.

Thank you
Andrea

**Comment by pvizeli** [comment]
ca-certificates should be inside container and can used like on a normal system. Otherwise you can make a PR and add this packages into add-on 👍

**Comment by andyinno** [comment]
Hi pvizeli,

thank you for your reply.
I am sorry, I found out that I mispelled the file name. Actually the cert data is in the correct place inside the container.

I have the bridge up and running right now.

For future reference, 
```connection home   
address mosquitto_hostname.com:port  
clientid client_name  
username the_username  
password the_difficult_password  
topic homeassistant/# out  
bridge_cafile /etc/ssl/certs/ca-certificates.crt  
```

allow me to connect to the remote mosquitto server.
username and password are the one setup on the remote server.
