### ISSUE TITLE
Clear Mosquitto retained messages?

### ISSUE THREAD

**Issue by Cabalist** [home-assistant/hassio-addons#262]
How do I clear the MosquittoDB?  I have quite a few messages retained in there from devices that no longer exist.  These are cluttering up my dashboard.  

I have already tried:
 - sending null length messages.  i.e.  `mosquitto_pub -h 10.50.50.77  -r -n  -t '/espurna/FurnacePump/energy -u <username> -P <password>`
 - Restarting mosquitto
 - uninstalling and reinstalling mosquitto
 - restarting hassio

I am at a loss since there is no ` /var/lib/mosquitto/mosquitto.db` to simply delete

I am left with a bunch of these:
<img width="436" alt="screen shot 2018-03-03 at 10 04 51 pm" src="https://user-images.githubusercontent.com/828557/36942736-f6810e56-1f2e-11e8-908e-6d9c24cb458a.png">

**Comment by pvizeli** [comment]
Copy the options. Remove/install the add-on agen and copy the options back.
