### ISSUE TITLE
letsencrypt port configuration

### ISSUE THREAD

**Issue by pho3nixf1re** [home-assistant/hassio-addons#263]
It appears that the Let's Encrypt addon cannot verify when the port is anything other than 80. This isn't practical since port 80 is often used by other services. The configured port needs to be added to the url. Is there a way to provide this value as part of the environment so it can be added in the run.sh script?

**Comment by pho3nixf1re** [comment]
Looks like the ACME protocol only supports port 80 and 443.

**Comment by pvizeli** [comment]
Yes and 443 was removed
