### ISSUE TITLE
Nginx does not pick up new certificate until restarted

### ISSUE THREAD

**Issue by frog32** [home-assistant/hassio-addons#266]
I am using duckdns with let's encrypt and the nginx addon. This week I had a problem that the in use certificate was outdated because I did not restart the nginx addon since a long time and it did not pick up the up to date certificate that was ready.

**Comment by andyinno** [comment]
It just happened to me too.
The main problem is that firefox does not allow you to display the page if the certificate is invalid.
I had to open chromium, then it displayed the invalid certificate and then I understood where was the issue.

A quick check on the duckdns addon displayed the updated certificate being correctly generated but not used.
A restart of the nginx addon was needed for the new certificate to being used.
