### ISSUE TITLE
[Feature request ssh]  private ssh key pair for root

### ISSUE THREAD

**Issue by kjellgren** [home-assistant/hassio-addons#269]
I want to git-push my config from hassio to external repo. Therefor I would like to able to configure public and private key for user root.

**Comment by carlba** [comment]
Yes agreed this would be usefull.

**Comment by frenck** [comment]
The Community SSH add-on supports the persistence of custom SSH keys (out of the box).

We could look into porting this part back into the core ssh add-on.
