### ISSUE TITLE
Incorrect cert expiry date in DuckDNS addon

### ISSUE THREAD

**Issue by rsokolowski** [home-assistant/hassio-addons#271]
Home Assistant release (hass --version):
0.65.5

Python release (python3 --version):
The one supplied with Hassio.

Component/platform:
DuckDNS version 1.2

Description of problem:
DuckDNS Addon fails to recognize that cert for my domain is expiring in less than 30 days, hence it is not refreshing it.

This is log from DuckDNS on restart:
starting version 3.2.4

```
INFO: Using main config file /data/workdir/config
Account already registered!
Sun Mar 25 21:33:35 CEST 2018: OK
NOCHANGE # INFO: Using main config file /data/workdir/config Unknown hook this_hookscript_is_broken__dehydrated_is_working_fine__please_ignore_unknown_hooks_in_your_script Processing <domain>.duckdns.org Unknown hook this_hookscript_is_broken__dehydrated_is_working_fine__please_ignore_unknown_hooks_in_your_script + Checking domain name(s) of existing cert... unchanged. + Checking expire date of existing cert... + Valid till Jun 22 17:50:27 2018 GMT (Longer than 30 days). Skipping renew! 
```

Config of DuckDNS:
```
{
"lets_encrypt": {
"accept_terms": true,
"certfile": "fullchain.pem",
"keyfile": "privkey.pem"
},
"token": ,
"domains": [
  <domain>.duckdns.org"
],
"seconds": 60
}
```

The SSL sensor correctly reports 29 days till expiry:
```
sensor.ssl_certificate_expiry | 29 | unit_of_measurement: days friendly_name: Dostęp SSL icon: mdi:certificate
-- | -- | --
```

Chrome (correctly) says that the cert for the UI (opened on the domain specified in the duckdns page) is valid till 2018-04-23.

Expected:
DuckDNS should referesh the cert since there are less than 30 days till expiry.

**Comment by rsokolowski** [comment]
I don't think this got fixed with the associated PR. I've updated to 1.3 DuckDNS and the addon still refuses to update cert due to incorrect expiry date considered.

**Comment by pvizeli** [comment]
@rsokolowski reboot home-assistant to load the new certs
