### ISSUE TITLE
Unable to add add-on repository. Doesn't show up in add-on store

### ISSUE THREAD

**Issue by msgowdara** [home-assistant/hassio-addons#282]
I've added the repository link. However, unable to add repository. Following is the log.

<\>18-04-22 02:41:01 INFO (MainThread) [hassio.addons.git] Clone addon https://github.com/home-assistant/hassio-addons repository
18-04-22 02:41:55 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/nginx_proxy/config.json
18-04-22 02:41:55 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/samba/config.json
18-04-22 02:41:55 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/configurator/config.json
18-04-22 02:41:55 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/google_assistant/config.json
18-04-22 02:41:55 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/cec_scan/config.json
18-04-22 02:41:55 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/rpc_shutdown/config.json
18-04-22 02:41:55 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/ssh/config.json
18-04-22 02:41:55 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/bluetooth_bcm43xx/config.json
18-04-22 02:41:55 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/git_pull/config.json
18-04-22 02:41:55 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/letsencrypt/config.json
18-04-22 02:41:55 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/mosquitto/config.json
18-04-22 02:41:55 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/dhcp_server/config.json
18-04-22 02:41:55 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/dnsmasq/config.json
18-04-22 02:41:55 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/snips/config.json
18-04-22 02:41:55 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/homematic/config.json
18-04-22 02:41:55 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/check_config/config.json
18-04-22 02:41:55 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/tellstick/config.json
18-04-22 02:41:55 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/mariadb/config.json
18-04-22 02:41:55 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/duckdns/config.json
18-04-22 02:41:55 WARNING (MainThread) [hassio.addons.data] Can't read repository information from /data/addons/git/e724ce20/repository.json
18-04-22 02:41:55 INFO (MainThread) [hassio.addons] Load addons: 14 all - 0 new - 0 remove<\>

**Comment by msgowdara** [comment]
Further log file shows this

cmdline: git pull -v origin
  stderr: 'fatal: index file smaller than expected'.
18-04-22 03:05:20 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/nginx_proxy/config.json
18-04-22 03:05:20 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/samba/config.json
18-04-22 03:05:20 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/configurator/config.json
18-04-22 03:05:20 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/google_assistant/config.json
18-04-22 03:05:20 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/cec_scan/config.json
18-04-22 03:05:20 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/rpc_shutdown/config.json
18-04-22 03:05:20 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/ssh/config.json
18-04-22 03:05:20 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/bluetooth_bcm43xx/config.json
18-04-22 03:05:20 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/git_pull/config.json
18-04-22 03:05:20 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/letsencrypt/config.json
18-04-22 03:05:20 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/mosquitto/config.json
18-04-22 03:05:21 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/dhcp_server/config.json
18-04-22 03:05:21 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/dnsmasq/config.json
18-04-22 03:05:21 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/snips/config.json
18-04-22 03:05:21 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/homematic/config.json
18-04-22 03:05:21 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/check_config/config.json
18-04-22 03:05:21 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/tellstick/config.json
18-04-22 03:05:21 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/mariadb/config.json
18-04-22 03:05:21 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/core/duckdns/config.json
18-04-22 03:05:21 WARNING (MainThread) [hassio.addons.data] Can't read repository information from /data/addons/git/e724ce20/repository.json
18-04-22 03:05:21 INFO (MainThread) [hassio.addons] Load addons: 14 all - 0 new - 0 remove

**Comment by pvizeli** [comment]
Do you try to run hass.io without root privileged?

**Comment by boaschti** [comment]
I have the same problem with hassio image 2.5 and the built in addon path: https://github.com/hassio-addons/repository

**Comment by boaschti** [comment]
I have the same problem with hassio image 2.5 and the built in addon path: https://github.com/hassio-addons/repository

**Comment by boaschti** [comment]
I have the same problem with hassio image 2.5 and the built in addon path: https://github.com/hassio-addons/repository
