### ISSUE TITLE
[Feature Request] Support for ddclient and custom DNS service

### ISSUE THREAD

**Issue by gabrielboliveira** [home-assistant/hassio-addons#286]
Hello! I have an add-on suggestion. 

Similar to the DuckDNS add-on, it would be great to update custom DNS domains on some service such as Cloudflare, Google Domains, etc.

[ddclient](https://github.com/ddclient/ddclient) supports a big list of supported services (DuckDNS included).

Usage example: I have my own personal domain `my-domain.com` and want to create one sub-domain for my rpi installation at home and another one for work. So I can create `home.my-domain.com` and `work.my-domain.com`. Assuming that I'm already using Cloudflare for my main domain, I can update the sub-domain with ddclient directly into Cloudflare.

Possible related PR: #277

**Comment by balloob** [comment]
This is a great feature suggestion but not something that we should implement in our official repository.
