### ISSUE TITLE
Google Assistant 1.0 Hassio problem

### ISSUE THREAD

**Issue by Macdave78** [home-assistant/hassio-addons#288]
hello, I just updated the google assistant addon on hassio, and to my surprise I find this:Traceback (most recent call last):
  File "/hassio_gassistant.py", line 30, in <module>
    with Assistant(credentials) as assistant:
TypeError: init() missing 1 required positional argument: 'device_model_id'

I removed everything and installed again but it gives me this error

Traceback (most recent call last):
  File "/hassio_oauth.py", line 6, in <module>
    import cherrypy
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/__init__.py", line 73, in <module>
    from ._cptools import default_toolbox as tools, Tool
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/_cptools.py", line 33, in <module>
    from cherrypy.lib import auth_basic, auth_digest
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/lib/auth_digest.py", line 26, in <module>
    from six.moves.urllib.parse import unquote_to_bytes
ImportError: cannot import name 'unquote_to_bytes'

**Comment by daanvc** [comment]
I've updated today and encoutered the same problem.
googling this error led me to this link:
https://forum.magicmirror.builders/topic/5809/possible-issue-mmm-googleassistant-with-recent-google-assistant-sdk-update

**Comment by dpeter99** [comment]
https://github.com/dpeter99/hassio-addons/commit/2ee57b89843b66c6bb6cb1df84ceb873774c6195
I think this change should work... But i can't get it to run as a Local addon
```
[FATAL tini (9)] exec /run.sh failed: No such file or directory
```
This is the error i get after a really long build process

**Comment by pvizeli** [comment]
Fix with last update. thanks @dpeter99
