### ISSUE TITLE
SSH hardening

### ISSUE THREAD

**Issue by fabaff** [home-assistant/hassio-addons#301]
In an [issue](https://github.com/home-assistant/hassio/issues/470) was mentioned that the SSH daemon for the debugging is using obsolete settings.

- Disable weak MAC algorithms
- Disable weak ciphers and modes

I would like to suggest that the SSH Add-on is set to more strict settings in regard of algorithms, ciphers and allowed modes.

**Comment by frenck** [comment]
I have those in the Community Version of the add-on, nevertheless, I do offer an option to fall back to older / the default set of ciphers and algorithms. The main reasoning for this is, is that most clients on mobile devices do not support the actual secure/newer algorithms.

Nevertheless, I've disabled the weak ones by default.
