### ISSUE TITLE
 404 Client Error

### ISSUE THREAD

**Issue by sgong4** [home-assistant/hassio-addons#307]
i try to install samba,but i don't work. i check the system log : samba can't install. what should i do to fix the problem. thanks.

[hassio.docker.interface] Can't install homeassistant/armhf-addon-samba:3.0 -> 404 Client Error: Not Found ("no such image: homeassistant/armhf-addon-samba:3.0: No such image: homeassistant/armhf-addon-samba:3.0").

**Comment by tjorim** [comment]
Is this still an isssue?
The tag is showing up and there have been several new releases since then.
Another possible cause is the lack of space on your SD Card.
Please check and close this issue if possible.
