### ISSUE TITLE
Split this repository in 2

### ISSUE THREAD

**Issue by balloob** [home-assistant/hassio-addons#312]
I think that we should limit the official repository to only the addons that are really useful for a broad audience and related to making Home Assistant more useful. A bunch of these add-ons are cool to run on your server (DNS, DHCP, Nginx proxy), but are just not Home Automation specific enough.

Here are the add-ons that I would suggest to move out of the official add-on repo:

 - `cec_scan`. Too niche of an add-on
 - `custom_deps`. Too dangerous to be in default repo. This is one of those add-ons that people first get a use case, than want to find the add-on.
 - `dhcp_server`. Very small use case. Also has danger of people breaking their network.
 - `dnsmasq`. I think pretty niche use case
 - `letsencrypt`. People can achieve this using DuckDNS + Let's Encrypt. By having a standalone add-on, it becomes confusing.
 - `nginx_proxy`. Not home automation specific
 - rpc_shutdown`. Too niche use case.

Having too many add-ons means that the user is getting overwhelmed and will be unable to find the add-ons that it probably needs. (not seeing the forrest through the trees)

**Comment by frenck** [comment]
@balloob I'm willing to adopt those into the Community add-ons.

**Comment by balloob** [comment]
I honestly am not sure either if Community add-ons is the right place for some of these ? I think that some of these would hardly have users and thus distract from the useful add-ons. I would almost do some "Advanced" repo (either under official or under community or just a personal account).

**Comment by frenck** [comment]
I agree... Some of these I would actually adopt like `letsencrypt`, since I rely on it myself.

Some I would archive (`custom_deps`).

`dhcp_server` and `dnsmasq` are actually covered by the `pi-hole` add-on.

**Comment by ryanm101** [comment]
I do agree with @balloob that some of the addons in communtiy are niche / advanced use case. 

Is it possible to have a "default" repo that is enabled and useable by default, but also have the advanced repo added to HA by default in a disabled / hidden state but enabled by a button / config option for more advanced users.

Better might be to have "tags" where we only show default addons unless advanced tags are enabled then we could have a single official repo.

**Comment by ciotlosm** [comment]
basic or core addons could have different design in the UI and be sorted first to be found easier.
