### ISSUE TITLE
Security policy for official add-ons

### ISSUE THREAD

**Issue by balloob** [home-assistant/hassio-addons#313]
I would like to propose a security policy for official add-ons:

All add-ons that can be user protected should:

 - Be protected with a default subnet mask limiting connections to local networks
 - If they can write config, should not have a guest mode at all and should not start without a username/password defined.

What do you think?

**Comment by fabaff** [comment]
Beside that we should also address the low hanging fruits in regard of common service hardening (like mentioned in #301). Most of them are easy to fix or to set (same as we do for HTTP with following Mozilla's Operations Security team recommendations for Server side SSL/TLS settings).

**Comment by frenck** [comment]
> "Be protected with a default subnet mask limiting connections to local networks" 

Can't we get Hass.io to provide this on an Hassio level? Like setting ports?
When we do this, we instantly give the user control over this for every add-on there is.

**Comment by balloob** [comment]
Maybe do both? Because at some point _some_ add-on will come along that will ask users to disable it, and they are insecure again.
