### ISSUE TITLE
Duck DNS ERROR: Challenge is invalid! (returned: invalid)

### ISSUE THREAD

**Issue by macrojames** [home-assistant/hassio-addons#316]
I had trouble renewing my cert with 3 SAN.

The hooks.sh loops 3 times through "deploy_challenge" for all domains butt different tokens. Therefore the 3rd call sets 2 wrong TXT records and 1 correct.
I exchanged $DOMAINS with $2 in deploy_challenge and clean_challenge to get it working again.

I am not sure which tool or API changed because it had been working on 12th of April the last time.
I think it is related to https://github.com/lukas2511/dehydrated/releases/tag/v0.6.0

> Challenge validation loop has been modified to loop over authorization identifiers instead of altnames (ACMEv2 + wildcard support)

**Comment by pvizeli** [comment]
Can you provide a PR for this?

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassio-addons/pull/325
