### ISSUE TITLE
Cert expiry date does not match what browser sees in DuckDNS addon

### ISSUE THREAD

**Issue by Petro31** [home-assistant/hassio-addons#317]
The addon claims my cert is up to date, expiring in 3 months.  When attempting to access the ddns domain, the resulting cert claims it expired yesterday.  There is no way to update the cert because the addon think's it's up to date.  I had to create a new ddns domain to get around this issue.  New domain works fine after a new cert was created.

**Comment by perwramdemark** [comment]
+ Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Aug 13 21:09:19 2018 GMT (Longer than 30 days). Skipping renew!

I got the same issue.

**Comment by pvizeli** [comment]
After you renew the certificate, you need restart home-assistant or other add-ons they use this certificate. They load the certificate on startup and use it until you restart it. Can you confirm this?

You can also copy the options and reinstall the add-on to reset the data.

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassio-addons/pull/325

**Comment by perwramdemark** [comment]
Strange, restart didn't solve this. 
However removing duckdns addon reinstalling it and then updating did update the certificate.

**Comment by Petro31** [comment]
I restarted a handful of times during this process.  Never uninstalled or reinstalled DDNS addon.  That's why I wrote the PR up.
