### ISSUE TITLE
Snips: Support for personal wake word [Feature Request]

### ISSUE THREAD

**Issue by andreasjacobsen93** [home-assistant/hassio-addons#318]
I would like to request the personal wake word feature for hass.io.
I don't know if it's possible with the current state of hass.io, but it would be a nice addition.

A possible solutions could be to create and train the wake word on another computer, and upload the files to the share folder.

**Comment by Phil1988** [comment]
+1 for this, as the "normal way" doesnt work (https://snips.gitbook.io/documentation/advanced-configuration/wakeword/personal-wakeword)

**Comment by tschmidty69** [comment]
I'll poke at this when I get a chance. It would almost certainly need to be from a recording on a second pc since I don't see a good way to make a UI for this for hassio.

**Comment by andreasjacobsen93** [comment]
@tschmidty69 Hey, did you get some time to look at this?

**Comment by spencer-scott** [comment]
I would also be interested in this feature as well.
