### ISSUE TITLE
Duck DNS setup ( Curl returned with 6)

### ISSUE THREAD

**Issue by Minerdog123** [home-assistant/hassio-addons#320]
Hello, I am not sure if I have the right thread for this, but I figure that I have to start somewhere so here goes. I have been trying to setup the DUck DNS addon for a couple of weeks now and have the remote access working fine except it is not https. When I check the logs for the DuckDNS platform, I see this message
`ERROR: Problem connecting to server (get for https://acme-v02.api.letsencrypt.org/directory; curl returned with 6)`
I have tried uninstalling and reinstalling the addon several times now to no avail. Any help would be much appreciated.

**Comment by pvizeli** [comment]
Should fix with new version

**Comment by angel12** [comment]
If you were referring to version 1.5, it is still not fixed, at least for me.

**Comment by Minerdog123** [comment]
I just fixed it not with the update but by going in and changing the DNS server manually on Ubuntu. For some reason even if the network manager settings are correct, it does not work correctly. I have attached a link to the guide that I used, and it worked perfectly for me. Though now I have errors elsewhere, but one problem at a time I guess.

https://pchelp.ricmedia.com/set-custom-dns-servers-linux-network-manager-resolv-conf/

**Comment by jasonehines** [comment]
I fixed this by using Portainer to change the containers network to host.

**Comment by konrness** [comment]
I confirmed this is also happening with me. 

Hass.io installed via Docker on Ubuntu 18.04 as per https://www.home-assistant.io/hassio/installation/#alternative-install-on-generic-linux-server 

I tried reproducing the issue where curl returns 6 with this command, but that was actually successful:
```
$ docker run --rm homeassistant/amd64-addon-duckdns:latest apk add --no-cache curl && curl -A "dehydrated/git-master-after-0.6.2 curl/7.58.0" -L -s "https://acme-v02.api.letsencrypt.org/directory"
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
OK: 20 MiB in 26 packages
{
  "Tx7Uu588NhA": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
```

If I change any of my host or Docker DNS settings to fix this, as described above, it seems to prevent other components (e.g. Home Assistant Cloud and yr) from accessing external hosts. Is it an issue specific to how the Docker container is run for this add-on?

**Comment by pvizeli** [comment]
The problem is, that ubuntu (generic) use systemd resolver and docker have actual a bug they will be fix with next version.
