### ISSUE TITLE
Update Mosquitto add-on

### ISSUE THREAD

**Issue by tjorim** [home-assistant/hassio-addons#338]
The official Mosquitto MQTT broker is still based on version 1.4.12.
There has been some releases addressing mostly security vulnerabilities (up to 1.4.15).
Also a 1.5 features release which "brings a host of changes to the broker, including performance improvements and [...] numerous bug fixes".

**Comment by pvizeli** [comment]
Please make a PR 👍 / If alpine 3.8 is out for docker, we update it anyway but not before. But if you provide a PR i will merge it.
