### ISSUE TITLE
Bluetooth BCM43xx Won't Init

### ISSUE THREAD

**Issue by justarandomgeek** [home-assistant/hassio-addons#359]
I have a brand new RPi 3 B+ that i just got out of the box yesterday and put Hass.IO on. I installed the Bluetooth BCM43xx add-on to try to enable bluetooth device tracking, but it always fails with the following messages:

    bcm43xx_init
    Failed to write reset command
    Can't initialize device: No error information

I've googled around this and found various references to running commands with `hciattach` or `hciconfig`, but as far as i can tell those commands aren't available. 

The documentation around this module is rather abysmal, what am i doing wrong? :)

Bluetooth 2.3
Supervisor 115
Hass os 1.7

**Comment by danielsjf** [comment]
The addon is not required anymore in Hass os. However, it currently also doesn't work for me. There is a pairing gui in the pipeline.

**Comment by danielsjf** [comment]
https://github.com/home-assistant/hassos/issues/52

**Comment by justarandomgeek** [comment]
I had found that thread, but it has different error messages and had no clear resolution.

So you're saying that i should remove the add-on module and that one day maybe bluetooth will "just work" with an update or something? There's nothing I can do in the mean time?

**Comment by danielsjf** [comment]
home-assistant/hassio-addons#340

**Comment by justarandomgeek** [comment]
I'd found that one also, and again it has different error messages. I'd missed the conclusion on it though.

Pairing? I thought this was for passively observing nearby bluetooth devices...

In any case, I don't even see any acknowledgement in Hassio that it *has* a bluetooth radio, which seems a few steps before pairing/scanning...

**Comment by treos33** [comment]
I ran into this issue last night while testing a new install of Hass.io. I installed the Bluetooth BCM43xx add-on and immediately ran into trouble. Even after disabling the add-on I was still seeing the following in the log when restarting HA:

> 2018-07-24 22:42:29 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform bluetooth_tracker
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/bluetooth/bluez.py", line 31, in discover_devices
    lookup_class=lookup_class, device_id=device_id)
_bluetooth.error: (110, 'Operation timed out')

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/device_tracker/__init__.py", line 183, in async_setup_platform
    disc_info)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/device_tracker/bluetooth_tracker.py", line 72, in setup_scanner
    for dev in discover_devices():
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/device_tracker/bluetooth_tracker.py", line 50, in discover_devices
    lookup_class=False)
  File "/usr/local/lib/python3.6/site-packages/bluetooth/bluez.py", line 34, in discover_devices
    raise BluetoothError ("error communicating with local "
bluetooth.btcommon.BluetoothError: error communicating with local bluetooth adapter

I was able to get bluetooth working by restarting the host with the add-on uninstalled. Once I activate the bluetooth tracker things started appearing in the known_devices file. It seems bluetooth is integrated into the current Hass.io built on HassOS, it is just terribly documented.

**Comment by justarandomgeek** [comment]
So it's built in but there's no UI at all for it? Great, i guess i'll dig around and try to find more of this undocumented magic... :(

**Comment by justarandomgeek** [comment]
Well, I disabled the add-on, and poked around a bit and nothing had apparently happened at the time, but I've just check again now and it's found my phone now! I guess it's working after all!

**Comment by LeroyZanzibar** [comment]
@justarandomgeek when you say it found your phone, where did you see that? I uninstalled the addon and rebooted my RPi 3 B+. I don't see my phone showing up on the homepage and I don't see it in the devices list. I also do not have a known_devices file for some reason...

**Comment by justarandomgeek** [comment]
A state bubble appeared for it on the (unconfigured, i'm using lovelace) /states view in the sea of them at the top. Not sure if it ever got into known_devices.

**Comment by LeroyZanzibar** [comment]
Thanks for the reply. I figured it out. I started from scratch recently and forgot to add device_tracker into my config file.
