### ISSUE TITLE
Configurator: Not able to fetch entities

### ISSUE THREAD

**Issue by hktomy** [home-assistant/hassio-addons#367]
Hi,

I've recently setup an new instance of hass.io and installed the configurator add-on (version 1.0). Initially I was able to fetch my entities, reload automation etc. However, once I enabled the api_password in the configuration.yaml, it doens't work anymore. By commenting out the api_password it worked again.
This hasn't been an issue when using the previous version (0.4). By looking at the previous commit history "Update to Configurator 0.3.1 (#357)", it looked like the configurator/map.py was removed. Not sure if this is the reason?

The error I found in the configurator were:
INFO:  - "GET / HTTP/1.1" 200 -
WARNING: __main__:Exception getting bootstrap
WARNING:__main__:HTTP Error 502: Bad Gateway

Here is the configuration I am using:

**configuration.yaml:**
http:
  api_password: my_password
  base_url: https://myaddress.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

**config in the configurator:**
{
  "username": my_username,
  "password": my_password,
  "ssl": true,
  "certfile": "ssl/fullchain.pem",
  "keyfile": "ssl/privkey.pem",
  "allowed_networks": [
    "0.0.0.0/0"
  ],
  "banned_ips": [
    "8.8.8.8"
  ],
  "banlimit": 0,
  "ignore_pattern": [
    "__pycache__"
  ],
  "dirsfirst": false,
  "enforce_basepath": false,
  "notify_service": "persistent_notification.create"
}

**Comment by pvizeli** [comment]
Need supervisor logs

**Comment by hktomy** [comment]
I've just did the some trials and found that it should be related to the hassio version instead. I downgraded hassio from 0.75.1 to 0.74.2 and everything just worked perfectly. Then I upgraded again to 0.75.2 and it has no issue too. Thanks a lot!
