### ISSUE TITLE
Update mosquitto

### ISSUE THREAD

**Issue by ezar** [home-assistant/hassio-addons#369]
Please update mosquitto to 1.5 release! 1.5 - 20180502
https://mosquitto.org/ChangeLog.txt

**Comment by SittingDuc** [comment]
Seconded. Any good online references for docker + hassio that I could read to learn how to start doing something like upgrading mosquitto?
(I want the work done, I know how to type on a keyboard, maybe I can do the work?)

**Comment by SittingDuc** [comment]
Poking around at random, it seems hass.io docker pulls from a base image using alpine linux. the "edge" version of this has mosquitto 1.5.3 available. 
So if it is possible to make hass.io docker pull from alpine linux "edge", probably with a customised build.json and maybe a new hub.docker BUILD_FROM, then it might be possible to get mosquitto 1.5.3 into hass.io.
