### ISSUE TITLE
Addon: Git Pull

### ISSUE THREAD

**Issue by finish06** [home-assistant/hassio-addons#371]
All other containers are able to resolve appropriately.

```
fatal: unable to access 'https://github.com/finish06/home-assistant-config.git/': Could not resolve host: github.com
[Error] Git pull failed
```

**Comment by finish06** [comment]
I was able to correct this DNS issue by placing the following in `/etc/docker/daemon.json` on a Debian based system:
```
{
  "dns": ["192.168.1.1", "8.8.8.8", "8.8.4.4"]
}
```

**Comment by YuyQuan** [comment]
I was having lots of troubles getting past the preparing splash screen on my hassio install It would load indefinitely. I tried using a RPi 3B + etcher on wired connection, I tried using the VMDK. Lastly, I tried using ubuntu + docker-ce. After reading the docker logs and googling my way here, this was the fix. Though, I had to switch my gateway to point to my router, of course.  I made a PSA on reddit.
