### ISSUE TITLE
Addon not starting anymore

### ISSUE THREAD

**Issue by Sholofly** [home-assistant/hassio-addons#373]
Hi,

Since a reboot a few weeks ago my Duck DNS addon is not starting anymore.
No specific actions are taken that can cause the error ( i guess). Log section is empty.
I can still connect with my duckDns domain but https is unsafe due to a expired certificate.

Config:
```
{
  "lets_encrypt": {
    "accept_terms": true,
    "certfile": "fullchain.pem",
    "keyfile": "privkey.pem"
  },
  "token": "<hidden>",
  "domains": [
    "<hidden>.duckdns.org"
  ],
  "seconds": 300
}
```

running:
hassio 0.75.3
duckdns: 1.5

Errors during attempts to fix/update ( not sure if useful) :

> 18-08-13 20:50:24 ERROR (SyncWorker_0) [hassio.docker] Can't create container from addon_core_duckdns: 409 Client Error: Conflict ("Conflict. The container name "/addon_core_duckdns" is already in use by container "f0811c656fffbfeb395fd1dbf1ee7b194024355e7871dc1a4e7226bc67f1cd28". You have to remove (or rename) that container to be able to reuse that name.")
> 
> 18-08-13 20:52:26 WARNING (SyncWorker_6) [hassio.docker.interface] Can't grap logs from homeassistant/armhf-addon-duckdns: 500 Server Error: Internal Server Error ("can not get logs from container which is dead or marked for removal")

Is it a bug, or is there a way to fix it?

**Comment by pvizeli** [comment]
Can you give more details about your setup. What do you do for reach that?

You should be able to reinstall the add-on, after that it should work again.

**Comment by Sholofly** [comment]
Hi, pvizeli,
Thanks for your reply.
I'm running the version mentioned above on a rpi 2
I've installed multiple add-ons wich are all disabled except mosquito and samba. Both the latest version.
I didn't  take any specific actions to come to this result. After a regular reboot the add on didn't start. When I push the start button it flashes red. The log section stays blank. Even disabling let's encrypt doesn't work.
I also tried to reinstall but it gave me the same result.
Do you need to know more? I'm happy to share..

**Comment by pvizeli** [comment]
I have a idea

**Comment by Sholofly** [comment]
Tell me more!

**Comment by tjorim** [comment]
Is this issue still occurring or can it be closed?

**Comment by Sholofly** [comment]
Sorry, missed this one. Not using the addon anymore.
