### ISSUE TITLE
git_pull always repeats regardless of the value of repeat.active

### ISSUE THREAD

**Issue by zybron** [home-assistant/hassio-addons#375]
I have tried using

`"repeat": {
    "active": false,
    "interval": 5
  }`

and 

`"repeat": {
    "active": "false",
    "interval": 5
  }`

Both yield the same result in that the script continues to repeat every interval seconds. I cannot save a valid config without a value for repeat.active and repeat.interval so if the script is just checking to see if repeat.active has a value, I think it would cause this behavior.

**Comment by Censored3** [comment]
@zybron: this issue was fixed by my pull request as referenced. Can you test again?

Mind you there is a new bug in git_pull rendering the add-on inoperable; best to wait for v6.1 until my fix PR is approved.

Can you close the issue if it's okay?

**Comment by zybron** [comment]
Yes, sorry, I should have closed this long ago. It has been working for me since your PR was merged.
