### ISSUE TITLE
Duck DNS addon and letsencrypt with custom domain

### ISSUE THREAD

**Issue by SquareBeard** [home-assistant/hassio-addons#392]
Hello, I added a CNAME record to point to the duckdns url and the challenge validation for the custom domain fails.
I believe this is because the addon is using DNS challenge validation and you can't add the TXT record for the custom domain into Duck DNS.

Is there a way to use the Duck DNS addon and letsencrypt with a custom domain name ?

**Comment by pueue** [comment]
Currently, DuckDNS addon does not support custom domain. But there is a way what I did.

1. Keep DuckDNS addon config for '*.duckdns.org' ssl certificate.
2. Install Let's encrypt addon.
3. Set domains and change `certfile` and `keyfile` names like `"custom-*.pem"` in let's encrypt addon config.
4. Change all `certfile` and `keyfile` configs on hass.io to `"custom-*.pem"` except DuckDNS addon.

**Comment by frenck** [comment]
@pueue 👍 

Closing this issue, since this is a limitation outside of our control.
