### ISSUE TITLE
nginx_proxy/*.conf and nginx_proxy_default*.conf do not appear in Samba 'Share' folder

### ISSUE THREAD

**Issue by CodebyADHawk** [home-assistant/hassio-addons#393]
I have configured the Nginx SSL/TLS Proxy add-on with:

"customize": {
    "active": true,
    "default": "nginx_proxy_default*.conf",
    "servers": "nginx_proxy/*.conf"
  }

Nonetheless, the config files do not appear in the Samba folder 'Share' as prescribed here:

https://www.home-assistant.io/addons/nginx_proxy/

I have tried stopping and restarting the server, and even uninstalling and reinstalling the entire add-on, but I cannot locate the conf files to edit them.

My ultimate goal is to add a location to Nginx as described here:

https://www.home-assistant.io/components/notify.html5/

to support HTML5 notifications, which I have already added to my config, GCM, and Firebase.

Thanks.

**Comment by frenck** [comment]
They do not exist.
You can create them in case you'd like...
