### ISSUE TITLE
Feature Request - Lets Encrypt

### ISSUE THREAD

**Issue by asdf1nit** [home-assistant/hassio-addons#397]
Ability to use DNS txt record for domain validation.

My ISP blocks port 80 and 25. I've requested that they open port 80 for me a few times but I've always gotten the same answer... No, it's against policy.

**Comment by frenck** [comment]
Could you please clarify a little more?
- Please make the title of the issue more descriptive.
- What add-on are we talking about here?

**Comment by asdf1nit** [comment]
Sorry I never saw a reply until I got a message from the stale bot.

The request was for the let's encrypt add on. I have my own domain but my home ISP provider blocks port 80 so I can't get a cert with it. If there was an option for doing validation through DNS txt records, this should solve the problem for me and many users who don't want to use the duckDNS, but can't get valid cert's through the LE add on because of blocked ports.

**Comment by hacker1024** [comment]
Can we re-open this? Blocking port 80 is quite common.
