### ISSUE TITLE
Addon listen on Multicast address

### ISSUE THREAD

**Issue by xsimek20** [home-assistant/hassio-addons#401]
Hi I'm not sure If this is correct place for my question but I was not able find better place.

I want to create addon for Shelly Device (http://shelly-api-docs.shelly.cloud/#coap), which will be listening on multicast address `224.0.1.187` (COAP protocol https://www.iana.org/assignments/multicast-addresses/multicast-addresses.xhtml). 
Shelly Docker container need to be run with parameters --net=host `docker run -v $PWD/data:/data --net=host shelly-coap`. If parameter `--net` is set to default (bridge) multicast package can not be transfer inside container (for example https://github.com/hazelcast/hazelcast-docker/issues/39 )

Is it posible to create addon with spefic run arguments or do you know other methods how addon can receive multicast packages?

thank you for your answer

**Comment by pvizeli** [comment]
I see no reason why you not should be able to run a add-on on host network: https://developers.home-assistant.io/docs/en/hassio_addon_config.html#add-on-config

**Comment by xsimek20** [comment]
thank you I completely overlook argument `host_network`
