### ISSUE TITLE
Mosquitto can't connect to Home Assistant

### ISSUE THREAD

**Issue by heytcass** [home-assistant/hassio-addons#402]
Just set up the Mosquitto add-on with the following config:
~~~~
{
  "plain": true,
  "plain_websockets": true,
  "ssl": true,
  "ssl_websockets": true,
  "anonymous": false,
  "logins": [
    {
      "username": "user",
      "password": "pass"
    }
  ],
  "customize": {
    "active": false,
    "folder": "mosquitto"
  },
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
} 
~~~~

Corresponding Home Assistant config is as follows:
``` 
mqtt:
  broker: core-mosquitto
  username: user
  password: pass 
```

My MQTT BRUH node's serial connection shows a successful connection to the MQTT broker and reporting information, but as soon as that happens, the Home Assistant logs show: `Disconnected from MQTT (1). Trying to reconnect in 1 s` every second and Mosquitto add-on's log shows `Socket error on client <unknown>, disconnecting.` The same errors show up if I restart Mosquitto with my sensor set up in configuration.yaml, but without the BRUH node plugged in.

I've tried every combination of true/false I can in the Mosquitto add-on config, same result every time.

**Comment by deylin** [comment]
@heytcass, Having the same issue with a similar configuration! Getting:
New connection from #.#.#.# on port 1883.
Socket error on client <unknown>, disconnecting.

Did you find a solution??

**Comment by cyrenaud** [comment]
I'm having the same issue. Did anyone find a solution?

**Comment by manny199** [comment]
Some problem, have you solved?
