### ISSUE TITLE
Xiaomi Gateway - Human Body Sensor Light Sensitivity Support

### ISSUE THREAD

**Issue by theunreal** [home-assistant/hassio-addons#404]
Hi,
By looking at the [Xiaomi Gateway component page](https://www.home-assistant.io/components/xiaomi_aqara/), There is "Motion Sensor" which refers to Xiaomi Human Body sensor. **(Model: RTCGQ11LM)** This sensor includes a light intensity sensor, but I can't find any way/documentation to get this data using the HA Xiaomi Gateway component.

Using the light intensity sensor along with the motion sensor could be great to turn on/off lights based on motion and light intensity in the room.
product image: http://ae01.alicdn.com/kf/HTB1v1q5jDnI8KJjSszbq6z4KFXaQ.jpg

I noticed the [Xiaomi Binary Sensor](https://github.com/home-assistant/hassio-addons/issues/404#issue-359432123) page, and wonder if this is the way to get data from the sensors connected to Xiaomi Gateway, but I couldn't find the light intensity sensor of the xiaomi human body sensor.

Is it possible to add a proper documentation about this sensor and how to get the data from each sensor?

**Comment by frenck** [comment]
Hi @theunreal,

This is a question about a Home Assistant component and therefore not related to an Hassio Add-on. 

I use the Xiaomi gateway and those sensors myself and the Lux is getting reported straight of the box. If you are still experiencing problems I would recommend to go into the Home Assistant Discord or the Community forums for support. GitHub issues are for tracking bugs, not support questions.
