### ISSUE TITLE
DuckDNS addon is not updating the SSL certificate properly

### ISSUE THREAD

**Issue by mattclar** [home-assistant/hassio-addons#409]
I have an invalid SSL certificate as it has expired. 
When I looked into it it seems that it hasn't been updated since I started this all in June and now 3 months later has expired!
I have tried everything I can think of
- Deleted certificates from SSL folder
- reconfigured permissions of SSL folder
- Deleted hassio and reinstalled from scratch with restore from snapshot

But STILL  when I restart the duckdns addon i get this message:

```
# INFO: Using main config file /data/workdir/config
 + Account already registered!
 Thu Sep 20 22:18:18 AEST 2018: KO
 # INFO: Using main config file /data/workdir/config
 Processing arthurst.duckdns.org
  + Checking domain name(s) of existing cert... unchanged.
  + Checking expire date of existing cert...
  + Valid till Nov 13 23:32:58 2018 GMT (Longer than 30 days). Skipping renew!
 Thu Sep 20 22:23:23 AEST 2018: KO

```
But the SSL certificate served expired last week!

**Comment by blackgold9** [comment]
Same issue.

**Comment by mattclar** [comment]
any luck resolving this @blackgold9

**Comment by itsmeltc** [comment]
I don't have a fix, but I have a workaround: Create another subdomain and add it to the domains array in the DuckDNS config, e.g.

```
{
  "lets_encrypt": {
    "accept_terms": true,
    "certfile": "fullchain.pem",
    "keyfile": "privkey.pem"
  },
  "token": "x",
  "domains": [
    "x.duckdns.org",
    "x2.duckdns.org"
  ],
  "seconds": 300
}
```

This will force the cert to renew the next time you restart the DuckDNS service.

**Comment by mattclar** [comment]
Still having issues: 
`# INFO: Using main config file /data/workdir/config
+ Account already registered!
Wed Oct 10 22:03:12 AEDT 2018: KO
# INFO: Using main config file /data/workdir/config
Processing arthurst.duckdns.org with alternative names: 20arthurst.duckdns.org
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 2 authorizations URLs from the CA
 + Handling authorization for 20arthurst.duckdns.org
 + Handling authorization for arthurst.duckdns.org
 + 2 pending challenge(s)
 + Deploying challenge tokens...
KOKO + Responding to challenge for 20arthurst.duckdns.org authorization...
 + Cleaning challenge tokens...
KOKO + Challenge validation has failed :(
ERROR: Challenge is invalid! (returned: invalid) (result: {
  "type": "dns-01",
  "status": "invalid",
  "error": {
    "type": "urn:ietf:params:acme:error:dns",
    "detail": "DNS problem: NXDOMAIN looking up TXT for _acme-challenge.20arthurst.duckdns.org",
    "status": 400
  },
  "url": "https://acme-v02.api.letsencrypt.org/acme/challenge/AT9eT_6Si_mThzN04hE3bJrn7-rVXvh2_92rxQh1qTA/8139855288",
  "token": "nCguX9mWtTO5Z-5PnOKa9PAgfqA3XvoU07NmPTBnY_c"
})`

**Comment by dj21d** [comment]
I'm having a similar issue. I'm trying to add a 2nd subdomain to my config (non DuckDNS) but it cannot pass the challenge portion. It does a DNS check, fails because my DNS record is different than what it expects. I've gone and changed the record to the new token but it never rechecks. Any suggestions?

My output is very similar to mattclar except my duckdns cert will renew without issue

**Comment by nickdaria** [comment]
> Still having issues:
> 
> ```
> # INFO: Using main config file /data/workdir/config
> + Account already registered!
> Wed Oct 10 22:03:12 AEDT 2018: KO
> # INFO: Using main config file /data/workdir/config
> Processing arthurst.duckdns.org with alternative names: 20arthurst.duckdns.org
>  + Signing domains...
>  + Generating private key...
>  + Generating signing request...
>  + Requesting new certificate order from CA...
>  + Received 2 authorizations URLs from the CA
>  + Handling authorization for 20arthurst.duckdns.org
>  + Handling authorization for arthurst.duckdns.org
>  + 2 pending challenge(s)
>  + Deploying challenge tokens...
> KOKO + Responding to challenge for 20arthurst.duckdns.org authorization...
>  + Cleaning challenge tokens...
> KOKO + Challenge validation has failed :(
> ERROR: Challenge is invalid! (returned: invalid) (result: {
>   "type": "dns-01",
>   "status": "invalid",
>   "error": {
>     "type": "urn:ietf:params:acme:error:dns",
>     "detail": "DNS problem: NXDOMAIN looking up TXT for _acme-challenge.20arthurst.duckdns.org",
>     "status": 400
>   },
>   "url": "https://acme-v02.api.letsencrypt.org/acme/challenge/AT9eT_6Si_mThzN04hE3bJrn7-rVXvh2_92rxQh1qTA/8139855288",
>   "token": "nCguX9mWtTO5Z-5PnOKa9PAgfqA3XvoU07NmPTBnY_c"
> })
> ```

Sorry to bump an old issue, but you might want to remove the token and domain info from this log.

**Comment by jscholtens** [comment]
> I don't have a fix, but I have a workaround: Create another subdomain and add it to the domains array in the DuckDNS config, e.g.
> 
> ```
> {
>   "lets_encrypt": {
>     "accept_terms": true,
>     "certfile": "fullchain.pem",
>     "keyfile": "privkey.pem"
>   },
>   "token": "x",
>   "domains": [
>     "x.duckdns.org",
>     "x2.duckdns.org"
>   ],
>   "seconds": 300
> }
> ```
> 
> This will force the cert to renew the next time you restart the DuckDNS service.

Thank you dear sir. This has forced my add-on to renew the certificate! Personally I added a domain and then removed it. Fixed it for now...

**Comment by mgale456** [comment]
For anyone that finds this thread in the future, your webserver (in my case NGINX) likely cached the files. Restart it, and the new cert that the DuckDNS addon is seeing will be used.
