### ISSUE TITLE
Homematic time drifting away

### ISSUE THREAD

**Issue by IceOnly** [home-assistant/hassio-addons#421]
The time on my homematic devices goes out of sync. Every day about 5 -10 min more in the future.
The docker time is correct.  After restarting the container the time is back in sync.
After some research, I figured out that the rfd process starts its own software clock an never sync it again with the system clock.

yahm, fhem and the orginal ccu  runs the $HM_HOME/bin/SetInterfaceClock 127.0.0.1:2001 periodically to sync the rfd software clock with the system time.

Source:
- https://forum.iobroker.net/viewtopic.php?t=7486
- https://github.com/hobbyquaker/hmcon/issues/37
- https://homematic-forum.de/forum/viewtopic.php?t=36875

On the way to work, i forked the project and make this change:
https://github.com/IceOnly/hassio-addons/commit/839eef200770517d8544ba37fa291cdabd59771d#diff-aecd1ec5d25063e39a74c2367c11a0ac

I will build the addon locally this evening and try it out.
If it work I will make a pull request.

**Comment by pvizeli** [comment]
Nice. I'm every time happy with contributions
