### ISSUE TITLE
Latest Snips.AI build missing

### ISSUE THREAD

**Issue by jariha** [home-assistant/hassio-addons#426]
Hi!

I cannot install the Snips.AI addon:
18-10-12 14:35:34 INFO (SyncWorker_10) [hassio.docker.interface] Pull image homeassistant/amd64-addon-snips tag 3.3.
18-10-12 14:35:36 ERROR (SyncWorker_10) [hassio.docker.interface] Can't install homeassistant/amd64-addon-snips:3.3 -> 404 Client Error: Not Found ("manifest for homeassistant/amd64-addon-snips:3.3 not found").

The tag 3.3 is missing also from here:
https://hub.docker.com/r/homeassistant/amd64-addon-snips/tags/

**Comment by tjorim** [comment]
Is this still an isssue?
The tag is showing up now and there have been 2 new releases since.
Please check and close this issue if possible.

**Comment by danito** [comment]
I just installed hassio (64b version, my bad) and snips is not available for install.

**Comment by tjorim** [comment]
@danito arm/aarch64 (on a raspi 3b+ for example) or amd64? It's not available for the first option, only armhf and amd64.

**Comment by danito** [comment]
I went alpha for the RP3b+ , so arm/aarch64 yes. So I'm not much of a help here then.
