### ISSUE TITLE
Update NGINX to the latest stable release

### ISSUE THREAD

**Issue by deviant-studio** [home-assistant/hassio-addons#428]
Proxy Addon bundled with nginx 1.12.2 which is pretty old (2017) and has vulnerabilities (like https://github.com/0-complexity/openvcloud/issues/1317)
Please update the bundled nginx to the latest stable release

**Comment by tjorim** [comment]
Version 2.1 of the nginx add-on comes with 1.14.2, the latest available on Alpine Linux.
