### ISSUE TITLE
missing manifest for snips image

### ISSUE THREAD

**Issue by lubeda** [home-assistant/hassio-addons#430]
When i try to install the snips addon to hass.io i get an error like "404 .. missing manifest homeassistant/amd64-addon-snips:3.3" on the supervisor console. The installation stops and does nothing. The same error occurs an manuall do a "docker pull" with the tag latest it should work

**Comment by noonie2k** [comment]
Specific error: 
`18-10-25 22:34:46 ERROR (SyncWorker_6) [hassio.docker.interface] Can't install homeassistant/amd64-addon-snips:3.3 -> 404 Client Error: Not Found ("manifest for homeassistant/amd64-addon-snips:3.3 not found").`

The latest tag on Docker Hub is 3.2
