### ISSUE TITLE
Custom deps: HASSIO clobbers settings on restart

### ISSUE THREAD

**Issue by deustis** [home-assistant/hassio-addons#434]
@georgemarshall, @pvizeli 

I am trying to use this add-on to pin a pip module to a specific version.

Using the web config, I can see the changes reflected in this HASSIO path:
'/config/deps/lib/python3.6/site-packages'

However, when I restart my homeassistant server, the module versions are overwritten back to the defaults. In my case, I'm using the tool to set `pynetgear` to `0.4.2`, but restarting the server brings it back to `0.5.0`, the version declared in [netgear.py](https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/device_tracker/netgear.py#L18).

Note, the documentation for this add-on doesn't seem to exist, so I could be using it wrong:
https://community.home-assistant.io/t/custom-deps-deployment-addon-what-does-it-do/55680

**Comment by jumpkick** [comment]
@deustis going by [line 25](https://github.com/home-assistant/hassio-addons/blob/master/custom_deps/run.sh#L25), it looks like any deps created by this module should be accessible from your main hass server container at /config/deps

You'll want to check if your stuff is there...   You may have to manually start the custom_deps addon... mine does not appear to run automatically at start-up despite having the option checked.

**Comment by frenck** [comment]
@deustis That is by design. The HA component dictates its dependencies.
If you want to override that, you should not use the add-on, but you should use a custom component (custom components actually overrides build in ones).

**Comment by deustis** [comment]
@frenck, thanks for the tip!
