### ISSUE TITLE
Official  addons passwords

### ISSUE THREAD

**Issue by vMeph** [home-assistant/hassio-addons#440]
will it be possible eventually all official addons to have passwords and usernames setup hidden in secrets?
doesn't make sense passwords be set in addons config sense alot times people with problems tend to share computers with TeamV etc...
so having more privacy would be great

thanks

**Comment by Gerto** [comment]
Yes, was just wondering why my samba password wasn't working but apparently it doesn't support secrets so the actual password I had to use was "!secret samba_password" :/

**Comment by frenck** [comment]
To answer the question (which @pvizeli already kinda did), we are moving to authentication against HA, which makes this obsolete.

Closing this issue.
