### ISSUE TITLE
Samba share - Update 7 & 8

### ISSUE THREAD

**Issue by Unpuertomex** [home-assistant/hassio-addons#443]
After installing updates 7 and then 8,  whenever I leave the add-on Samba share page the add-on turns off. I tried rebooting, hard refresh, on different systems, uninstalled it and reinstall but no change, it will not stay on.

**Config**
`{
  "workgroup": "WORKGROUP",
  "username": "root",
  "password": "password1",
  "interface": "",
  "allow_hosts": [
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16",
  ]
}`

**Log**
[INFO] Read hostname: hassio-Surface-Pro-3
addgroup: group 'root' in use

Hassio Version: 0.81.6
Host system: Ubuntu 18.04.1 LTS
Hass.io supervisor: 138

**System log**
18-11-04 20:45:23 WARNING (MainThread) [hassio.addons.validate] Unknown options map
18-11-04 20:45:23 INFO (SyncWorker_14) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 20:45:23 INFO (SyncWorker_7) [hassio.docker.interface] Clean homeassistant/amd64-addon-ssh Docker application
18-11-04 20:45:24 INFO (SyncWorker_14) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 7
18-11-04 20:45:24 INFO (SyncWorker_7) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-ssh with version 4
18-11-04 20:45:29 INFO (SyncWorker_8) [hassio.docker.interface] Clean homeassistant/qemux86-64-homeassistant Docker application
18-11-04 20:45:30 INFO (SyncWorker_8) [hassio.docker.homeassistant] Start homeassistant homeassistant/qemux86-64-homeassistant with version 0.81.0
18-11-04 20:45:40 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
18-11-04 20:45:40 INFO (MainThread) [hassio.addons] Startup application run 0 add-ons
18-11-04 20:45:40 INFO (MainThread) [hassio.tasks] All core tasks are scheduled
18-11-04 20:45:40 INFO (MainThread) [hassio.core] Hass.io is up and running
18-11-04 20:48:35 WARNING (MainThread) [hassio.addons.validate] Unknown options name
18-11-04 20:48:35 WARNING (MainThread) [hassio.addons.validate] Unknown options guest
18-11-04 20:48:35 WARNING (MainThread) [hassio.addons.validate] Unknown options map
18-11-04 20:48:35 WARNING (MainThread) [hassio.addons.validate] Unknown options name
18-11-04 20:48:35 WARNING (MainThread) [hassio.addons.validate] Unknown options guest
18-11-04 20:48:35 WARNING (MainThread) [hassio.addons.validate] Unknown options map
18-11-04 20:48:36 INFO (SyncWorker_9) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 20:48:36 INFO (SyncWorker_9) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 7
18-11-04 20:49:15 WARNING (MainThread) [hassio.addons.validate] Unknown options name
18-11-04 20:49:15 WARNING (MainThread) [hassio.addons.validate] Unknown options guest
18-11-04 20:49:15 WARNING (MainThread) [hassio.addons.validate] Unknown options map
18-11-04 20:49:15 WARNING (MainThread) [hassio.addons.validate] Unknown options name
18-11-04 20:49:15 WARNING (MainThread) [hassio.addons.validate] Unknown options guest
18-11-04 20:49:15 WARNING (MainThread) [hassio.addons.validate] Unknown options map
18-11-04 20:49:15 INFO (SyncWorker_4) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 20:49:16 INFO (SyncWorker_4) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 7
18-11-04 20:50:40 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
18-11-04 21:20:40 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
18-11-04 21:49:19 WARNING (MainThread) [hassio.addons.validate] Unknown options name
18-11-04 21:49:19 WARNING (MainThread) [hassio.addons.validate] Unknown options guest
18-11-04 21:49:19 WARNING (MainThread) [hassio.addons.validate] Unknown options map
18-11-04 21:49:19 WARNING (MainThread) [hassio.addons.validate] Unknown options name
18-11-04 21:49:19 WARNING (MainThread) [hassio.addons.validate] Unknown options guest
18-11-04 21:49:19 WARNING (MainThread) [hassio.addons.validate] Unknown options map
18-11-04 21:49:19 INFO (SyncWorker_12) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 21:49:19 INFO (SyncWorker_12) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 7
18-11-04 21:50:40 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
18-11-04 21:52:37 INFO (SyncWorker_15) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 21:52:37 INFO (SyncWorker_15) [hassio.docker.interface] Remove Docker homeassistant/amd64-addon-samba with latest and 7
18-11-04 21:52:37 INFO (MainThread) [hassio.addons.addon] Remove Home Assistant add-on data folder /data/addons/data/core_samba
18-11-04 21:57:47 INFO (MainThread) [hassio.homeassistant] Update Home Assistant to version 0.81.6
18-11-04 21:57:47 INFO (SyncWorker_13) [hassio.docker.interface] Update Docker 0.81.0 with homeassistant/qemux86-64-homeassistant:0.81.6
18-11-04 21:57:47 INFO (SyncWorker_13) [hassio.docker.interface] Pull image homeassistant/qemux86-64-homeassistant tag 0.81.6.
18-11-04 21:58:31 INFO (SyncWorker_13) [hassio.docker.interface] Tag image homeassistant/qemux86-64-homeassistant with version 0.81.6 as latest
18-11-04 21:58:31 INFO (SyncWorker_13) [hassio.docker.interface] Stop homeassistant/qemux86-64-homeassistant Docker application
18-11-04 21:59:02 INFO (SyncWorker_13) [hassio.docker.interface] Clean homeassistant/qemux86-64-homeassistant Docker application
18-11-04 21:59:02 INFO (SyncWorker_13) [hassio.docker.interface] Cleanup Docker images: ['homeassistant/qemux86-64-homeassistant:0.81.0']
18-11-04 21:59:05 INFO (SyncWorker_11) [hassio.docker.homeassistant] Start homeassistant homeassistant/qemux86-64-homeassistant with version 0.81.6
18-11-04 21:59:45 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
18-11-04 21:59:45 INFO (MainThread) [hassio.homeassistant] Successful run Home Assistant 0.81.6
18-11-04 22:01:06 INFO (MainThread) [hassio.addons.addon] Create Home Assistant add-on data folder /data/addons/data/core_samba
18-11-04 22:01:06 INFO (SyncWorker_10) [hassio.docker.interface] Pull image homeassistant/amd64-addon-samba tag 7.
18-11-04 22:01:11 INFO (SyncWorker_10) [hassio.docker.interface] Tag image homeassistant/amd64-addon-samba with version 7 as latest
18-11-04 22:01:36 INFO (SyncWorker_3) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 7
18-11-04 22:02:27 INFO (SyncWorker_19) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 22:02:27 INFO (SyncWorker_19) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 7
18-11-04 22:07:25 INFO (SyncWorker_15) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 22:07:25 INFO (SyncWorker_15) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 7
18-11-04 22:07:37 INFO (SyncWorker_9) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 22:07:41 INFO (SyncWorker_5) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 7
18-11-04 22:12:20 INFO (SyncWorker_6) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 22:12:20 INFO (SyncWorker_6) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 7
18-11-04 22:15:20 INFO (SyncWorker_8) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 22:15:20 INFO (SyncWorker_8) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 7
18-11-04 22:17:13 INFO (SyncWorker_3) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 22:17:14 INFO (SyncWorker_3) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 7
18-11-04 22:20:21 INFO (MainThread) [hassio.addons.git] Update add-on https://github.com/hassio-addons/repository repository
18-11-04 22:20:21 INFO (MainThread) [hassio.addons.git] Update add-on https://github.com/home-assistant/hassio-addons repository
18-11-04 22:20:22 INFO (MainThread) [hassio.addons] Load add-ons: 45 all - 0 new - 0 remove
18-11-04 22:20:39 INFO (SyncWorker_3) [hassio.docker.interface] Update Docker 7 with homeassistant/amd64-addon-samba:8
18-11-04 22:20:39 INFO (SyncWorker_3) [hassio.docker.interface] Pull image homeassistant/amd64-addon-samba tag 8.
18-11-04 22:20:40 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
18-11-04 22:20:41 INFO (SyncWorker_3) [hassio.docker.interface] Tag image homeassistant/amd64-addon-samba with version 8 as latest
18-11-04 22:20:41 INFO (SyncWorker_3) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 22:20:41 INFO (SyncWorker_3) [hassio.docker.interface] Cleanup Docker images: ['homeassistant/amd64-addon-samba:7']
18-11-04 22:20:47 INFO (SyncWorker_4) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 8
18-11-04 22:20:55 INFO (MainThread) [hassio.addons.git] Update add-on https://github.com/hassio-addons/repository repository
18-11-04 22:20:55 INFO (MainThread) [hassio.addons.git] Update add-on https://github.com/home-assistant/hassio-addons repository
18-11-04 22:20:55 INFO (MainThread) [hassio.addons] Load add-ons: 45 all - 0 new - 0 remove
18-11-04 22:21:15 INFO (SyncWorker_12) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 22:21:15 INFO (SyncWorker_12) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 8
18-11-04 22:28:40 INFO (SyncWorker_1) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 22:28:40 INFO (SyncWorker_1) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 8
18-11-04 22:31:47 INFO (SyncWorker_2) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 22:31:48 INFO (SyncWorker_2) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 8
18-11-04 22:34:58 INFO (SyncWorker_19) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 22:34:58 INFO (SyncWorker_19) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 8
18-11-04 22:35:09 INFO (SyncWorker_1) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 22:35:09 INFO (SyncWorker_1) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 8
18-11-04 22:44:43 INFO (SyncWorker_11) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 22:44:43 INFO (SyncWorker_11) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 8
18-11-04 22:46:53 INFO (SyncWorker_12) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 22:46:57 INFO (SyncWorker_2) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 8
18-11-04 22:47:06 INFO (SyncWorker_11) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 22:47:06 INFO (SyncWorker_11) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 8
18-11-04 22:50:40 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
18-11-04 23:20:40 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
18-11-04 23:35:07 INFO (SyncWorker_12) [hassio.docker.interface] Clean homeassistant/amd64-addon-samba Docker application
18-11-04 23:35:07 INFO (SyncWorker_12) [hassio.docker.addon] Start Docker add-on homeassistant/amd64-addon-samba with version 8

**Comment by pvizeli** [comment]
You can't use `root` because that is a system account. Use a different name, and it should work.

**Comment by Unpuertomex** [comment]
Well heck, I've been using root for the last year. However, I just changed it and it stays connected now.
