### ISSUE TITLE
When server port is changed web ui still goes to default port

### ISSUE THREAD

**Issue by jmesberg** [home-assistant/hassio-addons#447]
Example is node-red addon, but seems to be true for all. The addon defaults to port 1880 but since I use this port for other things I chose to use the config to change it to 2880. The server starts as you'd expect at port 2880, however when you click on the web ui button its uses a URL with :1880 at the end vs the correct port. 

Asked Frenck about this on discord and he responded: "There is no way for me to tell Hass.io the port changed". 

Given this I thought it would be a good idea to raise this issue to hassio-addons.

**Comment by pvizeli** [comment]
Can you post the add-on config? Is that a add-on they run on host network? You should only run on host network if there is no other way because a lot of function don't work for kind of that add-ons.

**Comment by jmesberg** [comment]
Here is the addon config:
`{
  "log_level": "info",
  "credential_secret": "xxxxxxxxxxxxxxx",
  "http_node": {
    "username": "",
    "password": ""
  },
  "http_static": {
    "username": "",
    "password": ""
  },
  "port": 2880,
  "ssl": true,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "require_ssl": true,
  "system_packages": [],
  "npm_packages": [
    "underscore"
  ],
  "init_commands": []
}`

and here is info on server from the log:
`6 Nov 08:58:51 - [info] Server now running at https://127.0.0.1:2880/`

Hopefully this answers your two questions. Thank you for your help.

**Comment by pvizeli** [comment]
I mean the `config.json` that you use to develop the add-on.

But that looks like the add-on run on the host. Ask the maintainer if they convert this add-on to the internal network and that what you want will work 👍

**Comment by frenck** [comment]
@pvizeli The node-red allows the user to spawn endpoints, which I cannot foresee, hence it running on the host network.

@jmesberg Like explained the ports are not managed by Hass.io, hence Hass.io does not know about the ports used, hence the URL isn't accurate in all situations.

Closing this issue.
