### ISSUE TITLE
Samba addon lost options to expose shares

### ISSUE THREAD

**Issue by cogneato** [home-assistant/hassio-addons#449]
The samba addon lost the configuration options to show/hide directories, and the /ssl directory is now shared by default.

**Comment by pvizeli** [comment]
Yes, we remove options they were added for guest access because they do not exist anymore.

**Comment by cogneato** [comment]
I had actually forgotten about guest, but this is in reference to the options to show and hide the different directories. Was that related to the guest account?

**Comment by cogneato** [comment]
Closing this as I understand now.
