### ISSUE TITLE
Mosquitto: Unable to connect over open websockets since version 3.0

### ISSUE THREAD

**Issue by rbray89** [home-assistant/hassio-addons#450]
Seems that the recent update to Mosquitto has broken it for websockets.

I will document my debugging here as I go along.

So far, I don't get any indication in the logs, just a disconnect in nginx. 
Rolling back to the previous Mosquitto addon version restored functionality.

**Comment by rbray89** [comment]
So this looks to be an issue with the base image or the docker build.
Using the 2.0 image in docker hub it works, but attempting to use the Dockerfile in 829fa7f0f66ddb577d647f9ebd429fcfb7d3d18c fails to connect.

**Comment by rbray89** [comment]
looks like the docker image armhf-base:3.8 broke the websocket support somehow. If I set the base image to be armhf-base:3.7 it works.

**Comment by pvizeli** [comment]
Is the broker listen on? Is there a client for testing? Can you see anything inside logs?

**Comment by rbray89** [comment]
Yeah, broker was installed and should have been listening. I enabled debug logging for mosquito, but nothing useful was shown. Do we have any insight into the differences between the armhf-base:3.7 and armhf-base:3.8 docker images?

**Comment by pvizeli** [comment]
only the version have change from mosquitto

**Comment by rbray89** [comment]
hmmm... well, if others end up seeing this issue, a workaround is to place a copy of the Mosquitto addon into the addon folder and update build_from in build.json to use an older base image (use correct architecture):
```
{
  "build_from": {
    "armhf": "homeassistant/armhf-base:3.7"
  },
  "args": {
    "MOSQUITTO_AUTH_VERSION": "0.1.3"
  }
}
```

and remove the image line in config.json:
```
...
  },
  "image": "homeassistant/{arch}-addon-mosquitto"   // Remove this line and the comma above.
}
```

**Comment by pvizeli** [comment]
https://github.com/eclipse/mosquitto/issues/708

maybe we can upgrade it

**Comment by pvizeli** [comment]
Is now fine? There is an issue with libwebsocket with version 3.0.0

**Comment by rbray89** [comment]
Looks like the fixed version is working well. Thanks!
