### ISSUE TITLE
Mosquitto migration

### ISSUE THREAD

**Issue by pvizeli** [home-assistant/hassio-addons#451]
There are some troubles with using the new MQTT Add-on. The problem is, that they edit the confiuration yaml and that doesn't work for the new generation of integration components aka config flow.

More information
-> https://www.home-assistant.io/addons/mosquitto/

## Migration
- Remove the broker settings inside old `configuration.yaml` if you have one.
- Remove integration (imported from configuration.yaml) on Configuration/Integration panel
- Restart Home Assistant
- Go to integrations and install the MQTT settings from Discovered section.

## FAQ
- Do I need to enable discovery? -> No
- `homeassistant` and `addons` don't work inside local logins. -> That now internal users and needed for auto setups. You need to use a new name.
- What kind of login data is now needed? -> You can use your normal user they were created inside Home Assistant. It's currently also supported to set login data with config, but that will remove in future after you can setups rights inside Home Assistant.
- Can I use the old manual settings? -> Yes, but they will also be converted to an Integration. After this manual setting are imported into a new integration panel, you can't change things inside the config.

![mqtt-hassio](https://user-images.githubusercontent.com/15338540/48149412-48541880-e2bc-11e8-80d7-a37b959d665d.gif)

**Comment by Schibum** [comment]
I like where this is going. 
Not being able to use 'homeassistant' as username with mosquito while that is the only option with the embedded broker, makes switching between those two a bit painfully right now though.

**Comment by dmoses1969** [comment]
In the video you don't have login/password configured in Mosquito MQTT.  I have tried the integration and selected discover twice now and I get the Success! prompt but when I click on MQTT Configuration it says "This integration has no devices". All of my MQTT devices are coming from SmartThings MQTT. Will that not work?

![image](https://user-images.githubusercontent.com/10082767/48176150-86f5cd00-e2d4-11e8-9d74-08f8e6a6e28f.png)

**Comment by isabellaalstrom** [comment]
@dmoses1969 I have the same problem. No devices. I have a username and login set in the config for the addon since I have a lot of other connections to mqtt that I would have to change. I plan to do this in the future but for now I would like it to just work in the meantime..

**Comment by cogneato** [comment]
@dmoses1969 @isabellaalstrom with the previous integration (before v3) I would get "no devices" in that window but the few mqtt entities I had would still work. I assumed seeing them in that panel was something coming in a future release.

**Comment by dmoses1969** [comment]
@cogneato Not only were the devices not showing in the integration window. They did not exist in HA anymore. The only way to get them back was to add them back into my binary_sensor.yaml file. After doing that and rebooting my SmartThings decided are showing again.

**Comment by dmoses1969** [comment]
I removed the credentials from Mosquito MQTT config. Removed all MQTT config from my configuration.yaml file, added all my devices back in to my binary_sensor.yaml and everything is good now. Apparently SmartThings devices are non discoverable.

**Comment by fernandex00** [comment]
Hi, what about the bridge with mqtt and cloudmqtt, with the latest update the battery sensors stop working
