### ISSUE TITLE
MariaDB: add more configuration options

### ISSUE THREAD

**Issue by sanyatuning** [home-assistant/hassio-addons#457]
Hi!
Please add option to:
* enable mysql slow log and make it accessible - ex.: place it in /shared folder
* other runtime options - ex.: [innodb buffer pool size](https://mariadb.com/kb/en/library/xtradbinnodb-server-system-variables/#innodb_buffer_pool_size) 

Thanks

**Comment by nyok92** [comment]
I tried to edit the my.cnf file to add required configs but each time the container retarts, the custom configs are erased and back to default ones.
Is there a way to configure other tha n mysql args ? thanks
