### ISSUE TITLE
Samba 64bit

### ISSUE THREAD

**Issue by TopdRob** [home-assistant/hassio-addons#467]
I tried to install the Samba 8 addon but the log gives this message

> 18-11-19 16:57:07 INFO (SyncWorker_18) [hassio.docker.interface] Pull image homeassistant/aarch64-addon-samba tag 8.
> 18-11-19 16:57:11 ERROR (SyncWorker_18) [hassio.docker.interface] Can't install homeassistant/aarch64-addon-samba:8 -> 404 Client Error: Not Found ("no such image: homeassistant/aarch64-addon-samba:8: No such image: homeassistant/aarch64-addon-samba:8").

Hostname | hassio
-- | --
System | HassOS 1.12
Deployment | production

Version | 139
-- | --
Latest version | 139

Home Assistant
0.82.1

**Comment by frenck** [comment]
@TopdRob Thanks for opening an issue.

The image does exist, see here: https://hub.docker.com/r/homeassistant/aarch64-addon-samba/tags/

Another reason for Docker to throw a 404 error, is because of low disk space, please be sure you have enough disk space available.

**Comment by TopdRob** [comment]
@frenck thanks for your support.

I checked diskspace and only 28% is used. I could install other add-ons as far as I see only this one refused to install.

**Comment by pvizeli** [comment]
I see that before. I install/pull a new image and they had a poweroff. After that the docker database was corrupt for this image and I was not able to do anything with this image :(

Is that possible?
