### ISSUE TITLE
custom_deps should install apks on the HA container

### ISSUE THREAD

**Issue by jumpkick** [home-assistant/hassio-addons#470]
Currently, the custom_deps addon installs apks in it's own container... 

All of the apk changes are then lost as soon as the container goes down, which happens immediately after the pypi packages are installed.   

I was hoping to install imagemagick's convert utility on my HA server, it seems the custom_deps component is not capable of doing that as it's currently written.

Perhaps that was never the intention of having the apk there, but as the addon documentation page link is broken, so it's not clear.

**Comment by frenck** [comment]
the packages on this add-on are to support the installation of Python Packages. Some packages require additional system packages to be able to build.

It is not possible to install additional packages in other containers via an add-on. A workaround for this might be calling a shell script using an automation in Home Assistant (on startup) to trigger the installation of APK's inside Home Assistant's container.

Nevertheless, those are not things I would generally recommend.

**Comment by jumpkick** [comment]
Ok thanks for the clarification.

I'll be wrapping up ssocr in a shell script to preprocess the image with convert first, so as a workaround I'll prepend:
```
if [ -z "$(grep imagemagick /etc/apk/world)" ]; then
	apk add --update imagemagick
fi
```
to that shell script to make sure the bin gets installed, if it's missing, when the script runs.
