### ISSUE TITLE
NGINX SSL proxy - X Forwarded for issue.

### ISSUE THREAD

**Issue by jonny3010** [home-assistant/hassio-addons#471]
Hi Guys,

When using Nginx SSL proxy, and enabling the following in configuration.yaml, so I can get actual IPs of users.
```
use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
```

User's IP addresses come through as IPv6 Addresses, even when my network doesn't have a hint of IPv6 Enabled, other than Local Link, which every device has now a days.

Looks like there's some sort of IPv6 bind with IPv4 going on. I'm an Apache person myself, so have limited knowledge of Nginx.

Error Log from Nginx
`2018/11/22 17:21:54 [error] 22#22: *51 connect() failed (111: Connection refused) while connecting to upstream, client: ::ffff:192.168.2.102, server: hassio.host, request: "GET /api/websocket HTTP/1.1", upstream: "http://172.30.32.1:8123/api/websocket", host: "hassio.host"`

Refresh Tokens
`Refresh token for https://hassio.host/
Created at November 22, 2018, 5:22 PM
Last used at November 22, 2018, 5:22 PM from ::ffff:c0a8:266`

Weird bit is then the IP address HA says is then different from what Nginx has.

Any ideas why this is happening?

**Comment by Barrysv** [comment]
Hi there in your Nginx config rather than specifying localhost:8123 use 127.0.0.1:8123 so this will ensure incoming IPv6 requests get redirected to Hass on IPv4.  "localhost:8123" means Nginx will try to connect to Hass using the same protocol that came in - and Hass doesn't do dual stack at present

**Comment by FingerlessGlov3s** [comment]
I'm using the "NGINX Home Assistant SSL proxy" which is apart of the HASSIO plugins, so the configuration is all already done!

I also don't have IPv6 support on my network, as I've disabled it.

**Comment by maxi1134** [comment]
I'm having this issue too, and would love to see ipv4 addresses. Did you ever found a solution?

**Comment by blacktirion** [comment]
@FingerlessGlov3s @maxi1134 If you are still having issues with this, I've submitted a pull request to turn off the listening by IPv6. Depending on that timeline, if it still isn't merged and you want it, let me know and I can send you a link to my repo.

**Comment by FingerlessGlov3s** [comment]
@blacktirion It working fine on my current install. I changed it to a Ubuntu Virtual Machine and used https://www.home-assistant.io/hassio/installation/#alternative-install-on-a-generic-linux-host to install Hassio though.

**Comment by blacktirion** [comment]
Yup, I've seen this happen more on RPi.
