### ISSUE TITLE
oocu won't start with Homematic ip enabled

### ISSUE THREAD

**Issue by ptc** [home-assistant/hassio-addons#472]
HM-MOD-RPI-PCB supports hmip. Yet, if I enable the option for hmip_enable and set device to /dev/ttyAMA0, the add-on won't start. It says that /dev/ttyAMA0 can't be opened. In RF mode, everything runs - except hmip.

**Comment by pvizeli** [comment]
That is currently not supported because it needs individual kernel modules and we did not maintain this in HassOS.
