### ISSUE TITLE
CEC addon: vc_cec could not be initialised

### ISSUE THREAD

**Issue by danielsjf** [home-assistant/hassio-addons#473]
After the last update, the CEC scanner also works (instead of FAILED) on the 64bit version of hassos, which is great! Thanks for all the great work.

Unfortunately, I still get an error that vc_cec could not be initialised. This is the log.

Log

opening a connection to the CEC adapter... ERROR: [ 76]	RegisterLogicalAddress - CEC is being used by another application. Run "tvservice --off" and try again. 
ERROR: [ 76]	Open - vc_cec could not be initialised 
ERROR: [ 76]	could not open a connection (try 1)

It seems that the HDMI connection is already used by something else and this connection can be reset by just calling tvservice --off

https://github.com/Pulse-Eight/libcec/issues/191#issuecomment-272531574

**Comment by pvizeli** [comment]
You need plugin the HDMI on boot time otherwise RPI doesn't activate it or you need to change the GPU settings with `config.txt`. See on Raspberry documentation.

**Comment by Superheld** [comment]
Can I ask a question for this? I want to use pyCEC, so I have never an HDMI-cable on the HASS.IO-Raspy. How to start HDMI in that case?
