### ISSUE TITLE
Snips.ai: allow to use as master without audio server

### ISSUE THREAD

**Issue by escoand** [home-assistant/hassio-addons#474]
I want to use the snips hassio addon as snips master only without an audio server but with multiple satellites.
This seems to be not possible at the moment despite having no microphone is the default raspberry hardware configuration.

More information:
https://docs.snips.ai/installing-snips/multi-device-setup-satellites

**Comment by tschmidty69** [comment]
Hmm, technically this should work without errors if you configure an audio server to send to the HA MQTT.

**Comment by tschmidty69** [comment]
Roger, I'll add an option since it would be nice to be able to use remotes with hassio on a pc in a closet somewhere, etc.

**Comment by solars** [comment]
I would also be interested to run the master on my NAS and only use the sattelites with audio

**Comment by escoand** [comment]
@tschmidty69 what do you say?

**Comment by tschmidty69** [comment]
Sorry, I have been swamped at work lately (new CIO, must change everything of course). I'll try to take a poke soon.

**Comment by escoand** [comment]
@tschmidty69 ping
