### ISSUE TITLE
Configurator: Support for secrets in configuration

### ISSUE THREAD

**Issue by koenvervloesem** [home-assistant/hassio-addons#477]
I have installed the Configurator addon in Hass.io and I'm used to addons supporting secrets for the configuration of the username and password, so I can have all my sensitive information in one file, `config/secrets.yaml`. I noticed that Configurator doesn't support this.

I'd love to be able to have a configuration like:

```
{
  "username": "!secret configurator_username",
  "password": "!secret configurator_password",
  ...
```

So then I can have in `config/secrets.yaml`:

```
configurator_username: foobar
configurator_password: loremipsum
```

**Comment by koenvervloesem** [comment]
I still think it's a valid request to be able to have all my sensitive information for all Home Assistant addons in one place. Six people reacted with a thumbs up on my feature request, so I don't think I'm the only one who wants this to happen.

**Comment by gotson** [comment]
if you use Hass.io with ingress you don't need login/password anymore for the configurator

**Comment by koenvervloesem** [comment]
Great, thanks for pointing this out, I'll have to update and try it then one of these days!

**Comment by frenck** [comment]
No longer an issue, since the add-on now uses Hass.io's Ingress.
