### ISSUE TITLE
DuckDNS: support for token secret in configuration

### ISSUE THREAD

**Issue by koenvervloesem** [home-assistant/hassio-addons#478]
I have installed the DuckDNS addon in Hass.io and I'm used to addons supporting secrets for the configuration of sensitive information, so I can have usernames, passwords, API tokens and so on in one file, `config/secrets.yaml`. I noticed that DuckDNS doesn't support this.

I'd love to be able to have a configuration like:

```
{
  "lets_encrypt": {
    "accept_terms": true,
    "certfile": "fullchain.pem",
    "keyfile": "privkey.pem"
  },
  "token": "!secret duckdns_token",
  ...
```

So then I can have my DuckDNS token in config/secrets.yaml:

```
duckdns_token: foobar
```

**Comment by BellatorInMachina** [comment]
bump, I'd like to see this supported as well.

**Comment by leikoilja** [comment]
Uh, that functionality would be very desirable

**Comment by meichhorn** [comment]
Try this syntax: 

token: '!secret Duck_DNS_Token'

**Comment by lka** [comment]
I tried this syntax:
  token: '!secret Duck_DNS_Token'

this leads to a replacement of '!secret Duck_DNS_Token' with xxxxx-xxxxx-xxxxx-xxxx the real token in the configuration.

I expect, that only the plugin works with the real token and not the configuration uses a replacement.
