### ISSUE TITLE
Git pull Regex not correct

### ISSUE THREAD

**Issue by JustinLavan** [home-assistant/hassio-addons#496]
Hey guys am I missing something. I am trying to create a config file for the repo and its giving me the "not a valid value for dictionary value @ data['options']."  error. 

So I checked the regex and it looks like this "(?:.+):(\/\/)?(.*?)(\\.git)(\/?|\\#[-\\d\\w._]+?)" the \\ in front of the .git means that the file needs to look like this:

https://example.com/my_configs\.git 

but the backslash breaks the functionality so you have to do:

https://example.com/my_configs\\.git 

Also it looks like options:

"deployment_user"
"deployment_password"
and repeat options

are required even though they are listed as optional

**Comment by jvravensberg** [comment]
Getting the same strange error as you @JustinLavan. I was just trying to setup Git Pull until I found your issue. I'm both getting the "not a valid value" error and it needs indeed the user and password options for me.
