### ISSUE TITLE
Occu - Not possible to use rf and hmIP simultaneously with HM-MOD-RPI-PCB

### ISSUE THREAD

**Issue by monkeydriven** [home-assistant/hassio-addons#499]
I´m using HM-MOD-RPI-PCB that is capable of bidcos-rf and hmIP (/dev/ttyAMA0).
Therefore my config looks as follows:

`{
  "rf_enable": true,
  "rf": [
    {
      "type": "CCU2",
      "device": "/dev/ttyAMA0"
    }
  ],
  "wired_enable": false,
  "wired": [
    {
      "serial": "xy",
      "key": "abc",
      "ip": "192.168.0.0"
    }
  ],
  "hmip_enable": true,
  "hmip": [
    {
      "type": "HMIP_CCU2",
      "device": "/dev/ttyAMA0"
    }
  ]
}`

Log:
[ERROR] Error while trying to open serial port: Exception while trying to open serial port. Check configured port ‘/dev/ttyAMA0’ [INFO] Exiting update tool.

If I set hmIP_enable to false so that only “rf” is using /dev/ttyAMA0 everythign works and the service starts normally…but of course without hmIP Support.

**Comment by pvizeli** [comment]
Yes, we don't support HmIP with HM-MOD-RPI-PCB because we don't want to integrate the kernel hack for this device.

Use the USB adapter for HmIP.

**Comment by Martwall** [comment]
> Yes, we don't support HmIP with HM-MOD-RPI-PCB because we don't want to integrate the kernel hack for this device.
> 
> Use the USB adapter for HmIP.

I'm not sure the what the kernel hack is and the reasons for not wanting to use it for HM-MOD-RPI-PCB, but I just wanted to ask if HmIP is ever going to be supported on HM-MOD-RPI-PCB and for example RP-RF-MOD?

I have been looking for this as it would be a nice feature if you didn't have to use the USB stick for HmIP. Possibly running both RF and HmIP at the same time and making it easier with for example antenna extensions in case it is needed. Also it would be the same case for RP-RF-MOD in case you want to have the increased range from the start and possibility of using wired products. It would also give a neater finish to be able to contain the module within a single casing. 

If there is any programming that needs to be done to make it happen I'd be happy to help out to the best of my somewhat limited capabilities in OCCU and add-on development.
