### ISSUE TITLE
nginx_proxy - Custom config unclear

### ISSUE THREAD

**Issue by jjpeet** [home-assistant/hassio-addons#505]
I'm looking at the documentation to add custom config for NGINX.  It tells me the following;
```
"customize": {
    "active": false,
    "default": "nginx_proxy_default*.conf",
    "servers": "nginx_proxy/*.conf"
```
and

> (boolean)(Optional)If true, additional NGINX configuration files for the default server and additional servers are read from files in the /share directory specified by the default and servers variables.
> Default value: false

So, I did the following;

1. added a subfolder to the /shares folder called nginx_proxy
2. inserted a file into this folder called MotionEye.conf
3. Changed     "active": false, to     "active": true,

The content of the config file is;
```
    location /motioneyetest {
       proxy_set_header X-Real-IP  $remote_addr;
       proxy_set_header X-Forwarded-For $remote_addr;
       proxy_set_header Host $host;
       proxy_pass http://http://192.168.0.24:80;
       }
```

After I restarted, HASS never came back and I had to do a restore using the Hassio command line tools.

All I'm trying to do is simply add another Pi at my house running a website at http://192.168.0.24:80
I want it to be called by hitting my home-assistant - https://hass.jjpeet.com/motioneye.  Eg, I want to hit a sub-folder that redirects to the MotionEyeOS box. That way I get SSL & don't need another certificate.

I've done what the docs says, but I think there are a few gaps in there that need to be filled eg;

1. When I turn on true, does that do away with all of the built-in NGINX config and it solely relies upon mine? If so, can more information be provided that tells me what I must now do to the config to make it work?
2. In the NGINX.conf file here on GitHub I note the include statements are commented out. Is that right?

So, this is an issue with the docs, but also is there an issue with implementing custom config int he NGINX plugin itself?

I'm not sure.  
Thx
James

**Comment by HeMUC** [comment]
Similar problem here: I try to add another "server" section with no avail yet. As soon as I add even the simplest customizing nginx fails not proxy altogether.
As I am pretty new to the container business I have not yet looked into the /etc/nginx.conf file used when nginx is started but this is how I will proceed...

**Comment by jjpeet** [comment]
Hi @HeMUC 
I moved to another plugin called Caddy. It does exactly what I’m after.
JP

**Comment by HeMUC** [comment]
Hi @jjpeet 
I also noticed Caddy but didn't look for a corresponding addon so far. Would you mind sharing how you integrated Caddy?

**Comment by madmurl0c** [comment]
@HeMUC I struggled with this today too, here's how I solved it.

Create a new config for your specific use case (nextcloud in my case):
`nano /usr/share/hassio/share/nginx_proxy/nas.example.duckdns.org`

And add the following
```
server {
  server_name nas.example.duckdns.org;

  ssl_session_timeout 1d;
  ssl_session_cache shared:MozSSL:10m;
  ssl_session_tickets off;
  ssl_certificate /ssl/certificate.pem;
  ssl_certificate_key /ssl/privkey.pem;

  # dhparams file
  ssl_dhparam /data/dhparams.pem;

  listen 443 ssl http2;
  add_header Strict-Transport-Security "max-age=31536000" always;

  # intermediate configuration
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
  ssl_prefer_server_ciphers off;

  proxy_buffering off;

  # nextcloud filesize upload fix
  client_max_body_size 0;

  location / {
    proxy_pass https://10.0.0.3:443/;
    proxy_set_header Host $host;
    proxy_redirect http:// https://;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
  }
}
```

Don't forget to edit server_name, etc.
