### ISSUE TITLE
Homematic aarch64 support

### ISSUE THREAD

**Issue by gpulido** [home-assistant/hassio-addons#507]
Hello,
I have HassOs installed on a raspberrypi 3. I also have a HmIp RFUSB and I'm trying to activate the Homematic addon.
At first it can't not be installed as the architecture seems to be aarch64 and the addon doesn't support it.
So I made a copy of the addon locally, and lifted the restriction, and the first problem is that doesn't exist a "homeassistant/aarch64-addon-homeassistant" image.
So just for testing I forced the addon to use the armhf-addon-homeassisntant image instead and I'm able to start it and all seems to work properly (I can teach devices and they appear on the ha gui) except that the addon docker stops by itself after a while (an hour aprox).
So my questions are:
 - Is anything on the aarch64 that forbids to create a homeassistant/aarch64-addon-homeassistant 
image?
- Why the armhf image can be used instead and seems to work?
- I'm trying to check why the image is stopping but the system logs doens't show anything wrong, and the addon docker log is missing after the addon stops by itself. How can I debug it?

Thanks in advance.
Gabriel

**Comment by gpulido** [comment]
Hello,
After accessing to the hassio host and checking the docker logs, I figure out why the image was stopping. I had enabled the rf module on the config, but the HmIp-RFUSB doesn't have the proper hardware, so the run.sh was exiting after 30m when the loop for fix the time shifting was run.

So now the only "issue" is to have a aarch64 image to run it directly without having to patch it to use the armhf image.

**Comment by pvizeli** [comment]
Next release of Hass.io support that a hardware CPU can support multiple arch of add-ons.

**Comment by gpulido** [comment]
Thanks for the answer, which number will have that version?
Also, regarding the docker stopping issue, I already have set as true the HMIp part of the addon and it was working properly, so I think that it should not stop the docker if the rf part is misconfigured.
However, maybe more information regarding the supporting hardware and supporting features of the hardware (for example that the HMIP-RFUSB doesn't support rf ) would be nice on the addon description.
Besides that, all seems to work properly and I have may thermostats already connected to the HA instance :)
