### ISSUE TITLE
Option to disable config check on git pull addon

### ISSUE THREAD

**Issue by teunehv** [home-assistant/hassio-addons#510]
Is it possible to add a configuration to the addon that disable the check on validity of the configuration?

I'm aware of the risks, but config is already checked on gitlab ci.

**Comment by BarrettLowe** [comment]
Also (sort of) going along with this, what if my got repository doesn't end in ".git"? Why can't I use any urk I want?

**Comment by pvizeli** [comment]
@teunehv sure, I'll merge such PR

**Comment by AlecRust** [comment]
This really shouldn't be closed!
