### ISSUE TITLE
git pull: new restart_ignode for directories not working

### ISSUE THREAD

**Issue by der-optimist** [home-assistant/hassio-addons#515]
I'm on git pull 7.1 with the following config:

{
"deployment_key": [],
"deployment_key_protocol": "rsa",
"deployment_user": "",
"deployment_password": "",
"git_branch": "master",
"git_command": "reset",
"git_remote": "origin",
"git_prune": false,
"repository": "github.com/der-optimist/hass.git",
"auto_restart": true,
"restart_ignore": [
"ui-lovelace.yaml",
".gitignore",
"appdaemon/apps/"
],
"repeat": {
"active": true,
"interval": 300
}
}

This is my log:

[Info] Local git repository exists 
[Info] Git origin is correctly set to github.com/der-optimist/hass.git 
[Info] Start git fetch... 
From https://github.com/der-optimist/hass 45ee24a..c82687f master -> origin/master 
[Info] Staying on currently checked out branch: master... 
[Info] Start git reset... HEAD is now at c82687f Create garbage.py 
[Info] Checking if something has changed... 
[Info] Something has changed, checking Home-Assistant config... 
ok 
Changed Files: appdaemon/apps/garbage.py 
[Info] Detected restart-required file: appdaemon/apps/garbage.py 
[Info] Restart Home-Assistant

**Comment by der-optimist** [comment]
@Censored3 maybe you could have a look on this? I think you wrote the update, right? Maybe I'm only using it the wrong way...

**Comment by Censored3** [comment]
Hi @der-optimist 

Yes I did, thanks for the mention. I see I made a stupid mistake which is triggered when specifying a sub-directory... I changed the directory detection mechanism to a more logical way (what was I thinking :p). Should be fixed as soon as my PR is merged; let me know when it works.

In the meantime, it still works for a top-dir; like 'appdaemon/'
