### ISSUE TITLE
Custom Docker Labels

### ISSUE THREAD

**Issue by timpur** [home-assistant/hassio-addons#517]
Hi i was wondering if there was a way to add custom docker labels to the containers that get created by hassio?

Im using Traefik and id like to add traefik labels for it to pick up on .... ??

Thanks

**Comment by signaleleven** [comment]
I found this issue specifically because I wanted to label addons for traefik. However, I think it might be an issue for https://github.com/home-assistant/hassio

**Comment by signaleleven** [comment]
I posted in the other project https://github.com/home-assistant/hassio/issues/1003

**Comment by frenck** [comment]
Closing the issue on this end, home-assistant/hassio is indeed the correct location for this.
