### ISSUE TITLE
Deconz addon's integration uses the docker internal ip

### ISSUE THREAD

**Issue by isabellaalstrom** [home-assistant/hassio-addons#522]
Not sure where this issue should be, but since it's regarding the addon I put it here.
I recently migrated my deconz installation from the un-official deconz addon to the official one. It seems like the config entry for the official addon uses the internal ip of the docker container to integrate. The problem with that is it can change with restarts. Then you have to remove the integration and make a new one to get the deconz integration working again. I tried adding the docker hosts ip and correct port in config entries manually and restarting, but that didn't work (it should, though?). I can try to provide other information/logs if needed.

**Comment by daranto** [comment]
I have the same problem. After that I moved back to the docket image.

**Comment by isabellaalstrom** [comment]
Yeah I'm running it separetly in docker now as well.

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassio-addons/blob/master/deconz/CHANGELOG.md

**Comment by Kane610** [comment]
Next release of hass (0.92) will also enable discovery to update deconz address if it changes

**Comment by frenck** [comment]
This issue has been addressed. Closing issue.
