### ISSUE TITLE
Unable to limit logs

### ISSUE THREAD

**Issue by sickidolderivative** [home-assistant/hassio-addons#523]
I want to limit the amount of messages in mosquitto addon logs. I have a simple mqtt client that reconnects every second to read and/or post. That results in excessive logs.

I run Home Assistant 0.87.0 on HassOS 2.8.

My addon setup is the following:
{
"logins": [],
"anonymous": false,
"customize": {
"active": true,
"folder": "mosquitto"
},
"certfile": "fullchain.pem",
"keyfile": "privkey.pem"
}

Content of /share/mosquitto/mosquitto.conf file is the following:
log_type none
connection_messages false
log_dest none

Despite the above settings, I get multiple [INFO] messages on every login:

[INFO] found mqtt on Home Assistant
[INFO] found mqtt on Home Assistant
[INFO] found mqtt on Home Assistant
[INFO] found mqtt on Home Assistant

mqtt is the username in HA used for login by mosquitto client.

**Comment by sickidolderivative** [comment]
There's even more messages in the System Log (Hass.io->System):
19-02-21 06:34:26 INFO (MainThread) [hassio.auth] Auth request from core_mosquitto for mqtt
19-02-21 06:34:27 INFO (MainThread) [hassio.auth] Success login from mqtt
19-02-21 06:34:27 INFO (MainThread) [hassio.auth] Auth request from core_mosquitto for mqtt
19-02-21 06:34:29 INFO (MainThread) [hassio.auth] Success login from mqtt
19-02-21 06:34:30 INFO (MainThread) [hassio.auth] Auth request from core_mosquitto for mqtt
19-02-21 06:34:31 INFO (MainThread) [hassio.auth] Success login from mqtt

Is there a way to stop this madness?

**Comment by sickidolderivative** [comment]
With the release of Mosquitto 4.1 the addon logs are flooded with even more messages:

`[INFO] found mqtt on local database
1552314298: |-- getuser(mqtt) AUTHENTICATED=1 by http
1552314298: |-- mosquitto_auth_acl_check(..., client id not available, mqtt, homie/mPowerPRO/port2/voltage, MOSQ_ACL_WRITE)
1552314298: |-- url=http://127.0.0.1:8080/superuser
1552314298: |-- data=username=mqtt&password=&topic=&acc=-1&clientid=
1552314298: |-- aclcheck(mqtt, homie/mPowerPRO/port2/voltage, 2) SUPERUSER=Y by http
1552314298: |--  Cached  [1B67C6B6012BE9AD042327A6813061E1495AA5EF] for (client id not available,mqtt,2)
1552314298: |-- mosquitto_auth_unpwd_check(mqtt)
1552314298: |-- ** checking backend http
1552314298: |-- url=http://127.0.0.1:8080/login
1552314298: |-- data=username=xxx&password=yyy&topic=&acc=-1&clientid=`

**Comment by signaleleven** [comment]
> [INFO] found mqtt on Home Assistant

These are logged by the bash script that acts as authentication interface to allow to use users set up on homeassistant. There is no way to silence those, that I could see, although it's a fairly simple change.
I'd take a crack at it, but as of now it's just a drop in the sea, given how chatty mosquitto is and how apparently the log directives in the config file are ignored (I suppose because it's started with `mosquitto -v ` but I am not sure)

**Comment by frenck** [comment]
This issue has been addressed in #572. Closing issue.
