### ISSUE TITLE
snips-injection

### ISSUE THREAD

**Issue by s00500** [home-assistant/hassio-addons#525]
Hi, Snips asr injection was removed instead of updated to the correct package name

>> snips-injection

This would be very very usefull!!!

**Comment by s00500** [comment]
https://docs.snips.ai/articles/advanced/dynamic-vocabulary

**Comment by pvizeli** [comment]
Please update the docker file that it does the right thing and I can make an update 👍

**Comment by s00500** [comment]
Checkout my pull request, all necessary changes should be there, I also did a version bump to 5.2 but I can remove that if you wish, just let me know

**Comment by s00500** [comment]
done in #546
