### ISSUE TITLE
Mosquitto Mqtt not connecting after update

### ISSUE THREAD

**Issue by sheminasalam** [home-assistant/hassio-addons#548]
My mosquitto addon was working fine before the last update to 4.1. Now none of my devices are connecting. i use the latest hassio for OPi Prime board. 

the log is as follows

```
[INFO] found username on local database
1552443135: |-- getuser(username) AUTHENTICATED=1 by http
1552443135: |-- mosquitto_auth_unpwd_check(username)
1552443135: |-- ** checking backend http
1552443135: |-- url=http://127.0.0.1:8080/login
1552443135: |-- data=username=username&password=password&topic=&acc=-1&clientid=
1552443135: New client connected from 192.168.0.53 as DVES_DB0966 (c1, k10, u'username').
[INFO] found username on local database
1552443137: New client connected from 192.168.0.64 as DVES_9775FA (c1, k10, u'username').
1552443137: |-- getuser(username) AUTHENTICATED=1 by http
1552443137: |-- mosquitto_auth_unpwd_check(username)
1552443137: |-- ** checking backend http
1552443137: |-- url=http://127.0.0.1:8080/login
1552443137: |-- data=username=username&password=password&topic=&acc=-1&clientid=
[INFO] found username on local database
1552443140: |-- getuser(username) AUTHENTICATED=1 by http
1552443140: New client connected from 192.168.0.54 as DVES_E0EAAD (c1, k10, u'username').
1552443140: |-- mosquitto_auth_unpwd_check(username)
1552443140: |-- ** checking backend http
1552443140: |-- url=http://127.0.0.1:8080/login
1552443140: |-- data=username=username&password=password&topic=&acc=-1&clientid=
[INFO] found username on local database
1552443143: |-- getuser(username) AUTHENTICATED=1 by http
1552443143: New client connected from 192.168.0.66 as DVES_A780E2 (c1, k10, u'username').
1552443143: |-- mosquitto_auth_unpwd_check(username)
1552443143: |-- ** checking backend http
1552443143: |-- url=http://127.0.0.1:8080/login
1552443143: |-- data=username=username&password=password&topic=&acc=-1&clientid=

```

**Comment by hcooper** [comment]
Potentially the same as https://github.com/home-assistant/hassio-addons/issues/545 (a new default drop all ACL).

**Comment by jirisembera** [comment]
I have a similar problem. It seems things are OK right after start - clients connect, some messages get through. But after a very short while everything breaks and clients are reconnecting. There's a clear pattern in the log:

`1553539841: New client connected from 192.168.0.116 as MQTT_FX_Client (c1, k60, u'user').
1553539841: |-- mosquitto_auth_acl_check(..., client id not available, d1mini, /test/vacuum/state, MOSQ_ACL_WRITE)
1553539841: |-- aclcheck(d1mini, /test/vacuum/state, 2) CACHEDAUTH: 0
1553539841: |-- mosquitto_auth_acl_check(..., client id not available, user, /test/vacuum/state, MOSQ_ACL_READ)
1553539841: |-- aclcheck(user, /test/vacuum/state, 1) CACHEDAUTH: 0
1553539841: |-- mosquitto_auth_acl_check(..., client id not available, d1mini, /test/vacuum/internal, MOSQ_ACL_WRITE)
1553539841: |-- aclcheck(d1mini, /test/vacuum/internal, 2) CACHEDAUTH: 0
1553539842: New connection from 192.168.0.116 on port 1883.
1553539842: |-- mosquitto_auth_unpwd_check(user)
1553539842: |-- ** checking backend http
1553539842: |-- url=http://127.0.0.1:8080/login
1553539842: |-- data=username=user&password=user&topic=&acc=-1&clientid=
[INFO] found user on local database
1553539845: |-- getuser(user) AUTHENTICATED=1 by http
1553539845: Client MQTT_FX_Client already connected, closing old connection.
1553539845: Socket error on client MQTT_FX_Client, disconnecting.
1553539845: New client connected from 192.168.0.116 as MQTT_FX_Client (c1, k60, u'user').
...and it repeats again and again...`

I've tried to setup the ACL according to the setup guide but it did not solve this one.

**Comment by sheminasalam** [comment]
any luck with the new update
