### ISSUE TITLE
MariaDB: Please use mysql_upgrade to fix this error after update

### ISSUE THREAD

**Issue by deejaybeam** [home-assistant/hassio-addons#555]
MariaDB shows many errors after upgrading. Message is "[Warning] InnoDB: Table mysql/innodb_table_stats has length mismatch in the column name table_name.  Please run mysql_upgrade" in core-mariadb.err and also when connecting with HeidiSQL: "/* SQL Error (1558): Column count of mysql.proc is wrong. Expected 21, found 20. Created with MariaDB 100122, now running 100313. Please use mysql_upgrade to fix this error */" Tryed to execute mysql_upgrade, but it is not installed in this container.

**Comment by peter1960** [comment]
I have the same issue and cannot create any store procedures:
Created with MariaDB 100122, now running 100313. Please use mysql_upgrade to fix this error

**Comment by pvizeli** [comment]
PR are welcome

**Comment by Sk-Azraf-Sami** [comment]
I find the solution from stackoverflow- https://stackoverflow.com/a/73882030/22856084. It works for me.
