### ISSUE TITLE
Not: command not found

### ISSUE THREAD

**Issue by mckaycr** [home-assistant/hassio-addons#556]
Everytime this add-on pulls changes I get this

`/usr/bin/hassio: line 1: Not: command not found`
`[Error] Configuration updated but it does not pass the config check. Do not restart until this is fixed!`

I didn't see any other issues like this.

thoughts?

**Comment by pvizeli** [comment]
hmm

**Comment by thijsdejong** [comment]
I am having the exact same issue.

**Comment by dgshue** [comment]
Dito

**Comment by fust** [comment]
Same issue, version ```7.2```

**Comment by scottsuine** [comment]
Yes same issue for me too, version 7.2

**Comment by mckaycr** [comment]
I know this doesn't really help fix this tool, but I switched from using this git add-on to just using gitlab deployment automation.  A pain to set up, but a breeze to use afterwords.

**Comment by fust** [comment]
@mckaycr That's a good workaround but unfortunately not feasible for me as I'm using Gogs with Drone on a private VPS.

**Comment by strangiato** [comment]
+1 for the issue

**Comment by thijsdejong** [comment]
@pvizeli any update on this?

**Comment by PProvost** [comment]
I'm guessing you guys don't need more votes, but I'm having the same experience. Have to manual restart after the pull. Manually running "hassio ha check" passes just fine.

**Comment by fust** [comment]
I've tested this on a x86_64 windows 10 machine using the aarch64 images and there it works just fine.
Further more, the problem seems to be related to the hassio-cli package for ARM being used in the current Docker image.

**Comment by strangiato** [comment]
Thanks for testing it out @fust.  

I have reported the issue upstream [here](https://github.com/home-assistant/home-assistant-cli/issues/240) if anyone else would like to comment.

**Comment by strangiato** [comment]
Sorry, looks like I posted to the wrong CLI project.  Correct issue has been posted [here](https://github.com/home-assistant/hassio-cli/issues/160) instead.

**Comment by fust** [comment]
It might be resolved by upgrading or downgrading the CLI image used in the git_pull addon.
As the addon worked in the past the problem seems to be specific to the version used now (2.0.1).
Unfortunately I can't test that right now.

**Comment by cwawak** [comment]
@fust would you be able to point to some directions to test an older version of the git_pull addon? Happy to test, but I have no idea how to launch custom addons like that on hass.io on a Pi.

**Comment by fust** [comment]
I'd have to experiment some to see if this actually works but I imagine you could:
- log in to the host (through SSH on [port 22222](https://developers.home-assistant.io/docs/en/hassio_debugging.html#hassos-based-hassio) or directly with a USB keyboard)
- remove the current version of the container
- spin up an older version through `docker run`

It should register with the supervisor so it is picked up in the hass.io dashboard.
