### ISSUE TITLE
Can't install addon-ssh on hassos 2.11

### ISSUE THREAD

**Issue by bahuma20** [home-assistant/hassio-addons#558]
## Problem/Motivation

After the update to hassos 2.11, when trying to install the addon via the addon store it can't be installed.

## Expected behavior

It should install the addon.

## Actual behavior

The addon isn't installed, in the system logs you see:
`19-03-26 18:34:50 ERROR (SyncWorker_2) [hassio.docker.interface] Can't install homeassistant/armv7-addon-ssh:5.3 -> 500 Server Error: Internal Server Error ("layer does not exist").`

## Steps to reproduce

Install hass.io 0.90.1 on hassos 2.11, go to the addon store, find the ssh addon, click on install.

**Comment by uglurass** [comment]
Did you try the ssh & web terminal?
