### ISSUE TITLE
Configurator V3 has no default config and unable to validate

### ISSUE THREAD

**Issue by jkabradley** [home-assistant/hassio-addons#564]
Hello,

I downloaded the Configurator V3, there is no default configuration provided, even when I click the button "Reset to Default".  When I copy/paste/edit the default config from the Home Assistant site (https://www.home-assistant.io/addons/configurator/), I am also unable to save it.  When I check the Hass.io supervisor's log, I see this:

`19-04-09 13:15:40 WARNING (MainThread) [hassio.addons.validate] Unknown options username
19-04-09 13:15:40 WARNING (MainThread) [hassio.addons.validate] Unknown options password
19-04-09 13:15:40 WARNING (MainThread) [hassio.addons.validate] Unknown options ssl
19-04-09 13:15:40 WARNING (MainThread) [hassio.addons.validate] Unknown options certfile
19-04-09 13:15:40 WARNING (MainThread) [hassio.addons.validate] Unknown options keyfile
19-04-09 13:15:40 WARNING (MainThread) [hassio.addons.validate] Unknown options verify_hostname
19-04-09 13:15:40 WARNING (MainThread) [hassio.addons.validate] Unknown options allowed_networks
19-04-09 13:15:40 WARNING (MainThread) [hassio.addons.validate] Unknown options banned_ips
19-04-09 13:15:40 WARNING (MainThread) [hassio.addons.validate] Unknown options banlimit
19-04-09 13:15:40 WARNING (MainThread) [hassio.addons.validate] Unknown options ignore_pattern
19-04-09 13:15:40 WARNING (MainThread) [hassio.addons.validate] Unknown options dirsfirst
19-04-09 13:15:40 WARNING (MainThread) [hassio.addons.validate] Unknown options enforce_basepath
19-04-09 13:15:40 WARNING (MainThread) [hassio.addons.validate] Unknown options notify_service`

I've tried removing/reinstalling the addon, but doesn't seem to help.

I'm running hass.io Docker image on top of Ubuntu 18.04LTS if that's relevant.

Thanks!

**Comment by pvizeli** [comment]
There is no config around now. 3.1 add 2 options back

**Comment by jkabradley** [comment]
OK it does work.  The issue was the documentation I linked above no longer applies.  This is tied to the V3 configurator using the new Ingress system.
