### ISSUE TITLE
Core configurator addon fails to install/upgrade

### ISSUE THREAD

**Issue by palvarez89** [home-assistant/hassio-addons#565]
It currently fails with:

    19-04-09 22:29:44 ERROR (MainThread) [hassio.addons.addon] Add-on core_configurator not supported on raspberrypi3 with ['armv7', 'armhf'] architecture.

**Comment by pvizeli** [comment]
You need to update to min 0.91.1

**Comment by palvarez89** [comment]
That's right, thanks!
