### ISSUE TITLE
DeCONZ and ingress problems

### ISSUE THREAD

**Issue by indyspike** [home-assistant/hassio-addons#566]
Since updating to version 2.0 of the addon, the "Open Web UI" link opens up what appears to be an unconfigured Phoscon instance with an unclickable raspbee image.

Connecting via IP address and port gives me the expected web interface and conbee image.

Hassio version 0.91.3

**Comment by SukramJ** [comment]
Hi,
i can confirm the issue, when my nginx (for ssl) is running.
If nginx is disabled and i use http + dns-name +port 8123 ingress works for deconz.
BR

**Comment by andersmolausson** [comment]
Me too, Phoscon works but no connection with Hassio. Can't find out why.

**Comment by ttroy50** [comment]
I've having a similar issue. I upgraded HA 0.91.4 and deconz to v2.1 and can not longer see any of my zigbee devices.

I'm running HA with hassio on a intel nuc and am getting the error

```
2019-04-20 23:10:59 DEBUG (MainThread) [pydeconz.utils] Sending {} to http://172.30.33.3:80/api/EA8CF97341
2019-04-20 23:11:02 ERROR (MainThread) [.] Error connecting to deCONZ gateway at 172.30.33.3
```
