### ISSUE TITLE
MariaDB ability to set different path for storage

### ISSUE THREAD

**Issue by escoand** [home-assistant/hassio-addons#576]
I would like to use an external path for the MariaDB storage. I use Hass.io on ODROID-HC1 which has an SATA slot and I would like to use SSD in it for the database.

**Comment by escoand** [comment]
I'm still interested in this feature.

**Comment by danimtb** [comment]
I found this interesting too. I would like to store the database in an external usb drive. I think it is just a matter of chaging the datadir in the configuration file https://github.com/home-assistant/hassio-addons/blob/97156f0f093c8ebfaa8fb6f1dec0dbe3506094eb/mariadb/mariadb-server.cnf#L6

**Comment by danimtb** [comment]
Or maybe making the variable `MARIADB_DATA` configurable from options
https://github.com/home-assistant/hassio-addons/blob/97156f0f093c8ebfaa8fb6f1dec0dbe3506094eb/mariadb/run.sh#L5

**Comment by danimtb** [comment]
Didn't have the time to look into this but I am still interested in having support for this

**Comment by danimtb** [comment]
I will be having a look at this soon once I set up everything for my new home assistant instance. Please do not close this issue

**Comment by frenck** [comment]
We have discussed this and decided not to go this route. There are many things that can go wrong if a user misconfigures this, and from our end things can become unpredictable. 

If you need this, we suggest maintaining your own version of the add-on.

**Comment by danimtb** [comment]
@frenck would you suggest any workaround for this?

**Comment by frenck** [comment]
@danimtb Well, the add-on is open source, so you are free to maintain/create a fork of it or create your own version.

**Comment by danimtb** [comment]
I know that alternative, I was asking about a workaround with the officially supported addons and home assistant features. Thanks

**Comment by frenck** [comment]
There is currently not a supported workaround available.

**Comment by danimtb** [comment]
Ok, thanks for the answer. I will take a look to the issue from my side.
