### ISSUE TITLE
Mosquitto daemon with enabled »auth-plug« plugin is very slow

### ISSUE THREAD

**Issue by vansoest** [home-assistant/hassio-addons#585]
### Problem
If the **mosquitto.conf** inside the docker container has the `auth_plugin` normally enabled like this:

snippet of **/etc/mosquitto.conf**:
```
auth_plugin /usr/share/mosquitto/auth-plug.so
auth_opt_backends http
auth_opt_http_ip 127.0.0.1
auth_opt_http_port 8080
auth_opt_http_getuser_uri /login
auth_opt_http_superuser_uri /superuser
auth_opt_http_aclcheck_uri /acl
auth_opt_log_quiet true
```

the mqtt command publishing will be very slow on my systems like:
`$ time mosquitto_pub -V mqttv311  -h mqtt.lan -t "/milight/commands/0xA/rgb_cct/1" -m '{"state":"ON"}' -u device -P secret `
> 0,00s user 0,00s system 0% cpu 3,256 total

responds after 3 seconds … 3 seconds later the answer will also be shown by the **mosquitto_sub** command.

If I disable the plugin inside the docker container temporary with out commenting all lines related to the plugin, publish command will work normally < 0,006s.

`$ time mosquitto_pub -V mqttv311  -h mqtt.lan -t "/milight/commands/0xA/rgb_cct/1" -m '{"state":"ON"}' -u device -P secret`
> 0,00s user 0,00s system 34% cpu 0,006 total

### Workaround

I’ve created **auth.conf** at **/share/mosquitto/** also enabled active to true in the json. And copied my generated **passwd** file also to /share/mosquitto/passwd now it run’s fast.

**auth.conf**
`password_file /share/mosquitto/passwd`

**Comment by frenck** [comment]
There is not much we can do about this. The authentication against an external source (Home Assistant) adds extra processing time.

The workaround is actually pretty fine to use since that is the freedom the add-on gives.

I would suggest on closing this issue, since, from an add-on perspective, there is not much we can do.

**Comment by vansoest** [comment]
We can add my way to the documentation or add an easy way to enable it for the container. I think it’s not best practice to have +3 seconds extra processing time for each MQTT command. It makes the whole automation with the default configuration very slow.
