### ISSUE TITLE
Clean install of hass.io with HASS Configurator gives 401: Unauthorized error

### ISSUE THREAD

**Issue by YRRK** [home-assistant/hassio-addons#595]
Hi,

I just did a clean install of Hass os on raspberrie pie 3b+ everything works great immidiately. But then i want to add some custom things so I installs HASS Configurator according to the online manual. After install i'm going to the configurator on the left menu bar. And I get an 401: Unauthorized error imidiately.
I followed all procedures. What's wrong?
With kind regards!

**Comment by frenck** [comment]
@YRRK Just tested this on a clean installation myself (just to make sure the last release of the add-on didn't break things).

But I'm unable to reproduce. Could you provide us more details? Like reproduction steps, hardware information, add-on configurations and log outputs? Thanks! 👍

**Comment by YRRK** [comment]
The cleaninstall detected HUE plugin with it's zigbee device offcourse. And the HomeAssistent detected my 2 Panasonic TV's and Apple TV. So that's extra on my rasperry pie 3b+

Here's my Hass configurator log after installing:

[12:07:58] INFO: Add-on running
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file './resty/core.lua'
	no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core/init.lua'
	no file '/usr/share/lua/5.1/resty/core.lua'
	no file '/usr/share/lua/5.1/resty/core/init.lua'
	no file '/usr/share/lua/common/resty/core.lua'
	no file '/usr/share/lua/common/resty/core/init.lua'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
2019/06/02 12:07:58 [notice] 21#21: using the "epoll" event method
2019/06/02 12:07:58 [notice] 21#21: nginx/1.14.2
2019/06/02 12:07:58 [notice] 21#21: OS: Linux 4.14.98-v7
2019/06/02 12:07:58 [notice] 21#21: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2019/06/02 12:07:58 [notice] 21#21: start worker processes
2019/06/02 12:07:58 [notice] 21#21: start worker process 29
	no file '/usr/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so')
INFO:2019-06-02 12:07:59,068:hass_configurator.configurator:Starting server
INFO:2019-06-02 12:07:59,069:hass_configurator.configurator:Listening on: http://127.0.0.1:80

**Comment by YRRK** [comment]
By the way. I used the version I downloaded from the homeassistent website: hassos_rpi3-2.12.img.gz

**Comment by frenck** [comment]
The resty core warnings are not pretty, but not blocking for the working of the add-on.

From the log file you posted, it looks great! 😟

**Comment by frenck** [comment]
Could you get the logs from the supervisor, right after you get the error?
Supervisor logs can be found at: **Hass.io** panel in the menu bar -> **System** tab -> Log.

**Comment by YRRK** [comment]
Here the logs after the install, starting, and then clicking to see the 401 error.

19-06-03 18:03:54 INFO (MainThread) [__main__] Initialize Hass.io setup
19-06-03 18:03:54 INFO (MainThread) [__main__] Setup HassIO
19-06-03 18:03:54 INFO (SyncWorker_0) [hassio.docker.supervisor] Attach to Supervisor homeassistant/armv7-hassio-supervisor with version 165
19-06-03 18:03:54 INFO (MainThread) [hassio.utils.gdbus] Introspect org.freedesktop.systemd1 on /org/freedesktop/systemd1
19-06-03 18:03:55 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.systemd1 - /org/freedesktop/systemd1
19-06-03 18:03:55 INFO (MainThread) [hassio.utils.gdbus] Introspect org.freedesktop.hostname1 on /org/freedesktop/hostname1
19-06-03 18:03:55 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: org.freedesktop.hostname1 - /org/freedesktop/hostname1
19-06-03 18:03:55 INFO (MainThread) [hassio.utils.gdbus] Introspect de.pengutronix.rauc on /
19-06-03 18:03:55 INFO (MainThread) [hassio.utils.gdbus] Connect to dbus: de.pengutronix.rauc - /
19-06-03 18:03:55 INFO (MainThread) [hassio.host.info] Update local host information
19-06-03 18:03:55 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.DBus.Properties.GetAll on /org/freedesktop/hostname1
19-06-03 18:03:55 INFO (MainThread) [hassio.host.services] Update service information
19-06-03 18:03:55 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ListUnits on /org/freedesktop/systemd1
19-06-03 18:03:56 INFO (MainThread) [hassio.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
19-06-03 18:03:56 INFO (MainThread) [hassio.host.services] Reload local service hassos-apparmor.service
19-06-03 18:03:56 INFO (MainThread) [hassio.utils.gdbus] Call org.freedesktop.systemd1.Manager.ReloadOrRestartUnit on /org/freedesktop/systemd1
19-06-03 18:03:56 INFO (SyncWorker_2) [hassio.docker.interface] Attach to homeassistant/raspberrypi3-homeassistant with version 0.93.2
19-06-03 18:03:56 INFO (MainThread) [hassio.hassos] Detect HassOS 2.12 on host system
19-06-03 18:03:56 INFO (SyncWorker_0) [hassio.docker.hassos_cli] Found HassOS CLI homeassistant/armv7-hassio-cli with version 9
19-06-03 18:03:57 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/core repository
19-06-03 18:03:57 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/git/a0d7b954 repository
19-06-03 18:03:57 INFO (MainThread) [hassio.store] Load add-ons from store: 59 all - 59 new - 0 remove
19-06-03 18:03:57 INFO (MainThread) [hassio.addons] Found 2 installed add-ons
19-06-03 18:03:57 INFO (SyncWorker_4) [hassio.docker.interface] Attach to homeassistant/armv7-addon-check_config with version 2.1
19-06-03 18:03:57 INFO (SyncWorker_5) [hassio.docker.interface] Attach to hassioaddons/influxdb-armv7 with version v3.0.5
19-06-03 18:03:57 INFO (MainThread) [hassio.updater] Fetch update data from https://s3.amazonaws.com/hassio-version/stable.json
19-06-03 18:03:58 INFO (MainThread) [hassio.snapshots] Found 0 snapshot files
19-06-03 18:03:58 INFO (MainThread) [hassio.discovery] Load 0 messages
19-06-03 18:03:58 INFO (MainThread) [hassio.ingress] Load 2 ingress session
19-06-03 18:03:58 INFO (MainThread) [__main__] Run Hass.io
19-06-03 18:03:58 INFO (MainThread) [hassio.misc.dns] Start DNS port forwarding for host add-ons
19-06-03 18:03:58 INFO (MainThread) [hassio.api] Start API on 172.30.32.2
19-06-03 18:03:58 INFO (MainThread) [hassio.addons] Phase 'initialize' start 0 add-ons
19-06-03 18:03:58 INFO (MainThread) [hassio.addons] Phase 'system' start 0 add-ons
19-06-03 18:03:58 INFO (MainThread) [hassio.addons] Phase 'services' start 1 add-ons
19-06-03 18:04:03 INFO (SyncWorker_6) [hassio.docker.addon] Start Docker add-on hassioaddons/influxdb-armv7 with version v3.0.5
19-06-03 18:04:06 INFO (MainThread) [hassio.api.security] /host/info access from a0d7b954_influxdb
19-06-03 18:04:08 INFO (SyncWorker_2) [hassio.docker.interface] Start homeassistant/raspberrypi3-homeassistant
19-06-03 18:04:51 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
19-06-03 18:04:51 INFO (MainThread) [hassio.addons] Phase 'application' start 0 add-ons
19-06-03 18:04:51 INFO (MainThread) [hassio.tasks] All core tasks are scheduled
19-06-03 18:04:51 INFO (MainThread) [hassio.core] Hass.io is up and running
19-06-03 18:06:24 INFO (MainThread) [hassio.addons] Create Home Assistant add-on data folder /data/addons/data/core_configurator
19-06-03 18:06:24 INFO (SyncWorker_18) [hassio.docker.interface] Pull image homeassistant/armv7-addon-configurator tag 3.4.
19-06-03 18:06:34 INFO (SyncWorker_18) [hassio.docker.interface] Tag image homeassistant/armv7-addon-configurator with version 3.4 as latest
19-06-03 18:06:37 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-06-03 18:06:37 INFO (MainThread) [hassio.ingress] Update Ingress as panel for core_configurator
19-06-03 18:06:46 INFO (SyncWorker_10) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-configurator with version 3.4
19-06-03 18:06:51 WARNING (MainThread) [hassio.api.ingress] No valid ingress session None

**Comment by YRRK** [comment]
Wait a minute...what the heck! The Ghostery Add blocker browser plug-in couses the 401: Unauthorized error. 
Strange, I'd never had any trouble with that plugin....what's there to block then...
Well case solved, but maybe interesting to investigate what goes wrong there.... :-)

**Comment by frenck** [comment]
Glad you got it resolved @YRRK! Interesting... if you find out, please let me know :D

**Comment by gadgetsmith** [comment]
> 
> 
> Wait a minute...what the heck! The Ghostery Add blocker browser plug-in couses the 401: Unauthorized error.

Oh My Goodness!  THANK YOU.  I've been searching for months to a definitive answer to this issue.  This was it.  What's worse is that Ghostery is blocking it, but doesn't indicate it's blocking.  Just needed to add it to "Trust Site", and everything works as it should.

Thanks again!

**Comment by SittingDuc** [comment]
+1
Been chasing this one for weeks and telling ghostery "trusted site" fixed it. 
FYI: "home assistant" "configurator" "401 Unauthorised" is almost useless as a google search term.
