### ISSUE TITLE
core_ssh addon fails to run after 5.5 update

### ISSUE THREAD

**Issue by colindunn** [home-assistant/hassio-addons#599]
Just updated to 5.5 and the core_ssh addon stops after starting. 

```
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                       PORTS                                            NAMES
69bdb4fda944        homeassistant/armv7-addon-ssh              "/run.sh"                4 minutes ago       Exited (141) 4 minutes ago                                                    addon_core_ssh
```

Logs:
```
# docker logs addon_core_ssh
[21:29:03] INFO: Initializing add-on for use...
[21:29:04] INFO: Setup authorized_keys
```

I've made no config changes, only updated the addon

**Comment by aceat64** [comment]
I have the same issue, it works if I don't specify any authorized_keys and instead use a password.

```
[12:18:17] INFO: Initializing add-on for use...
[12:18:18] INFO: Setup password login
[12:18:19] INFO: Restoring host keys...
[12:18:19] INFO: Starting SSH daemon...
debug1: Set /proc/self/oom_score_adj from 0 to -1000
debug1: Bind to port 22 on 0.0.0.0.
Server listening on 0.0.0.0 port 22.
debug1: Bind to port 22 on ::.
Server listening on :: port 22.
```

**Comment by frenck** [comment]
Hmmm looking into it right now.

**Comment by frenck** [comment]
Issue has been addressed, update your SSH add-on to 5.6.

If the update does not appear: **Hass.io panel** -> **Add-on store** tab, hit the refresh icon top right. Wait for a second, update shows up 👍

**Comment by ossgeek314** [comment]
I get this when trying to upgrade/install

```19-06-03 18:31:20 ERROR (SyncWorker_9) [hassio.docker.interface] Can't install homeassistant/aarch64-addon-ssh:5.6 -> 404 Client Error: Not Found ("manifest for homeassistant/aarch64-addon-ssh:5.6 not found").```

**Comment by bjornconnolly** [comment]
Same here (for amd64)

19-06-03 19:23:21 ERROR (SyncWorker_0) [hassio.docker.interface] Can't install homeassistant/amd64-addon-ssh:5.6 -> 404 Client Error: Not Found ("manifest for homeassistant/amd64-addon-ssh:5.6 not found").

**Comment by frenck** [comment]
@ossgeek314 @bjornconnolly 
The build seems to be stuck... We are looking into kicking it back to live... hold on!

**Comment by frenck** [comment]
@ossgeek314 @bjornconnolly Fixed. Should be there now. Sorry about the delay.

**Comment by colindunn** [comment]
Thanks for the quick fix @frenck

**Comment by bjornconnolly** [comment]
Works perfectly again, thanks @frenck
