### ISSUE TITLE
[Feature Request-deCONZ] Allow VNC access to container to view ZigBee mesh

### ISSUE THREAD

**Issue by SiliconAvatar** [home-assistant/hassio-addons#609]
The [marthoc deCONZ Docker Image](https://github.com/marthoc/docker-deconz) has the option to enable a [VNC server](https://github.com/marthoc/docker-deconz#viewing-the-deconz-zigbee-mesh-with-vnc) to connect to the addon to view the ZigBee mesh. This is valuable for troubleshooting your mesh, as well as seeing the exact details of nodes, and debugging.

In the marthoc container, there are [3 environment variables](https://github.com/marthoc/docker-deconz#environment-variables): `DECONZ_VNC_MODE`, `DECONZ_VNC_PORT`, and `DECONZ_VNC_PASSWORD`.

It would be great if similar functionality was available in this core addon, with the ability to enable the VNC server, set the port, and password via the addon config.

**Comment by ricmik** [comment]
I would really like to see this too.

**Comment by hgelpke** [comment]
Please add this feature. It's necessary to properly diagnose and evaluate your mesh.

**Comment by SiliconAvatar** [comment]
Closing Issue.

Request has been fulfilled by [PR #615](https://github.com/home-assistant/hassio-addons/pull/615).

Thanks!
