### ISSUE TITLE
Unable to Install Deconz add-on

### ISSUE THREAD

**Issue by Parsnc** [home-assistant/hassio-addons#613]
Hello, 

I had problems updating the Deconz add-on. I then uninstalled it. But now i am unable to Install it. I find the following error message. 

ERROR (SyncWorker_15) [hassio.docker.interface] Can't install homeassistant/armhf-addon-deconz:2.6 -> 500 Server Error: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument").

Can someone please help me with this?
Thank you
Regards, 
Pars

**Comment by frenck** [comment]
That is not an error with the add-on, but an issue with your system.
Unfortunately, it seems like you are experiencing file system corruption.
