### ISSUE TITLE
Can not add new devices to deCONZ

### ISSUE THREAD

**Issue by thisisme** [home-assistant/hassio-addons#614]
**Home Assistant release with the issue:**
0.94.4

**Operating environment (Hass.io/Docker/Windows/etc.):**
Hass.io/Docker/Ubuntu
**Component/platform:**
Hass.io Core Add-on: deCONZ

**Description of problem:**
Since 2.7 I am unable to add new sensors.
I added several Aqara sensors, upgraded to 2.7 and now I can not add any more devices. The ones that has been added is working fine.

**Comment by frenck** [comment]
I'm not able to reproduce this issue.
Which stick are you using and what is the firmware version on that stick?

**Comment by thisisme** [comment]
It is Conbee ZigBee USB Gateway with firmware 260B0500.
How do I update the firmware?

**Comment by manup** [comment]
That's a quite old firmware, it can normally be updated in the Phoscon App > Menu > Settings > Gateway.

If that doesn't work you can try the manual update instructions on a native system:

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

**Comment by Kugelfang666** [comment]
@manup for some odd reason I cannot access the Phoscon App > Menu > Settings > Gateway menu. I'm always ending up with the interface but the actual buttons are missing. Any idea on what I'm doing wrong?

**Comment by frenck** [comment]
@Kugelfang666 You've already opened an issue for that. Please don't spam other issues with unrelated content. Thanks.

**Comment by thisisme** [comment]
I can't see any way to update the firmware in Phoscon app.
So I will need to get another computer and install phoscon to update the firmware?

How did @Kugelfang666 get Phoscon into the Hassio menu?

**Comment by frenck** [comment]
@thisisme As linked by @manup:

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

Yes, you can do that on a separate machine.

About the Hassio menu, that is most likely an iframe panel.

**Comment by Kugelfang666** [comment]
@thisisme

yep. I'm using an iframe for the integration:

`panel_iframe:
  phoscon:
    title: Phoscon
    icon: mdi:source-branch
    url: http://192.168.178.67:40850/pwa`

**Comment by thisisme** [comment]
Finally found an old laptop with windows on it.
It worked fine to install new firmware and now it works fine!
Thanks for the help

**Comment by frenck** [comment]
Glad you got it resolved there @thisisme! :D
