### ISSUE TITLE
deCONZ gateway settings not loading

### ISSUE THREAD

**Issue by Kugelfang666** [home-assistant/hassio-addons#618]
Dear all, 

im currently running HASSIO 0.94.4 and deCONZ 3.1 on my Raspberry pi 3+ with an attached ConBee USB gateway (V1).

If I access the web interface and go to settings --> gateway the page is basically empty and all the buttons are missing except the two buttons on the bottom of the page (basic / advanced) which are not functioal

the Add-on itself (connection to my sensors etc) is working flawlessly 

![Bildschirmfoto 2019-06-28 um 18 29 45](https://user-images.githubusercontent.com/3289654/60357101-fb4fbe80-99d2-11e9-9935-1d28ad72658d.png)

**Comment by frenck** [comment]
I don't know or see what this problem causes.

Some things you can do: 

- Try a different browser
- Try it directly without the iframe
- Ensure your deCONZ USB stick runs the latest firmware (I've had some weird issue like these).

Please check the add-on log output for issues and the debug console of your browser for hints.

**Comment by Kugelfang666** [comment]
@frenck: thanks for looking into this! 

I already tried chrome, FF and Safari. Also with and without I frame. I remember that I updated the firmware a few weeks ago but I'll give it another try on a dedicated machine and see if that fixes it.

**Comment by Kugelfang666** [comment]
Hmm just updated the stick via my windows machine using the instruction to the latest firmware available from Dresden Electronic (deCONZ_Rpi_0x26330500.bin.GCF) unfortunately the problem still persits

**Comment by Kugelfang666** [comment]
so I just tried to access the gateway settings page using safari on my iPhone and to my surprise that works! so it seems that there is really something wrong when accessing via my Mac

**Comment by Kugelfang666** [comment]
Seems to be a problem related to deCONZ:

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1572
