### ISSUE TITLE
Trouble with migration from marthoc deconz to official deconz adon

### ISSUE THREAD

**Issue by eskimos2000** [home-assistant/hassio-addons#621]
I tried to migrate to official deconz and what I have done:
1. Backup up at Phoscan app all lights etc.
2. Stoped marthoc addon installed.
3.  Restarted HA
4. Installed official aaddon 3.1 version.
5. Started and looks ok, webui (phoscan) setup new password and name. And restored from backup. Restarted addon, restarted HA.

`[17:18:34] INFO: Starting the deCONZ gateway...
[17:18:34] INFO: Running the deCONZ OTA updater...
[17:18:34] INFO: Running the IKEA OTA updater...
[17:18:34] INFO: Running Hass.io discovery task...
{"uuid":"f810487dcb11420280ff011b4aae55f2"}
[17:18:34] INFO: Success send discovery information to Home Assistant
[17:18:34] INFO: deCONZ is set up and running!
libpng warning: iCCP: known incorrect sRGB profile
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
17:18:35:132 HTTP Server listen on address 0.0.0.0, port: 40850, root: /usr/share/deCONZ/webapp/
17:18:35:215 CTRL. 3.16.217:18:35:633 COM: /dev/ttyUSB0 / serialno: 
17:18:35:633 COM: --dev: /dev/ttyUSB0 (ConBee)
17:18:35:634 ZCLDB init file /data/.local/share/dresden-elektronik/deCONZ/zcldb.txt
17:18:35:831 parent process bash
17:18:35:831 gw run mode: docker/hassio
17:18:35:832 GW sd-card image version file does not exist: /data/.local/share/dresden-elektronik/deCONZ/gw-version
17:18:35:832 sd-card cid: 1b534d454231515430ffffffff01253f
17:18:35:834 DB sqlite version 3.16.2
17:18:35:835 DB PRAGMA page_count: 59
17:18:35:835 DB PRAGMA page_size: 1024
17:18:35:835 DB PRAGMA freelist_count: 1
17:18:35:835 DB file size 60416 bytes, free pages 1
17:18:35:835 DB PRAGMA user_version: 6
17:18:35:835 DB cleanup
17:18:35:836 DB create temporary views
17:18:35:854 don't close database yet, keep open for 900 seconds
17:18:35:864 started websocket server at port 40860
17:18:35:870 discovery updated announce interval to 10 minutes
17:18:35:875 found node plugin: libde_rest_plugin.so - REST API Plugin
17:18:35:880 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
17:18:36:935 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
17:18:37:271 COM: /dev/ttyUSB0 / serialno: 
17:18:37:271 COM: --dev: /dev/ttyUSB0 (ConBee)
17:18:37:405 Device firmware version 0x26330500
17:18:37:416 unlocked max nodes: 200
17:18:37:705 Device protocol version: 0x010B
17:18:37:728 new node - ext: 0x00212effff017192, nwk: 0x0000
17:18:37:897 don't close database yet, keep open for 900 seconds
17:18:37:897 LightNode 1: Hallway light added
17:18:38:020 don't close database yet, keep open for 900 seconds
17:18:38:021 LightNode 4: Floor lamp added
17:18:38:022 SensorNode 9 set node 0x00158d00024919de
17:18:38:024 SensorNode 8 set node 0x00158d00024919de
17:18:38:110 don't close database yet, keep open for 900 seconds
17:18:38:111 LightNode 3: Reading lamp added
17:18:38:111 SensorNode 7 set node 0x00158d0001fa21b7
17:18:38:112 SensorNode 6 set node 0x00158d0001fa21b7
17:18:38:178 SensorNode 13 set node 0x00158d000215cb22
17:18:38:259 SensorNode 10 set node 0x00158d00030a049c
17:18:38:259 SensorNode 11 set node 0x00158d00030a049c
17:18:38:259 SensorNode 12 set node 0x00158d00030a049c
17:18:38:506 Current channel 15
17:18:38:593 CTRL ANT_CTRL 0x03
17:18:38:730 Device protocol version: 0x010B
17:18:38:781 scan skip host .18
17:18:38:923 Current channel 15
17:18:38:987 CTRL ANT_CTRL 0x03
17:18:41:231 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_Rpi_0x26330500.bin.GCF
17:18:41:231 GW firmware version: 0x26330500
17:18:41:231 GW firmware version is up to date: 0x26330500
17:18:42:161 Announced to internet
17:18:42:161 discovery server date: Tue, 02 Jul 2019 07:18:41 GMT
17:18:42:162 	 local time seems to be ok
17:18:42:162 discovery found version 2.04.35 for update channel stable
17:18:48:330 New websocket 192.168.0.104:51968 (state: 3) 
17:18:52:455 Websocket disconnected 192.168.0.104:51968 (state: 0) 
17:19:00:062 0x0017880104E85ABA error APSDE-DATA.confirm: 0xE1 on task
17:19:03:860 0x0017880104E85ABA error APSDE-DATA.confirm: 0xE1 on task
17:19:07:563 0x0017880104E85ABA error APSDE-DATA.confirm: 0xE1 on task
17:19:11:361 0x0017880104E85ABA error APSDE-DATA.confirm: 0xE1 on task
17:19:15:062 0x0017880104E85ABA error APSDE-DATA.confirm: 0xE1 on task
17:19:18:862 0x0017880104E85ABA error APSDE-DATA.confirm: 0xE1 on task
17:19:22:563 0x0017880104E85ABA error APSDE-DATA.confirm: 0xE1 on task
17:19:26:362 0x0017880104E85ABA error APSDE-DATA.confirm: 0xE1 on task
17:19:28:386 scan skip host .250
17:19:28:593 scan finished
17:19:30:097 0x0017880104E85ABA error APSDE-DATA.confirm: 0xE1 on task
17:19:33:878 0x0017880104E85ABA error APSDE-DATA.confirm: 0xE1 on task
17:19:34:952 Current channel 15
17:19:34:984 Device TTL 6033 s flags: 0x7
17:19:37:581 0x0017880104E85ABA error APSDE-DATA.confirm: 0xE1 on task
17:19:41:379 0x0017880104E85ABA error APSDE-DATA.confirm: 0xE1 on task`

5. HA discovered a new device, went to and:

![deconz1](https://user-images.githubusercontent.com/42510582/60491040-26941f80-9ceb-11e9-9247-a408d214ef8f.png)
I have to zigbee gateway now!?
Click first form the to to integrate (opened on Phoscan for authentication):
![deconz3](https://user-images.githubusercontent.com/42510582/60491159-71ae3280-9ceb-11e9-8bcd-b50fe0d93843.png)
Cliked second one:
![deconz2](https://user-images.githubusercontent.com/42510582/60491212-9acec300-9ceb-11e9-93bb-ceada96575e3.png)
Different popup but submit and seems to OK, I have deconz integrated:
![deconz4](https://user-images.githubusercontent.com/42510582/60491275-c18cf980-9ceb-11e9-8dce-d68182b2aedf.png)
But there is nothing in that integration?

And yeah Phoscan is running weird, I can not edit group names, or add or remove lights from group. 
What went wrong?

**Comment by eskimos2000** [comment]
I have un
![deconz5](https://user-images.githubusercontent.com/42510582/60501983-484bd180-9d00-11e9-8aeb-88c89c1916eb.png)
installed official deconz and installed marthoc one add I  have 4 gateway now, what the heck?

**Comment by frenck** [comment]
- Make backup of deconz data
- Remove add-ons
- Remove integration
- Restart Home Assistant
- Install add-on
- Add integration

That should do the trick.

**Comment by eskimos2000** [comment]
That did the trick, indeed, thx @frenck.

**Comment by frenck** [comment]
Glad you got it resolved @eskimos2000! 👍

**Comment by ChristophQu** [comment]
> * Make backup of deconz data
> * Remove add-ons
> * Remove integration
> * Restart Home Assistant
> * Install add-on
> * Add integration

ok, everthing works finde after this steps. There is a "deCONZ Zigbee Gateway: deCONZ-0000000000000000" integration with the sensor daylight.

But after restoring the backup my old devices are not there. Also sensor daylight is no longer available. In Phoscon the old zigbee network is there and can be used. Is there a way to switch from marthoc deconz to official deconz and keep the zigbee network?
