### ISSUE TITLE
deCONZ Add-on not populating services, devices or data to Home Assistant

### ISSUE THREAD

**Issue by cdrom1028** [home-assistant/hassio-addons#624]
The deCONZ Add-on seems to be working in that I can add sensors and access them via the Plug-in or via VNC and I can see the sensors reporting data correctly.  The Plugin is not communicating to Home Assistant at all. The deCONZ services (deconz.device_refresh and deconz.configure) are not populating and neither are any devices.  The integration panel shows "This integration has no devices."

The only indication I get of any issues are in the Home Assistant logs where I get a recurring error and warning.

```
WARNING (MainThread) [.] Invalid key for deCONZ at 172.30.32.1
ERROR (MainThread) [.] Error connecting with deCONZ gateway
```
I have upgraded the ConBee II, removed and reinstalled deCONZ, Reset the entire environment including removing and rebuilding the integration completely and I get the same results.

**Comment by pvizeli** [comment]
You need remove the integration first, after that the add-on. Then restart Home Assistant and setup a new deconz add-on

**Comment by cdrom1028** [comment]
Apparently I was the victim of an order of operations issue.. Thank you @pvizeli

1. Reset ConBee II using the reset gateway option.... (takes a while)
2. Stop and uninstall deCONZ Add-on, remove Integration from Lovelace.
3. Reboot Home assistant.
4. Install and configure deCONZ Add-on.
5. Recover password for ZigBee Gateway and configure time zone. 
          (If time zone does not write start over)
6. Add integration in Lovelace integration panel.
          (sensor.daylight and ConBee II should populate, If they do not, start over)
7. Pair Devices in deCONZ then configure devices in Lovelace.
          (Update names of devices and add to the UI)
8. Joy !!!

**Comment by 0evmc** [comment]
> Apparently I was the victim of an order of operations issue.. Thank you @pvizeli
> 
> 1. Reset ConBee II using the reset gateway option.... (takes a while)
> 2. Stop and uninstall deCONZ Add-on, remove Integration from Lovelace.
> 3. Reboot Home assistant.
> 4. Install and configure deCONZ Add-on.
> 5. Recover password for ZigBee Gateway and configure time zone.
>    (If time zone does not write start over)
> 6. Add integration in Lovelace integration panel.
>    (sensor.daylight and ConBee II should populate, If they do not, start over)
> 7. Pair Devices in deCONZ then configure devices in Lovelace.
>    (Update names of devices and add to the UI)
> 8. Joy !!!

I essentially ended up following these steps. My issue the last time around was that I tried to restore a backup file to the gateway instead of just re-adding all the nodes manually. I re-added all the nodes manually and everything is working fine now.

**Comment by estevez-dev** [comment]
> > Apparently I was the victim of an order of operations issue.. Thank you @pvizeli
> > 
> > 1. Reset ConBee II using the reset gateway option.... (takes a while)
> > 2. Stop and uninstall deCONZ Add-on, remove Integration from Lovelace.
> > 3. Reboot Home assistant.
> > 4. Install and configure deCONZ Add-on.
> > 5. Recover password for ZigBee Gateway and configure time zone.
> >    (If time zone does not write start over)
> > 6. Add integration in Lovelace integration panel.
> >    (sensor.daylight and ConBee II should populate, If they do not, start over)
> > 7. Pair Devices in deCONZ then configure devices in Lovelace.
> >    (Update names of devices and add to the UI)
> > 8. Joy !!!
> 
> I essentially ended up following these steps. My issue the last time around was that I tried to restore a backup file to the gateway instead of just re-adding all the nodes manually. I re-added all the nodes manually and everything is working fine now.
> The other important thing to mention is that, in order to re-add the nodes and have them discovered by the Phoscon portal, I had to delete them in the DeCONZ interface and re-discover them. Once I re-added all of them I was able to run the deconz refresh service to have them show up in Home Assistant.

Thank you so much @0evmc
Indeed restoring the gateway config will bring the issue back.
