### ISSUE TITLE
Mosquitto V5.0: No form during integration configuration

### ISSUE THREAD

**Issue by TomBrien** [home-assistant/hassio-addons#626]
I am following the [instructions here](https://www.home-assistant.io/addons/mosquitto/) to set up the mosquitto add on. All goes well until [step 3](https://www.home-assistant.io/addons/mosquitto/#using-mosquitto-with-hassio). When clicking configure, I do not get a form or text area to configure the add on, just the text and check box to enable discovery. 
![Hassio_mosquitto_conf](https://user-images.githubusercontent.com/12411302/60725628-84b24400-9f31-11e9-9e4f-d478512ac03a.PNG).

If I enable discovery and click Submit, I can see a device connecting in the add on log with:
```
1562333463: New client connected from 192.168.2.31 as shelly1-E30DD1 (p2, c1, k60, u'MQTT_user').
1562333966: New connection from 172.30.32.1 on port 1883.
```

But it does not appear in the integration.

Any attempt to call:
```
$ mosquitto_pub -h 127.0.0.1 -t home-assistant/switch/1/on -m "Switch is ON"
```
Gives `Error: Connection refused` even if I specify `-u MQTT_user -P <PASSWORD_HERE>` as well.

Using the actual IP of my RPi not `127.0.0.1` and a local username and password seems to remove the `Error: Connection refused response`. However, I am unable to see any messages being published or update a simple mqtt sensor created in `configuration.yaml`

**Comment by pvizeli** [comment]
the host is `core-mosquitto`

**Comment by TomBrien** [comment]
I got it working in the end following the instructions [here](https://community.home-assistant.io/t/mosquitto-mqtt-4-1-doesnt-work-after-update/104855/225). Mostly I think issue came from out of date docs. I'll try and get around to submitting an update. @pvizeli cheers that helps and is much more universal.
