### ISSUE TITLE
Allow more dnsmasq config options

### ISSUE THREAD

**Issue by danielo515** [home-assistant/hassio-addons#628]
I would love to be able to configure my dnsmasq addon as a dhcp server too, so I can also activate the functionality to use dhcp hosts to DNS local domain.

Is this possible in any way now? If not, could you consider adding it to the addon?

Thanks in advance.

**Comment by danielo515** [comment]
It is not stalled, just ignored.
Why did you added the wontfix label?

**Comment by danielo515** [comment]
Would love to read any kind of words written by a human, please.

**Comment by frenck** [comment]
We currently provide a DHCP add-on already. However, if someone wants to contribute DHCP functionality to the dnsmasq add-on, a PR can be created.

**Comment by danielo515** [comment]
@frenck which add-on are you talking about? Does it allow what I asked for (to serve leased ips through DNS). I think it is a very useful use-case.

**Comment by danielo515** [comment]
Oh, I see what you mean.
Yeah, there is an addon for DHCP and another for DNS, but they don't work together so the synergy is lost.

**Comment by pvizeli** [comment]
I used that together before and now with amazing ADGuard as DNS server and the DHCP add-on like before with dnsmasq

**Comment by danielo515** [comment]
Yes, you can use them together, but they will not share information, so you can not access your local devices by hostname, or am I wrong?

**Comment by mbrancato** [comment]
I had issues with the ISC DHCP server as well on a multi-homed network device. The wireless network I am serving is getting a secondary IP assigned by the ISC DHCP server. I agree dnsmasq is probably a clean option to serve both DNS and DHCP using a single service.
