### ISSUE TITLE
Git pull plugin requires repository to end in ".git"

### ISSUE THREAD

**Issue by pbolduc** [home-assistant/hassio-addons#629]
I am trying to pull from an Azure DevOops repository.  The clone url does not end in git.   For testing, I tried a fake url to check if ".git" was required to be at the end,

```json
"repository": "https://localhost/something",
```
gives an error: "not a valid value for dictionary value @ data['options']. Got ...", however, if I add a .git on the end,

```json
"repository": "https://localhost/something.git",
```

The configuration saves correctly.  Azure DevOps git repositories do not have .git at end, the basic format is:

```
https://username@dev.azure.com/account/project/_git/repository
```

I do not think there is any specification or standard that requires git clone urls to end in .git.  Can the validation be relaxed on the repository property?

**Comment by pbolduc** [comment]
Is this something that can be changed? I would gladly close this if there is some specification stating git repository urls MUST have .git on the end.   It really just seems like a convention used by many servers.

**Comment by pbolduc** [comment]
ping

**Comment by pvizeli** [comment]
I don't touch this, but feel free to provide improvements as a PR

**Comment by Cloudenius** [comment]
@pbolduc Would really like to use Azure DevOps as well. I can propose the improvement by changing the schema, but that might have impact I cannot foresee. @frenck, what do you think?

https://github.com/home-assistant/hassio-addons/blob/fc04afbba41bd1738ee0ae6aa16887258a389ef5/git_pull/config.json#L39

**Comment by frenck** [comment]
@Cloudenius If you want to contribute, that is welcome. Be sure to test the different use cases.

**Comment by Cloudenius** [comment]
Thanks @frenck. I'm working on it. Can you have a look at the test cases mentioned in the [draft PR](https://github.com/home-assistant/hassio-addons/pull/966)? Let me know if you are missing a test.

**Comment by Cloudenius** [comment]
@pbolduc My PR was merged into master. Can you install the add-on and let us know if it works for you? **Do make sure to backup your full config folder before you install the add-on.** Because of e.g. #968.

**Comment by frenck** [comment]
The issue has been addressed and published. The check has been removed in total, which will allow for any repo (even on a local path).

Closing this issue.
