### ISSUE TITLE
Configurator: snapshot upload fails

### ISSUE THREAD

**Issue by RyanRayNeff** [home-assistant/hassio-addons#636]
When uploading a snapshot to the backup folder via Configurator, the upload fails. I get a console error "Failed to load resource: the server responded with a status of 413 (Request Entity Too Large)".  Using hass.io 96.4, same error on both Raspberry pi 3B+ and Rapsberry pi 4.  It looks like 1Mb is the max allowed upload size.  Is this a bug, or a feature?
![Screen Shot 2019-07-25 at 9 15 41 AM](https://user-images.githubusercontent.com/11164951/61890701-d7da3f80-aebc-11e9-9f1e-c16c77b67c90.png)

**Comment by bennierex** [comment]
I have the same issue. Trying to upload a snapshot to the backup folder, but no luck. No messages in the front-end and no errors in the log, just in the browser console...

**Comment by fraiss-c** [comment]
I have the same issue, on a fresh new install, impossible for me to restore from a 10mb snapshots, error 413 Entity too large...

**Comment by frenck** [comment]
@fraiss-c Don't use the configurator for that. Instead, use the upload feature, that is available with the snapshots panels, directly.

![image](https://user-images.githubusercontent.com/195327/98418893-301e5c00-2084-11eb-868d-0489249dc942.png)
