### ISSUE TITLE
DuckDNS Let's Encrypt "Malformed account ID in KeyID header" error

### ISSUE THREAD

**Issue by trankillity** [home-assistant/hassio-addons#637]
Receiving the following error when trying to get launch the DuckDNS addon. Looks to be something to do with Let's Encrypt. There seems to be [a few other people](https://community.home-assistant.io/t/duckdns-lets-encrypt-error/128322/21) reporting this error in the last day or two too.

**Error**

```
# INFO: Using main config file /data/workdir/config
+ Account already registered!
Sat Jul 27 10:22:47 AEST 2019: OK
x.x.x.x
NOCHANGE
# INFO: Using main config file /data/workdir/config
Processing xdomain.duckdns.org
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
  + ERROR: An error occurred while sending post-request to https://acme-v02.api.letsencrypt.org/acme/new-order (Status 400)
Details:
HTTP/1.1 100 Continue
Expires: Sat, 27 Jul 2019 00:23:26 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache

HTTP/1.1 400 Bad Request
Server: nginx
Content-Type: application/problem+json
Content-Length: 178
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: sQ509SCFyTOZ0fUKC3vZY29SlsHnHDmZ5prob-eAfy8
Expires: Sat, 27 Jul 2019 00:23:27 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sat, 27 Jul 2019 00:23:27 GMT
Connection: close

{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Malformed account ID in KeyID header URL: \"https://acme-v02.api.letsencrypt.org/acme/acct/\"",
  "status": 400
}
```

**My add-on config**

```
{
  "lets_encrypt": {
    "accept_terms": true,
    "certfile": "fullchain.pem",
    "keyfile": "privkey.pem"
  },
  "token": "my-token-key",
  "domains": [
    "xdomain.duckdns.org"
  ],
  "seconds": 300
}
```

**Steps I've taken:**
- Given the Hassio host a static IP
- Forwarded ports 80, 443, and 8123 to the Hassio host
- Ensured I'm not on CGNAT with my ISP
  - Tested by remotely connecting/pinging my duckdns entry.
- Rebooted the Hassio host a few times to ensure all settings had stuck

I believe it's exclusively something to do with the Let's Encrypt certificate generation because I can remotely connect to my Hassio instance using my DuckDNS entry, just **NOT** via SSL because the certificate doesn't get generated. I've also checked the /ssl/ folder for the fullchain.pem and privkey.pem files and neither exist.

**Comment by cogneato** [comment]
I'm also getting the same error.

**Comment by inputd** [comment]
So one thing to add:

Rolling the add-on to 1.6 prevents the add-on from getting the error, and it successfully generates the certificate. However, when loading hass.io, the web browser still pulls up the old, expired certificate. I have no idea why...

**Comment by trankillity** [comment]
Looks like it could be to do with initial IPv6 support that was just added for the DuckDNS part of the addon. The only file that's really changed is [this file](https://github.com/home-assistant/hassio-addons/commit/9a399a68097403017fae02493a0394b66aae3d33#diff-9c27c635194ff48f8cadf3c7c837a92c) and the change log calls out specifically adding in options for IP address types. Perhaps Let's Encrypt is failing because it's resolving IPv4 and IPv6 to the same address.

**Comment by PremiumUsername** [comment]
I also have this exact problem, using the 1.7 version.

**Comment by Ryanmt-Deep3** [comment]
I have done some experimenting, It's not the 1.7 change at fault it seems but dehydrated

https://github.com/lukas2511/dehydrated/issues/650

Its resolved, but the version of dehydrated packaged with the plugin needs updating.

**Comment by jakobeissler** [comment]
I'm having the exact same problem on a fresh hass.io install and duck dns plugin version 1.6.

**Comment by jakobeissler** [comment]
@pvizeli, thabk you for the fix, however i re isntalled the add on and still getting the same error.

**Comment by Jeffrey-H** [comment]
I am still experiencing this issue as of today. I already tried to regenerate an account a couple of times. But I just get stuck on this error. I even tried it on a couple of different environments.

**Comment by jxbrown** [comment]
I'm new to HA. How does one "update dehydrated" in hassio? Can you layout the specific steps?

Thanks
