### ISSUE TITLE
update conbee

### ISSUE THREAD

**Issue by SergiSuarez** [home-assistant/hassio-addons#644]
I have hassio 0.96.5 under ubuntu 18.4.2 with deconz hass.io addon version 3.1 and I'm unable to update my conbee I gaved by the addon description even the manual one that goes into marthoc add-on but I don't have marthoc addon

Are there any other option I can try?

Thanks

**Comment by frenck** [comment]
I'm not sure where it write about the marthoc add-on anywhere in our docs?

https://github.com/home-assistant/hassio-addons/tree/master/deconz#upgrading-raspbee-and-conbee-firmware

**Comment by SergiSuarez** [comment]
The last sentence in the Upgrading section is:

If that is still not working, try upgrading the firmware manually.
Following the link there is no hass.io instructions but docker, ubuntu, windows...
The nearest to me (probably I'm wrong) to hass.io should be docker and then it starts to reference marthoc add-on.

Now I'm thinking as I'm running hass.io under an ubuntu I could stop the add-on and follow the ubuntu instructions. If this works then I will try to PR the upgrading doc sections to improve the manual upgrade.

Thanks

**Comment by SergiSuarez** [comment]
Following the manual upgrade needs I install deconz on the host OS. I'm running in a NUC so no problem to install, upgrade and deinstall but those running in a Pi should have issues doing it. I recommend to remove the last sentence (the manual upgrade) as it doesn't work for a hass.io add-on.
