### ISSUE TITLE
Snips.ai addon doesn't start

### ISSUE THREAD

**Issue by starfarer** [home-assistant/hassio-addons#645]
I have tried to install snips.ai via the addon but it doesn't start.

The main complaint is about version numbers, see below:

INFO:snips_nlu_hermes: loading nlu engine "/usr/share/snips/assistant/nlu_engine"
ERROR:rumqtt::client  : snips-nlu|92-core-snips-1 Disconnected: (Error(SyncMpsc(Disconnected), State { next_error: None, backtrace: None }))
ERROR:snips_common_cli::cli: Unable to reconnect to the mqtt broker, ending the program.
1564940651: Socket error on client snips-nlu|92-core-snips-1, disconnecting.
2019-08-04 18:44:11,354 INFO exited: snips-nlu (exit status 1; not expected)
2019-08-04 18:44:13,369 INFO spawned: 'snips-nlu' with pid 94
2019-08-04 18:44:13,376 INFO spawnerr: can't find command '/usr/bin/snips-analytics'
1564940653: New connection from 127.0.0.1 on port 1883.
1564940653: New client connected from 127.0.0.1 as snips-nlu|94-core-snips-1 (c0, k10).
INFO:snips_nlu_hermes: loading nlu engine "/usr/share/snips/assistant/nlu_engine"
ERROR:rumqtt::client  : snips-nlu|94-core-snips-1 Disconnected: (Error(SyncMpsc(Disconnected), State { next_error: None, backtrace: None }))
ERROR:snips_common_cli::cli: Unable to reconnect to the mqtt broker, ending the program.
1564940653: Socket error on client snips-nlu|94-core-snips-1, disconnecting.
2019-08-04 18:44:13,470 INFO exited: snips-nlu (exit status 1; not expected)
2019-08-04 18:44:16,486 INFO spawned: 'snips-nlu' with pid 96
2019-08-04 18:44:16,492 INFO spawnerr: can't find command '/usr/bin/snips-analytics'
2019-08-04 18:44:16,493 INFO gave up: snips-analytics entered FATAL state, too many start retries too quickly
1564940656: New connection from 127.0.0.1 on port 1883.
1564940656: New client connected from 127.0.0.1 as snips-nlu|96-core-snips-1 (c0, k10).
INFO:snips_nlu_hermes: loading nlu engine "/usr/share/snips/assistant/nlu_engine"
ERROR:snips_nlu       : Unable to read file '/usr/share/snips/assistant/nlu_engine/nlu_engine.json'
 -> caused by: Mismatched model version: model is 0.17.0 but runner is 0.19.0
ERROR:rumqtt::client  : snips-nlu|96-core-snips-1 Disconnected: (Error(SyncMpsc(Disconnected), State { next_error: None, backtrace: None }))
ERROR:snips_common_cli::cli: Unable to reconnect to the mqtt broker, ending the program.

**Comment by frankj91** [comment]
I've the same issue. Update?
