### ISSUE TITLE
Configurator add-on - no icons

### ISSUE THREAD

**Issue by Max-Loco** [home-assistant/hassio-addons#663]
On my RPi it seems the Configurator add-on can't find the icons:
The words "Folder, Close, Search, Settings, check_circle and edit" appear instead of the icons.

Other than that, the add-on seems to work fine.

Configurator 3.4
hass.io 179
HassOS 2.12

I am using the Pi-hole add-on - I'm not blocking anything in addition to gravity atm except for one regex entry ((^)|(\.))meethue\. which I can't delete for unknown reasons.
I can ping materialdesignicons.com from an ssh login to the hass.io RPi.

**Comment by danielperna84** [comment]
Did you solve the issue meanwhile? The symptoms you mention are exactly what happens when there is no connectivity to where the icons are hosted. I've seen this before from other people that are using Pi-hole or similar software.

**Comment by bridge-four** [comment]
What domains are the icons pulling from so we can whitelist on pi-hole?

**Comment by danielperna84** [comment]
A few possible domains are listed here: https://community.home-assistant.io/t/hass-configurator-has-gone-wonkey/79401/2

**Comment by Max-Loco** [comment]
Hi Daniel,
Yes it seems to be a problem with firefox. It works fine with chromium.

Thanks

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
