### ISSUE TITLE
SSH daemon has debug logging

### ISSUE THREAD

**Issue by robin13** [home-assistant/hassio-addons#666]
**Home Assistant release with the issue:**
Hassio: 0.96.5

**Component/platform:**

HassOS: 2.12
board: rpi3
SSH Server: 6.0

**Description of problem:**

In the ssh daemon configuration, debug logging is enabled:

```
LogLevel DEBUG
```
This results in this line being output every time one connects:

```
debug1: permanently_set_uid: 0/0
```
And this in turn breaks backuppc from being able to connect to make a backup and other ssh based automations.

Is it possible to set LogLevel to INFO?

This was previously raised here: https://github.com/home-assistant/hassos/issues/364

**Comment by pvizeli** [comment]
Sure, feel free to open a PR for it 👍

**Comment by robin13** [comment]
I don't like issues being closed without a resolution: the problem has not gone away.

I've created a PR which should fix it:
https://github.com/home-assistant/hassio-addons/pull/686
