### ISSUE TITLE
Error in Version 2.2/ Hassio, Docker

### ISSUE THREAD

**Issue by wisesokol** [home-assistant/hassio-addons#669]
I have in Log:
[INFO] Running nginx...
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx.conf:45
In Home assistent forums there is such a problem
https://community.home-assistant.io/t/i-get-this-message-after-updating-nginx/132845

**Comment by jimholmesNZ** [comment]
I'm having the same issue on Hassio version 0.98.3.

**Comment by Klangen82** [comment]
I have the same issue on Hassio version 0.98.5

**Comment by Shiwigy** [comment]
Fixed in #693, version 2.3
