### ISSUE TITLE
Aqara PIR/Temp sensors work only after restarting plugin

### ISSUE THREAD

**Issue by HackThatNow** [home-assistant/hassio-addons#672]
When I reboot HASSIO, I will not get temperature information or PIR status changes. It keeps listing the state "unavailable" in HASSIO under device states. 

It only get fixed, if I restart the plugin manually _after_ hassio is done rebooting.

However, when I login to Dresden webinterface, I can see that all temperature senors and PIR sensors are updated upon movement / temperature change. It is somehow not forwarded to the HASSIO environment unless I restart the plugin.

So to double check I explain it right.

-Reboot HASSIO
-Wait for HASSIO to come alive in webinterface
-All Aqara PIR/Temp sensors do not work, you can however control Aqara light switches. Also Aqara buttons DO work perfectly fine.
-If I do not restart the dresden plugin manually, everything actually works fine exept for no PIR status updates and temperature units.
-restart the plugin, then in several minutes the status updates get updated within HASSIO environment.

Latest build HASSIO (184 / HassOS 2.12)
I am on version 3.1 of the plugin version

> 13:36:19:460 Current channel 25
13:36:19:479 Device TTL 6690 s flags: 0x7
13:36:24:821     * different nwk address 0x1EF7 / 0x1EF8
13:36:25:315     * different nwk address 0x1C92 / 0x1C93
13:36:25:315     * different nwk address 0x6321 / 0x6322
13:36:25:779     * different nwk address 0x5A56 / 0x5A57
13:36:48:481     * different nwk address 0x1EF7 / 0x1EF8
13:36:48:987     * different nwk address 0x1C92 / 0x1C93
13:36:48:987     * different nwk address 0x6321 / 0x6322
13:36:49:456     * different nwk address 0x5A56 / 0x5A57
13:37:00:044 ZCL attribute report 0x00158D00024F274E for cluster 0x0000, ep 0x01
13:37:00:044 0x00158D00024F274E extract Xiaomi special attribute 0xFF01
13:37:00:044 	64 on/off 0
13:37:00:044 	03 temperature 30 °C
13:37:00:044 	98 power (?) 0x00000000
13:37:00:044 	95 consumption (?) 0x3FEE4510
13:37:00:044 	05 RSSI dB (?) 6 (0x0006)
13:37:00:044 	9a unknown 0 (0x00)
13:37:00:044 	08 unknown 4894 (0x131E)
13:37:00:044 	07 unknown 0 (0x0000000000000000)
13:37:00:044 	09 unknown 1795 (0x0703)
13:37:02:229 verified group capacity: 13 and group count: 3 of LightNode 0x00158d00024f274e
13:37:02:230 0x00158d00024f274e found group 0x0000
13:37:02:230 0x00158d00024f274e found group 0xFFF0
13:37:02:230 0x00158d00024f274e found group 0x0003
13:37:11:998     * different nwk address 0x1EF7 / 0x1EF8
13:37:12:474     * different nwk address 0x1C92 / 0x1C93
13:37:12:474     * different nwk address 0x6321 / 0x6322
13:37:12:960     * different nwk address 0x5A56 / 0x5A57
13:37:19:456 Current channel 25
13:37:19:476 Device TTL 6630 s flags: 0x7
13:37:35:517     * different nwk address 0x1C92 / 0x1C93
13:37:36:042     * different nwk address 0x6321 / 0x6322
13:37:36:043     * different nwk address 0x5A56 / 0x5A57
13:37:40:722 ZCL attribute report 0x00158D0003928B86 for cluster 0x0000, ep 0x01
13:37:40:722 0x00158D0003928B86 extract Xiaomi special attribute 0xFF01
13:37:40:722 	64 on/off 0
13:37:40:722 	03 temperature 36 °C
13:37:40:722 	98 power (?) 0x00000000
13:37:40:722 	95 consumption (?) 0x3F205E38
13:37:40:722 	05 RSSI dB (?) 8 (0x0008)
13:37:40:722 	9a unknown 0 (0x00)
13:37:40:722 	08 unknown 4898 (0x1322)
13:37:40:722 	07 unknown 0 (0x0000000000000000)
13:37:40:722 	09 unknown 1026 (0x0402)
13:37:58:567     * different nwk address 0x1C92 / 0x1C93
13:37:59:032     * different nwk address 0x6321 / 0x6322
13:37:59:032     * different nwk address 0x5A56 / 0x5A57
13:38:06:010 no button map for: lumi.weather ep: 0x01 cl: 0x0000 cmd: 0x0A pl[0]: 001
13:38:06:010 ZCL attribute report 0x00158D00030A01BA for cluster 0x0000, ep 0x01
13:38:06:010 0x00158D00030A01BA extract Xiaomi special attribute 0xFF01
13:38:06:010 	01 battery 3005 (0x0BBD)
13:38:06:010 	04 unknown 17320 (0x43A8)
13:38:06:010 	05 RSSI dB (?) 6 (0x0006)
13:38:06:010 	06 LQI (?) 4294967296 (0x0100000000)
13:38:06:010 	64 temperature 2904
13:38:06:010 	65 humidity 5916
13:38:06:010 	66 pressure 1013
13:38:06:010 	0a unknown 45727 (0xB29F)
13:38:19:468 Current channel 25
13:38:19:487 Device TTL 6570 s flags: 0x7
13:38:21:788     * different nwk address 0x1C92 / 0x1C93
13:38:22:278     * different nwk address 0x6321 / 0x6322
13:38:22:278     * different nwk address 0x5A56 / 0x5A57
13:38:36:866 no button map for: lumi.sensor_motion.aq2 ep: 0x01 cl: 0x0400 cmd: 0x0A pl[0]: 000
13:38:36:866 ZCL attribute report 0x00158D00029A9903 for cluster 0x0400, ep 0x01
13:38:36:874 no button map for: lumi.sensor_motion.aq2 ep: 0x01 cl: 0x0406 cmd: 0x0A pl[0]: 000
13:38:36:874 ZCL attribute report 0x00158D00029A9903 for cluster 0x0406, ep 0x01
13:38:36:923 Set sensor check interval to 100 milliseconds
13:38:40:440 saved node state in 6 ms
13:38:40:486 sync() in 46 ms
13:38:40:652 no button map for: lumi.sensor_magnet.aq2 ep: 0x01 cl: 0x0000 cmd: 0x0A pl[0]: 001
13:38:40:653 ZCL attribute report 0x00158D000277B50D for cluster 0x0000, ep 0x01
13:38:40:653 0x00158D000277B50D extract Xiaomi special attribute 0xFF01
13:38:40:653 	01 battery 3115 (0x0C2B)
13:38:40:653 	03 temperature 28 °C
13:38:40:653 	04 unknown 5032 (0x13A8)
13:38:40:653 	05 RSSI dB (?) 55 (0x0037)
13:38:40:653 	06 LQI (?) 94489346048 (0x1600010000)
13:38:40:653 	0a unknown 0 (0x0000)
13:38:40:653 	64 on/off 0
13:38:45:430     * different nwk address 0x9F47 / 0x9F48
13:38:45:430     * different nwk address 0x1C92 / 0x1C93
13:38:45:896     * different nwk address 0x6321 / 0x6322
13:38:45:897     * different nwk address 0x5A56 / 0x5A57
13:38:51:866 no button map for: lumi.remote.b1acn01 ep: 0x01 cl: 0x0000 cmd: 0x0A pl[0]: 001
13:38:51:866 ZCL attribute report 0x00158D00021386CE for cluster 0x0000, ep 0x01
13:38:51:866 0x00158D00021386CE extract Xiaomi special attribute 0xFF01
13:38:51:866 	01 battery 3005 (0x0BBD)
13:38:51:866 	03 temperature 33 °C
13:38:51:866 	04 unknown 17320 (0x43A8)
13:38:51:866 	05 RSSI dB (?) 551 (0x0227)
13:38:51:866 	06 LQI (?) 4294967296 (0x0100000000)
13:38:51:866 	0a unknown 24419 (0x5F63)
13:39:09:192     * different nwk address 0x9F47 / 0x9F48
13:39:09:192     * different nwk address 0x5A56 / 0x5A57
13:39:19:454 Current channel 25
13:39:19:487 Device TTL 6510 s flags: 0x7
13:39:24:464 GW firmware version: 0x26490700
13:39:24:464 GW firmware version is up to date: 0x26490700

>

**Comment by pergolafabio** [comment]
also almost exact same issue here, running HassOS, hassio 97.2 , deconz 3.1 official plugin
after about 1 day, no states are coming to Hassio from deconz

i have a verry easy setup, only some Xiaomi motion sensors and some osram smart plugs
so  i also enabled debug level, nothing to see there, all looks fine, and then suddenly i dont see any debug anymore, seems its just stops

deconz still works, if i logon in phoscon, i still see motion detected, i can still power on/off my smart plugs, its just the state thats not going to Hassio

whats also strange, my osram plugs, i can still power on/off them FROM hassio, i see the state also changing in phoscon, but phoscon doesnt push new state to hassio , it just stays on same state...
at that moment, when state should change there is NO info

in order to get it work again, i just need to restart Hassio, i dont need to restart deconz
then it works again, for like about a day

more detailed post here with logs

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1789#issuecomment-525932212

**Comment by pergolafabio** [comment]
I am removing my last components one by one, that I added lately , maybe there is a conflict

I removed as first test the asuswrt en audimmi component (custom) , now I have deconz running more then a day, more then last week...
Too soon to be sure, but we will see...

Have you also added new components lately?

**Comment by kakaki** [comment]
I have the same issue since update to 0.98.x and HassOS 3.4 - fresh installation 2 weeks ago - was working fine for one week with 2 xiaomi motion sensors and one water leak - now state is stopping to update after couple of minutes from restarting hassio

**Comment by pergolafabio** [comment]
are you using deconz also?

**Comment by kakaki** [comment]
> 
> 
> are you using deconz also?

Yes, deconz with conbee2 usb stick

**Comment by pergolafabio** [comment]
but you aready have it after a few minutes? my state is stopping aftre about 12...24 hours 

not minutes

**Comment by kakaki** [comment]
It's updating only after restarting hassio, after that it stops updating state.

**Comment by pergolafabio** [comment]
can you enable debug on deconz in hassio? then you can see if you are receiving states
maybe there is an error there

**Comment by kakaki** [comment]
Changed setting and state only updated on restart of plugin:

`14:28:02:130 APS-DATA.indication request id: 168 -> finished
14:28:02:130 APS-DATA.request id: 168 erase from queue
14:28:05:955 APS-DATA.request id: 170, addrmode: 0x03, addr: 0x00212effff0486b0, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
14:28:05:962 APS-DATA.confirm id: 170, status: 0x00 SUCCESS
14:28:05:962 APS-DATA.confirm request id: 170 -> confirmed, timeout 18103536
14:28:05:963 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 241, rssi: 19
14:28:05:963 APS-DATA.indication request id: 170 -> finished
14:28:05:963 APS-DATA.request id: 170 erase from queue
14:28:09:795 APS-DATA.request id: 172, addrmode: 0x03, addr: 0x00212effff0486b0, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
14:28:09:808 APS-DATA.confirm id: 172, status: 0x00 SUCCESS
14:28:09:808 APS-DATA.confirm request id: 172 -> confirmed, timeout 18363816
14:28:09:812 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 241, rssi: 19
14:28:09:812 APS-DATA.indication request id: 172 -> finished
14:28:09:812 APS-DATA.request id: 172 erase from queue
14:28:13:635 APS-DATA.request id: 174, addrmode: 0x03, addr: 0x00212effff0486b0, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
14:28:13:648 APS-DATA.confirm id: 174, status: 0x00 SUCCESS
14:28:13:648 APS-DATA.confirm request id: 174 -> confirmed, timeout 18103536
14:28:13:652 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 241, rssi: 19
14:28:13:652 APS-DATA.indication request id: 174 -> finished
14:28:13:652 APS-DATA.request id: 174 erase from queue
14:28:17:475 APS-DATA.request id: 176, addrmode: 0x03, addr: 0x00212effff0486b0, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
14:28:17:489 APS-DATA.confirm id: 176, status: 0x00 SUCCESS
14:28:17:489 APS-DATA.confirm request id: 176 -> confirmed, timeout 18363816
14:28:17:492 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 241, rssi: 19
14:28:17:493 APS-DATA.indication request id: 176 -> finished
14:28:17:493 APS-DATA.request id: 176 erase from queue
14:28:21:315 APS-DATA.request id: 178, addrmode: 0x03, addr: 0x00212effff0486b0, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
14:28:21:329 APS-DATA.confirm id: 178, status: 0x00 SUCCESS
14:28:21:329 APS-DATA.confirm request id: 178 -> confirmed, timeout 18103536
14:28:21:333 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 241, rssi: 19
14:28:21:333 APS-DATA.indication request id: 178 -> finished
14:28:21:333 APS-DATA.request id: 178 erase from queue
14:28:25:155 APS-DATA.request id: 180, addrmode: 0x03, addr: 0x00212effff0486b0, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
14:28:25:167 APS-DATA.confirm id: 180, status: 0x00 SUCCESS
14:28:25:167 APS-DATA.confirm request id: 180 -> confirmed, timeout 18363816
14:28:25:171 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 241, rssi: 19
14:28:25:171 APS-DATA.indication request id: 180 -> finished
14:28:25:171 APS-DATA.request id: 180 erase from queue
14:28:28:995 APS-DATA.request id: 182, addrmode: 0x03, addr: 0x00212effff0486b0, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
14:28:29:008 APS-DATA.confirm id: 182, status: 0x00 SUCCESS
14:28:29:008 APS-DATA.confirm request id: 182 -> confirmed, timeout 18103536
14:28:29:012 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 241, rssi: 19
14:28:29:012 APS-DATA.indication request id: 182 -> finished
14:28:29:012 APS-DATA.request id: 182 erase from queue
14:28:32:835 APS-DATA.request id: 184, addrmode: 0x03, addr: 0x00212effff0486b0, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
14:28:32:847 APS-DATA.confirm id: 184, status: 0x00 SUCCESS
14:28:32:847 APS-DATA.confirm request id: 184 -> confirmed, timeout 18363816
14:28:32:851 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 241, rssi: 19
14:28:32:851 APS-DATA.indication request id: 184 -> finished
14:28:32:851 APS-DATA.request id: 184 erase from queue
14:28:36:675 APS-DATA.request id: 186, addrmode: 0x03, addr: 0x00212effff0486b0, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
14:28:36:686 APS-DATA.confirm id: 186, status: 0x00 SUCCESS
14:28:36:686 APS-DATA.confirm request id: 186 -> confirmed, timeout 18103536
14:28:36:690 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 241, rssi: 19
14:28:36:691 APS-DATA.indication request id: 186 -> finished
14:28:36:691 APS-DATA.request id: 186 erase from queue
14:28:40:515 APS-DATA.request id: 188, addrmode: 0x03, addr: 0x00212effff0486b0, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
14:28:40:526 APS-DATA.confirm id: 188, status: 0x00 SUCCESS
14:28:40:526 APS-DATA.confirm request id: 188 -> confirmed, timeout 18363816
14:28:40:530 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 241, rssi: 19
14:28:40:530 APS-DATA.indication request id: 188 -> finished
14:28:40:530 APS-DATA.request id: 188 erase from queue
14:28:44:355 APS-DATA.request id: 190, addrmode: 0x03, addr: 0x00212effff0486b0, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
14:28:44:365 APS-DATA.confirm id: 190, status: 0x00 SUCCESS
14:28:44:365 APS-DATA.confirm request id: 190 -> confirmed, timeout 18103536
14:28:44:369 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 241, rssi: 19
14:28:44:369 APS-DATA.indication request id: 190 -> finished
14:28:44:370 APS-DATA.request id: 190 erase from queue
14:28:48:196 APS-DATA.request id: 192, addrmode: 0x03, addr: 0x00212effff0486b0, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
14:28:48:207 APS-DATA.confirm id: 192, status: 0x00 SUCCESS
14:28:48:207 APS-DATA.confirm request id: 192 -> confirmed, timeout 18363816
14:28:48:211 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 241, rssi: 19
14:28:48:211 APS-DATA.indication request id: 192 -> finished
14:28:48:211 APS-DATA.request id: 192 erase from queue
14:28:52:036 APS-DATA.request id: 194, addrmode: 0x03, addr: 0x00212effff0486b0, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
14:28:52:043 APS-DATA.confirm id: 194, status: 0x00 SUCCESS
14:28:52:043 APS-DATA.confirm request id: 194 -> confirmed, timeout 18103536
14:28:52:044 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 241, rssi: 19
14:28:52:044 APS-DATA.indication request id: 194 -> finished
14:28:52:044 APS-DATA.request id: 194 erase from queue
14:28:55:876 APS-DATA.request id: 196, addrmode: 0x03, addr: 0x00212effff0486b0, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
14:28:55:881 APS-DATA.confirm id: 196, status: 0x00 SUCCESS
14:28:55:881 APS-DATA.confirm request id: 196 -> confirmed, timeout 18363816
14:28:55:882 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 241, rssi: 19
14:28:55:882 APS-DATA.indication request id: 196 -> finished
14:28:55:882 APS-DATA.request id: 196 erase from queue
14:28:59:715 APS-DATA.request id: 198, addrmode: 0x03, addr: 0x00212effff0486b0, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
14:28:59:728 APS-DATA.confirm id: 198, status: 0x00 SUCCESS
14:28:59:728 APS-DATA.confirm request id: 198 -> confirmed, timeout 18103536
14:28:59:732 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 241, rssi: 19
14:28:59:732 APS-DATA.indication request id: 198 -> finished
14:28:59:732 APS-DATA.request id: 198 erase from queue
14:29:00:567 Current channel 11
14:29:00:575 Device TTL 6296 s flags: 0x7
14:29:03:555 APS-DATA.request id: 200, addrmode: 0x03, addr: 0x00212effff0486b0, profile: 0x0000, cluster: 0x0031, ep: 0x00 -> 0x00 queue: 0 len: 2 tx.options 0x00
14:29:03:569 APS-DATA.confirm id: 200, status: 0x00 SUCCESS
14:29:03:569 APS-DATA.confirm request id: 200 -> confirmed, timeout 18363816
14:29:03:573 APS-DATA.indication srcAddr: 0x0000, srcEp: 0x00 dstAddrMode: 2, profile: 0x0000, cluster: 0x8031, lqi: 241, rssi: 19
14:29:03:573 APS-DATA.indication request id: 200 -> finished
14:29:03:573 APS-DATA.request id: 200 erase from queue`

**Comment by pergolafabio** [comment]
hmm, thats not debug from hassio? look here in my post,

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1789#issuecomment-525932212

**Comment by kakaki** [comment]
Hi, it seems to work after last update of deconz to new version, data is updated on lux sensor, but motion sensors only updates if it detect motion - without it apears as not working (state is showing last update over 2 hours). Water sensors readings seems to give same problem.

![obraz](https://user-images.githubusercontent.com/156115/64327601-489c6d80-cfcc-11e9-9d81-5797085fbe63.png)

![obraz](https://user-images.githubusercontent.com/156115/64327648-5eaa2e00-cfcc-11e9-849f-8206fd00fc52.png)

![obraz](https://user-images.githubusercontent.com/156115/64327730-7d102980-cfcc-11e9-8f48-a5c0871e7e8e.png)

`2019-09-05 10:55:32 DEBUG (MainThread) [pydeconz.websocket] Websocket data: {"config":{"battery":100,"on":true,"reachable":true,"temperature":3500,"tholddark":12000,"tholdoffset":7000},"e":"changed","id":"5","r":"sensors","t":"event","uniqueid":"00:15:8d:00:03:6b:9e:bc-01-0400"}
2019-09-05 10:55:32 DEBUG (MainThread) [pydeconz.websocket] Websocket data: {"e":"changed","id":"5","r":"sensors","state":{"dark":false,"daylight":true,"lastupdated":"2019-09-05T08:55:32","lightlevel":20570,"lux":114},"t":"event","uniqueid":"00:15:8d:00:03:6b:9e:bc-01-0400"}
2019-09-05 10:55:32 DEBUG (MainThread) [pydeconz.websocket] Websocket data: {"config":{"battery":100,"duration":90,"on":true,"reachable":true,"temperature":3500},"e":"changed","id":"6","r":"sensors","t":"event","uniqueid":"00:15:8d:00:03:6b:9e:bc-01-0406"}
2019-09-05 10:55:32 DEBUG (MainThread) [pydeconz.websocket] Websocket data: {"e":"changed","id":"6","r":"sensors","state":{"lastupdated":"2019-09-05T08:55:32","presence":false},"t":"event","uniqueid":"00:15:8d:00:03:6b:9e:bc-01-0406"}
2019-09-05 10:55:51 DEBUG (MainThread) [pydeconz.websocket] Websocket data: {"config":{"battery":100,"on":true,"reachable":true,"temperature":2900,"tholddark":12000,"tholdoffset":7000},"e":"changed","id":"3","r":"sensors","t":"event","uniqueid":"00:15:8d:00:03:6b:9e:82-01-0400"}
2019-09-05 10:55:51 DEBUG (MainThread) [pydeconz.websocket] Websocket data: {"e":"changed","id":"3","r":"sensors","state":{"dark":false,"daylight":false,"lastupdated":"2019-09-05T08:55:51","lightlevel":17243,"lux":53},"t":"event","uniqueid":"00:15:8d:00:03:6b:9e:82-01-0400"}
2019-09-05 10:55:51 DEBUG (MainThread) [pydeconz.websocket] Websocket data: {"config":{"battery":100,"duration":90,"on":true,"reachable":true,"temperature":2900},"e":"changed","id":"4","r":"sensors","t":"event","uniqueid":"00:15:8d:00:03:6b:9e:82-01-0406"}
2019-09-05 10:55:51 DEBUG (MainThread) [pydeconz.websocket] Websocket data: {"e":"changed","id":"4","r":"sensors","state":{"lastupdated":"2019-09-05T08:55:51","presence":false},"t":"event","uniqueid":"00:15:8d:00:03:6b:9e:82-01-0406"}
2019-09-05 10:55:51 DEBUG (MainThread) [pydeconz.websocket] Websocket data: {"e":"changed","id":"3","r":"sensors","state":{"dark":false,"daylight":false,"lastupdated":"2019-09-05T08:55:51","lightlevel":17243,"lux":53},"t":"event","uniqueid":"00:15:8d:00:03:6b:9e:82-01-0400"}
2019-09-05 10:55:51 DEBUG (MainThread) [pydeconz.websocket] Websocket data: {"config":{"battery":100,"duration":90,"on":true,"reachable":true,"temperature":2900},"e":"changed","id":"4","r":"sensors","t":"event","uniqueid":"00:15:8d:00:03:6b:9e:82-01-0406"}
2019-09-05 10:55:51 DEBUG (MainThread) [pydeconz.websocket] Websocket data: {"e":"changed","id":"4","r":"sensors","state":{"lastupdated":"2019-09-05T08:55:51","presence":false},"t":"event","uniqueid":"00:15:8d:00:03:6b:9e:82-01-0406"}
2019-09-05 10:59:26 DEBUG (MainThread) [pydeconz.websocket] Websocket data: {"config":{"battery":100,"on":true,"reachable":true,"temperature":2700},"e":"changed","id":"2","r":"sensors","t":"event","uniqueid":"00:15:8d:00:03:58:0b:af-01-0500"}
2019-09-05 10:59:26 DEBUG (MainThread) [pydeconz.websocket] Websocket data: {"e":"changed","id":"2","r":"sensors","state":{"lastupdated":"2019-09-05T08:59:26","lowbattery":false,"tampered":false,"water":false},"t":"event","uniqueid":"00:15:8d:00:03:58:0b:af-01-0500"}`

**Comment by pergolafabio** [comment]
yeah, my motion sensors also dont update lux/temp, its by design
they only update indeed when motion, its because they go in sleep mode

**Comment by pvizeli** [comment]
That is not an issue of the add-on. Open an issue on Home Assistant if you think it's an integration issue of HA or on deCONZ if you think that is an issue of manifactory.

**Comment by HackThatNow** [comment]
> That is not an issue of the add-on. Open an issue on Home Assistant if you think it's an integration issue of HA or on deCONZ if you think that is an issue of manifactory.

Can you explain why this is not the add-on and it must be HA? Do you have logs that shows that it is HA? That way I can better search for a solution.

--
Since updating to 0.99.2 and updating the plugin to the latest version (3.6) this is back for me and even worse. Couple of restarts of HASSIO and the plugin but still it stays working in Phoscon, not in hassio. Hassio shows the sensor as unavailable while in phoscon I can see the latest PIR movements (so it is working correctly in phoscon, but not in hassio)
