### ISSUE TITLE
Hass.io: add-on Configurator

### ISSUE THREAD

**Issue by AliminGuntoro** [home-assistant/hassio-addons#673]
Hi. Master...
I have problem with configurator, why after i change Config to new setting, and start the  information on box Config always return to default

this default config right.
 {
  "dirsfirst": false,
  "enforce_basepath": false,
  "ignore_pattern": [
    "__pycache__"
  ]
}

I change to 

{
  "username": "abcd",
  "password": "123456",
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "ssl": true,
  "allowed_networks": [
    "192.168.0.0/16",
    "172.30.0.0/16"
  ],
  "banned_ips": [
    "8.8.8.8"
  ],
  "banlimit": 0,
  "ignore_pattern": [
    "__pycache__"
  ],
  "dirsfirst": false,
  "enforce_basepath": false
}

and I save it,..than start...configurator....but i see the box information on config..back to default ,,,what is the problem...
I'm using raspberry PI 3 B+

Thank you very much.

**Comment by pvizeli** [comment]
This is old config and the new configurator work with ingress out of the box
