### ISSUE TITLE
deconz syslog warning: No API token provided

### ISSUE THREAD

**Issue by casperklein** [home-assistant/hassio-addons#674]
HASSIO @ RPI: HassOS 2.12; Home-Assistant 0.97.2 

deconz works fine. However I see a syslog warning once the addon starts:

    [hassio.api.security] No API token provided for /api/config

Related: https://github.com/marthoc/hassio-addons/issues/95

**Comment by pvizeli** [comment]
the software scan the network and call `/api/config` on every port 80. We can't solve that. You need open a issue on deconz manifactor.

**Comment by casperklein** [comment]
Thanks for clarification. Then the warning can be safely ignored.
