### ISSUE TITLE
Host 'core-samba.local.hass.io' is not allowed

### ISSUE THREAD

**Issue by rschuiling** [home-assistant/hassio-addons#675]
After restoring a hass.io snapshot, then after reboot, the recorder won't start anymore. 

More topics on the forum are reporting this same error:
```
Error during connection setup: (MySQLdb._exceptions.OperationalError) (1130, "Host 'core-samba.local.hass.io' is not allowed to connect to this MariaDB server")
(Background on this error at: http://sqlalche.me/e/e3q8) (retrying in 3 seconds)
```
I tried changing the MariaDB config:   "host": "%"
Also tried this change in configuration.yaml:
  `db_url: mysql://hass:xxxxx@core-mariadb/homeassistant`
to:
`  db_url: mysql://hass:xxxxx@127.0.0.1/homeassistant`

And also uninstalled and reinstalled the MariaDB Hass.io add-on. But no luck.

[Hass.io / HA 0.97.2 / supervisor 184 / host Ubuntu Server 18.04.2]

**Comment by y0ast** [comment]
It's a permission issue. There are two places where you need to set host to % (or `%.local.hass.io` is better) in mariadb. Did you catch both?

`core-mariadb` should still be fine.

**Comment by rschuiling** [comment]
Yes that worked, thanks.
