### ISSUE TITLE
Unable to recognize Conbee 2 USB stick on Intel NUC running CentOS 

### ISSUE THREAD

**Issue by ragnarbullnielsen** [home-assistant/hassio-addons#680]
deCONZ version 3.3
hass.io 0.98

Hass.io hardware info:

serial:
/dev/ttyS0
/dev/ttyACM0
/dev/ttyS2
/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1963639-if00
/dev/ttyS3
/dev/ttyS1
input:
HDA Intel PCH HDMI/DP,pcm=10
HDA Intel PCH HDMI/DP,pcm=8
HDA Intel PCH HDMI/DP,pcm=3
ITE8708 CIR transceiver
HDA Intel PCH Front Headphone
HDA Intel PCH HDMI/DP,pcm=9
HDA Intel PCH HDMI/DP,pcm=7
PC Speaker
Power Button
MCE IR Keyboard/Mouse (ite-cir)
Sleep Button
Video Bus
disk:
gpio:
audio:

I have tried configuring the add-on using:

{
  "device": "/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1963639-if00",
  "vnc_password": ************"
}

In the Phoscon web app, the gateway shows up as a RaspBee, and 'Not connected'

From the deCONZ log:

20:31:05:726 wait reconnect 2 seconds
20:31:06:726 wait reconnect 1 seconds
20:31:06:743 COM: --dev: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1963639-if00 (RaspBee)
This plugin does not support propagateSizeHints()
20:31:06:765 Device firmware version 0x26420700
20:31:06:767 unlocked max nodes: 200
20:31:06:841 Device protocol version: 0x0108
20:31:06:848 new node - ext: 0x00212effff0424b0, nwk: 0x0000
20:31:06:896 Current channel 11
20:31:06:912 CTRL ANT_CTRL 0x03
20:40:07:057 Announced to internet

**Comment by lauer** [comment]
Same problem here. It does not work if using the by-id link, however worked fine, if I change back to directly link to e.g /dev/ttyACM2

**Comment by jamescadd** [comment]
I'm having the same issue with a Nortek HUSBZB-1 on .98.1. Only the ttyUSB0/1 devices work.

**Comment by pvizeli** [comment]
We wait until 185 is installed on all device and we push the fix out

**Comment by jamescadd** [comment]
Just checking but does this mean that if my supervisor version is 185 then this should be fixed? If so I will retest.

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassio-addons/issues/685#issuecomment-527809892 could be that you need rerun installer on generic linux
