### ISSUE TITLE
Configurator: Allow ability to hide left panel (list of events, entities, etc.)

### ISSUE THREAD

**Issue by Tediore** [home-assistant/hassio-addons#687]
The repo for the non-Hassio version of this add-on includes instructions for disabling the left panel that's displayed when you open the add-on (the one that shows dropdown menus for events, entities, and so on). Would be nice to have in the Hassio add-on since it would free up a good chunk of space.

**Comment by pvizeli** [comment]
?

**Comment by Tediore** [comment]
I...did not post this in the right repo. Sorry about that.

**Comment by Tediore** [comment]
Reopened with a description of which add-on I was talking about and more details.
