### ISSUE TITLE
Unable to specify Conbee device as '/dev/serial/by-id/...' after deCONZ v3.1

### ISSUE THREAD

**Issue by linfoxo** [home-assistant/hassio-addons#689]
I had previous been specifying my ConBee II device in deCONZ as `/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1963947-if00`, and that worked great up until at least v3.1.

However now on trying v3.5, the addon fails to start, simply stating `[22:37:42] FATAL: No device /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1963947-if00 found!`

Is there any chance this could be restored? I use the by-id mounts as in my particular setup I can't guarantee the /dev/ttyACM* device name will be consistent each boot.

Here's the device on the host -
```
[root@lin54-homeauto deCONZ]# ls -al /dev/serial/by-id/usb-dre*
lrwxrwxrwx. 1 root root 13 Sep  7 22:15 /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1963947-if00 -> ../../ttyACM0
```

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassio-addons/issues/685

**Comment by KennethLavrsen** [comment]
@pvizeli there is no fix on the item you refer to and now you close the same issue raised by what must be the 5th or 6th with the same problem when you read the comments here.

Latest is here https://community.home-assistant.io/t/deconz-official-thread/100504/577

Why do you refuse that there is a problem?`I solved mine by going to bare metal. But that is not a solution for the HA addon.
