### ISSUE TITLE
After delete I can't install deCONZ from Hass.io add-ons.

### ISSUE THREAD

**Issue by Piteriuz** [home-assistant/hassio-addons#690]
After delete I can't install deCONZ from Hass.io add-ons.

My logs from install:
`19-09-08 21:33:54 INFO (SyncWorker_0) [hassio.docker.interface] Pull image homeassistant/armhf-addon-deconz tag 3.5.
19-09-08 21:33:57 ERROR (SyncWorker_0) [hassio.docker.interface] Can't install homeassistant/armhf-addon-deconz:3.5 -> 500 Server Error: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument").`

Any ideas? I must reinstall home assistant... ?

**Comment by frenck** [comment]
Looks like your Docker filesystem is corrupted. You can try fixing it using the following command: `hassio supervisor repair`

**Comment by Piteriuz** [comment]
Thaanks @frenck - it took a little while but it's working
