### ISSUE TITLE
Option to enable upnp.

### ISSUE THREAD

**Issue by vandalon** [home-assistant/hassio-addons#691]
Hi,

Thanks for al the great work on this addon.
Would it be possible to add an option to enable upnp on deconz start? (--upnp=1).

Thanks!

**Comment by frenck** [comment]
Could you provide a use-case for that?
This add-on uses Hass.io/Home Assistant auto-discovery and we want to prevent mixing those up.

**Comment by vandalon** [comment]
Well some 3th party apps works with deconz, and some of these require upnp for detection :)

**Comment by vandalon** [comment]
this would also mean that udp/1900 needs to be enabled

**Comment by frenck** [comment]
Hmm, maybe we could add the configuration for port `udp/1900` and leave if disabled (null) by default. If a port is set/enabled by the user, the add-on could add the switch automatically. The documentation would need a good note about the consequences for HA autodiscovery though.

**Comment by vandalon** [comment]
would this have any consequences for HA autodiscovery?

**Comment by pvizeli** [comment]
I think an option is more usefull because they listen on host only and can't be changed because that is multicast.

**Comment by vandalon** [comment]
I agree that to have it as een option is always the best way to go :)

**Comment by gambrose** [comment]
This seems to have been rolled back in version 4.0. But I can't seem to find a reason for this being reverted.
What is the current status of adding suport for UPnP?

**Comment by vandalon** [comment]
Since the use of ingress all ports are disabled except for vnc. So upnp in this situation makes no sense. It would be nice though to have the option to open direct acces over network towards deconz, including upnp

**Comment by gambrose** [comment]
> Since the use of ingress all ports are disabled except for vnc. So upnp in this situation makes no sense. It would be nice though to have the option to open direct acces over network towards deconz, including upnp

Version 5.0 change log mentions "Re-instate direct access capabilities to the Phoscon/deCONZ API"

**Comment by via-justa** [comment]
2 years later and still no answer. 
Is there an RFC describing why UPnP is not enabled even though the changelog says the functionality should be available?
I'm using 3rd party apps (Alexa among them) and it's a big problem that they cannot be connected.
I've been reading all the documentation and changelogs before doing the reinstall of the host with hassio and there was no mentioning you do not expose the UPnP. I see it either as a bug in the code or the documentation. 
I really think the decision to open the port or not, should be of the user as there are valid use cases for that.

**Comment by popy2k14** [comment]
Any hints how i can connect deconz to alexa wihtout upnp?
I migrated my deconz from my rpi4 which was seamless, just to see that such an BIG feature is missing.

Every help is welcome.
