### ISSUE TITLE
[git_pull] Multi-line deployment keys are not allowed

### ISSUE THREAD

**Issue by janpieper** [home-assistant/hassio-addons#695]
I cannot save my git_pull-configuration because a multi-line deployment key is not allowed. The text turns red and the "SAVE" button will be disabled.

![hassio-git-pull-valid](https://user-images.githubusercontent.com/426371/64721515-f1673300-d4cc-11e9-98ef-abf0b858d55b.png)

![hassio-git-pull-invalid](https://user-images.githubusercontent.com/426371/64721514-f1673300-d4cc-11e9-9864-dff597bf4af0.png)

**Comment by TravelinMax** [comment]
@janpieper put each line of your key in quotes and separate each line with a comma. E.g.
```
"--------BEGIN RSA PRIVATE KEY ----------",
"why-is-this-not-allowed?",
"actually-it-is!",
"--------END RSA PRIVATE KEY------------"
```

**Comment by frenck** [comment]
Yep, @TravelinMax is correct.
👍
