### ISSUE TITLE
SSH addon, even if you change port in settings, it still uses port 22

### ISSUE THREAD

**Issue by Klagio** [home-assistant/hassio-addons#696]
SSH addon, even if you change port in settings, it still uses port 22
HASSIO 0.98.4
SSH addon ver 6.3

**Comment by Levdbas** [comment]
Same here. The logs read: 

`Server listening on 0.0.0.0 port 22.`

**Comment by pvizeli** [comment]
You see the add-on port. You can only change the host port.
