### ISSUE TITLE
Check Home Assistant configuration FLAG

### ISSUE THREAD

**Issue by IsaTTeN** [home-assistant/hassio-addons#698]
Hi

Good job for this awesome project

Would it be possible to add a binary sensor fot the Check Home Assistant configuration Addon which would indicate if the new version is ok?

In this way we could automate actions, for example automatically update, etc

Best regards

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

Welcome to the project! 🎉
