### ISSUE TITLE
changing config.txt messes up Hassio

### ISSUE THREAD

**Issue by Try2Fly** [home-assistant/hassio-addons#699]
EDIT: this is with regards to the DECONZ add-on

I have a raspbee and am trying to get this working. As per guide i try to add the following to the end of config.txt in the root folder:

enable_uart=1
dtoverlay=pi3-miniuart-bt

However this messes up my system, and home assistant will no longer start. Als not after deleting it again. I have to do a full reinstall to get HA back.

I'm I placing the text in the wrong location?

**Comment by pvizeli** [comment]
Doublicate: https://github.com/home-assistant/hassos/issues/480
