### ISSUE TITLE
SSH 6.4 not starting: hassio.docker end point error

### ISSUE THREAD

**Issue by mikewebb70** [home-assistant/hassio-addons#700]
I've also tried uninstalling and doing an install vs upgrade and still the result.

I've tried using ssh keys alone and a password alone and still the same result

There are no entries in either the log addon, system log or the addon log

EDIT:  Thanks to Home Assistant Discord I found the logs for addons.  My error appears to be HASSIO docker related:
`19-09-16 04:41:27 ERROR (SyncWorker_18) [hassio.docker] Can't start addon_core_ssh: 403 Client Error: Forbidden ("endpoint with name addon_core_ssh already exists in network hassio")`

**Comment by pvizeli** [comment]
Yeah, that is a docker bug. I need to extend the "hassio su repair" command to fix such issues to. You need run on terminal with docker access: `docker network disconnect -f addon_core_ssh`

**Comment by mikewebb70** [comment]
Yep, did the trick, thanks
