### ISSUE TITLE
Lets Encrypt 4.0 Addon error: not a valid value for dictionary value @ data

### ISSUE THREAD

**Issue by rlopez2005** [home-assistant/hassio-addons#717]
Just upgraded Home Assistant to 0.99.3 and Lets Encrypt Addon to v4.0 and i receive a Lets Encrypt addon error. So i delete the addon and reinstalled it again and now i continue receiving this error with addon config:  "not a valid value for dictionary value @ data['options']. Got {'email': 'xxxx@gmail.com', 'domains': ['xxxxxx.ddns.net'], 'certfile': 'fullchain.pem', 'keyfile': 'privkey.pem', 'challenge': 'http'}"
![2019-09-26 095336](https://user-images.githubusercontent.com/28844145/65689517-a0fee200-e043-11e9-96e2-c70517e88623.jpg)
Hass.io Supervisor is version 189.

**Comment by pvizeli** [comment]
Is fix with >= 4.1

**Comment by rlopez2005** [comment]
Hello again.
Just installed 4.2 but still not working.
![2019-09-26 124655](https://user-images.githubusercontent.com/28844145/65703913-f810b100-e05b-11e9-8d54-e96c517e324a.jpg)
