### ISSUE TITLE
Complete DuckDNS add-on documentation

### ISSUE THREAD

**Issue by frenck** [home-assistant/hassio-addons#719]
The [DuckDNS add-on documentation](https://github.com/home-assistant/hassio-addons/blob/master/duckdns/README.md) is currently incomplete.

The following sections need more information:

- The "How to use" section is empty.
- The "Configuration" section, has not documented the add-on configuration options.
- The "Known issues and limitations" is empty.

**Comment by dnguyen800** [comment]
I'd like to update the documentation. Can you assign to me?
