### ISSUE TITLE
Add documentation to the google_assistant add-on

### ISSUE THREAD

**Issue by frenck** [home-assistant/hassio-addons#724]
The [`google_assistant`](https://github.com/home-assistant/hassio-addons/tree/master/google_assistant) add-on, currently, does not have documentation in its repository.
We should add it, so the users see the documentation and information in the Hass.io add-on and add-on store pages in the Home Assistant frontend.

A `README.md` file needs to be added. The documentation of the [`check_config`](https://github.com/home-assistant/hassio-addons/blob/master/check_config/README.md) add-on is a good example that can be used.

**Comment by RahulRavishankar** [comment]
Hey! I would like to work on it

**Comment by frenck** [comment]
Thanks! Looking forward to the PR 🎖
