### ISSUE TITLE
Add documentation to the nginx_proxy add-on

### ISSUE THREAD

**Issue by frenck** [home-assistant/hassio-addons#732]
The [`nginx_proxy`](https://github.com/home-assistant/hassio-addons/tree/master/nginx_proxy) add-on, currently, does not have documentation in its repository.
We should add it, so the users see the documentation and information in the Hass.io add-on and add-on store pages in the Home Assistant frontend.

A `README.md` file needs to be added. The documentation of the [`check_config`](https://github.com/home-assistant/hassio-addons/blob/master/check_config/README.md) add-on is a good example that can be used.

**Comment by dnguyen800** [comment]
Hi @frenck , I can add the documentation. I plan to leverage the documentation from [check_config](https://github.com/home-assistant/hassio-addons/blob/master/check_config/README.md) add-on and the Home Assistant [website](https://www.home-assistant.io/addons/nginx_proxy/).
