### ISSUE TITLE
Update rpc_shutdown add-on to use Bashio

### ISSUE THREAD

**Issue by frenck** [home-assistant/hassio-addons#733]
The add-ons now have [Bashio](https://github.com/hassio-addons/bashio) available, which makes it easier and nicer to work with and is easier to understand. The `rpc_shutdown` add-on needs to be rewritten to use the Bashio functions.

In general, this only requires changes to the add-on [`run.sh`](https://github.com/home-assistant/hassio-addons/blob/master/rpc_shutdown/run.sh) script. A good example of an add-on that has been migrated already, is [`deconz`](https://github.com/home-assistant/hassio-addons/blob/master/deconz/data/run.sh).

Please note, nothing has to be done to make Bashio available, it is already baked-in into the add-on base images.

**Comment by stefanroelofs** [comment]
If somebody is already updating the run.sh file, here's an unrelated request:

Add the argument -t 60 to line number 26:

if ! msg="$(net rpc shutdown -I "$ADDRESS" -U "$CREDENTIALS" -t 60)"; then

Supposedly, this will give any user currently using the computer about to be shut down a 60 second heads up, before actually shutting down the PC. The user may also be able to cancel the request, but I'm not sure. I've not tested this myself.

**Comment by frenck** [comment]
@stefanroelofs Moved your comments into a separate issue.

**Comment by stefanroelofs** [comment]
This issue may be closed.
The addon was updated to bashio:
https://github.com/home-assistant/hassio-addons/pull/792

**Comment by frenck** [comment]
👍
