### ISSUE TITLE
Add documentation to the samba add-on

### ISSUE THREAD

**Issue by frenck** [home-assistant/hassio-addons#736]
The [`samba`](https://github.com/home-assistant/hassio-addons/tree/master/samba) add-on, currently, does not have documentation in its repository.
We should add it, so the users see the documentation and information in the Hass.io add-on and add-on store pages in the Home Assistant frontend.

A `README.md` file needs to be added. The documentation of the [`check_config`](https://github.com/home-assistant/hassio-addons/blob/master/check_config/README.md) add-on is a good example that can be used.

**Comment by adonno** [comment]
I've created a README.md and started filling it out not sure though if it's alright

**Comment by frenck** [comment]
Thanks, @adonno 👍
