### ISSUE TITLE
Add documentation to the snips add-on

### ISSUE THREAD

**Issue by frenck** [home-assistant/hassio-addons#738]
The [`snips`](https://github.com/home-assistant/hassio-addons/tree/master/snips) add-on, currently, does not have documentation in its repository.
We should add it, so the users see the documentation and information in the Hass.io add-on and add-on store pages in the Home Assistant frontend.

A `README.md` file needs to be added. The documentation of the [`check_config`](https://github.com/home-assistant/hassio-addons/blob/master/check_config/README.md) add-on is a good example that can be used.

**Comment by Mofeywalker** [comment]
I would like to provide the README,

**Comment by Mofeywalker** [comment]
What about the mqtt_bridge config? I didn't find anything regarding the entries here: [https://www.home-assistant.io/addons/snips/]()
Is the config mandatory? Is it deprecated?
