### ISSUE TITLE
deCONZ + Hassio on pi 4/RaspBee, firmware not found

### ISSUE THREAD

**Issue by youlib** [home-assistant/hassio-addons#740]
Hi,
I have a pi 4 with a hassio installed, together with a RaspBee. The board is on the pi, and if I check under system->hardware, I see "serial: /dev/ttyAMA0. ". 
deCONZ plugin is installed, and started. 
"discovery" is on my yaml, and under integrations the device shows up. 
If I go to the Phoscon page and do discovery, my philips hue light is not discovered. Under gateway, firmware shows as "Not connected". 
I have not managed to do anything regarding the API key, and I cannot understand how to address this. If I visit the integrations hassio page, I cannot trigger the API key call, in any way.
HassOS 3.4 What am I missing?

**Comment by youlib** [comment]
More info regarding getting an API key.
I am attaching my postman request, plus the unlocked status from the gui, while I make the request:

<img width="1044" alt="Screenshot 2019-09-29 at 19 48 52" src="https://user-images.githubusercontent.com/16777300/65836774-5eaefc80-e2f2-11e9-9f28-88dcd92f7ddb.png">

<img width="957" alt="Screenshot 2019-09-29 at 19 47 49" src="https://user-images.githubusercontent.com/16777300/65836786-68d0fb00-e2f2-11e9-8f47-51a15e0c849d.png">

**Comment by LeroyShirto** [comment]
I had a similar issue the other day with my raspberry pi 4. I had missed step 1 in the installation guide https://phoscon.de/en/raspbee/install

```
Would you like the serial port hardware to be enabled? → Yes
```

After doing this and a reboot deconz was able to connect to the device.

**Comment by youlib** [comment]
Thanks for the reply, LeroyShirto, but if I'm non mistaken this step refers to rasbian, I have a hassio

**Comment by thelefty** [comment]
Were you able to fix this? I'm having the same issue.

**Comment by mwegener-com** [comment]
same for me. How to fix this?
