### ISSUE TITLE
ipv6 update for duck dns addon not working

### ISSUE THREAD

**Issue by ajfriesen** [home-assistant/hassio-addons#755]
I have hassio installed on my ubuntu server.
I used this installation method: https://www.home-assistant.io/hassio/installation/#alternative-install-on-a-generic-linux-host

I am using nginx proxy manager add on and did setup port forwarding for ipv4.
I also configured duck dns add on, but it only updates my ipv6 adress:

```
[23:18:13] INFO: OK
89.0.117.166

NOCHANGE
[23:23:14] INFO: OK
89.0.117.166
```

When I check the interface with the hassio terminal:
```
2: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 9c:b6:54:06:74:e1 brd ff:ff:ff:ff:ff:ff
    inet 192.168.178.60/24 brd 192.168.178.255 scope global enp3s0
       valid_lft forever preferred_lft forever
    inet6 fd00::9eb6:54ff:fe06:74e1/64 scope global deprecated dynamic 
       valid_lft 1287sec preferred_lft 0sec
    inet6 2001:4dd2:45c1:0:9eb6:54ff:fe06:74e1/64 scope global dynamic 
       valid_lft 6715sec preferred_lft 3115sec
    inet6 fe80::9eb6:54ff:fe06:74e1/64 scope link 
       valid_lft forever preferred_lft forever
```
the current ipv6 adress is this one "2001:4dd2:45c1::9eb6:54ff:fe06:74e1".
But as stated above it is not updating that address.
Could it be the format?

When updating duck dns manually with that ip everything works perfectly.
It is also rather stable for me but still the issue persists that this is not automated for now.

Any idea?

**Comment by scop** [comment]
Duck DNS doesn't support IPv6 autodetection at the moment, see https://www.duckdns.org/faqs.jsp

See also #1019
