### ISSUE TITLE
Add timeout option to RPC shutdown

### ISSUE THREAD

**Issue by frenck** [home-assistant/hassio-addons#757]
If somebody is already updating the run.sh file, here's an unrelated request:

Add the argument -t 60 to line number 26:

if ! msg="$(net rpc shutdown -I "$ADDRESS" -U "$CREDENTIALS" -t 60)"; then

Supposedly, this will give any user currently using the computer about to be shut down a 60 second heads up, before actually shutting down the PC. The user may also be able to cancel the request, but I'm not sure. I've not tested this myself.

_Originally posted by @stefanroelofs in https://github.com/home-assistant/hassio-addons/issues/733#issuecomment-538546617_

**Comment by frenck** [comment]
IMHO that value should not be hardcoded. Let's make it a variable on each machine configuration.

**Comment by stefanroelofs** [comment]
I made this and created a pull request for this:
https://github.com/home-assistant/hassio-addons/pull/759

**Comment by stefanroelofs** [comment]
This issue may be closed.
Option was added in: https://github.com/home-assistant/hassio-addons/pull/792

**Comment by frenck** [comment]
👍
