### ISSUE TITLE
Configurator not working offline (without the internet) + weird requests

### ISSUE THREAD

**Issue by Misiu** [home-assistant/hassio-addons#760]
I've noticed that Configurator needs internet access to start. Many resources (js, css, png's) are downloaded while opening Configurator:
![image](https://user-images.githubusercontent.com/1741838/66350937-d917f600-e95c-11e9-94e1-fba449634fe3.png)

Many resources are downloaded from cloudflare, gstatic and googleapis.

I noticed that there are some avatars downloading from github, but there are 3 requests to drive.google.com. What are they for?
In Chrome I get this warning:

> Cross-Origin Read Blocking (CORB) blocked cross-origin response https://drive.google.com/uc?export=view&id=0B6wTGzSOtvNBeld4U09LQkV0c2M with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

![image](https://user-images.githubusercontent.com/1741838/66351292-90147180-e95d-11e9-8e90-7f4ca2149915.png)

Would it be possible to make Configurator work offline? All files required by Add-on should be included in addon and not downloaded from the internet every time You go to Configurator.

I think that this would be a great improvement, because now (especially on slow internet) You must wait really long for Configurator to load. Also sometimes the user wants to set up HA to work offline (without the internet). Currently this isn't possible

**Comment by frenck** [comment]
That is out of scope for the add-on.
Add-ons wrap existing applications, you are requesting a change to that application.
Please file a feature request to the upstream project.

👍
