### ISSUE TITLE
Remove jQuery dependency from Configurator

### ISSUE THREAD

**Issue by Misiu** [home-assistant/hassio-addons#761]
[Recent PR](https://github.com/home-assistant/home-assistant-polymer/pull/3734) in home-assistant-polymer removes jQuery.
Currently, Configurator is requiring jQuery as a dependency.
Please consider removing it.

**Comment by frenck** [comment]
I'm not sure how that is related to the add-on?

**Comment by Misiu** [comment]
For some reasons Home Assistant front-end is removing jQuery.
I thought that this add-on, that is one of the "must have" add-ons should follow the same road.

**Comment by iantrich** [comment]
Are you thinking it will break or just think jQuery should be removed?

**Comment by balloob** [comment]
The frontend and add-ons are not sharing their dependencies and development is not related. Configurator is built with jQuery and it cannot be removed.

**Comment by Misiu** [comment]
@balloob @iantrich is Configurator build from https://github.com/danielperna84/hass-configurator?
I was searching for the sources in this repo but couldn't find them. I think it's better to create such a request there.

**Comment by iantrich** [comment]
Why are you meeting this request though?

**Comment by frenck** [comment]
@misiu, yes that is the one.
But once again, changes in Home Assistant do not affect the applications running inside an addon.

**Comment by Misiu** [comment]
@iantrich Currently, Configurator is requiring all dependencies (including jQuery) from CDN.
My main goal is to be able to use Configurator in an offline scenario (I know it's an uncommon case, but I need it).
I know that Home Assistant and add-ons aren't related (they don't share dependencies).

@danielperna84 mentioned [here](https://github.com/danielperna84/hass-configurator/issues/166#issuecomment-539251346) that Configurator will become obsolete with HA 1.0. Does that mean that a feature like Configurator will be build-in into HA? Maybe Configurator will be added do HA?

As I mentioned my main goal is to be able to edit all files via a web interface in an offline scenario. (I'm aware that there is cloud9 based add-on but it is too complex, Configurator is ideal)

**Comment by frenck** [comment]
@misiu, you are asking these questions in the wrong please. Please consult the upstream repository.

**Comment by Misiu** [comment]
@frenck I'll do that. Thanks 🙂
