### ISSUE TITLE
Snips addon ver 5.3 : issue on the NLU engine 

### ISSUE THREAD

**Issue by dpieri58** [home-assistant/hassio-addons#763]
The last version of Snips addon (5.3) is running with a NLU model (ver 0.19.0) not aligned with the model used bt the Snips console (ver 0.20.0).
Following the error message when start the Snips addon  with an assistant.zip made by the Snips console:
INFO:snips_nlu_hermes: loading nlu engine "/usr/share/snips/assistant/nlu_engine"
ERROR:snips_nlu       : Unable to read file '/usr/share/snips/assistant/nlu_engine/nlu_engine.json'
 -> caused by: Mismatched model version: model is 0.20.0 but runner is 0.19.0

**Comment by bqv** [comment]
What needs to be done to fix this. I'm unable to use this addon because I'm starting on this version and don't have any previous assistants to fall back on

**Comment by pvizeli** [comment]
Maybe an version update?
