### ISSUE TITLE
wanted to change my login's tried reinstalling it, but it has never worked anymore

### ISSUE THREAD

**Issue by Chaosflori25** [home-assistant/hassio-addons#772]
![image](https://user-images.githubusercontent.com/44469989/66608222-52f6ec00-ebb6-11e9-88f8-4e6d0b712b8b.png)
 That's my error, maybe you can help me?

**Comment by frenck** [comment]
`require_certificate` is missing in the list of options. See https://github.com/home-assistant/hassio-addons/blob/master/mosquitto/README.md for the latest documentation and example.
