### ISSUE TITLE
Samba add-on doesn't start

### ISSUE THREAD

**Issue by ivelin** [home-assistant/hassio-addons#774]
Just installed Samba add-on on a brand new clean Hass.io image on RPI4. Waited 15 minutes after Start. Still no logs. No obvious indication what's going on. Maybe I'm missing something obvious. Screenshots attached for reference.

![Screen Shot 2019-10-11 at 5 53 19 PM](https://user-images.githubusercontent.com/2234901/66689370-33ac9d00-ec50-11e9-920c-43254744aa51.png)
![Screen Shot 2019-10-11 at 5 52 46 PM](https://user-images.githubusercontent.com/2234901/66689373-360ef700-ec50-11e9-822b-40548ba98083.png)
![Screen Shot 2019-10-11 at 5 53 11 PM](https://user-images.githubusercontent.com/2234901/66689376-38715100-ec50-11e9-854f-4a2ebe82e5f0.png)

**Comment by frenck** [comment]
Could you please supply some logs?
If there are logs from the add-on tab, that would be nice.
Else, there are always logs visible in **Hass.io panel** -> **System tab** -> **Logs**

**Comment by ivelin** [comment]
OK, I got it start. See longs. 

It wasn't obvious from the add-on intro screen or docs that password cannot be left as null. Similar to the other services, the initial UX is confusing. Maybe we can think about a mandatory initial screen for any add-on that makes sure the user understands and enters the minimum required information.

What also makes things confusing is that the Hass.io official documentation promises the user that they won't have to deal with authentication for each add-on, because that's part of the contract between the add-on developer and Hass.io. So having to bump into basic authentication , login and SSL for an add-on that's running within Hass.io's already SSL and credentials secured local UI is counter intuitive.

I will ping @frenck on Discord to see how we can turn this discussion into action. 

Feel free to close this issue.

```
Log
[09:59:17] INFO: Hostname: hassio
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
No builtin backend found, trying to load plugin
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
tdb(/var/lib/samba/winbindd_idmap.tdb): tdb_open_ex: could not open file /var/lib/samba/winbindd_idmap.tdb: No such file or directory
tdb(/var/lib/samba/account_policy.tdb): tdb_open_ex: could not open file /var/lib/samba/account_policy.tdb: No such file or directory
account_policy_get: tdb_fetch_uint32_t failed for type 1 (min password length), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 2 (password history), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 3 (user must logon to change password), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 4 (maximum password age), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 5 (minimum password age), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 6 (lockout duration), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 7 (reset count minutes), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 8 (bad lockout attempt), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 9 (disconnect time), returning 0
account_policy_get: tdb_fetch_uint32_t failed for type 10 (refuse machine password change), returning 0
Added user hassio.
nmbd version 4.10.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2019
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
added interface docker0 ip=172.17.0.1 bcast=172.17.255.255 netmask=255.255.0.0
added interface hassio ip=172.30.32.1 bcast=172.30.33.255 netmask=255.255.254.0
added interface eth0 ip=192.168.86.248 bcast=192.168.86.255 netmask=255.255.255.0
making subnet name:192.168.86.248 Broadcast address:192.168.86.255 Subnet mask:255.255.255.0
making subnet name:172.30.32.1 Broadcast address:172.30.33.255 Subnet mask:255.255.254.0
making subnet name:172.17.0.1 Broadcast address:172.17.255.255 Subnet mask:255.255.0.0
making subnet name:UNICAST_SUBNET Broadcast address:0.0.0.0 Subnet mask:0.0.0.0
making subnet name:REMOTE_BROADCAST_SUBNET Broadcast address:0.0.0.0 Subnet mask:0.0.0.0
load_lmhosts_file: Can't open lmhosts file /etc/samba/lmhosts. Error was No such file or directory
daemon_ready: daemon 'nmbd' finished starting up and ready to serve connections
smbd version 4.10.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2019
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Processing section "[config]"
Processing section "[addons]"
Processing section "[ssl]"
Processing section "[share]"
Processing section "[backup]"
added interface docker0 ip=172.17.0.1 bcast=172.17.255.255 netmask=255.255.0.0
added interface hassio ip=172.30.32.1 bcast=172.30.33.255 netmask=255.255.254.0
added interface eth0 ip=192.168.86.248 bcast=192.168.86.255 netmask=255.255.255.0
INFO: Profiling support unavailable in this build.
No builtin backend found, trying to load plugin
tdb(/var/lib/samba/registry.tdb): tdb_open_ex: could not open file /var/lib/samba/registry.tdb: No such file or directory
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
waiting for connections
check_for_master_browser_fail: Forcing election on workgroup WORKGROUP subnet 172.17.0.1
check_for_master_browser_fail: Forcing election on workgroup WORKGROUP subnet 172.30.32.1
check_for_master_browser_fail: Forcing election on workgroup WORKGROUP subnet 192.168.86.248
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.17.0.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.30.32.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 192.168.86.248
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.17.0.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.30.32.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.17.0.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.30.32.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.17.0.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.30.32.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.17.0.1
run_elections: >>> Won election for workgroup WORKGROUP on subnet 172.17.0.1 <<<
become_local_master_browser: Starting to become a master browser for workgroup WORKGROUP on subnet 172.17.0.1
send_election_dgram: Sending election packet for workgroup WORKGROUP on subnet 172.30.32.1
run_elections: >>> Won election for workgroup WORKGROUP on subnet 172.30.32.1 <<<
become_local_master_browser: Starting to become a master browser for workgroup WORKGROUP on subnet 172.30.32.1
```

**Comment by frenck** [comment]
I guess the installation steps for this addon could use an additional step, let’s leave this issue open to achieve that

**Comment by dtx360** [comment]
A related follow-up on the original issue (add-on not starting):

When I tried to access my samba share today the add-on had failed to start.
Checking the add-on log and it says:
/run.sh: line 21: bashio::log.warn: command not found

The Hassio log just says:
19-10-12 18:28:32 INFO (SyncWorker_6) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-samba with version 8.2

Tried to re-install add-on, update HA to 0.100, re-install add-on again, still no-go.

**Comment by robmikulec** [comment]
> A related follow-up on the original issue (add-on not starting):
> 
> When I tried to access my samba share today the add-on had failed to start.
> Checking the add-on log and it says:
> /run.sh: line 21: bashio::log.warn: command not found
> 
> The Hassio log just says:
> 19-10-12 18:28:32 INFO (SyncWorker_6) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-samba with version 8.2
> 
> Tried to re-install add-on, update HA to 0.100, re-install add-on again, still no-go.

I am having the exact same issue.  Any help would be greatly appreciated,

**Comment by frenck** [comment]
I've just put out a new version addressing the issue, also address the "How to use" section to be more clear on setting a username & password.

**Comment by dtx360** [comment]
Updated and comfirmed working. Good job!
// Per

På 13 oktober 2019 till 14:57:12, Franck Nijhof (notifications@github.com)
skrev:
