### ISSUE TITLE
nginx cloudflare docs missing

### ISSUE THREAD

**Issue by scop** [home-assistant/hassio-addons#776]
The cloudflare feature added in #697 is missing from docs in:
- https://github.com/home-assistant/hassio-addons/blob/master/nginx_proxy/README.md (#751)
- https://github.com/home-assistant/home-assistant.io/blob/current/source/_addons/nginx_proxy.markdown

**Comment by frenck** [comment]
Wel spotted @scop! 👍 

### 🆘 Marked as "Help wanted"

If you want to help out on this, go ahead, it is really appreciated!

Please leave a comment if you started working on this, so we can avoid multiple people working on the same things. Thanks! 👍

**Comment by scop** [comment]
I did start a bit, but I'm not using the feature nor do I plan to, and I have more "pressing" things to learn/spend time on :) I think it would be a breeze for someone who actually knows exactly what this is about to document it.

**Comment by frenck** [comment]
Both docs are adjusted. Thanks @mrwacky42 👍
