### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by mszymura** [home-assistant/hassio-addons#800]
hi, trying to nstall on a proxmox hassio  and keep getting an error which stops the download.

19-10-21 21:14:29 INFO (SyncWorker_2) [hassio.docker.interface] Pull image homeassistant/amd64-addon-deconz tag 3.6.
19-10-21 21:14:30 ERROR (SyncWorker_2) [hassio.docker.interface] Can't install homeassistant/amd64-addon-deconz:3.6 -> 500 Server Error: Internal Server Error ("readlink /mnt/data/docker/overlay2: invalid argument").

**Comment by pvizeli** [comment]
`hassio su repair`
