### ISSUE TITLE
Snips tts rate change

### ISSUE THREAD

**Issue by lambtho12** [home-assistant/hassio-addons#801]
Some speakers (Jabra 410/510 for instance) do not use the default sampling rate, making the tts functionality of Snips unusable (text is spoken way too fast to be understood).
The solution would be to be able to modify the `rate` parameter in `/root/.asoundrc`, directly from the addon configuration ideally. 

See following forum topic regarding this issue and temporary workaround.
https://community.home-assistant.io/t/how-to-modify-the-file-in-the-pre-built-image-of-snips-addon/28479

**Comment by pvizeli** [comment]
Instead to see a workaround -> https://github.com/home-assistant/hassio make it configurable per add-on. Would be nice 👍

**Comment by lambtho12** [comment]
I saw you flagged it as "help wanted". Unfortunately I do not think I am competent enough to do the PR myself. I never really used git, nor Docker proactively.

I think the way to go would be to:
1. Add a line like `sound_rate` in the `config.json` file
2. Create `asound.conf`file with default rate of 16000
3. Make docerfile copy the `asound.conf`file in `/etc/`
4. In `run.sh` add a few lines to insert the correct rate in `asound.conf` file using the input `sound_rate` (if nothing specified, do nothing)

Would that work?

**Comment by frenck** [comment]
Sonos bought Snips and decided to take it offline. Therefore the add-on is now deprecated and will be removed soon.
