### ISSUE TITLE
Let's encrypt support for Webmin TXT records

### ISSUE THREAD

**Issue by JustinHoeky** [home-assistant/hassio-addons#802]
Hi there,

Is there any implementation schedulded to support Webmin TXT records as a DNS option?
Since i don't have any of the cloud dns service providers, i cannot get it working.

Kind regards,
Justin

**Comment by DSuds** [comment]
LetsEncrypt depends on finding a trusted resource in the cloud to decide to give you a certificate.  To have this happen in an automated fashion you need to be able to create the records automatically - steps for the specified providers are built in.
For a local Webmin I could just say I was google.com and serve TXT records, but it won't check out and letsEncrypt will not give me a cert saying I am.
If you don't have a domain you actually own you should look at creating your own certificates and not using LetsEncrypt to confirm you control the domain.
