### ISSUE TITLE
CEC Scanner "autodetect FAILED" error on Pi 3 B

### ISSUE THREAD

**Issue by waded** [home-assistant/hassio-addons#815]
CEC Scanner, when installed and started using the Hass.io add-ons interface, just outputs the following:

```
INFO: Starting CEC client scan...
autodetect FAILED
```

Expected more useful cec-client output.

I did some exploration and it appears that libcec in homeassistant/armv7-addon-cec_scan:2.1 doesn't include RPi support. I say that because I ran this command on the hass.io Pi 3 B host in question: 

```
docker run -it homeassistant/armv7-addon-cec_scan:2.1 cec-client -i
```

and in the result:

```
libCEC version: 4.0.3, git revision: libcec-4.0.3, compiled on Sat Jun  1 19:54:31 UTC 2019 by root@fdb1f35be05b on Linux 4.15.0-1041-azure (armv7l), features: P8_USB, DRM, P8_detect
```

did not see the `RPi` at the end of the list of features as expected.

I interactively recompiled libcec in that container on the host, using the most recent change to the Dockerfile https://github.com/home-assistant/hassio-addons/commit/7e6adcab3280f458172d6d6a5653276c16f80107 for reference, and I was able to get cec-client to work that way, suggesting something wrong w/ the container build.

After the recompile, within the container `cec-client i` then showed RPi support:

```
libCEC version: 4.0.3, git revision: libcec-4.0.3, compiled on Tue Nov  5 21:42:57 UTC 2019 by root@c6a286913f8d on Linux 4.14.98-v7 (armv7l), features: P8_USB, DRM, P8_detect, RPi
```
and the command the add-on runs now works within the container instead of saying *autodetect FAILED*:

```
echo scan | cec-client -s -d 1
opening a connection to the CEC adapter...
requesting CEC bus information ...
CEC bus information
===================
device #0: TV
address:       0.0.0.0
active source: no
vendor:        Unknown
osd string:    TV
CEC version:   unknown
power status:  unknown
language:      ???


device #1: Recorder 1
address:       1.5.0.0
active source: no
vendor:        Pulse Eight
osd string:    CECTester
CEC version:   1.4
power status:  on
language:      eng


<snipped here>
```

Hass.io is the 32-bit build, version 0.101.2. CEC Scanner version is 2.1.

```
arch: armv7
boot: true
custom: false
image: homeassistant/raspberrypi3-homeassistant
ip_address: 172.30.32.1
last_version: 0.101.2
machine: raspberrypi3
port: 8123
ssl: false
version: 0.101.2
wait_boot: 600
watchdog: true
```

**Comment by waded** [comment]
Other people are possibly trying to report they're seeing this behavior on closed issues:
https://github.com/home-assistant/hassos/issues/100
and 
https://github.com/home-assistant/hassio-homeassistant/issues/1

**Comment by waded** [comment]
The two things I did when recompiling that the Dockerfile would only conditionally do are:

`apk add --no-cache raspberrypi-dev raspberrypi-libs`
and
`cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DRPI_INCLUDE_DIR=/opt/vc/include -DRPI_LIB_DIR=/opt/vc/lib ..`

Not sure which of those did the trick. Hopefully this is enough information to get someone on the  path to a fix!

**Comment by waded** [comment]
To revive this issue I suggest going through the steps in this addon's readme verbatim ("Installation" mentions installing using Hass.io addon-on store and "How to use.") (as described in "How to use".) Do those steps result in useful 'cec-client' scan output, or just the error message described here? I am not so sure the Pi hardware revision matters.

If the addon doesn't work even on the Hass.io happy path maybe it should be removed from the store.

**Comment by waded** [comment]
I can confirm this is fixed on Pi 3 B with a clean install of hass.io and CEC Scanner 2.2. The scan now shows up in CEC Scanner's log (you may have to refresh it a few times after pressing Start.)

![image](https://user-images.githubusercontent.com/1535656/72210694-90e90200-347c-11ea-9cc3-8834a9e1a359.png)

If anyone continues to see _autodetect FAILED_ errors I suggest you make sure you're on CEC Scanner 2.2, and please file a new issue with hardware/build info. I think it is still likely there are other root causes of _autodetect FAILED_ that were masked by this issue.

**Comment by docholiday** [comment]
I am on a Raspberry Pi 3 B, too and also received the "autodetect FAILED" message.
Hass.io info:

hassio > info
arch: armv7
channel: stable
hassos: "3.8"
homeassistant: 0.104.3
hostname: hassio
logging: info
machine: raspberrypi3
supervisor: "195"
supported_arch:
- armv7
- armhf

CEC scanner version only says "2", so I'm not sure if I am on the newest one. But it doesn't tell me, that it is possible to update.

**Comment by waded** [comment]
@docholiday There was a version "2" release of the CEC Scanner add-on. I don't know how addon updates are expected to work in hass.io, but getting it up to "2.2" is where you should focus if you'd like to use CEC Scanner. This bug was concerned with a break that occurred in "2.1", but it is quite possible "2" was similarly broken. (I don't know, but I didn't start using this until 2.1, at which point it had been broken for 6 months, so I take it it's a rather unpopular add-on for the Pi, a "if a tree falls in the forest" situation.)

**Comment by waded** [comment]
@docholiday Keep in mind also that CEC Scanner and hdmi_cec integration are functionally separate. You don't need to have one working to use the other. Although it's be helpful to see the physical addresses using CEC Scanner to use when [configuring hdmi_cec](https://www.home-assistant.io/integrations/hdmi_cec/) you can also just guess them, and I believe the debug level logging for the hdmi_cec component may expose approximately as much information as CEC Scanner.

**Comment by docholiday** [comment]
@waded Thanks a lot for the heads up! I guess the devs have to include the version into hass.io.
I'll try it your way, but I'll also write a new issue, that version 2.2 is missing in hass.io.

**Comment by alecsandes** [comment]
Hi Folks,

I have installed Home Assistant supervised using this tutorial: https://peyanski.com/how-to-install-home-assistant-supervised-official-way/

When I try to start CEC-Scan:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[02:10:19] INFO: Starting CEC client scan...
autodetect FAILED
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

In HA I don't have any HDMI in Developer Tools > Services

![image](https://user-images.githubusercontent.com/19631942/140236098-e84c431b-b637-4afe-b58f-1150915cef18.png)

What to do?
When I run the cec-utils scan from SSH in raspbian, i get the list of devices.

Please help

**Comment by waded** [comment]
@alecsandes I suggest opening a new issue and including version of CEC Scanner you're using, and being more specific about install steps - the install steps you linked included multiple methods, and if you used the OS install method and are on CEC Scanner 3.0 it'd be very good to know details. If you used container install method - which I think is what you did - I suspect those steps are incomplete - what you said at "When I run the scan from cli i get" seems to indicate the container does not have access to the HDMI hardware (and so CEC Scanner doesn't either.) I highly recommend using the OS install method!

**Comment by farridav** [comment]
I am struggling with this issue too, and despite this issue being closed, its the most relevant to my problem, so im posting here in the hope there might be some help out there.

Setup:
- rpi4
- Latest HA installed in the recommended way (https://www.home-assistant.io/installation/raspberrypi#install-home-assistant-operating-system) 
- RPI connected to AV Receiver, along with some other devices

When I do the following:

`ssh root@homeassistant.local -p22222 docker exec -it homeassistant bash`
`bash-5.1# echo scan | cec-client -s -d 1`
> autodetect FAILED


`bash-5.1# cec-client -l`
> libCEC version: 6.0.2, git revision: libcec-6.0.2, compiled on 2022-11-24 15:21:51 by root@localhost on Linux 5.15.0-1023-azure (aarch64), features: P8_USB, DRM, P8_detect, Linux
> Found devices: NONE

Though i too have noticed that when i reboot my pi, connected to my AV receiver, it turns the receiver on, so CEC is working, but just not inside HA.

I've tried sending CEC commands via HA interface, but nothing

Should i be concerned that my `cec-client` is not built with RPi support, and if so, how do i recompile it?

**Comment by farridav** [comment]
*bump.. I've still not had any luck with this, and have been getting by with IR/RF for a while now, but would love to know how to solve this properly.

Anyone out there had this issue and found a resolution?

Thanks

**Comment by jonniepanda** [comment]
I'm getting the same issue with a clean HA install on RP4B :-(
