### ISSUE TITLE
Let's Encrypt add-on will not take my configuration no matter what

### ISSUE THREAD

**Issue by theofficefan** [home-assistant/hassio-addons#823]
No matter what I put into the add-on configuration, I always get this error when I save: "not a valid value for dictionary value @ data['options']." It says I have everything else, but it will not take the config. I have not been able to find anyone having this exact issue. Does anyone know what is going on?

**Comment by frenck** [comment]
Could you please share the config you are trying to use? There is not much for us to debug/support without it.

(Please be sure to redact/replace any sensitive data).

**Comment by theofficefan** [comment]
{
  "email": "user@gmail.com",
  "domains": [
    "hass.example.com"
  ],
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "challenge": "http"
}

**Comment by Zapfmeister** [comment]
Leave the "DNS" option in:

{
"email": "user@gmail.com",
"domains": [
"hass.example.com"
],
"certfile": "fullchain.pem",
"keyfile": "privkey.pem",
"challenge": "http",
"dns": {
  }
}

**Comment by theofficefan** [comment]
Thank you, that worked! I don't understand why that needs to be in though. I've seen so many tutorials, including home-assistant's own knowledgebase, that shows you don't need it.

**Comment by Zapfmeister** [comment]
Your welcome. Maybe i did something wrong with the integration, but im not aware of an possibility to have this option as optional item.
@frenck @pvizeli is there a way to have "dns": {} optional? Maybe with the schema "dns": {}? ?

**Comment by frenck** [comment]
It is currently not possible to make those optional.

Tutorials might get outdated, we cannot control the content on the web created by third-parties.

Nevertheless, glad you got it resolved! :+1:

**Comment by europacafe** [comment]
Hi,
If I want it to update more than one domain, how to specify them? Does the second domain need to have comma and blank preceding it?
