### ISSUE TITLE
HassIO Raspbee firmware update fails

### ISSUE THREAD

**Issue by craigrallen** [home-assistant/hassio-addons#828]
Installed and set up deCONZ and Raspbee into a Raspberry PI 3B+. The installation is successfull and the Zigbee network is working with remote test devices. When I try to update the firmware of the Raspbee in the deCONZ interface it says success, and then prompts to upgrade again after saying successful. The original firmware version shows up again once it reconnects.

In the deCONZ logs there is an update loop. see log out output at bottom for full details, but it keeps repeating the following two lines in the log

GW firmware version: 0x26050500
GW firmware version shall be updated to: 0x26330500

I'm stuck, I cannot flash using the Raspbian method on HassIO as far as I am aware?

The web interface keeps going back to the same installed version and presenting the update button, see screenshot

![image](https://user-images.githubusercontent.com/56693437/69008834-400ece80-094f-11ea-8d8a-23bfd64594b5.png)

LOG OUTPUT

14:38:44:695 Current channel 15
14:39:44:698 Current channel 15
14:40:20:699 dev /dev/ttyAMA0
14:40:20:699 GW firmware version: 0x26050500
14:40:20:699 GW firmware version shall be updated to: 0x26330500
14:40:44:694 Current channel 15
14:41:44:697 Current channel 15
14:42:30:695 dev /dev/ttyAMA0
14:42:30:696 GW firmware version: 0x26050500
14:42:30:696 GW firmware version shall be updated to: 0x26330500
14:42:44:695 Current channel 15
14:43:44:696 Current channel 15
14:44:40:686 dev /dev/ttyAMA0
14:44:40:686 GW firmware version: 0x26050500
14:44:40:686 GW firmware version shall be updated to: 0x26330500
14:44:44:696 Current channel 15
14:45:44:696 Current channel 15
14:46:44:704 Current channel 15
14:46:50:698 dev /dev/ttyAMA0
14:46:50:698 GW firmware version: 0x26050500
14:46:50:698 GW firmware version shall be updated to: 0x26330500
14:47:44:694 Current channel 15
14:48:44:695 Current channel 15
14:49:00:688 dev /dev/ttyAMA0
14:49:00:689 GW firmware version: 0x26050500
14:49:00:689 GW firmware version shall be updated to: 0x26330500
14:49:44:697 Current channel 15
14:49:47:154 Announced to internet
14:49:47:154 discovery server date: Sun, 17 Nov 2019 13:49:47 GMT
14:49:47:154 	 local time seems to be ok
14:50:25:106 New websocket 192.168.255.164:53523 (state: 3) 
14:50:30:184 New websocket 192.168.255.164:53534 (state: 3) 
14:50:44:694 Current channel 15
14:51:10:682 dev /dev/ttyAMA0
14:51:10:682 GW firmware version: 0x26050500
14:51:10:682 GW firmware version shall be updated to: 0x26330500
14:51:44:694 Current channel 15
14:52:44:696 Current channel 15
14:53:20:698 dev /dev/ttyAMA0
14:53:20:698 GW firmware version: 0x26050500
14:53:20:698 GW firmware version shall be updated to: 0x26330500
14:53:44:702 Current channel 15
14:54:44:695 Current channel 15
14:55:30:692 dev /dev/ttyAMA0
14:55:30:692 GW firmware version: 0x26050500
14:55:30:692 GW firmware version shall be updated to: 0x26330500
14:55:44:694 Current channel 15
14:56:44:696 Current channel 15
14:57:40:680 dev /dev/ttyAMA0
14:57:40:680 GW firmware version: 0x26050500
14:57:40:680 GW firmware version shall be updated to: 0x26330500
14:57:44:696 Current channel 15
14:58:44:700 Current channel 15
14:59:44:696 Current channel 15
14:59:50:679 dev /dev/ttyAMA0
14:59:50:680 GW firmware version: 0x26050500
14:59:50:680 GW firmware version shall be updated to: 0x26330500
15:00:44:700 Current channel 15
15:01:44:694 Current channel 15
15:02:00:699 dev /dev/ttyAMA0
15:02:00:699 GW firmware version: 0x26050500
15:02:00:699 GW firmware version shall be updated to: 0x26330500
15:02:44:697 Current channel 15
15:03:44:698 Current channel 15
15:04:10:695 dev /dev/ttyAMA0
15:04:10:695 GW firmware version: 0x26050500
15:04:10:695 GW firmware version shall be updated to: 0x26330500
15:04:44:696 Current channel 15
15:05:44:695 Current channel 15
15:06:20:691 dev /dev/ttyAMA0
15:06:20:691 GW firmware version: 0x26050500
15:06:20:691 GW firmware version shall be updated to: 0x26330500
15:06:44:702 Current channel 15
15:07:44:700 Current channel 15
15:08:30:698 dev /dev/ttyAMA0
15:08:30:698 GW firmware version: 0x26050500
15:08:30:698 GW firmware version shall be updated to: 0x26330500
15:08:44:696 Current channel 15
15:09:44:695 Current channel 15
15:10:11:656 SensorNode id: 2 (Bathroom Double Switch) no longer available
15:10:40:693 dev /dev/ttyAMA0
15:10:40:693 GW firmware version: 0x26050500
15:10:40:693 GW firmware version shall be updated to: 0x26330500
15:10:44:694 Current channel 15
15:11:44:695 Current channel 15
15:12:44:696 Current channel 15
15:12:50:692 dev /dev/ttyAMA0
15:12:50:693 GW firmware version: 0x26050500
15:12:50:693 GW firmware version shall be updated to: 0x26330500
15:13:44:694 Current channel 15
15:14:09:721 saved node state in 8 ms
15:14:09:793 sync() in 72 ms
15:14:44:695 Current channel 15
15:15:00:688 dev /dev/ttyAMA0
15:15:00:688 GW firmware version: 0x26050500
15:15:00:688 GW firmware version shall be updated to: 0x26330500
15:15:17:994 toggle LQU 1
15:15:44:699 Current channel 15
15:16:44:695 Current channel 15
15:17:10:689 dev /dev/ttyAMA0

**Comment by frenck** [comment]
In those cases, you can update the firmware manually using a different machine.
This is also linked in the add-on documentation.

See: <https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually>

From personal experience, the upgrade may fail if you have other serial devices connected to the same machine. In my case, the Aeontec Z-Wave stick causes a conflict. Disconnecting that device, allows me to upgrade.

**Comment by craigrallen** [comment]
Wow, that was such a quick reply, you're a legend :) 

I have a Aeontec Z-Wave USB stick... I completely overlooked removing that.... I'll test without it installed. 

I did look at the manual upgrade document, but wasn't sure if HassIO followed the Raspbian update procedure, it wasn't clear in the document. Maybe there should be a mention for it in HassIO?

Many thanks again for replying so quickly, I really appreciate it

**Comment by frenck** [comment]
LOL, I was just processing GitHub notifications 😉 So your timing was just good good 😉 

It is mentioned in the add-on documentation. So I'm not sure what you are trying to suggest.

If this provided a solution for you (and you feel like it is solved), I would suggest on closing the issue.

**Comment by craigrallen** [comment]
Just to confirm, in the manual upgrade document, I follow the Raspbian manual update procedure, I cannot find any reference in the document to HassIO manual update process. I do not have a spare Raspberry Pi to run the manual update on and the manual update commands don't work in the HassIO  SSH session... I  understand that HassIO is a docker image, but I don't know how to run the manual update inside HassIO. Sorry, it it's a dumb question :( How do I get the manual update working on a HassIO installed Pi?

**Comment by frenck** [comment]
That document linked by me (and the add-on documentation), is not OUR document. It does not list Hass.io/HassOS.

If the update from the UI fails, you need to do the upgrade on a different system, since you can't do it with the system running Hass.io at that point. Dresden provided upgrade guidelines in the linked document, even for doing it on a Window machine. After upgrading the firmware on a different system, simply place back the deCONZ stick in the Hass.io machine.

**Comment by craigrallen** [comment]
ok, cool. Needs a different host system for the manual upgrade. Many thanks for your help and confirming the situation.
