### ISSUE TITLE
Deconz 3.7+Conbee 2 stick sudden failure of the network

### ISSUE THREAD

**Issue by airens** [home-assistant/hassio-addons#830]
Hello, today all my ZigBee network stopped responding until I restarted image. That never happend before and I haven't done any changes in my network for maybe a week. Can somebody explain me what has happend and how to prevent it in the future?

> 07:02:50:707 device state timeout ignored in state 3
> 07:02:51:658 device state timeout ignored in state 3
> 07:02:52:614 device state timeout ignored in state 3
> 07:02:53:615 device state timeout ignored in state 3
> 07:02:54:613 device state timeout ignored in state 3
> 07:02:55:614 device state timeout (handled)
> 07:02:56:376 dev /dev/ttyAMA0
> 07:02:56:376 COM: /dev/ttyACM0 / serialno: DE1995779
> 07:02:56:376 COM: --dev: /dev/ttyACM0 (ConBee II)
> 07:02:56:515 start reconnect to network
> 07:02:56:515 void zmMaster::handleStateIdle(zmMaster::MasterEvent) not connected goto OFF state
> 07:02:56:515 device state timeout ignored in state 2
> 07:02:56:597 0x00158D0003967782 error APSDE-DATA.confirm: 0xA7 on task
> 07:02:56:754 0x00158D0003CF03AD error APSDE-DATA.confirm: 0xA7 on task
> 07:02:57:152 dev /dev/ttyAMA0
> 07:02:57:152 COM: /dev/ttyACM0 / serialno: DE1995779
> 07:02:57:152 COM: --dev: /dev/ttyACM0 (ConBee II)
> 07:02:57:183 dev /dev/ttyAMA0
> 07:02:57:183 COM: /dev/ttyACM0 / serialno: DE1995779
> 07:02:57:183 COM: --dev: /dev/ttyACM0 (ConBee II)
> 07:02:58:162 dev /dev/ttyAMA0
> 07:02:58:162 COM: /dev/ttyACM0 / serialno: DE1995779
> 07:02:58:162 COM: --dev: /dev/ttyACM0 (ConBee II)
> 07:02:58:191 dev /dev/ttyAMA0
> 07:02:58:191 COM: /dev/ttyACM0 / serialno: DE1995779
> 07:02:58:191 COM: --dev: /dev/ttyACM0 (ConBee II)
> 07:02:59:156 dev /dev/ttyAMA0
> 07:02:59:156 COM: /dev/ttyACM0 / serialno: DE1995779
> 07:02:59:156 COM: --dev: /dev/ttyACM0 (ConBee II)
> 07:02:59:186 dev /dev/ttyAMA0
> 07:02:59:186 COM: /dev/ttyACM0 / serialno: DE1995779
> 07:02:59:186 COM: --dev: /dev/ttyACM0 (ConBee II)
> 07:03:00:161 dev /dev/ttyAMA0
> 07:03:00:161 COM: /dev/ttyACM0 / serialno: DE1995779
> 07:03:00:161 COM: --dev: /dev/ttyACM0 (ConBee II)
> 07:03:00:191 dev /dev/ttyAMA0
> 07:03:00:191 COM: /dev/ttyACM0 / serialno: DE1995779
> 07:03:00:191 COM: --dev: /dev/ttyACM0 (ConBee II)
> 07:03:01:156 dev /dev/ttyAMA0
> 07:03:01:156 COM: /dev/ttyACM0 / serialno: DE1995779
> 07:03:01:156 COM: --dev: /dev/ttyACM0 (ConBee II)
> 07:03:01:186 dev /dev/ttyAMA0
> 07:03:01:186 COM: /dev/ttyACM0 / serialno: DE1995779
> 07:03:01:186 COM: --dev: /dev/ttyACM0 (ConBee II)
> 07:03:01:613 failed to reconnect to network try=1
> 07:03:02:156 dev /dev/ttyAMA0
> 07:03:02:156 COM: /dev/ttyACM0 / serialno: DE1995779
> 07:03:02:156 COM: --dev: /dev/ttyACM0 (ConBee II)
> 07:03:02:186 dev /dev/ttyAMA0
> 07:03:02:186 COM: /dev/ttyACM0 / serialno: DE1995779
> 07:03:02:186 COM: --dev: /dev/ttyACM0 (ConBee II)
> 07:03:03:165 dev /dev/ttyAMA0
> 07:03:03:165 COM: /dev/ttyACM0 / serialno: DE1995779
> 07:03:03:165 COM: --dev: /dev/ttyACM0 (ConBee II)
> 07:03:03:196 dev /dev/ttyAMA0
> 07:03:03:196 COM: /dev/ttyACM0 / serialno: DE1995779
> 07:03:03:196 COM: --dev: /dev/ttyACM0 (ConBee II)
> 07:03:04:114 wait reconnect 15 seconds
> 07:03:04:158 dev /dev/ttyAMA0
> 07:03:04:158 COM: --dev: /dev/ttyACM0 (ConBee II)
> 07:03:05:114 wait reconnect 14 seconds
> 07:03:06:114 wait reconnect 13 seconds
> 07:03:06:615 failed to reconnect to network try=2
> 07:03:07:113 wait reconnect 12 seconds
> 07:03:08:114 wait reconnect 11 seconds
> libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)

**Comment by iantrich** [comment]
Seeing a similar issue after upgrading to 3.7 last night

**Comment by frenck** [comment]
Meantime, we have upgraded the add-on. Has the situation improved?

**Comment by iantrich** [comment]
The situation, for me at least, was resolved with a restart. So not a show stopper. I'll see about upgrading tonight when everyone is asleep and will report back 👍

**Comment by airens** [comment]
> The situation, for me at least, was resolved with a restart. So not a show stopper. I'll see about upgrading tonight when everyone is asleep and will report back
The same for me. After restarting my server everything looks ok. And so after upgrading to the last version

**Comment by pvizeli** [comment]
Hmm, I have no issue with my ConbeII with 3.7

**Comment by iantrich** [comment]
Upgrade from 3.7 to 3.9 went smoothly

**Comment by frenck** [comment]
Well, let's close it up for now!

Please let me know if it happens again 👍

**Comment by Alvinger** [comment]
Ok, so this issue has resurfaced. I got the exact same error after a snapshot create/restore when moving to a larger SD card. If I use the old SD card everything works but when I try the new card (with a restored full snapshot of the old card) I get this error. Rebooting does not solve the issue, nor restore the snapshot.

I am on HA 106.2 with DeCONZ addon 5.2.

**Comment by jasonhyland** [comment]
After a reboot, I seem to be having the same issue - is this a problem with the network ?

`10:21:47:877 failed to reconnect to network try=5
10:21:47:877 wait reconnect 11 seconds
10:21:48:876 wait reconnect 10 seconds
10:21:49:876 wait reconnect 9 seconds
10:21:50:876 wait reconnect 8 seconds
10:21:51:876 wait reconnect 7 seconds
10:21:52:876 failed to reconnect to network try=6
10:21:52:876 wait reconnect 6 seconds
10:21:53:876 wait reconnect 5 seconds
10:21:54:876 wait reconnect 4 seconds
10:21:55:876 wait reconnect 3 seconds
10:21:56:876 wait reconnect 2 seconds
10:21:57:876 failed to reconnect to network try=7
10:21:57:876 wait reconnect 1 seconds
10:21:58:198 COM: --dev: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2154040-if00 (RaspBee)
10:21:58:234 device disconnected reason: 4, index: 0
10:21:58:876 wait reconnect 15 seconds
10:21:59:200 COM: --dev: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2154040-if00 (RaspBee)`

**Comment by markmghali** [comment]
Yes On the latest update I am now have this issue where it loses the network. extremely annoying.

deconz 5.3.4

Supervisor 225 
HassOS 4.8

Any help would be appreciated
