### ISSUE TITLE
[Feature Request] Enable Python for SSH addon

### ISSUE THREAD

**Issue by sunnythaper** [home-assistant/hassio-addons#835]
I am utilizing Ansible to control my infrastructure and one piece I can't control currently is Hass.io due to a missing Python dependency. I hope others will utilize the inclusion of Python for Ansible playbooks as well. My current and future playbooks will all be open to browse if Python is enabled!

**Comment by frenck** [comment]
The Core-SSH add-on is small a minimal add-on for accessing SSH.
Adding Python to it will at least double the size of the add-on.

The community version of the SSH, however, does provide these tools and is more aimed at doing these kinds of things.

**Comment by sunnythaper** [comment]
@frenck very much appreciate the answer! I wasn't even aware of the community version! I'll def check it out and thank you for explaining the focus differences between the two!

**Comment by frenck** [comment]
No problem!
