### ISSUE TITLE
Deconz 3.6 + node-red-contrib-deconz (Node-Red ) can not setup server

### ISSUE THREAD

**Issue by schumi2004** [home-assistant/hassio-addons#836]
I'm running HassIO (HassOS 2.12 / Supervisor 192) with a ConBee2 (version 2.05.69 / 6-9-2019
Firmware: 264A0700 ) stick connected.
Installed deCONZ add-on, setup devices and they are visible in Home Assistant.

Then i wanted to play with Node-Red (v5.0.1) and found the palette: node-red-contrib-deconz
Installed it and wanted to setup server and there it failed.

![settings](https://user-images.githubusercontent.com/968545/69126898-82e4b980-0aa9-11ea-931e-c6df5dd05087.png)

Followed this video to set things up https://www.youtube.com/watch?v=i3TiZiuNofM but when you try to retrieve API key it fails and no error or message is shown.

You will see a message in Node-Red log for a connection refused if you use a different websocket port then configured but that's all you will see, it will never connect as a third party app.

Any one got this successfully working?

I can telnet to configured (default) websocket port but for some reason this doesn't work in HassIO.

**Comment by frenck** [comment]
The add-on was designed to work with Home Assistant.
The only option we currently offer is to use the Home Assistant node in Node-RED and the deConz integration in Home Assistant.

Using that route, you will be able to access all your devices.
