### ISSUE TITLE
wrong path to VERSION in Homematic Addon

### ISSUE THREAD

**Issue by michas79** [home-assistant/hassio-addons#837]
This week I tried to install Homematic Addon. Everything went right except on little error. In HomeMatic WebUI (OCCU) it wasn’t possible to access Einstellungen > Systemsteuerung (Settings> system control)

I got this error in log file:
```
syntax error in expression "*1"
    while executing
"expr $product*1"
    (procedure "getProduct" line 6)
    invoked from within
"getProduct"
    (file "/opt/hm/www/config/control_panel.cgi" line 1) 
```

It happens because in common.tlc the first line in proc get_Version was commented out
#return [read_var /boot/VERSION VERSION]
and a new line was put under it
return [read_var /VERSION VERSION]

The mistake: there is no file in /VERSION

My fast fix: I just copy the file from /boot/VERSION to /VERSION

**Comment by DerChristophe** [comment]
Hi,
because I have exactly the same problem I wanted to try your fast fix. But how will I get access to /boot/Version? Just found a file named Dockerfile in supervisor\addons\core\homematic\ on the SD.
Did you use DEBUG SSH or how did you get there?

Thanks
Christophe

**Comment by michas79** [comment]
Hi,
it is not that hard to get access. 
Firstly I did it like this https://developers.home-assistant.io/docs/en/hassio_debugging.html#hassos-based-hassio. I always use ssh keys for server access. 
Second step is **ssh root@hassio.local -p 22222** via console. I always use cygwin terminal under Win10. I also generated my ssh-keys there.
After ssh login (on Hass.io CLI I use command **login** for access to host system.
With a **docker ps**  I found my container name, which was 'addon_core_homematic'

 Last thing  was to do **docker exec -it addon_core_homematic /bin/bash** and I was inside the container. You just need a **cp /boot/VERSION /VERSION** and done. 

Only problem, it is not static. After restart of docker container you have to do it again. But as I see, it is not really needed to have access to "Systemsteuerung" of HomeMatic CCU. 

Hope I could helped you. 
Best Regards
Micha

**Comment by pvizeli** [comment]
Can you make a PR to fix that?

**Comment by frenck** [comment]
This has been addressed in the latest release of the add-on.
