### ISSUE TITLE
Fyrtur Battery implementation

### ISSUE THREAD

**Issue by D3nnisd** [home-assistant/hassio-addons#838]
Since release [2.05.70](Ohgithub.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_70) battery status of the Fyrtur is included:
Add ZHABattery resource for IKEA FYRTUR and KADRILJ smart blinds #1827

Can this be added :)?

**Comment by frenck** [comment]
The current release is already @ 2.05.70

I think you are referring to the Home Assistant integration? If that is the case, feature requests for those should go into the community forum.

Thanks! 👍
