### ISSUE TITLE
can't install snips - missing manifest

### ISSUE THREAD

**Issue by killthewiseone** [home-assistant/hassio-addons#845]
HassOS 2.12 on Raspberry Pi 3 Model B.

> ERROR (SyncWorker_18) [hassio.docker.interface] Can't install homeassistant/armhf-addon-snips:6.1 -> 404 Client Error: Not Found ("manifest for homeassistant/armhf-addon-snips:6.1 not found").

**Comment by Ninuss** [comment]
https://github.com/home-assistant/hassio-addons/issues/804#issuecomment-546686869

Maybe there is not enough space left for install the upgrade... I have the same issue, but my microSD-card has 1.2 GiB free...

**Comment by killthewiseone** [comment]
Thank you for confirming it's not just me experiencing the issue.
I don't think the issue you referenced is the same, the error there is "no such image", and also I've >4GB space available. Have managed to restore the add-on from a backup and the update process also fails with the same manifest error.

**Comment by Ninuss** [comment]
I have done the same... you have right. I lost the logic for a while...  :)

**Comment by hakanuysal** [comment]
if i'm not mistaken, hassio is trying the pull the image from here https://hub.docker.com/r/homeassistant/armhf-addon-snips/tags and there's no 6.1 there yet.

**Comment by frenck** [comment]
Seems that the release build has failed, going to look into it.

**Comment by killthewiseone** [comment]
thanks @frenck

**Comment by frenck** [comment]
Fix pending in PR #846 (Snips add-on version 6.2)
