### ISSUE TITLE
Configurator can't open files

### ISSUE THREAD

**Issue by Shwamp** [home-assistant/hassio-addons#851]
Any help would be much appreciated.
Got a RPI 3 with Hass.io (Home Assistant 0.102.0, Configurator 3,6) and are trying to open files in the configurator, but I'm getting a stage error, in the window for showing the yaml code.
`"'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte".`

I think i got something to do with the file names every file got "._" in the beginning of the file name, but i don't know.

![Pic](https://user-images.githubusercontent.com/28205516/69447332-95cfe600-0d56-11ea-9c37-ce1b942747e0.png)

Here are the logs from the Hass.io add-on page:

Log
[18:37:31] INFO: Add-on running
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file './resty/core.lua'
	no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core/init.lua'
	no file '/usr/share/lua/5.1/resty/core.lua'
	no file '/usr/share/lua/5.1/resty/core/init.lua'
	no file '/usr/share/lua/common/resty/core.lua'
	no file '/usr/share/lua/common/resty/core/init.lua'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
	no file '/usr/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so')
2019/11/22 18:37:31 [notice] 24#24: using the "epoll" event method
2019/11/22 18:37:31 [notice] 24#24: nginx/1.16.1
2019/11/22 18:37:31 [notice] 24#24: OS: Linux 4.14.98-v7
2019/11/22 18:37:31 [notice] 24#24: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2019/11/22 18:37:31 [notice] 24#24: start worker processes
2019/11/22 18:37:31 [notice] 24#24: start worker process 31
INFO:2019-11-22 18:37:32,155:hass_configurator.configurator:Starting server
INFO:2019-11-22 18:37:32,157:hass_configurator.configurator:Listening on: http://127.0.0.1:80
INFO:2019-11-22 18:38:03,861:hass_configurator.configurator:127.0.0.1 - "GET / HTTP/1.1" 200 -
172.30.32.2 - - [22/Nov/2019:18:38:04 +0100] "GET / HTTP/1.1" 200 52056 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15"
INFO:2019-11-22 18:38:04,521:hass_configurator.configurator:127.0.0.1 - "GET /api/file?filename=/config/._configuration.yaml HTTP/1.1" 200 -
WARNING:2019-11-22 18:38:04,523:hass_configurator.configurator:'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
172.30.32.2 - - [22/Nov/2019:18:38:04 +0100] "GET /api/file?filename=/config/._configuration.yaml HTTP/1.1" 200 82 "http://192.168.xx.xxx:8123/api/hassio_ingress/6cTLZ2etaibEbwYxscQkbWZldbtP32XqhShY717Ghyk/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15"
INFO:2019-11-22 18:38:04,626:hass_configurator.configurator:127.0.0.1 - "GET /api/listdir?path=. HTTP/1.1" 200 -
172.30.32.2 - - [22/Nov/2019:18:38:04 +0100] "GET /api/listdir?path=. HTTP/1.1" 200 16250 "http://192.168.xx.xxx:8123/api/hassio_ingress/6cTLZ2etaibEbwYxscQkbWZldbtP32XqhShY717Ghyk/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15"

**Comment by frenck** [comment]
This is related to your file or Configurator itself.
Please report this upstream on the Configurator repository: <https://github.com/danielperna84/hass-configurator>

Thanks! 👍
