### ISSUE TITLE
Configurator : Bad Gateway : After addon install

### ISSUE THREAD

**Issue by Thijzer** [home-assistant/hassio-addons#856]
Fresh install (today) of hass.io on a raspi 3b 32bit.

Something with Ingress not able to connect.

Syslog
```
hassio.api.ingress] Ingress error: Cannot connect to host 0.0.0.0:8099 ssl:None [Connection refused]
```
I also don't see any port 8099 as part of the configuration file.

**Comment by Thijzer** [comment]
I figured it out, the container has not started before I manually tell it too.
This still might be a minor UI disconnect, maybe "service not running/started" would be a better Error.

**Comment by frenck** [comment]
I'm glad you got it resolved. Improving the UI for Hass.io is a general to do for us at this moment, nevertheless, thanks! 👍
