### ISSUE TITLE
Lets encrypt addon DNS fails for Digitalocean

### ISSUE THREAD

**Issue by haniffm** [home-assistant/hassio-addons#857]
I'm trying to get Lets Encrypt 4.2 with DNS challenge to work with my provider (DigitalOcean). I'm getting the following error message:

```
Attempting to renew cert (<my domain>) from /data/letsencrypt/renewal/<my domain>.conf produced an unexpected error: None of the preferred challenges are supported by the selected plugin. Skipping.
...
```

The configuration that I'm using is:
```
{
  "email": "<MY EMAIL>",
  "domains": [
    "<MY HOME ASSISTANT DOMAIN>"
  ],
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "challenge": "dns",
  "dns": {
    "provider": "dns-digitalocean",
    "digitalocean_token": "<MY DIGITAL OCEAN TOKEN WITH R/W ACCESS>"
  }
}
```

**Comment by lemonlatte** [comment]
I encounter the same problem as you describe. It's like you try to switch from `http` challenge to `dns`. It is not currently acceptable. To make it work, you need to remove the add-on and install it again. So that it will issue a brand new certificate with `dns` challenge.

**Comment by haniffm** [comment]
@lemonlatte your solution worked like a charm. I was switching from `http` to `dns` challenge.
