### ISSUE TITLE
DuckDNS Let's Encrypt Certificate expired

### ISSUE THREAD

**Issue by bwoodworth** [home-assistant/hassio-addons#858]
I have the DuckDNS add-on installed and configured like so:

> {
>   "lets_encrypt": {
>     "accept_terms": true,
>     "certfile": "fullchain.pem",
>     "keyfile": "privkey.pem"
>   },
>   "token": "************",
>   "domains": [
>     "******.duckdns.org"
>   ],
>   "seconds": 300
> }

When I try to access Home Assistant the browser is telling me the SSL cert is expired (Nov.24th), but the logs for the DuckDNS add-on say the certificate is good until Feb. 23:

> INFO: Using main config file /data/workdir/config
> Processing *****.duckdns.org
>  + Checking domain name(s) of existing cert... unchanged.
>  + Checking expire date of existing cert...
>  + Valid till Feb 23 18:24:46 2020 GMT Certificate will not expire
> (Longer than 30 days). Skipping renew!

The http: config is like this:

> http:
>   base_url: https://*****.duckdns.org:8123
>   ssl_certificate: /ssl/fullchain.pem
>   ssl_key: /ssl/privkey.pem

I can't figure out why the expiry date between the cert served up in the browser and the one in the logs of the DuckDNS add-on are different.  I can provide any other info if necessary.

**Comment by GoWithitRoger** [comment]
How are you getting logging at that level for DuckDNS? I'm running Hassio (which might be the difference) and only see, for example:
`[14:26:52] INFO: OK
12.234.567.89
NOCHANGE`

**Comment by bwoodworth** [comment]
The log is on the add-on page at the bottom

**Comment by GoWithitRoger** [comment]
My issue was the log wasn’t showing anything useful; it was just that basic info, when my certificate was expired. Through some combo of resetting my config and restarts, I was able to get DuckDNS doing what it should’ve been again.

**Comment by frenck** [comment]
The service consuming the certificate needs to be restarted after the certificate has been renewed, in order to pick it up.

Do you both have the issue resolved?

**Comment by bwoodworth** [comment]
The issue seems to have resolved itself.  Not sure why or what happened.

**Comment by frenck** [comment]
🤷‍♂ If it returns, please let us know. Right now, I'm just glad you got it resolved 👍

**Comment by mpigsley** [comment]
My certificate expired on April 6, 2020 but the log output says the certificate is valid through Jun 6, 2020. I'm not quite sure how that's possible.

Any thoughts?

**Comment by KBrownConsulting** [comment]
@mpigsley Take a look at the issue I just opened: #1280
