### ISSUE TITLE
Lets Encrypt DNS validation with AWS Route 53 does not work

### ISSUE THREAD

**Issue by thesoftwarejedi** [home-assistant/hassio-addons#862]
When using DNS validation, `run.sh` assumes $provider-credentials as a format to send in the credentials configuration for a provider to certbot.  However, the Route 53 provider does not work this way and in fact will get an error: `certbot: error: unrecognized arguments: --dns-route53-credentials /data/dnsapikey`.

If you look at [the certbot page for route53](https://certbot-dns-route53.readthedocs.io/en/stable/), it explains the standard AWS ways to get credentials to the provider.  I think the simplest solution would be to simply add:

`export AWS_CONFIG_FILE=/data/dnsapikey`

to the `run.sh` file inside the plugin.  That should do the trick and not affect other providers.

**Comment by pvizeli** [comment]
Fix with #864
