### ISSUE TITLE
Can't install deconz 3.9

### ISSUE THREAD

**Issue by Nossnevs** [home-assistant/hassio-addons#874]
I can't install deconz. I'm running Hassio in kvm with Ubuntu server 18.04 as both guest and host.
Syslog:
`Can't install homeassistant/amd64-addon-deconz:3.9 -> 404 Client Error: Not Found ("manifest for homeassistant/amd64-addon-deconz:3.9 not found: manifest unknown: manifest unknown"`

**Comment by brisketfingers** [comment]
I am seeing the same. I have verified traffic passes firewall. Hass.io running as VM on Unraid 6.7.2

> 19-12-06 03:03:22 INFO (SyncWorker_1) [hassio.docker.interface] Update image homeassistant/amd64-addon-deconz:3.8 to homeassistant/amd64-addon-deconz:3.9
19-12-06 03:03:22 INFO (SyncWorker_1) [hassio.docker.interface] Pull image homeassistant/amd64-addon-deconz tag 3.9.
19-12-06 03:03:22 ERROR (SyncWorker_1) [hassio.docker.interface] Can't install homeassistant/amd64-addon-deconz:3.9 -> 404 Client Error: Not Found ("manifest for homeassistant/amd64-addon-deconz:3.9 not found").

**Comment by ajdezigns** [comment]
Same error here on my intel nuc running HASS.io

`19-12-06 03:30:40 INFO (SyncWorker_17) [hassio.docker.interface] Update image homeassistant/amd64-addon-deconz:3.8 to homeassistant/amd64-addon-deconz:3.9
19-12-06 03:30:40 INFO (SyncWorker_17) [hassio.docker.interface] Pull image homeassistant/amd64-addon-deconz tag 3.9.
19-12-06 03:30:41 ERROR (SyncWorker_17) [hassio.docker.interface] Can't install homeassistant/amd64-addon-deconz:3.9 -> 404 Client Error: Not Found ("manifest for homeassistant/amd64-addon-deconz:3.9 not found"). `

**Comment by frenck** [comment]
We are looking into the issue. It seems the build has only partly succeeded causing the add-on update not to be available for all architectures.

**Comment by fastender** [comment]
Same problem on my VM Ubuntu 18.04.3 LTS on Unraid.

**Comment by frenck** [comment]
We have reverted the update for now. So 3.8 is now the latest until we have found the issues/fixed it from publishing while being broken.

**Comment by frenck** [comment]
Fixed, 3.9 is now available

![image](https://user-images.githubusercontent.com/195327/70311070-33c0b780-1811-11ea-88dd-05bee8d620e1.png)

**Comment by brisketfingers** [comment]
> Fixed, 3.9 is now available
> 
> ![image](https://user-images.githubusercontent.com/195327/70311070-33c0b780-1811-11ea-88dd-05bee8d620e1.png)

Works for me, thanks!

**Comment by fastender** [comment]
Works, many thanks.
