### ISSUE TITLE
deCONZ not starting after Proxmox update.

### ISSUE THREAD

**Issue by jdenver13** [home-assistant/hassio-addons#879]
After running a Proxmox update, deconz now refuses to start. Ive shutdown and restarted the nuc, the ConBee stick shows as /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1997638-if00 on the hardware page and my config is:
`{
  "device": "/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1997638-if00",
  "vnc_password": "password"
}`

The only error in the hassio logs is:
```
2019-12-10 16:19:07 ERROR (MainThread) [homeassistant.components.deconz] Error connecting to deCONZ gateway at 172.30.32.1
2019-12-10 16:19:07 WARNING (MainThread) [homeassistant.config_entries] Config entry for deconz not ready yet. Retrying in 80 seconds
```
The ports are:

Container | Host | Description
5900/tcp |   5900 | deCONZ graphical desktop via VNC
80/tcp |   40850 | deCONZ API backend
8080/tcp |   40860 | deCONZ WebSocket Server

In the system log is:
`19-12-10 16:19:33 ERROR (SyncWorker_11) [hassio.docker] Can't create container from addon_core_deconz: 404 Client Error: Not Found ("No such image: homeassistant/amd64-addon-deconz:3.9")`

Im running deconz 3.9 and hassio 0.102.3

**Comment by frenck** [comment]
Could you elaborate on how you have installed Hass.io on Promax? As an LXC container? Or as a VM? If a VM, are you running HassOS or another system?

**Comment by jdenver13** [comment]
Its ran as a VM with hassOS using whiskerz one line install. And proxmox is version 6.1-3.

I have installed portainer addon after seeing the error regarding hassio unable to create the deconz container and its shown there is no decenz container, so im currently uninstalling the deconz add-on and reinstalling a fresh one.

Thanks for coming back, Ill let you know how things turn out.

**Comment by pvizeli** [comment]
I think the diskspace of you VM is to small

**Comment by pvizeli** [comment]
There was an issue with expander. I think the issue is fix with 3.7 and if you give more disk space

**Comment by jdenver13** [comment]
I reinstalled DeConz in the end and then realised I didn't have a back up so had to reinstall lights, sensors and switches again. All working well and now have a backup of Deconz. Still not sure why it was the only add-on that mis functioned all of a sudden.

**Comment by frenck** [comment]
Well, whatever it was, good to hear you've got it running again! 👍
