### ISSUE TITLE
letsencrypt poor/bad documentation for config

### ISSUE THREAD

**Issue by prabbit237** [home-assistant/hassio-addons#881]
In the page for letsencrypt, it shows:

**### Configuration**
Add-on configuration:
````
{
  "email": "hello@home-assistant.io",
  "domains": [
    "home-assistant.io"
  ],
  "challenge": "dns",
  "dns": {
    "provider": "dns-cloudflare",
    "cloudflare_email": "cf@home-assistant.io",
    "cloudflare_api_key": "31242lk3j4ljlfdwsjf0"
  }
}
````

The default configuration settings are:

````
{
  "email": null,
  "domains": [
    null
  ],
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "challenge": "http",
  "dns": {}
}
````

On either of these, if you click **save** it gives an error reading something along the lines of:

**not a valid value for dictionary value @ data['options']. Got {'email': None, 'domains': [None], 'certfile': 'fullchain.pem', 'keyfile': 'privkey.pem', 'challenge': 'http', 'dns': {}}**

This error message is very **nonusefull** in that doesn't tell you what part of it is causing the problem. Now the error message may be generated by some library provided by someone else, thus making it very difficult to change but if the examples/defaults are changed to be syntactically valid, it would at least make it easier to figure out what's wrong when the user changes those defaults to the user's information.

The example configuration needs the two lines giving the cert and key filenames (and it took me quite some time to realize that.)

````
{
  "email": "hello@home-assistant.io",
  "domains": [
    "home-assistant.io"
  ],
  "challenge": "dns",
  "dns": {
    "provider": "dns-cloudflare",
    "cloudflare_email": "cf@home-assistant.io",
    "cloudflare_api_key": "31242lk3j4ljlfdwsjf0"
  },
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}
````

The default settings should show an example of settings that **will* save error-free (but in such a way that it's obvious what needs to be changed in the default and what can be left as-is.)
````
{
  "email": "changeme@yourdomain.tld",
  "domains": [
    "www.yourdomain.tld","yourdomain.tld","subdomain.yourdomain.tld","etc.yourdomain.tld"
  ],
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "challenge": "http",
  "dns": {}
}

````

**Comment by cwiggs** [comment]
Just wanted to mention I was having the same issue and your post helped me get the plugin working, thanks!

**Comment by Zapfmeister** [comment]
If im not mistaken, the issue you had is related to not filling email and domain, not the cert and keyfile.
This was actually done on purpose, as the proper domain and email need to be filled, as described in the documentation.
Let me know if that solves the issue.

**Comment by prabbit237** [comment]
I can understand not wanting the default settings to be save-able but the issue I had was that it wasn't clear **WHY** there was an issue. 

I do a clean install and I'm greeted with:

```
{
  "email": null,
  "domains": [
    null
  ],
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "challenge": "http",
  "dns": {}
}
```

So I just do a quick test by clicking on "save" and...... oops, here's an error message. It doesn't tell me very clearly what the problem is but it's telling me that **something** is wrong. Well OK, the email address and domains show "null", which is apparently not valid and that's clear and easy to spot. I put those in and I also try adding the CloudFlare info and then click on "save", waiting for the magic to happen and.....another error? Hmmmmmm.....

Ok, so I RTFM more and scroll up and see the example:

```
{
  "email": "hello@home-assistant.io",
  "domains": [
    "home-assistant.io"
  ],
  "challenge": "dns",
  "dns": {
    "provider": "dns-cloudflare",
    "cloudflare_email": "cf@home-assistant.io",
    "cloudflare_api_key": "31242lk3j4ljlfdwsjf0"
  }
}
```

Well, maybe I have a typo somewhere. Let me copy and paste that example into the box and click on "save", knowing that it won't work as desired if I start the docker container, but this time it should at least **save** with no err...or...........s......................... WTH????????????? Why is **that** one not working? It's at least **syntactically** correct as far as a JSON file goes, showing indention, etc.

As noted, it worked OK once I figured out that I needed elements of **BOTH** the example configuration that shows HomeAssistant's info **AND** of the default configuration and that neither was syntactically complete as it was even after making the obvious changes of the email address and the domain name(s.) If the sample configuration at https://github.com/home-assistant/hassio-addons/tree/master/letsencrypt#configuration just had the cert/key file lines added to it, then it would be easy to take that sample, copy and paste it into the settings box, make the obvious needed changes and **then** watch the magic happen. But as it is, if I look at the example with HomeAssistant's info, it looks like the cert file lines are optional when they aren't.

![lets](https://user-images.githubusercontent.com/36862951/72079614-41aea000-32c9-11ea-80fe-9e754dc282c1.PNG)

**Comment by Zapfmeister** [comment]
Ok, i understood what you meant. I just wanted to make sure that the email and domains part wasnt lost.
I updated the documentation and will merge it asap.
