### ISSUE TITLE
Mosquitto MQTT with zigbee2mqtt connection problem

### ISSUE THREAD

**Issue by fremut** [home-assistant/hassio-addons#887]
I am using combination of mosquitto-mqtt offical add-on with zigbee2mqtt addon. Everything works fine till stops wifi connection or LAN network (home router turn off). It is possile to set up broker IP independent on LAN ? I tried to use internal docker (mosquitto containers) IP 172.30.33.0 but with same effect. After turning home wifi off. Zigbee devices doesnt function. Thanks for your help.

**Comment by pvizeli** [comment]
I don't know about the zigbee2mqtt add-on but if they use the internal service bus, they should work also if the network changed outside.
