### ISSUE TITLE
deConz + rpi4 + raspbee = firmware update fails

### ISSUE THREAD

**Issue by panhans** [home-assistant/hassio-addons#890]
Hi there,

I just want to update the firmware of my raspbee but I get following output. I followed every step like discribed. 

Hardware: 
- Raspberry Pi 4b (hassio 32Bit)
- RaspBee (current firmware version: 26050500)

I saw the update script here is version 0.4 and there is 0.5 allready out. Next thing I've read is that WiringPi 2.52 is needed for flashing the firmware correctly. But its all given in marthocs repository. Dont know if you merge from there.

Here is the whole log:

```
# docker run -it --rm --device=/dev/ttyAMA0 --privileged --cap-add=ALL -v /lib/m
odules:/lib/modules --entrypoint "/firmware-update.sh" marthoc/hassio-addon-deco
nz-armhf
-------------------------------------------------------------------
 
       marthoc/deconz Conbee/RaspBee Firmware Flashing Script
 
                       Version: 0.4
 
-------------------------------------------------------------------
 
Enter C for Conbee, R for RaspBee, or press Enter now to exit: R
 
-------------------------------------------------------------------
 
Firmware available for flashing:
 
deCONZ_ConBeeII_0x26480700.bin.GCF
deCONZ_ConBeeII_0x26490700.bin.GCF
deCONZ_Rpi_0x261f0500.bin.GCF
deCONZ_Rpi_0x26320500.bin.GCF
deCONZ_Rpi_0x26330500.bin.GCF
 
Enter the firmware file name from above, including extension,
or press Enter now to exit.
 
File Name : deCONZ_Rpi_0x26330500.bin.GCF
 
-------------------------------------------------------------------
 
Device: RaspBee
 
Firmware File: deCONZ_Rpi_0x26330500.bin.GCF
 
Are the above device and firmware values correct?
Enter Y to proceed, any other entry to exit: Y
 
Flashing...
 
GCFFlasher V3_05 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device RaspBee (RaspBee)
deCONZ firmware version 26050500
action: reset device RaspBee
action: update firmware after 2 ms
could not sync with bootloader
 
Flashing Error! Please re-run this script... 
```

**Comment by pvizeli** [comment]
`marthoc/hassio-addon-deconz-armhf`. That is not our add-on. Our add-on support firmware update over the deconz UI without any scripts or command line stuff.

**Comment by panhans** [comment]
> `marthoc/hassio-addon-deconz-armhf`. That is not our add-on. Our add-on support firmware update over the deconz UI without any scripts or command line stuff.

Ok. I installed the official deconz addon using the add-on store. I have no other repos in my setup except the comunity repo. But when trying to upgrade the firmware over ui it says its been updated but after a minute it shows me the old firmware version and tells me there is a new one.

**Comment by pvizeli** [comment]
hmm, that is proper a very old issue. The UI should work, not sure if it is an RPi4 issue. I'm very happy that the new fast Conbee2 is USB
