### ISSUE TITLE
Configurator: "Access Denied" for other folders then "config" (Since v4.0)

### ISSUE THREAD

**Issue by Venice-89** [home-assistant/hassio-addons#903]
Hi,

since updating the Plugin to v4.0 I can't acces other directorys then config.
I get the following error message:

WARNING:2019-12-18 19:08:03,491:hass_configurator.configurator:Access denied.

enforce_basepath is false (default config is used)
"enforce_basepath": false,

**Comment by joshwapohlmann** [comment]
related #904

**Comment by frenck** [comment]
Picked up #904, let's continue the conversation there.
