### ISSUE TITLE
Addon - Configurator - Access denied

### ISSUE THREAD

**Issue by joshwapohlmann** [home-assistant/hassio-addons#904]
I updated the configurator addon to version 4.0 and suddenly I cannot edit files outside of /config.
I found that in commit e0ebcbca6 the option to choose wether the base path is enforced or not has been removed.

This feature should stay, because there are use cases where files have to be edited outside of /config.
Further, the current release (4.0) already has this change applied while the documentation hasn't been updated.

**Comment by joshwapohlmann** [comment]
duplicate of #903

**Comment by joshwapohlmann** [comment]
@frenck don't get why all options where deleted. they were useful.

**Comment by Venice-89** [comment]
It's not only useful, it's absolutely needed for configuring other addons which store there config in other folders.... For example: WireGuard AddOn, Zigbee2Mqtt

I can't access their configs now :/

**Comment by joshwapohlmann** [comment]
@Venice-89 same, I lost my devices.yaml of zigbee2mqtt due to this error (it said access denied but saved the "Access Denied" message without a problem >_>)

**Comment by djmalin** [comment]
i have this same problem

INFO:2019-12-18 20:16:40,791:hass_configurator.configurator:172.30.x.x - "GET /api/listdir?path=/ HTTP/1.1" 200 -
WARNING:2019-12-18 20:16:40,792:hass_configurator.configurator:Access denied.
INFO:2019-12-18 20:16:41,105:hass_configurator.configurator:172.30.x.x - "GET /api/listdir?path=/ HTTP/1.1" 200 -
WARNING:2019-12-18 20:16:41,106:hass_configurator.configurator:Access denied.

**Comment by frenck** [comment]
It has not been removed, don't jump into conclusions so fast.

https://github.com/home-assistant/hassio-addons/blob/master/configurator/data/run.sh#L35

There it is, and it contains a typo in the variable name. I will put out a fix asap.

**Comment by frenck** [comment]
I've pushed out version 4.1 to address this issue.
Please note, 4.1. has the default setting to enforce the basepath. You might need to disable that in the add-on options if you need or want to go beyond the `/config`.

If the update doesn't show up on your system yet, go to the add-on store and hit the refresh icon in the top right. After that, reload your browser page and it should show up as a regular update.

**Comment by joshwapohlmann** [comment]
> It has not been removed, don't jump into conclusions so fast.
> 
> https://github.com/home-assistant/hassio-addons/blob/master/configurator/data/run.sh#L35
> 
> There it is, and it contains a typo in the variable name. I will put out a fix asap.

Sorry, i tried to grasp as quickly as possible what happened so the issue can resolved quickly. Obviously I didn't get the whole picture, so thanks for reacting quickly. 
Thank you for your work! ❤️
