### ISSUE TITLE
Support for last will & testament (LWT) messages 

### ISSUE THREAD

**Issue by thanksmister** [home-assistant/hassio-addons#919]
I couldn't see in the mqtt config that there is a LWT message setup for this addon, is there something to subscribe to that gives the LWT message?  

https://mosquitto.org/api/files/mosquitto-h.html#mosquitto_will_set

Thanks!

**Comment by frenck** [comment]
Hi there @thanksmister!

The broker (that is in the add-on) supports it, it is up to the MQTT client to use it, which is out of scope for the add-on.

The documentation you've linked is about the client API, which will just work with the add-on without any additional configuration.

**Comment by thanksmister** [comment]
So what is the call MQTT topic to subscribe to or set in this the add-on?

**Comment by frenck** [comment]
@thanksmister I don't think I fully understand. The client is allowed to set whatever it likes... That is not a limitation or rule the add-on enforces. The add-on provides a plain simple and open MQTT broker. What goes in and out of it, is not a concern for the add-on, but the clients. They provide data, topics, LWT, QoS, etc.

**Comment by SiliconAvatar** [comment]
If you are using the MQTT broker addon, it gets added to HA via config flow, yet the config flow does not allow setting a LWT message for HA (being a client). 

I think that's what he's asking to be added, in which case it's a feature request for the HA codebase, not the addon.

**Comment by thanksmister** [comment]
@SiliconAvatar yes this is exactly what I was asking because if you manually setup the MQTT broker in HA you have an option to setup birth and LWT for the broker.  See that documentation here https://www.home-assistant.io/docs/mqtt/birth_will/.

**Comment by pvizeli** [comment]
Or someone update the config flow to support it over the config flow

**Comment by bjladner** [comment]
@thanksmister - Was this ever added.  I can't find out how to add the birth message either?  How did you solve the problem?

**Comment by thanksmister** [comment]
> @thanksmister - Was this ever added. I can't find out how to add the birth message either? How did you solve the problem?

No, it was not.  It was considered out of scope I believe.
