### ISSUE TITLE
Samba addon ignores username, tries to connect as guest

### ISSUE THREAD

**Issue by unikitty37** [home-assistant/hassio-addons#924]
Since upgrading to hassOS 3.0 and HA 103.2, I have been unable to connect over Samba. Despite connecting with the username `abcdef` and having this config:

```
{
  "workgroup": "WORKGROUP",
  "username": "abcdef",
  "password": "REDACTED",
  "interface": "",
  "allow_hosts": [
    "192.168.69.1"
  ],
  "veto_files": [
    "._*",
    ".DS_Store",
    "Thumbs.db",
    "icon?",
    ".Trashes"
  ],
  "guest": false
}
```

I just get this in the log every time I try to connect:

```
check_ntlm_password:  Authentication for user [guest] -> [guest] FAILED with error NT_STATUS_NO_SUCH_USER, authoritative=1
Auth: [SMB2,(null)] user []\[guest] at [Thu, 19 Dec 2019 21:09:04.516919 GMT] with [NTLMv2] status [NT_STATUS_NO_SUCH_USER] workstation [] remote host [ipv4:192.168.69.1:65232] mapped to []\[guest]. local host [ipv4:192.168.69.14:445] 
{"timestamp": "2019-12-19T21:09:04.517177+0000", "type": "Authentication", "Authentication": {"version": {"major": 1, "minor": 1}, "eventId": 4625, "logonType": 3, "status": "NT_STATUS_NO_SUCH_USER", "localAddress": "ipv4:192.168.69.14:445", "remoteAddress": "ipv4:192.168.69.1:65232", "serviceDescription": "SMB2", "authDescription": null, "clientDomain": "", "clientAccount": "guest", "workstation": "", "becameAccount": null, "becameDomain": null, "becameSid": null, "mappedAccount": "guest", "mappedDomain": "", "netlogonComputer": null, "netlogonTrustAccount": null, "netlogonNegotiateFlags": "0x00000000", "netlogonSecureChannelType": 0, "netlogonTrustAccountSid": null, "passwordType": "NTLMv2", "duration": 3305}}
```

I hadn't changed the client config in between this working and not working — the failures started after the hassOS upgrade. That might have bumped the add-on up to version 9.0, which is what is installed — but I have auto update turned on, and that version seems to have been out for at least a week beforehand. I don't know if it actually was running 9.0 when it was working, though :(

**Comment by frenck** [comment]
This is not an add-on issue. You client is trying to authenticate with the `guest` user first, since that option is disabled in the add-on configuration, it is expected to fail.

**Comment by unikitty37** [comment]
Right, that's what I thought — but the client config wasn't changed from before the hassOS upgrade, so why has this gone from connecting to not connecting?

**Comment by frenck** [comment]
The Samba add-on is a separate Docker container and is not influenced in any way by the Samba add-on (add-on are in isolated spaces). The upgrade of HassOS cannot influence the functionality of an add-on. Maybe something changed on your network or computer?
