### ISSUE TITLE
DeCONZ update to 4.1 causes invalid login attempts

### ISSUE THREAD

**Issue by Cloudenius** [home-assistant/hassio-addons#929]
Thanks for making ingress work on DeCONZ! (All the add-ons that I use are on ingress now! (Y))

After enabling ingress, DeCONZ seems to create invalid login attempts as I'm constantly locked out. Even when I just go to the DeCONZ add-on from the sidebar without doing anything, the Home Assistant log starts to fill up with the several of the following warning messages:

``
2019-12-20 12:52:36 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from <external IP address>
``

After disabling IP ban, I'm able to login with my password while still seeing above messages in the Home Assistant logs.

**Comment by hellcry37** [comment]
Thanks for the update guys, I am so grateful my bluetooth integration is not working again after this update and i also have invalid login attempts.
Now I can't open deconz interface with http://ip:port anymore.

You did good job. Thank you!

p.s. every time I do an update is a new chalange

**Comment by frenck** [comment]
@hellcry37 That is somewhat unrelated to this issue report. I hear all kinds of frustration in your tone, which is far from friendly. If you like to be supported and want help, I highly suggest adjusting that, instead of just go wild unrelated in an issue. I'll hide your comment because of that. Feel free to join on Discord, where we can talk about this.

**Comment by frenck** [comment]
@Cloudenius Thank you for making an issue on this. We are aware of this issue and are looking for a solution. This will probably involve teaming up upstream with Dresden, since their frontend seems to do pretty random request for discovery.

Will keep you posted in this issue.

**Comment by VivantSenior** [comment]
I had the same issue but thought I just mistype the password. After a few attempts (and maybe deCONZ addon / HA reset) the same password worked.

**Comment by bratanon** [comment]
I just wanna share some of my findings:

The phoscon app is doing request every 1500ms to a list of urls for discovery.
Usually one of them is correct and respond with OK 200, and some data for my conbee. 

The others are:
- _https://xxxxx.duckdns.org/api/config?_=1576972098437_
  responds with 401 (This is why the we are getting IP banned I guess)

- _https://172.30.33.6:40850/api/config?_=1576972176605_
  gets failed as of a timeout.

**Comment by frenck** [comment]
@bratanon, thanks, we are aware.

**Comment by frenck** [comment]
ℹ️ Little status update, I'm currently testing a version of the add-on that has a workaround for this issue.

**Comment by Cloudenius** [comment]
That's great Franck - thanks! Let me know if you need an early tester!

**Comment by LucasHokerberg** [comment]
In the meantime, you can disable the IP ban or preferably raise the login attempts threshold under the http configuration:
`login_attempts_threshold: 50`
The above workaround worked for me.
