### ISSUE TITLE
Usage of Ingress in deCONZ causes HA to ban my IP

### ISSUE THREAD

**Issue by VivantSenior** [home-assistant/hassio-addons#930]
Hi,

my config is:
Conbee 2,
RPi 3B+,
Hass.io 0.103.2,
deCONZ add-on 4.1.

I tried to use deCONZ UI via Ingress but after that HA bans my IP. I think it's unexpected behavior.

**Comment by ricmik** [comment]
This is already reported in https://github.com/home-assistant/hassio-addons/issues/929

**Comment by VivantSenior** [comment]
I wouldn't say it's the same issue. I understood #929 is regarding access to Phoscon app (invalid password). I can access my Phoscon app (password is correct) but after I close the app I can see notification from HA about banned IP (my IP).

**Comment by ricmik** [comment]
Oh, I see. I have issues both with logging into phoscon and getting banned when trying to access the add on. I just assumed that you also had login issues into phoscon.

**Comment by frenck** [comment]
@VivantSenior It is a duplicate/result of #929
