### ISSUE TITLE
PHOSCAN 4.1 Web socket removed

### ISSUE THREAD

**Issue by branitelj91** [home-assistant/hassio-addons#931]
phoscan 4.1
Ok. 

I understand the websocket has been removed. 
Being relatively new into this I have setup (outer world) integration in this which now stopped working, and I'd like it back, but without the integration I got lost. 
Any advices ?

**Comment by thecode** [comment]
I would also like it back, Apparently it is not possible. You can read about it here:
https://github.com/home-assistant/hassio-addons/issues/926
https://github.com/home-assistant/hassio-addons/issues/928

**Comment by frenck** [comment]
Duplicates of the above. Please make sure you check for existing issues before creating a new one. Thanks! 👍
