### ISSUE TITLE
Configurator: option 'dirsfirst' is not working

### ISSUE THREAD

**Issue by Gooman-rus** [home-assistant/hassio-addons#932]
Hello.
I have used option `dirsfirst: true` because it's comfortable for me. But now it does not work (dirs and files are randomly placed). 
Version of configurator: 4.1 
Version of hassio: Home Assistant 0.103.2

**Comment by frenck** [comment]
Started the processes to put out Configurator 4.2. This version will address the issue. Sorry about that!
