### ISSUE TITLE
deCONZ 4.1 and new gateway

### ISSUE THREAD

**Issue by VivantSenior** [home-assistant/hassio-addons#934]
Hi,

after upgrading to 4.0 / 4.1 I can see in the Phoscon App welcome page (through Ingress) additional gateway (bramka == gateway, gateway IP intentionally changed):
![image](https://user-images.githubusercontent.com/49829548/71305252-3efb1200-23d1-11ea-8673-5bf5e8f8a5fd.png)

Is it an intended addition?

**Comment by frenck** [comment]
Not intended, but not harmful as well.
deCONZ finds another route to itself, discovering itself, which is... smart and not so smart at the same time 😂 

Since this is not causing issues (besides showing itself), I'll go ahead and close this issue up.

**Comment by VivantSenior** [comment]
Thanks for the quick answer. I think the additional gateway appeared after the last addon updates (4.0 and 4.1). I can't find this gateway on my local network (based on provided IP). There is no device with this IP assigned.

**Comment by frenck** [comment]
Both conclusions are correct. It runs differently on the internal network now, so that explains the additional gateway at this moment.

Yes, you won't find it on your local network, since it is bind to the internal hassio network.
