### ISSUE TITLE
Deconz 4.1 3rd party Hue app problem

### ISSUE THREAD

**Issue by Fastfinguh** [home-assistant/hassio-addons#937]
Hello!

Due to the Deconz update the API is no longer exposed and I'm unable to add the Conbee 2 stick as a hue bridge in any of the apps. On version 3.9 I had no problem adding the stick to Hue Essentials. Is there a workaround how to pair this with any of the hue apps? Or am I doing something wrong? I'm using hassio on a ubuntu server inside docker. Any assistance would be greatly appreciated.

**Comment by frenck** [comment]
Those are multiple issues in a single issue, which is not recommended in general if you raise issues.

The API is no longer exposed. This is correct and is documented. This is not a bug. See the add-on documentation for more information (e.g., the Known issues and Limitation section).

More information can also be found in #928

**Comment by capstan1** [comment]
Hi frenck. I there any way to get a option to get the old behavior back if one doesn't need ingress?
I always used Hue Essentials and suddenly can't. Im using shortcuts and am configuring buttons with Hue Essentials. And as seen here I'm not the only one.
