### ISSUE TITLE
After system restart deConz can't find the stick

### ISSUE THREAD

**Issue by adonno** [home-assistant/hassio-addons#938]
Every time I update HA I have this annoying issue where deConz can't find my stick even though it's recognized by Home-Assistant in the "hardware" section 

If I wait some time... maybe half a day maybe 24 hours and try starting the add on again, it will work. (without changing the config) 

![image](https://user-images.githubusercontent.com/13216947/71315246-6b0da600-2458-11ea-993b-f45df7b0be9f.png)

![image](https://user-images.githubusercontent.com/13216947/71315250-7eb90c80-2458-11ea-97df-1030abd636ee.png)

![image](https://user-images.githubusercontent.com/13216947/71315229-1c600c00-2458-11ea-9dda-e3bd5002f423.png)

I have no idea where to check one thing though I have my stick on a 5m USB Cable. But I don't get why it's recognized by Hass.io and not by the add on.

**Comment by SiliconAvatar** [comment]
Might this be related to Issue #781 , which is an issue with `/dev/serial/by-id` not working correctly/consistently?

If you set the device using ` /dev/ttyACM0` (replace with the correct ID for the USB stick) does that work correctly and consistently?

**Comment by frenck** [comment]
Any luck with the `/dev/tty*` version @adonno ?

**Comment by jamesking420** [comment]
Is it supported to give the parameter as /dev/serial/by-id as per OP in this example?  This seems a much better option - but not if it's not supported of course! :)

**Comment by frenck** [comment]
@jamesking420 Yes, that is supported.

I've talked with @adonno over Discord. The `/dev/ttyACM0` currently works on his system. I'll help him with solving the #718 case for his system (Ubuntu-based).

Closing this issue for now.
