### ISSUE TITLE
Can not access Web-Interface over Ingress since 4.1

### ISSUE THREAD

**Issue by thaefner** [home-assistant/hassio-addons#939]
Over Ingress I can not access the Phoscon Web-Interface, so I am unable to access the Webinterface at all. But my Devices work in HA, so the API seems to be accessable and I can access the VNC-Interface. The Gateway also shows up with the IP 172.30.33.0 which is defnitly wrong. I am using HassOS.

**Comment by frenck** [comment]
Please see #928 For all information around this. Furthermore, the add-on documentation has been updated to cover most cases.

About the gateway showing up, this has been raised before in #934 

It would be really helpful if you'd checked out previously raised issues before raising a new one. Thanks. 👍
