### ISSUE TITLE
After 4.1 / 103.3 , Phoscon cant be accessed on port 40850 anymore.

### ISSUE THREAD

**Issue by D3nnisd** [home-assistant/hassio-addons#941]
Hi,

After 4.1 / 103.3, i am not able to connect to phoscon on 40850 anymore.  After some waiting, i can open the webui and sign-in on my IP. But, most of the time it shows a gateway i am not familiar with: 
![image](https://user-images.githubusercontent.com/43333120/71324937-8bd00d00-24e5-11ea-8786-7e79ca2b0dee.png)

Any idea how i can fix this?

thanks!

**Comment by PalmMx** [comment]
I have the same issue. Way back I renamed my gateway to "ConBee" and set my own password. Now when I try to open the WebUI the gateway is named "Phoscon-GW" (the standard name) and then I need to use the standard password 'delight'. When logged in like that, I can't reach the Gateway page in Phoscon. But if I then click 'Log out' the gateway change its name to "ConBee" and I can log in with my own password and also access the Gatewat page. Strange?

I assume this is related to issue #928 . 

Also running 4.1 and 0.103.3.

**Comment by D3nnisd** [comment]
@PalmMx  I have no missing entities. All is working as intended. Only my Fyrtur seem to be having issues sometimes.

**Comment by frenck** [comment]
@D3nnisd Currently I'm testing a version that addresses this.

**Comment by LucasHokerberg** [comment]
I'm also no longer able to access the web UI with port 40850. My Hue Essentials app is also no longer able to communicate with deCONZ. It works as expected if I select "Open Web UI" within Home Assistant.

After upgrading to the latest release, I thought about trying VNC out, but my VNC Viewer is unable to connect. Not sure if this is related, but it seems like deCONZ can't communicate outside of the container.

**Comment by frenck** [comment]
@LucasHokerberg Not related to this issue, please see #928

**Comment by D3nnisd** [comment]
@frenck Thanks for your response! the original issue or the issue with the Fyrtur?

**Comment by LucasHokerberg** [comment]
@frenck Thanks! By adding a port number in the Host filed under the Network section of the deCONZ configuration page, I'm now able to access VNC.

**Comment by filoor** [comment]
Do you have any ide when i will be able to access deconz from port 40850?

**Comment by filoor** [comment]
I have just updated to 5 but still no access with port 40850 and also my hassio (difrent machine) won't see deconz
