### ISSUE TITLE
Invalid key for deCONZ after HA restart

### ISSUE THREAD

**Issue by KKlitgaard** [home-assistant/hassio-addons#942]
Until the latest update (4.1) this addon has been working perfectly. 

With the update to 4.1 I experienced the described issue with no access to the Gateway (I guess this was related to the ingress-support). I did remove the integration, restarted Home Assistant and added the integration. 
The autodiscovered integration was added but without prompting me to enable the authentication from the addon webinterface. The integration seemed successful without any errors, but with no discovered devices.

Adding the integration by manually selection deConz from HA integrations flow list was normal including the expected authentication prompting and all my devices were discovered. However: Each time I restart Home Assistant I get the following error in the HA-log: 
"Invalid key for deCONZ at core-deconz.local.hass.io".

The only solution for this seems to be removing the integration and add it again.

**Comment by tyk0s** [comment]
Same experience here, upgraded from 3.9 to 4.1

**Comment by frenck** [comment]
Thanks, @KKlitgaard Your detailed explanation actually gave me a hint! 👍 
Diving back in.

**Comment by tyk0s** [comment]
@frenck I just updated to 103.4 and issue is still there, logg shows me "Invalid key for deCONZ at core-deconz". I have to remove the integration and add it again for it to work until next restart of HA.

**Comment by KKlitgaard** [comment]
> @frenck I just updated to 103.4 and issue is still there, logg shows me "Invalid key for deCONZ at core-deconz". I have to remove the integration and add it again for it to work until next restart of HA.

I can confirm this. I updated to 103.4 and the integration stayed functional, but after a restart O again get the same error in the log.

**Comment by frenck** [comment]
Home Assistant 0.103.4 is part of the fix. The add-on needs updates too, which is expected soon.
