### ISSUE TITLE
deconz 4.1/ 103.4 can't open gateway settings from hassio ingress

### ISSUE THREAD

**Issue by Viktor45** [home-assistant/hassio-addons#943]
can't access deconz gateway settings via ingress anymore - got blank screen
Menu - Settings - Gateway

deconz 4.1
hassio  0.103.4

<img width="773" alt="Снимок экрана 2019-12-23 в 14 39 53" src="https://user-images.githubusercontent.com/12881238/71356068-24bc6200-2592-11ea-82ed-76d4279d8cba.png">

<img width="1018" alt="Снимок экрана 2019-12-23 в 14 37 05" src="https://user-images.githubusercontent.com/12881238/71356014-f3439680-2591-11ea-93aa-5d38e6270568.png">

**Comment by frenck** [comment]
This seems to be related to a caching issue. Please try flushing your browser cache, try a different browser, or use a browser in incognito mode.

**Comment by Viktor45** [comment]
cache reset/incognito won't helps 
safari 13.0.4 (15608.4.9.1.3)
macOS 10.15.2 (19C57)

**Comment by frenck** [comment]
Anything helpful in the browser logs? Console, networking tab?

**Comment by Viktor45** [comment]
browser console error logs
<img width="2559" alt="Снимок экрана 2019-12-23 в 15 33 48" src="https://user-images.githubusercontent.com/12881238/71358452-078b9180-259a-11ea-8546-e23ba8751d3a.png">

**Comment by D3nnisd** [comment]
I notice you use 2 different urls on connecting to the window. 

Might be related to #941 

Ingress worked for me when i connected to the local ip (from within the network as HAS) and wait a bit, then it would show up.

**Comment by Viktor45** [comment]
yay. fixed with 5.0

**Comment by chadderksen** [comment]
deConz Gateway Page is not loaded on Safari Version 13.0.5 (15608.5.11), Chrome is working OK on MacOS 10.15.3 (19D76)

**Comment by dreynolds** [comment]
Same as @chadderksen for some reason this works in Chrome and not Safari
