### ISSUE TITLE
FEATURE request: Support GoDaddy in the Letsencrypt add-on

### ISSUE THREAD

**Issue by netweaver1970** [home-assistant/hassio-addons#946]
Hi,
GoDaddy also has an (by the looks of it) usable API to be used by the LetsEncrypt addon.
Here is a nice write-up on how to integrate/script it in a CertBot way so I think it can work also (if supported/coded accordingly) in the hassio addon.
[http://pbxhacks.com/automating-lets-encrypt-ssl-certs-via-godaddy-dns-challenge/](http://pbxhacks.com/automating-lets-encrypt-ssl-certs-via-godaddy-dns-challenge/)

Thanks for having a look at for inclusion in future versions.

Cheers,
Geert

**Comment by cnschulz** [comment]
Please re-open. This is one of the largest dns providers.

**Comment by mrmichaelrb** [comment]
I created a GoDaddy DNS add-on which registers my public IP with my GoDaddy DNS hosting and also creates an SSL certificate with Let’s Encrypt:

[New Home Assistant Add-on: GoDaddy DNS](https://community.home-assistant.io/t/new-home-assistant-add-on-godaddy-dns/329052)
