### ISSUE TITLE
Core Add-on Configurator - git repository path fail

### ISSUE THREAD

**Issue by pejotigrek** [home-assistant/hassio-addons#949]
Configurator: **4.2**
System: **HassOS 3.7**
HomeAssistant: **0.102.3** _[update pending - I need to make some changes to yaml, but this is not relevant to the issue]_
Hass.io supervisor: **193**
Hardware: **RaspberryPi3**

I have my hassio's samba share mapped to a windows drive letter. so whenever I want to access the `/config/` directory, I just go to the "disk" `A:/`
I use GitHub Desktop & my git repository is pointed to the `A:/` - and this is the root directory. I'm guessing, that Configurator can't understand this while reading git configuration files and this makes files read impossible; also when I try to see the files/folders structure in Configurator - there's nothing to see; and the `branch` pull-down list is empty. below you can find my Configurator's log

```
INFO:2019-12-26 23:08:07,455:hass_configurator.configurator:Starting server
INFO:2019-12-26 23:08:07,457:hass_configurator.configurator:Listening on: http://0.0.0.0:8099
INFO:2019-12-26 23:08:34,444:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2019-12-26 23:08:36,824:hass_configurator.configurator:172.30.32.2 - "GET /api/listdir?path=. HTTP/1.1" 200 -
WARNING:2019-12-26 23:08:36,866:hass_configurator.configurator:Cmd('git') failed due to: exit code(128)
  cmdline: git status --porcelain --untracked-files
  stderr: 'fatal: cannot chdir to 'a:/': No such file or directory
```

is there any possibility to fix that?

**Comment by frenck** [comment]
Ok, so there are a couple of things going on here.

First of all, this is the add-on repository. Add-ons wrap existing software, including their existing bugs and issues 😉 

So a bug to the application running in an add-on, should be reported at the repository/application, in this case right here:

<https://github.com/danielperna84/hass-configurator>

About the error you see, I'm not sure, but I doubt this is a Configurator issue, to be honest. However, creating an issue on the above-listed repository might be a good start.

**Comment by pejotigrek** [comment]
thanks for clarifying that :)
just for the record: I was pointed here by the link in this add-on's details seen in the dashboard which said - "In case you've found a bug, please [open an issue on our GitHub.](https://github.com/home-assistant/hassio-addons/issues)"

I'm going now to the repo you've linked. thank you!

**Comment by frenck** [comment]
@pejotigrek 👍 

I understand the confusion, at the same time, we want to prevent people from opening GitHub issues at the upstream project because of add-on issues. 😉 

So it is hard to find the balance there, nevertheless, we are always happy to guide and point people to the right direction.

**Comment by pejotigrek** [comment]
ok, after a small brainstorm I've found the solution - in case someone will meet the same problem and won't read the mentioned issue in the Configurator repo - fix is below:

it came out that somehow `.git/config` file contained worktree = `a:/` setting in the [core] part - it had to be entered automatically at some point [I didn't do it for sure]. all you have to do is comment that out & Configurator will work again [of course instead of `a:/` search for your path-letter]
