### ISSUE TITLE
mosquitto "no valid certificates found" - TLS path config is poorly documented

### ISSUE THREAD

**Issue by lockan** [home-assistant/hassio-addons#950]
The mosquitto broker add-on has settings for the certificate and key files in order to enable tls for secure communication to the broker. 
However, these config properties will not accept just any arbitrary path. If the key and cert files are not in the right location on the host, the add-on will return a "no valid certificates found" error in the logs and TLS will not be enabled. 

After some troubleshooting and reading through the run.sh script that gets run by the Dockerfile I discovered that the key and cert files MUST be in the host /ssl folder, or they will not be found. 
This is completely undocumented in the setup instructions, and has wasted me (and possibly others) hours of time digging into. 

A clarification in the setup documents would be appreciated regarding the /ssl path requirement.

**Comment by darootler** [comment]
I also wasted hours of time to get this information.
Please reopen this issue and update the docs.

A better way would be to be able to configure the path for the certificates.

Regards
Richard
