### ISSUE TITLE
Snips won't run on Hassos 3.7

### ISSUE THREAD

**Issue by mapulu** [home-assistant/hassio-addons#955]
Running HassOs 3.7 and try to start Snips.Ai got this error message and it does not work.
```
ERROR:snips_nlu       : Unable to read file '/usr/share/snips/assistant/nlu_engine/nlu_engine.json'
 -> caused by: Mismatched model version: model is 0.17.0 but runner is 0.20.0

```

**Comment by frenck** [comment]
The model you are using does not match the version of the add-on.

Please note that: <https://www.home-assistant.io/blog/2019/12/03/sonos-shutting-down-local-voice-option-snips/>

**Comment by mapulu** [comment]
I am new to this and using the default settings. 
I did read the news title before but think that was only something that affects Sonos users. 
I am closing this.
