### ISSUE TITLE
my first add-on error

### ISSUE THREAD

**Issue by djmalin** [home-assistant/hassio-addons#960]
hello, I followed these tips from this page [https://developers.home-assistant.io/docs/en/hassio_addon_tutorial.html](url), when I want to run helo world, I get the following error, and I still can't go with it :( 

19-12-30 14:52:13 INFO (SyncWorker_0) [hassio.docker.addon] Start build local/armv7-addon-hello_world:1
19-12-30 14:52:13 ERROR (SyncWorker_0) [hassio.docker.addon] Can't build local/armv7-addon-hello_world:1: 500 Server Error: Internal Server Error ("Cannot locate specified Dockerfile: Dockerfile")

my conf: raspberry pi3 b+
System HassOS 3.7
arch armv7
dev false
docker true
hassio true
os_name Linux
python_version 3.7.5
version 0.103.5
virtualenv false

**Comment by frenck** [comment]
Hi there @djmalin!

Good to see you starting on development! 👍 

It cannot find the `Dockerfile`, so make sure that is in the right location (in the same folder as the `config.json` file).

BTW; we use GitHub to track issues, not for providing support. So in case you need help, I can recommend you'd join our Discord chat server. We have a #dev_hassio channel in there, where people can help you with this matter.

👍
