### ISSUE TITLE
Deconz showing wrong state on Aqara door/windows sensors

### ISSUE THREAD

**Issue by HaaVeeEnn** [home-assistant/hassio-addons#961]
Version 2.05.72 / 12/12/2019
Conbee 2 firmware 264A0700
Hass.io version 0.103.5
Some first times it worked correctly but after it stopped.
Even if i open and close window state not changes, refreshed staying "21 minutes ago"
![Screenshot (39)](https://user-images.githubusercontent.com/16451882/71596192-4ba50600-2b47-11ea-9229-a4a6ce8a1b3e.png)
![Screenshot (40)](https://user-images.githubusercontent.com/16451882/71596220-637c8a00-2b47-11ea-83b8-fa10ff6564a8.png)
![Screenshot (41)](https://user-images.githubusercontent.com/16451882/71596237-73946980-2b47-11ea-8460-b2b6c14ce22b.png)
![20191230_210105](https://user-images.githubusercontent.com/16451882/71596278-945cbf00-2b47-11ea-94e0-98c743c5e477.jpg)
![conbee](https://user-images.githubusercontent.com/16451882/71596351-e271c280-2b47-11ea-9d70-2f2181bd7ac8.PNG)
![conbee2](https://user-images.githubusercontent.com/16451882/71596423-1947d880-2b48-11ea-9519-eb95204fc202.PNG)

**Comment by frenck** [comment]
I'm sorry to say, but this part of the logic is not in control of the add-on.
Add-on's wrap existing software, in this case, software made by dresden.

Please report this issue upstream @ <https://github.com/dresden-elektronik/deconz-rest-plugin/>. Thanks! 👍
