### ISSUE TITLE
Initial setup of deCONZ plugin impossible: not a valid value for dictionary value @ data['options']. 

### ISSUE THREAD

**Issue by matthiaslein** [home-assistant/hassio-addons#963]
After a fresh installation of home-assistant (from "hassos_rpi4-3.7.img") on my new 4GB Raspberry Pi 4, I am unable to setup the deCONZ add-on (v5.0 pulled from the "Official add-ons" repo).

Every time I enter the "device" specification, I get the following error message:

not a valid value for dictionary value @ data['options']. Got {'device': '/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1965444-if00'}

The original input in the "Config" input section was:

{
  "device": "/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1965444-if00"
}

but the error appears no matter what device I actually use for the config. Curiously, I also get an error message if I revert to "Reset to defaults":

not a valid value for dictionary value @ data['options']. Got {'device': None, 'vnc_password': ''}

Since I'm not able to save my config, I can't start the add-on and use my zigbee devices with my new installation.

**Comment by D3nnisd** [comment]
Hey! I have this in my config:

{
  "device": "/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2119319-if00",
  "vnc_password": "editedtoshowyou"
}


Maybe it's missing the VNC password?

**Comment by matthiaslein** [comment]
Huh... You're right. Adding the VNC password to the configuration fixes the issue.

I think the documentation needs to be updated to explain that it is necessary, not optional.
