### ISSUE TITLE
deconz, no longer a remote-integration?

### ISSUE THREAD

**Issue by lordfiSh** [home-assistant/hassio-addons#965]
I'm using two HAs. One Home Assistant via pyton and one with Hass.io. With the Upgrade of the deconz plugin to 5.0 I can't use the Integrations remotely since its announcing the internal Docker IP, can this somehow changed?

Before 3.8?
Discovered the following bridges: [{'bridgeid': 'xxx', 'host': '192.168.1.115', 'port': 40850}].

After: 
Discovered the following bridges: [{'bridgeid': 'xxx', 'host': '172.30.33.5', 'port': 40850}].

**Comment by BananaPukeh** [comment]
Same issue here. Just updated Deconz on my PI 3 running hassio with a Raspbee stick. Now my main server, also running hassio doesn't see Deconz anymore.

Looks like with the Ingress update, http ports and API ports are no longer exposed to the host system.

**Comment by basekk** [comment]
Hi all, I'm facing the same issue. Direct access to Phoscon via port 40850 of the host system is not possible anymore. Hence, also mobile access via web browser to Phoscon isn't working anymore. 

Is there any solution to bring it back to the behaviour as in version <5.0?

**Comment by frenck** [comment]
@lordfiSh 
> I'm using two HAs. One Home Assistant via pyton and one with Hass.io. With the Upgrade of the deconz plugin to 5.0 I can't use the Integrations remotely since its announcing the internal Docker IP, can this somehow changed?

That is correct. The deCONZ add-on now runs in a secure and isolated environment.

@BananaPukeh 
> Looks like with the Ingress update, http ports and API ports are no longer exposed to the host system.

Correct!

> Direct access to Phoscon via port 40850 of the host system is not possible anymore.

Incorrect. You can open up a port in the Network settings section of the add-on. If the port isn't shown, reset the network section to the defaults and try again.

**Comment by BananaPukeh** [comment]
@frenck 
Resetting the network settings did indeed show the port mapping fields again. However, when I try to add the DeCONZ integration on my main server again it instantly shows: `Couldn't get an API key`

Is there any way of adding it back to my main server? 
On the PI running hassio with DeCONZ, it does show up in the integrations menu. 

I used default port mapping: `8081 -> 8081`, `40850 -> 40850`

**Comment by BananaPukeh** [comment]
Figured it out, seems like the DeCONZ integration setup in hass is broken. 

When DeCONZ became unreachable due the ingress port issues, I tried to re-add the DeCONZ integration with no luck. After that I figured how to re-open the DeCONZ add-on ports, the web UI was working on port 40850 again. Other third-party apps did work, but hass still didn't work.   

When attempting to add the DeCONZ integration in hass, it immediately said to click on "authenticate app" in the Phoscon UI. There was no input for specifying a remote host. 

**How I got it working again:** 
Rolled back a snapshot of my hass config, where I didn't remove the DeCONZ integration yet. After that hass could see the DeCONZ integration immediately.

Seems like hass update 0.103.3 and 0.103.4 had some changes regarding the DeCONZ setup procedure that doesn't allow to specify remote hosts.

**Comment by Spirituss** [comment]
> @frenck
> Resetting the network settings did indeed show the port mapping fields again. However, when I try to add the DeCONZ integration on my main server again it instantly shows: `Couldn't get an API key`

The same is here. I can't add integration on my second Hass.io to Deconz. Port reset doesn't help. Hope it will be fixed soon. Looks like the developers wanted to change the concept but didn't think out it carefully. Thus the last version of HA and Deconz don't not match each other.

**Comment by BananaPukeh** [comment]
@Spirituss You could try to manually add it at own risk. 
Hass stores the DeCONZ config in the `core.config_entries` file.

You only need to grab an API key from DeCONZ.

My entry looks like this:
```{
                "connection_class": "local_push",
                "data": {
                    "api_key": "xxxxxxxx",
                    "bridgeid": "xxxxxx",
                    "host": "10.0.0.200",
                    "port": 40850,
                    "uuid": "088d4ed0-47cf-4ac8-ab9a-xxxxx"
                },
                "domain": "deconz",
                "entry_id": "5bf6193d9ad14c0aa5af597e981cxxxx",
                "options": {
                    "allow_clip_sensor": false,
                    "allow_deconz_groups": true,
                    "master": true
                },
                "source": "user",
                "system_options": {
                    "disable_new_entities": false
                },
                "title": "deCONZ-00212EFFFF03CB73",
                "version": 1
            },```

**Comment by nin9s** [comment]
How does the manual grab of an api key helps for 3rd party apps which do not provide a functionality to set such keys e.g only having a Auto search feature ?

**Comment by fillwe** [comment]
Hoping for a fix with this also! Don’t think it is all to uncommon to run Deconz on a remote instance. Would be perfect to be able to manually specify ip and port in the integration flow again!

**Comment by Spirituss** [comment]
Rejoice guys! I found working solution how to connect several Hass.io instances to one deconz:
1) Don't use Hass.io add-on Deconz, since it is not visible outside the Hass.io. Instead, install https://github.com/marthoc/docker-deconz if you use docker or official deconz distributive otherwise. 
2) Use 'host' network mode for docker-deconz container. Set DECONZ_WEB_PORT = 40850 and better DECONZ_UPNP = 0 for environment variables.
3) Remove existing deconz integration on your Hass.io instances.
4) Manually add deconz integration for every Hass.io instance with usual procedure (with prior authentification in phoscon/gateway/advanced).
5) Enjoy!

**Comment by nin9s** [comment]
Thanks @Spirituss that worked great. Had in mind that marthoc/docker-deconz isnt officially supported anymore but I guess this isnt really the case.

**Comment by lordfiSh** [comment]
> 1. Don't use Hass.io add-on Deconz, since it is not visible outside the Hass.io. Instead, install https://github.com/marthoc/docker-deconz if you use docker or official deconz distributive otherwise.
There is Hass.io Repo URL: https://github.com/marthoc/hassio-addons thats the Image I used before, will also switch back to it
