### ISSUE TITLE
configurator UI is not display properly.

### ISSUE THREAD

**Issue by ghugari** [home-assistant/hassio-addons#967]
configurator UI is not display properly. I am not able to view/edit the files.

the logs are as below.
INFO:2020-01-03 13:53:37,909:hass_configurator.configurator:Starting server
INFO:2020-01-03 13:53:37,909:hass_configurator.configurator:Listening on: http://0.0.0.0:8099
INFO:2020-01-03 13:53:39,228:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -

PFA screenshots
![configuator](https://user-images.githubusercontent.com/59469346/71713875-8356cb00-2e31-11ea-9b1f-34fb969ceb18.jpg)

**Comment by frenck** [comment]
Privacy badger blocking requests to external resources?

**Comment by ghugari** [comment]
Thanks ....

Resolved.

**Comment by jankete** [comment]
> Privacy badger blocking requests to external resources?

When I call the Configurator, via VPN I get "500 Internal Server Error". At home all is fine. Might this also be related to this? What does "Privacy badger blocking requests to external resources?" mean and where can I change that?
