### ISSUE TITLE
Config folder is emptied when repository is invalid

### ISSUE THREAD

**Issue by Cloudenius** [home-assistant/hassio-addons#968]
When setting up the git_pull add-on, I noticed that when HassIO is unable to login to the repository, it clears the config directory. See GIF below.

![HomeAssistant-GitPullRemovesFiles](https://user-images.githubusercontent.com/14926452/71725349-d5005500-2e33-11ea-8702-aefd63882fdb.gif)

**Comment by Cloudenius** [comment]
Bump to prevent closure.

**Comment by parkr** [comment]
This happened to me as well.

**Comment by jerometerrier** [comment]
I had also this issue.
