### ISSUE TITLE
Config issue with Let's Encrypt add-on

### ISSUE THREAD

**Issue by mauriziomarras** [home-assistant/hassio-addons#977]
I'm trying to connect in https to my Hassio using the add-on. The Config results in an error message: "not a valid value for dictionary value at data  ['options']....
I have a public IP address so I don't need to use a DNS service.
Where is my mistake? the error messag doesn't allow to understand where the issue is.
thank you

**Comment by borpin** [comment]
+1 same issue. The defaults do not parse, nor does the example

![image](https://user-images.githubusercontent.com/1322749/71851575-ca152100-30ce-11ea-811b-d38615604310.png)

I want to use the DNS challenge.

**Comment by Zapfmeister** [comment]
@borpin you didnt enter an email adress nor a domain. Those are required.
@mauriziomarras just leave the "dns": {} entry in the config and it should be fine. Like this:

  "email": "user@gmail.com",
  "domains": [
    "hass.example.com"
  ],
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "challenge": "http",
  "dns": {}
}

**Comment by borpin** [comment]
@Zapfmeister, yes I know but still doesn't parse - did you try and save those settings and use the add-on?

This does parse

```
{
  "email": "hello@home-assistant.io",
  "domains": "home-assistant.io",
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "challenge": "dns",
  "dns": [{
    "provider": "dns-cloudflare",
    "cloudflare_email": "cf@home-assistant.io",
    "cloudflare_api_key": "31242lk3j4ljlfdwsjf0"
  }]
}
```

BUT BUT BUT, when I enter valid credentials,

When I try and start the add-on, it reverts back to the defaults. no log entries that I can see. 😭 

Note this is not a HASSOS setup but a docker system on DietPi (generic Linux install).

**Comment by Zapfmeister** [comment]
@borpin really strange. I will do some updates on the documentation.
Can you please give it a try with the following and let me know the result?

{
  "email": "hello@home-assistant.io",
  "domains": "home-assistant.io",
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "challenge": "dns",
  "dns": {
    "provider": "dns-cloudflare",
    "cloudflare_email": "cf@home-assistant.io",
    "cloudflare_api_key": "31242lk3j4ljlfdwsjf0"
  }
}

**Comment by Zapfmeister** [comment]
@borpin 

Im sorry, this should be correct:
{
"email": "hello@home-assistant.io",
"domains": ["home-assistant.io"],
"certfile": "fullchain.pem",
"keyfile": "privkey.pem",
"challenge": "dns",
"dns": {
"provider": "dns-cloudflare",
"cloudflare_email": "cf@home-assistant.io",
"cloudflare_api_key": "31242lk3j4ljlfdwsjf0"
}
}

**Comment by aapit** [comment]
I can confirm this issue also occurs on my hass.io install on a RPI3B+.

**Comment by a575606** [comment]
Bump.. me too on packaged Hass.io running on Synology
