### ISSUE TITLE
Can't add integration to Deconz add-on on another HA instance

### ISSUE THREAD

**Issue by Spirituss** [home-assistant/hassio-addons#982]
I have updated Deconz add-on from 4 to 5.0 (ingress version) installed on Hass.io 0.103.5. 
Now I can't add Deconz integration on another Hass.io instance and receive 'Can't get API key' message in integration add dialog box.
I try to reset Deconz ports to default and then specify 8081 and 40850 for web sockets and API respectively. Nothing helps. 
It seems that API is bounded inside Hass.io container and is not accessible outside it. 

<img width="586" alt="Screen Shot 2020-01-06 at 15 13 01" src="https://user-images.githubusercontent.com/47206760/71817482-0fb5f780-3097-11ea-92e3-65f51c313606.png">

**Comment by BananaPukeh** [comment]
See #965
