### ISSUE TITLE
deCONZ add a way to upload firmware binaries in the container for OTA Zigbee device update

### ISSUE THREAD

**Issue by oncleben31** [home-assistant/hassio-addons#985]
The deCONZ app alow to maje OTA update of Zigbee devices. 
Detailed instructions here (https://phoscon.de/en/support#ota-update-osram-devices)
To be able to implement this, we need a way to put firmware binaries file in the container to let the deCONZ app access to this file.

**Comment by frenck** [comment]
This is currently being worked on in #983
