### ISSUE TITLE
Bulb delay - deCONZ 5.0 

### ISSUE THREAD

**Issue by Henrik1986** [home-assistant/hassio-addons#989]
After update the deCONZ addon to 5.0 from 4.1 there is at delay when turning lamps on and off. The delay i randomly. Some bulbs turns of direct and some after 2-3 second. This behavior dosen't exist in version 4.1. 

Running Hass.io on a raspberry pi with a conbee (version 1).

**Comment by frenck** [comment]
The add-on cannot help or improve the delay.
This is either an issue with the deCONZ software (report at dresden) or the deCONZ integration (report at main Home Assistant repository).

From an add-on perspective, there is not much we can do to help this.
