### ISSUE TITLE
What to do if username and password contain special characters that aren't compatible?

### ISSUE THREAD

**Issue by rszemplinski** [home-assistant/hassio-addons#994]
Hi,

My username for my PC is my email and my password contains a `%` which is also the delimiter. What can I do to fix this without having to change my username or password?

Edit:

I apologize, I thought this was a specific repo for the RPC shutdown. So some context, I am trying to configure the RPC shutdown addon.

**Comment by TravelinMax** [comment]
Try escaping the % in your password by putting a \ in front of it. Like `username%passw\%rd`
