### ISSUE TITLE
DECONZ: add a way to update getaway firmware through the addon

### ISSUE THREAD

**Issue by gabrielemariotti** [home-assistant/hassio-addons#998]
I know that the deconz add-on support firmware update of the getaway over the deconz UI without any scripts.
However sometimes the firmware upgrade fails silently.
The [manual update](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually) is not so easy for an end users.
It would be nice to have the ability to update the firmware through the addon, maybe providing the filename in the deconz-firmware repo or simply the version number of the firmware.

**Comment by pvizeli** [comment]
Instead to workaround things they not work, let fix the issue. Open an issue by dresden electronics, provide information they he can use to fix that.

**Comment by gabrielemariotti** [comment]
@pvizeli Thanks for the feedback. I totally agree with you. 
I created the issue 20+ days ago without useful answer (and the manual update is not a solution).

In any case the ability to update the firmware of the gateway in this kind of addon is not necessarily a workaround.

**Comment by valeriodifrancia** [comment]
> I know that the deconz add-on support firmware update of the getaway over the deconz UI without any scripts.
> However sometimes the firmware upgrade fails silently.
> The [manual update](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually) is not so easy for an end users.
> It would be nice to have the ability to update the firmware through the addon, maybe providing the filename in the deconz-firmware repo or simply the version number of the firmware.

Totally agree!

**Comment by frenck** [comment]
> maybe providing the filename in the deconz-firmware repo or simply the version number of the firmware.

That is not something the add-on can change. Add-ons wrap exiting software. If you like to suggest a change for the software running inside the add-on, please contact the vendor, in this case: Dresden.

> However sometimes the firmware upgrade fails silently

Yes, unfortunately, there is nothing we can do about that, hence the guide on manually upgrading.
